#!/usr/bin/env python3
"""Build and write the fixed gen_solutions.py to Downloads."""
import os, sys

OUT = r"C:\Users\Victor\Downloads\gen_solutions.py"

lines = []
def L(s=""):
    lines.append(s)

L('#!/usr/bin/env python3')
L('# -*- coding: utf-8 -*-')
L('"""')
L('Генерация решений для олимпиадных задач через DeepSeek с двойным проходом:')
L('  генератор -> аудитор -> (при необходимости) регенерация.')
L('  Поддерживает checkpointing, обработку битых JSON от DeepSeek и продолжение прерванных прогонов.')
L('')
L('Fixes applied:')
L('  1. _escape_control_chars_in_strings() - экранирует управляющие символы (\\n, \\t) внутри JSON-строк')
L('  2. _sanitize_json_content() - расширена: control-char -> backslash fix -> brute force')
L('  3. sys.stdout переключён на utf-8 для предотвращения UnicodeEncodeError на Windows')
L('"""')
L('import os, sys, json, time, requests, io, re')
L('')
L('DEEPSEEK_KEY = os.environ["DEEPSEEK_API_KEY"]')
L('API_URL = "https://api.deepseek.com/chat/completions"')
L('MODEL = "deepseek-chat"')
L('')
L('_IN_DIR = os.path.dirname(os.path.abspath(__file__))')
L('IN_FILE   = os.path.join(_IN_DIR, "tasks_need_solutions.json")')
L('DB_PATH   = os.path.join(_IN_DIR, "tasks_solutions_out.json")')
L('LOG_OK    = os.path.join(_IN_DIR, "solutions_log.jsonl")')
L('LOG_BROKEN= os.path.join(_IN_DIR, "solutions_broken.jsonl")')
L('LOG_FAIL  = os.path.join(_IN_DIR, "solutions_fail.jsonl")')
L('CHECKPOINT_INTERVAL = 20')
L('')
L('# ---------- SANITIZE DeepSeek JSON ----------')
L('')
L('def _escape_control_chars_in_strings(text):')
L('    """')
L('    Экранирует управляющие символы (< 0x20), которые находятся ВНУТРИ JSON-строк.')
L('    DeepSeek иногда возвращает JSON с реальными символами новой строки (0x0A)')
L('    внутри строковых значений, что вызывает "Invalid control character" при парсинге.')
L('    """')
L('    result = []')
L('    in_string = False')
L('    escape = False')
L('    for ch in text:')
L('        if escape:')
L('            result.append(ch)')
L('            escape = False')
L('            continue')
L('        if ch == "\\\\":')
L('            result.append(ch)')
L('            escape = True')
L('            continue')
L('        if ch == \'"\':')
L('            in_string = not in_string')
L('            result.append(ch)')
L('            continue')
L('        if in_string and ord(ch) < 0x20:')
L('            if ch == "\\n":')
L('                result.append("\\\\n")')
L('            elif ch == "\\t":')
L('                result.append("\\\\t")')
L('            elif ch == "\\r":')
L('                result.append("\\\\r")')
L('            else:')
L('                result.append("\\\\u{:04x}".format(ord(ch)))