OLYMPIAD_PROBLEMS_DB = [
    {
        "id": 1,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_1",
        "problem_number": 1,
        "title": "IMO 2025 Problem 1",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 2,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_1",
        "problem_number": 2,
        "title": "IMO 2025 Problem 2",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 3,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_1",
        "problem_number": 3,
        "title": "IMO 2025 Problem 3",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 4,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_2",
        "problem_number": 4,
        "title": "IMO 2025 Problem 4",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 5,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_2",
        "problem_number": 5,
        "title": "IMO 2025 Problem 5",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 6,
        "olympiad_slug": "imo",
        "year": 2025,
        "round": "day_2",
        "problem_number": 6,
        "title": "IMO 2025 Problem 6",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 7,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_1",
        "problem_number": 1,
        "title": "IMO 2024 Problem 1",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 8,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_1",
        "problem_number": 2,
        "title": "IMO 2024 Problem 2",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 9,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_1",
        "problem_number": 3,
        "title": "IMO 2024 Problem 3",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 10,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_2",
        "problem_number": 4,
        "title": "IMO 2024 Problem 4",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 11,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_2",
        "problem_number": 5,
        "title": "IMO 2024 Problem 5",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 12,
        "olympiad_slug": "imo",
        "year": 2024,
        "round": "day_2",
        "problem_number": 6,
        "title": "IMO 2024 Problem 6",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://www.imo-official.org/problems.aspx",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["imo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 13,
        "olympiad_slug": "ukmt_bmo",
        "year": 2025,
        "round": "round_1",
        "problem_number": 1,
        "title": "BMO 2025 Round 1 Problem 1",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://bmos.ukmt.org.uk/home/bmo.shtml",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["bmo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 14,
        "olympiad_slug": "ukmt_bmo",
        "year": 2025,
        "round": "round_1",
        "problem_number": 2,
        "title": "BMO 2025 Round 1 Problem 2",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://bmos.ukmt.org.uk/home/bmo.shtml",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["bmo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    },
    {
        "id": 15,
        "olympiad_slug": "ukmt_bmo",
        "year": 2025,
        "round": "round_1",
        "problem_number": 3,
        "title": "BMO 2025 Round 1 Problem 3",
        "text": "Скоро будет добавлено условие задачи.",
        "answer": "",
        "solution": "",
        "source_url": "https://bmos.ukmt.org.uk/home/bmo.shtml",
        "has_statement": False,
        "has_answer": False,
        "has_solution": False,
        "tags": ["bmo", "archive"],
        "grade_hint": None,
        "difficulty_hint": None
    }
]
