PROBLEMS_DB = [   {   'id': 5001,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Наименьшее число',
        'text': 'Напишите наименьшее десятичное число, у которого все цифры различны.',
        'answer': '1023456789'},
    {   'id': 5002,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Кто на каком этаже',
        'text': 'В четырехэтажном доме Ваня живет выше Пети, но ниже Сени. Определите, кто на '
                'каком этаже живет.',
        'answer': '4 этаж - Сеня, 3 этаж - Ваня, 2 этаж - Петя'},
    {   'id': 5003,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Спички',
        'text': 'Из 12 спичек сложено 4 квадрата. Переложите 4 спички так, чтобы получилось 3 '
                'квадрата.',
        'answer': 'Из фигуры убрать 4 спички, оставив 3 квадрата'},
    {   'id': 5004,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Лотерейные билеты',
        'text': 'В номерах 625517 и 322324 расставьте знаки арифметических действий и скобки так, '
                'чтобы результат равнялся 100.',
        'answer': '62+55-17 = 100; (3+22)*(3-2)*4 = 100'},
    {   'id': 5005,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Фрукты в корзине',
        'text': 'В корзине лежат яблоки, груши и персики – всего 37 плодов. Яблок в корзине в два '
                'раза больше, чем персиков, и на 3 штуки больше, чем груш. Сколько в корзине '
                'яблок, груш и персиков?',
        'answer': 'Персиков - 8, яблок - 16, груш - 13'},
    {   'id': 5006,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Ребус с умножением',
        'text': 'Найдите цифры в примере: * 8 * × 4 * 2 = 7 * 0, в результате получается * * * * 2 '
                '*',
        'answer': '385 × 412 = 158620'},
    {   'id': 5007,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Пачки чая',
        'text': 'На одной чаше весов 6 пачек чая и гиря 50 г, на другой – 1 пачка чая и гири 100 г '
                'и 200 г. Весы в равновесии. Сколько весит пачка чая?',
        'answer': '50 г'},
    {   'id': 5008,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Головы и ноги',
        'text': 'В команде 5 голов и 14 ног. Сколько людей и сколько лошадей?',
        'answer': '3 человека и 2 лошади'},
    {   'id': 5009,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Циферблат часов',
        'text': 'Разрежьте циферблат часов на три части так, чтобы сумма цифр в каждой части была '
                'одинаковой.',
        'answer': 'Разрезы между 10-11, 2-3, 5-6'},
    {   'id': 5010,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Талисманы и чай',
        'text': 'Белый Мишка и Зайка выпили 11 чашек, Леопард и Белый Мишка — 15, Зайка и Леопард '
                '— 14. Сколько чашек выпили все вместе?',
        'answer': '20 чашек'},
    {   'id': 5011,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Произведение цифр',
        'text': 'Сколько трёхзначных чисел имеют произведение цифр, равное 120?',
        'answer': '6 чисел: 345, 354, 435, 453, 534, 543'},
    {   'id': 5012,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Сумма цифр',
        'text': 'Найдите сумму цифр числа 10^5 - 1',
        'answer': '45'},
    {   'id': 5013,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Нули в произведении',
        'text': 'Сколькими нулями заканчивается произведение 1×2×3×...×10?',
        'answer': '2 нуля'},
    {   'id': 5014,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Последняя цифра',
        'text': 'Найдите последнюю цифру числа 2^10',
        'answer': '4'},
    {   'id': 5015,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Делители',
        'text': 'Сколько делителей у числа 24?',
        'answer': '8'},
    {   'id': 5016,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости',
        'text': 'Число 1234567890 делится на 9?',
        'answer': 'Да, сумма цифр 45 делится на 9'},
    {   'id': 5017,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Четные числа',
        'text': 'Сколько четных двузначных чисел?',
        'answer': '45'},
    {   'id': 5018,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Простые числа',
        'text': 'Какие из чисел 17, 27, 37, 47 простые?',
        'answer': '17, 37, 47'},
    {   'id': 5019,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОД',
        'text': 'Найдите НОД(36, 48)',
        'answer': '12'},
    {   'id': 5020,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОК',
        'text': 'Найдите НОК(12, 18)',
        'answer': '36'},
    {   'id': 5021,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Уравнение 1',
        'text': 'x + 17 = 35',
        'answer': 'x = 18'},
    {   'id': 5022,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Уравнение 2',
        'text': '2x - 5 = 15',
        'answer': 'x = 10'},
    {   'id': 5023,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Уравнение 3',
        'text': 'x/3 = 7',
        'answer': 'x = 21'},
    {   'id': 5024,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Уравнение 4',
        'text': '3x + 4 = 22',
        'answer': 'x = 6'},
    {   'id': 5025,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Уравнение 5',
        'text': '45 - x = 28',
        'answer': 'x = 17'},
    {   'id': 5026,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Скорость',
        'text': 'Пешеход прошел 12 км за 3 часа. Найдите скорость.',
        'answer': '4 км/ч'},
    {   'id': 5027,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Площадь прямоугольника',
        'text': 'Стороны прямоугольника 6 см и 9 см. Найдите площадь.',
        'answer': '54 см²'},
    {   'id': 5028,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Периметр квадрата',
        'text': 'Сторона квадрата 8 см. Найдите периметр.',
        'answer': '32 см'},
    {   'id': 5029,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Объем куба',
        'text': 'Сторона куба 5 см. Найдите объем.',
        'answer': '125 см³'},
    {   'id': 5030,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Проценты',
        'text': 'Найдите 20% от 300',
        'answer': '60'},
    {   'id': 5031,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Сумма углов',
        'text': 'Чему равна сумма углов треугольника?',
        'answer': '180°'},
    {   'id': 5032,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Периметр прямоугольника',
        'text': 'Длина 12 см, ширина 5 см. Найдите периметр.',
        'answer': '34 см'},
    {   'id': 5033,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Сторона квадрата',
        'text': 'Периметр квадрата 36 см. Найдите сторону.',
        'answer': '9 см'},
    {   'id': 5034,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Углы треугольника',
        'text': 'Два угла треугольника 40° и 60°. Найдите третий.',
        'answer': '80°'},
    {   'id': 5035,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Диаметр',
        'text': 'Радиус окружности 7 см. Найдите диаметр.',
        'answer': '14 см'},
    {   'id': 5036,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Площадь квадрата',
        'text': 'Сторона квадрата 10 см. Найдите площадь.',
        'answer': '100 см²'},
    {   'id': 5037,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Периметр треугольника',
        'text': 'Стороны 5, 7, 9 см. Найдите периметр.',
        'answer': '21 см'},
    {   'id': 5038,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Куб',
        'text': 'Сколько граней у куба?',
        'answer': '6'},
    {   'id': 5039,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Параллелепипед',
        'text': 'Сколько вершин у прямоугольного параллелепипеда?',
        'answer': '8'},
    {   'id': 5040,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Перестановки',
        'text': 'Сколькими способами можно расставить 3 разные книги?',
        'answer': '6'},
    {   'id': 5041,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Двузначные числа',
        'text': 'Сколько двузначных чисел из цифр 1,2,3 (с повторениями)?',
        'answer': '9'},
    {   'id': 5042,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Трехзначные числа',
        'text': 'Сколько трехзначных чисел из цифр 4,5,6 без повторений?',
        'answer': '6'},
    {   'id': 5043,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Мороженое',
        'text': '3 вида мороженого, 4 вида сиропа. Сколько разных порций?',
        'answer': '12'},
    {   'id': 5044,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Ручки и карандаши',
        'text': '2 ручки, 3 карандаша. Сколькими способами выбрать один предмет?',
        'answer': '5'},
    {   'id': 5045,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Пицца',
        'text': '5 начинок. Сколько пицц с двумя разными начинками?',
        'answer': '10'},
    {   'id': 5046,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Обед',
        'text': '3 первых, 4 вторых. Сколько обедов?',
        'answer': '12'},
    {   'id': 5047,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 1,
        'title': 'Флаги',
        'text': 'Сколько флагов из 3 полос из 3 цветов (все разные)?',
        'answer': '6'},
    {   'id': 5048,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Четные трехзначные',
        'text': 'Сколько четных трехзначных чисел?',
        'answer': '450'},
    {   'id': 5049,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Нечетные двузначные',
        'text': 'Сколько нечетных двузначных чисел?',
        'answer': '45'},
    {   'id': 5050,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Кратные 3',
        'text': 'Сколько чисел от 1 до 100 кратно 3?',
        'answer': '33'},
    {   'id': 5051,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Кратные 5',
        'text': 'Сколько чисел от 1 до 100 кратно 5?',
        'answer': '20'},
    {   'id': 5052,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Кратные 15',
        'text': 'Сколько чисел от 1 до 100 кратно 15?',
        'answer': '6'},
    {   'id': 5053,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Простые числа до 20',
        'text': 'Назовите все простые числа от 1 до 20.',
        'answer': '2,3,5,7,11,13,17,19'},
    {   'id': 5054,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Составное число',
        'text': 'Какое число составное: 23, 29, 31, 35?',
        'answer': '35'},
    {   'id': 5055,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Разложение 60',
        'text': 'Разложите 60 на простые множители.',
        'answer': '2×2×3×5'},
    {   'id': 5056,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Разложение 84',
        'text': 'Разложите 84 на простые множители.',
        'answer': '2×2×3×7'},
    {   'id': 5057,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Остатки',
        'text': 'Число при делении на 7 даёт остаток 4. Какой остаток даст удвоенное число при '
                'делении на 7?',
        'answer': '1'},
    {   'id': 5058,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Делители 12',
        'text': 'Сколько делителей у числа 12?',
        'answer': '6'},
    {   'id': 5059,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Делители 16',
        'text': 'Сколько делителей у числа 16?',
        'answer': '5'},
    {   'id': 5060,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Делители 18',
        'text': 'Сколько делителей у числа 18?',
        'answer': '6'},
    {   'id': 5061,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Сложение дробей',
        'text': '1/2 + 1/3 = ?',
        'answer': '5/6'},
    {   'id': 5062,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Вычитание дробей',
        'text': '2/3 - 1/4 = ?',
        'answer': '5/12'},
    {   'id': 5063,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Умножение дробей',
        'text': '3/4 × 2/5 = ?',
        'answer': '3/10'},
    {   'id': 5064,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Деление дробей',
        'text': '2/3 : 4/5 = ?',
        'answer': '5/6'},
    {   'id': 5065,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Десятичная дробь',
        'text': 'Запишите 3/5 в виде десятичной дроби.',
        'answer': '0,6'},
    {   'id': 5066,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Десятичная дробь 2',
        'text': 'Запишите 7/8 в виде десятичной дроби.',
        'answer': '0,875'},
    {   'id': 5067,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Сравнение дробей',
        'text': 'Что больше: 2/3 или 3/4?',
        'answer': '3/4'},
    {   'id': 5068,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Смешанное число',
        'text': 'Преобразуйте 7/3 в смешанное число.',
        'answer': '2 1/3'},
    {   'id': 5069,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Обыкновенная дробь',
        'text': 'Преобразуйте 3,5 в обыкновенную дробь.',
        'answer': '7/2'},
    {   'id': 5070,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Среднее арифметическое',
        'text': 'Найдите среднее чисел 10, 20, 30',
        'answer': '20'},
    {   'id': 5071,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Прямой угол',
        'text': 'Сколько градусов в прямом угле?',
        'answer': '90°'},
    {   'id': 5072,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Острый угол',
        'text': 'Какой угол называют острым?',
        'answer': 'Меньше 90°'},
    {   'id': 5073,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Тупой угол',
        'text': 'Какой угол называют тупым?',
        'answer': 'Больше 90°, меньше 180°'},
    {   'id': 5074,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Развернутый угол',
        'text': 'Чему равен развернутый угол?',
        'answer': '180°'},
    {   'id': 5075,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Равносторонний треугольник',
        'text': 'Как называется треугольник с равными сторонами?',
        'answer': 'Равносторонний'},
    {   'id': 5076,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Равнобедренный треугольник',
        'text': 'Как называется треугольник с двумя равными сторонами?',
        'answer': 'Равнобедренный'},
    {   'id': 5077,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Оси симметрии прямоугольника',
        'text': 'Сколько осей симметрии у прямоугольника?',
        'answer': '2'},
    {   'id': 5078,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Оси симметрии квадрата',
        'text': 'Сколько осей симметрии у квадрата?',
        'answer': '4'},
    {   'id': 5079,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Радиус',
        'text': 'Что такое радиус окружности?',
        'answer': 'Отрезок от центра до точки на окружности'},
    {   'id': 5080,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Диаметр и радиус',
        'text': 'Как связаны диаметр и радиус?',
        'answer': 'Диаметр = 2 × радиус'},
    {   'id': 5081,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости на 3',
        'text': 'Делится ли число 12345 на 3?',
        'answer': 'Да'},
    {   'id': 5082,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости на 4',
        'text': 'Делится ли число 1236 на 4?',
        'answer': 'Да'},
    {   'id': 5083,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости на 5',
        'text': 'Какие числа делятся на 5?',
        'answer': 'Оканчивающиеся на 0 или 5'},
    {   'id': 5084,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости на 9',
        'text': 'Делится ли число 12348 на 9?',
        'answer': 'Да'},
    {   'id': 5085,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Признак делимости на 10',
        'text': 'Какие числа делятся на 10?',
        'answer': 'Оканчивающиеся на 0'},
    {   'id': 5086,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Простые числа до 30',
        'text': 'Простые числа от 20 до 30',
        'answer': '23, 29'},
    {   'id': 5087,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Простые числа до 40',
        'text': 'Простые числа от 30 до 40',
        'answer': '31, 37'},
    {   'id': 5088,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'Простые числа до 50',
        'text': 'Простые числа от 40 до 50',
        'answer': '41, 43, 47'},
    {   'id': 5089,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОД 18 и 24',
        'text': 'Найдите НОД(18, 24)',
        'answer': '6'},
    {   'id': 5090,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОД 30 и 45',
        'text': 'Найдите НОД(30, 45)',
        'answer': '15'},
    {   'id': 5091,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОК 6 и 8',
        'text': 'Найдите НОК(6, 8)',
        'answer': '24'},
    {   'id': 5092,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 1,
        'title': 'НОК 9 и 12',
        'text': 'Найдите НОК(9, 12)',
        'answer': '36'},
    {   'id': 5093,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Проценты 2',
        'text': 'Найдите 25% от 200',
        'answer': '50'},
    {   'id': 5094,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Проценты 3',
        'text': 'Найдите 75% от 400',
        'answer': '300'},
    {   'id': 5095,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Проценты 4',
        'text': 'Сколько процентов составляет 30 от 150?',
        'answer': '20%'},
    {   'id': 5096,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 1,
        'title': 'Проценты 5',
        'text': 'Сколько процентов составляет 45 от 300?',
        'answer': '15%'},
    {   'id': 5097,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Площадь прямоугольника 2',
        'text': 'Длина 8 см, ширина 5 см. Найдите площадь.',
        'answer': '40 см²'},
    {   'id': 5098,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Периметр прямоугольника 2',
        'text': 'Длина 10 см, ширина 6 см. Найдите периметр.',
        'answer': '32 см'},
    {   'id': 5099,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Объем куба 2',
        'text': 'Сторона куба 3 см. Найдите объем.',
        'answer': '27 см³'},
    {   'id': 5100,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 1,
        'title': 'Объем параллелепипеда',
        'text': 'Измерения 2, 3, 4 см. Найдите объем.',
        'answer': '24 см³'},
    {   'id': 5101,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Сумма цифр 10^100-1',
        'text': 'Найдите сумму цифр числа 10^100 - 1',
        'answer': '900'},
    {   'id': 5102,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Произведение цифр 0',
        'text': 'Сколько трехзначных чисел имеют произведение цифр, равное 0?',
        'answer': '171'},
    {   'id': 5103,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД и НОК 24 и 36',
        'text': 'Найдите НОД(24,36) и НОК(24,36)',
        'answer': 'НОД=12, НОК=72'},
    {   'id': 5104,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Взаимно простые с 24',
        'text': 'Сколько чисел от 1 до 40 взаимно просты с 24?',
        'answer': '16'},
    {   'id': 5105,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Остатки 6 и 7',
        'text': 'Найдите наименьшее число, которое при делении на 6 дает остаток 5, а на 7 - '
                'остаток 3',
        'answer': '17'},
    {   'id': 5106,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простое число 97',
        'text': 'Докажите, что 97 - простое число',
        'answer': 'Не делится на 2,3,5,7'},
    {   'id': 5107,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Сумма цифр 9',
        'text': 'Сумма цифр двузначного числа равна 9. Если переставить цифры, получится число на '
                '27 меньше. Найдите число.',
        'answer': '63'},
    {   'id': 5108,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение с дробью',
        'text': '(x+2)/3 = 5',
        'answer': 'x = 13'},
    {   'id': 5109,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Проценты повышение',
        'text': 'Цена повысилась с 200 до 240 руб. На сколько процентов?',
        'answer': '20%'},
    {   'id': 5110,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби сложные',
        'text': '2/5 + 3/7 - 1/2 = ?',
        'answer': '3/70'},
    {   'id': 5111,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД 36 и 48',
        'text': 'Найдите НОД(36, 48)',
        'answer': '12'},
    {   'id': 5112,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОК 12 и 18',
        'text': 'Найдите НОК(12, 18)',
        'answer': '36'},
    {   'id': 5113,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Скорость 2',
        'text': 'Велосипедист проехал 24 км за 2 часа. С какой скоростью он ехал?',
        'answer': '12 км/ч'},
    {   'id': 5114,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Скорость 3',
        'text': 'Поезд проехал 120 км за 2 часа. Найдите скорость.',
        'answer': '60 км/ч'},
    {   'id': 5115,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Время',
        'text': 'Сколько времени потребуется, чтобы проехать 150 км со скоростью 50 км/ч?',
        'answer': '3 часа'},
    {   'id': 5116,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь треугольника 2',
        'text': 'Основание 10 см, высота 6 см. Найдите площадь треугольника.',
        'answer': '30 см²'},
    {   'id': 5117,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь прямоугольника 3',
        'text': 'Площадь 48 см², ширина 6 см. Найдите длину.',
        'answer': '8 см'},
    {   'id': 5118,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делимость на 11',
        'text': 'Признак делимости на 11. Делится ли 121 на 11?',
        'answer': 'Да'},
    {   'id': 5119,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делимость на 11 2',
        'text': 'Делится ли 123321 на 11?',
        'answer': 'Да'},
    {   'id': 5120,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Комбинаторика 3',
        'text': 'Сколько трехзначных чисел можно составить из цифр 1,2,3,4,5, если цифры не '
                'повторяются?',
        'answer': '60'},
    {   'id': 5121,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Комбинаторика 4',
        'text': 'Сколько трехзначных чисел можно составить из цифр 0,1,2,3,4, если цифры не '
                'повторяются?',
        'answer': '48'},
    {   'id': 5122,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Комбинаторика 5',
        'text': 'Сколько существует трехзначных чисел с различными цифрами?',
        'answer': '648'},
    {   'id': 5123,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Четные числа 2',
        'text': 'Сколько четных трехзначных чисел с различными цифрами?',
        'answer': '328'},
    {   'id': 5124,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Нечетные числа 2',
        'text': 'Сколько нечетных трехзначных чисел с различными цифрами?',
        'answer': '320'},
    {   'id': 5125,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение 6',
        'text': '5x - 3 = 2x + 9',
        'answer': 'x = 4'},
    {   'id': 5126,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение 7',
        'text': '7x + 2 = 3x + 14',
        'answer': 'x = 3'},
    {   'id': 5127,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение 8',
        'text': '4(x - 2) = 12',
        'answer': 'x = 5'},
    {   'id': 5128,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение 9',
        'text': '3(2x - 1) = 15',
        'answer': 'x = 3'},
    {   'id': 5129,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Уравнение 10',
        'text': '2(x + 3) - 4 = 10',
        'answer': 'x = 4'},
    {   'id': 5130,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Периметр 3',
        'text': 'Периметр прямоугольника 30 см, ширина 5 см. Найдите длину.',
        'answer': '10 см'},
    {   'id': 5131,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Периметр 4',
        'text': 'Периметр квадрата 48 см. Найдите сторону.',
        'answer': '12 см'},
    {   'id': 5132,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь 4',
        'text': 'Площадь прямоугольника 72 см², длина 12 см. Найдите ширину.',
        'answer': '6 см'},
    {   'id': 5133,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простые числа 2',
        'text': 'Сколько простых чисел от 1 до 50?',
        'answer': '15'},
    {   'id': 5134,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простые числа 3',
        'text': 'Сколько простых чисел от 1 до 100?',
        'answer': '25'},
    {   'id': 5135,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Составные числа 2',
        'text': 'Сколько составных чисел от 1 до 50?',
        'answer': '34'},
    {   'id': 5136,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Разложение 3',
        'text': 'Разложите 72 на простые множители.',
        'answer': '2³ × 3²'},
    {   'id': 5137,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Разложение 4',
        'text': 'Разложите 96 на простые множители.',
        'answer': '2⁵ × 3'},
    {   'id': 5138,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД 3',
        'text': 'Найдите НОД(42, 56)',
        'answer': '14'},
    {   'id': 5139,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД 4',
        'text': 'Найдите НОД(45, 75)',
        'answer': '15'},
    {   'id': 5140,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОК 3',
        'text': 'Найдите НОК(8, 12)',
        'answer': '24'},
    {   'id': 5141,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОК 4',
        'text': 'Найдите НОК(15, 20)',
        'answer': '60'},
    {   'id': 5142,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 8',
        'text': 'Сравните 3/7 и 4/9',
        'answer': '3/7 > 4/9'},
    {   'id': 5143,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 9',
        'text': 'Сравните 5/12 и 7/18',
        'answer': '5/12 > 7/18'},
    {   'id': 5144,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 10',
        'text': 'Сократите 24/36',
        'answer': '2/3'},
    {   'id': 5145,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 11',
        'text': 'Сократите 45/75',
        'answer': '3/5'},
    {   'id': 5146,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Проценты 6',
        'text': 'Число увеличили на 25%, получили 250. Найдите исходное.',
        'answer': '200'},
    {   'id': 5147,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Проценты 7',
        'text': 'Число уменьшили на 20%, получили 160. Найдите исходное.',
        'answer': '200'},
    {   'id': 5148,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Проценты 8',
        'text': 'Сколько процентов составляет 60 от 240?',
        'answer': '25%'},
    {   'id': 5149,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Проценты 9',
        'text': 'Сколько процентов составляет 90 от 360?',
        'answer': '25%'},
    {   'id': 5150,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Углы 3',
        'text': 'Один угол треугольника 70°, другой 60°. Найдите третий.',
        'answer': '50°'},
    {   'id': 5151,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Углы 4',
        'text': 'В треугольнике углы относятся как 3:4:5. Найдите углы.',
        'answer': '45°, 60°, 75°'},
    {   'id': 5152,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Углы 5',
        'text': 'Один из смежных углов 120°. Найдите другой.',
        'answer': '60°'},
    {   'id': 5153,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Углы 6',
        'text': 'Разность смежных углов 40°. Найдите углы.',
        'answer': '70° и 110°'},
    {   'id': 5154,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Перестановки 3',
        'text': "Сколько слов можно составить из букв слова 'МАМА'?",
        'answer': '6'},
    {   'id': 5155,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Перестановки 4',
        'text': "Сколько слов можно составить из букв слова 'ПАПА'?",
        'answer': '6'},
    {   'id': 5156,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Сочетания 2',
        'text': 'Сколькими способами выбрать 3 учеников из 7?',
        'answer': '35'},
    {   'id': 5157,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Сочетания 3',
        'text': 'Сколькими способами выбрать 4 из 9?',
        'answer': '126'},
    {   'id': 5158,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Остатки 2',
        'text': 'Число при делении на 8 дает остаток 5. Какой остаток даст утроенное число?',
        'answer': '7'},
    {   'id': 5159,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Остатки 3',
        'text': 'Число при делении на 9 дает остаток 4. Какой остаток даст удвоенное число?',
        'answer': '8'},
    {   'id': 5160,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делители 5',
        'text': 'Сколько делителей у числа 72?',
        'answer': '12'},
    {   'id': 5161,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делители 6',
        'text': 'Сколько делителей у числа 100?',
        'answer': '9'},
    {   'id': 5162,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делители 7',
        'text': 'Сколько делителей у числа 120?',
        'answer': '16'},
    {   'id': 5163,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простые числа 4',
        'text': 'Является ли 101 простым?',
        'answer': 'Да'},
    {   'id': 5164,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простые числа 5',
        'text': 'Является ли 121 простым?',
        'answer': 'Нет (11×11)'},
    {   'id': 5165,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Простые числа 6',
        'text': 'Является ли 169 простым?',
        'answer': 'Нет (13×13)'},
    {   'id': 5166,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 1',
        'text': 'В двух корзинах 80 яблок. В первой в 3 раза больше, чем во второй. Сколько в '
                'каждой?',
        'answer': '60 и 20'},
    {   'id': 5167,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 2',
        'text': 'В трех корзинах 90 яблок. Во второй в 2 раза больше, чем в первой, в третьей на '
                '10 больше, чем во второй. Сколько в каждой?',
        'answer': '10, 20, 60'},
    {   'id': 5168,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 3',
        'text': 'Сумма двух чисел 45, а разность 15. Найдите числа.',
        'answer': '30 и 15'},
    {   'id': 5169,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 4',
        'text': 'Сумма двух чисел 72, одно больше другого в 5 раз. Найдите числа.',
        'answer': '60 и 12'},
    {   'id': 5170,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 5',
        'text': 'В классе 28 учеников. Девочек на 4 больше, чем мальчиков. Сколько девочек?',
        'answer': '16'},
    {   'id': 5171,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Периметр 5',
        'text': 'Прямоугольник разрезали на два квадрата. Периметр одного 16 см. Найдите периметр '
                'прямоугольника.',
        'answer': '24 см'},
    {   'id': 5172,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Периметр 6',
        'text': 'Квадрат разрезали на 4 равных квадрата. Периметр большого 32 см. Найдите периметр '
                'маленького.',
        'answer': '16 см'},
    {   'id': 5173,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь 5',
        'text': 'Прямоугольник состоит из двух квадратов площадью 25 см² каждый. Найдите площадь '
                'прямоугольника.',
        'answer': '50 см²'},
    {   'id': 5174,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь 6',
        'text': 'Квадрат площадью 64 см² разделили на 4 равных квадрата. Найдите площадь каждого.',
        'answer': '16 см²'},
    {   'id': 5175,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Объем 3',
        'text': 'Куб с ребром 4 см разделили на 8 равных кубиков. Найдите объем каждого.',
        'answer': '8 см³'},
    {   'id': 6000,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Сложная комбинаторика 5 класс',
        'text': 'Сколько существует пятизначных чисел, у которых все цифры нечетные и различные?',
        'answer': '5! = 120'},
    {   'id': 5176,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делимость на 4',
        'text': 'Какие цифры можно поставить вместо * в числе 123*, чтобы оно делилось на 4?',
        'answer': '2, 6'},
    {   'id': 5177,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делимость на 8',
        'text': 'Какие цифры можно поставить вместо * в числе 123*, чтобы оно делилось на 8?',
        'answer': '2'},
    {   'id': 5178,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Делимость на 25',
        'text': 'Какие цифры можно поставить вместо * в числе 12*5, чтобы оно делилось на 25?',
        'answer': '2, 7'},
    {   'id': 5179,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Среднее арифметическое 2',
        'text': 'Среднее арифметическое трех чисел равно 15. Два числа 12 и 18. Найдите третье.',
        'answer': '15'},
    {   'id': 5180,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Среднее арифметическое 3',
        'text': 'Среднее арифметическое четырех чисел равно 20. Три числа 15, 20, 25. Найдите '
                'четвертое.',
        'answer': '20'},
    {   'id': 5181,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь 7',
        'text': 'Длина прямоугольника в 3 раза больше ширины. Периметр 48 см. Найдите площадь.',
        'answer': '108 см²'},
    {   'id': 5182,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Площадь 8',
        'text': 'Ширина прямоугольника в 2 раза меньше длины. Периметр 36 см. Найдите площадь.',
        'answer': '72 см²'},
    {   'id': 5183,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Четные числа 3',
        'text': 'Сколько четных четырехзначных чисел?',
        'answer': '4500'},
    {   'id': 5184,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'Нечетные числа 3',
        'text': 'Сколько нечетных четырехзначных чисел?',
        'answer': '4500'},
    {   'id': 5185,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Количество чисел',
        'text': 'Сколько четырехзначных чисел можно составить из цифр 1,2,3,4,5,6, если цифры не '
                'повторяются?',
        'answer': '360'},
    {   'id': 5186,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 2,
        'title': 'Количество чисел 2',
        'text': 'Сколько четырехзначных чисел можно составить из цифр 0,1,2,3,4,5, если цифры не '
                'повторяются?',
        'answer': '300'},
    {   'id': 5187,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 6',
        'text': 'В первой корзине в 4 раза больше яблок, чем во второй. Если из первой переложить '
                '15 яблок во вторую, станет поровну. Сколько яблок в каждой?',
        'answer': '40 и 10'},
    {   'id': 5188,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Задача 7',
        'text': 'Во второй корзине в 3 раза меньше яблок, чем в первой. Если в первую добавить 10 '
                'яблок, а из второй убрать 5, то в первой станет в 4 раза больше. Сколько яблок в '
                'каждой?',
        'answer': '45 и 15'},
    {   'id': 5189,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД 5',
        'text': 'Найдите НОД(84, 126)',
        'answer': '42'},
    {   'id': 5190,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОД 6',
        'text': 'Найдите НОД(105, 165)',
        'answer': '15'},
    {   'id': 5191,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОК 5',
        'text': 'Найдите НОК(12, 18, 24)',
        'answer': '72'},
    {   'id': 5192,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 2,
        'title': 'НОК 6',
        'text': 'Найдите НОК(15, 20, 30)',
        'answer': '60'},
    {   'id': 5193,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 12',
        'text': '2/3 + 3/4 + 5/6 = ?',
        'answer': '2 1/4'},
    {   'id': 5194,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 13',
        'text': '3/5 - 1/3 + 2/15 = ?',
        'answer': '2/5'},
    {   'id': 5195,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 14',
        'text': '5/6 × 3/10 × 4/7 = ?',
        'answer': '1/7'},
    {   'id': 5196,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 2,
        'title': 'Дроби 15',
        'text': '2/3 : 4/5 × 3/5 = ?',
        'answer': '1/2'},
    {   'id': 5197,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Объем 4',
        'text': 'Объем прямоугольного параллелепипеда 120 см³. Длина 6 см, ширина 5 см. Найдите '
                'высоту.',
        'answer': '4 см'},
    {   'id': 5198,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Объем 5',
        'text': 'Объем куба 64 см³. Найдите ребро.',
        'answer': '4 см'},
    {   'id': 5199,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Объем 6',
        'text': 'Объем куба 125 см³. Найдите ребро.',
        'answer': '5 см'},
    {   'id': 5200,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 2,
        'title': 'Объем 7',
        'text': 'Объем прямоугольного параллелепипеда 180 см³. Длина 6 см, высота 5 см. Найдите '
                'ширину.',
        'answer': '6 см'},
    {   'id': 5201,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Остатки 4',
        'text': 'Найдите наименьшее число, которое при делении на 5 дает остаток 4, а при делении '
                'на 7 дает остаток 5.',
        'answer': '19'},
    {   'id': 5202,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Остатки 5',
        'text': 'Найдите наименьшее число, которое при делении на 4 дает остаток 3, на 5 - остаток '
                '4, на 6 - остаток 5.',
        'answer': '59'},
    {   'id': 5203,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Простые числа 7',
        'text': 'Сколько простых чисел в промежутке от 100 до 120?',
        'answer': '5 (101,103,107,109,113)'},
    {   'id': 5204,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Простые числа 8',
        'text': 'Сколько простых чисел в промежутке от 150 до 170?',
        'answer': '4 (151,157,163,167)'},
    {   'id': 5205,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Делители 8',
        'text': 'Сколько делителей у числа 144?',
        'answer': '15'},
    {   'id': 5206,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Делители 9',
        'text': 'Сколько делителей у числа 180?',
        'answer': '18'},
    {   'id': 5207,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Делители 10',
        'text': 'Сколько делителей у числа 200?',
        'answer': '12'},
    {   'id': 5208,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Задача 8',
        'text': 'Три числа относятся как 2:3:5. Их сумма 100. Найдите числа.',
        'answer': '20, 30, 50'},
    {   'id': 5209,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Задача 9',
        'text': 'Четыре числа относятся как 1:2:3:4. Их сумма 200. Найдите числа.',
        'answer': '20, 40, 60, 80'},
    {   'id': 5210,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Задача 10',
        'text': 'Разделите число 120 на три части в отношении 2:3:5.',
        'answer': '24, 36, 60'},
    {   'id': 5211,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Задача 11',
        'text': 'Разделите число 180 на три части в отношении 3:4:5.',
        'answer': '45, 60, 75'},
    {   'id': 5212,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 3,
        'title': 'Периметр 7',
        'text': 'Периметр прямоугольника 56 см. Длина в 3 раза больше ширины. Найдите площадь.',
        'answer': '147 см²'},
    {   'id': 5213,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 3,
        'title': 'Периметр 8',
        'text': 'Периметр прямоугольника 48 см. Длина на 6 см больше ширины. Найдите площадь.',
        'answer': '135 см²'},
    {   'id': 5214,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 3,
        'title': 'Периметр 9',
        'text': 'Периметр квадрата равен периметру прямоугольника со сторонами 8 см и 12 см. '
                'Найдите сторону квадрата.',
        'answer': '10 см'},
    {   'id': 5215,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 3,
        'title': 'Площадь 9',
        'text': 'Площадь квадрата равна площади прямоугольника со сторонами 9 см и 16 см. Найдите '
                'сторону квадрата.',
        'answer': '12 см'},
    {   'id': 5216,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'НОД и НОК 3',
        'text': 'Произведение двух чисел равно 288, НОД равен 12. Найдите НОК.',
        'answer': '24'},
    {   'id': 5217,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'НОД и НОК 4',
        'text': 'НОК двух чисел равен 180, НОД равен 15. Одно число 45. Найдите другое.',
        'answer': '60'},
    {   'id': 5218,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'НОД и НОК 5',
        'text': 'НОК двух чисел равен 240, НОД равен 20. Найдите числа.',
        'answer': '20 и 240 или 40 и 120 или 60 и 80'},
    {   'id': 5219,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 3,
        'title': 'Перестановки 5',
        'text': "Сколько слов можно составить из букв слова 'МАТЕМАТИКА'?",
        'answer': '151200'},
    {   'id': 5220,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 3,
        'title': 'Перестановки 6',
        'text': "Сколько слов можно составить из букв слова 'КОМБИНАТОРИКА'?",
        'answer': '3113510400'},
    {   'id': 5221,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Уравнение 11',
        'text': '5(2x - 3) - 4(3x - 2) = 7',
        'answer': 'x = -2'},
    {   'id': 5222,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Уравнение 12',
        'text': '3(4x - 1) - 2(5x - 3) = 10',
        'answer': 'x = 2.5'},
    {   'id': 5223,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Уравнение 13',
        'text': '2(3x - 1) + 3(2x - 5) = 17',
        'answer': 'x = 3'},
    {   'id': 5224,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Проценты 10',
        'text': 'Цена товара сначала повысилась на 20%, потом снизилась на 20%. Как изменилась '
                'цена?',
        'answer': 'Снизилась на 4%'},
    {   'id': 5225,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Проценты 11',
        'text': 'Цена товара сначала снизилась на 20%, потом повысилась на 20%. Как изменилась '
                'цена?',
        'answer': 'Снизилась на 4%'},
    {   'id': 5226,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Проценты 12',
        'text': 'Цена товара повысилась на 25%. На сколько процентов нужно снизить новую цену, '
                'чтобы вернуться к исходной?',
        'answer': '20%'},
    {   'id': 5227,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 3,
        'title': 'Проценты 13',
        'text': 'Цена товара снизилась на 25%. На сколько процентов нужно повысить новую цену, '
                'чтобы вернуться к исходной?',
        'answer': '33 1/3%'},
    {   'id': 5228,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Делимость 2',
        'text': 'Найдите все числа вида 3x5y, которые делятся на 36.',
        'answer': '3150, 3456, 3750? (уточнить)'},
    {   'id': 5229,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 3,
        'title': 'Делимость 3',
        'text': 'Найдите все числа вида 2x3y, которые делятся на 45.',
        'answer': '2340, 2835?'},
    {   'id': 5230,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 3,
        'title': 'Углы 7',
        'text': 'Один из углов треугольника в 2 раза больше второго и на 20° меньше третьего. '
                'Найдите углы.',
        'answer': '40°, 80°, 60°'}]
