PROBLEMS_DB = [   {   'id': 8144,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 2,
        'title': 'Прямоугольник 4',
        'text': 'Диагональ 17, периметр 46. Найдите стороны.',
        'answer': '15 и 8'},
    {   'id': 8145,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 2,
        'title': 'Квадрат 4',
        'text': 'Радиус описанной окружности квадрата 5√2. Найдите сторону.',
        'answer': '10'},
    {   'id': 8146,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 2,
        'title': 'Трапеция 4',
        'text': 'Основания 10 и 16, боковые стороны 5 и 7. Найдите высоту.',
        'answer': '4'},
    {   'id': 8147,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 2,
        'title': 'Арифметическая прогрессия 5',
        'text': 'a1 = 4, a7 = 22. Найдите S7.',
        'answer': '91'},
    {   'id': 8148,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 2,
        'title': 'Арифметическая прогрессия 6',
        'text': 'a3 = 8, a5 = 14. Найдите a1 и d.',
        'answer': 'a1 = 2, d = 3'},
    {   'id': 8149,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 2,
        'title': 'Геометрическая прогрессия 5',
        'text': 'b1 = 3, b4 = 24. Найдите q и S4.',
        'answer': 'q = 2, S4 = 45'},
    {   'id': 8150,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 2,
        'title': 'Геометрическая прогрессия 6',
        'text': 'b2 = 12, b5 = 324. Найдите b1 и q.',
        'answer': 'b1 = 4, q = 3'},
    {   'id': 8151,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные уравнения 20',
        'text': 'Решите уравнение: 2x^2 - 7x + 5 = 0',
        'answer': 'x1 = 2.5, x2 = 1'},
    {   'id': 8152,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные уравнения 21',
        'text': 'Решите уравнение: 3x^2 + 8x - 11 = 0',
        'answer': 'x1 = 1, x2 = -11/3'},
    {   'id': 8153,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные уравнения 22',
        'text': 'Решите уравнение: 4x^2 - 9x + 2 = 0',
        'answer': 'x1 = 2, x2 = 0.25'},
    {   'id': 8154,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные уравнения 23',
        'text': 'Решите уравнение: 5x^2 + 12x - 9 = 0',
        'answer': 'x1 = 0.6, x2 = -3'},
    {   'id': 8155,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные уравнения 24',
        'text': 'Решите уравнение: 6x^2 - 19x + 10 = 0',
        'answer': 'x1 = 2.5, x2 = 2/3'},
    {   'id': 8156,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Биквадратные уравнения',
        'text': 'Решите уравнение: x^4 - 5x^2 + 4 = 0',
        'answer': 'x = ±1, ±2'},
    {   'id': 8157,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Биквадратные уравнения 2',
        'text': 'Решите уравнение: x^4 - 10x^2 + 9 = 0',
        'answer': 'x = ±1, ±3'},
    {   'id': 8158,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Биквадратные уравнения 3',
        'text': 'Решите уравнение: 2x^4 - 5x^2 + 2 = 0',
        'answer': 'x = ±√2, ±1/√2'},
    {   'id': 8159,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Теорема Виета 5',
        'text': 'Найдите сумму квадратов корней: x^2 - 6x + 8 = 0',
        'answer': '20'},
    {   'id': 8160,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Теорема Виета 6',
        'text': 'Найдите сумму кубов корней: x^2 - 4x + 3 = 0',
        'answer': '28'},
    {   'id': 8161,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Дискриминант 5',
        'text': 'При каких a уравнение x^2 + (a-3)x + 4 = 0 имеет два корня?',
        'answer': 'a < -1 или a > 7'},
    {   'id': 8162,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Дискриминант 6',
        'text': 'При каких a уравнение 2x^2 + ax + 8 = 0 имеет один корень?',
        'answer': 'a = ±8'},
    {   'id': 8163,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Четырехугольники 3',
        'text': 'Углы параллелограмма относятся как 2:3. Найдите углы.',
        'answer': '72°, 108°, 72°, 108°'},
    {   'id': 8164,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Прямоугольник 5',
        'text': 'Периметр прямоугольника 68, диагональ 26. Найдите стороны.',
        'answer': '24 и 10'},
    {   'id': 8165,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Ромб 5',
        'text': 'Сторона ромба 13, разность диагоналей 14. Найдите диагонали.',
        'answer': '24 и 10'},
    {   'id': 8166,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадрат 5',
        'text': 'Площадь квадрата равна площади прямоугольника 18×8. Найдите сторону квадрата.',
        'answer': '12'},
    {   'id': 8167,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Трапеция 5',
        'text': 'Основания 6 и 14, диагонали 13 и 15. Найдите высоту.',
        'answer': '12'},
    {   'id': 8168,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Окружность 5',
        'text': 'Хорда стягивает дугу 120°. Радиус 12. Найдите длину хорды.',
        'answer': '12√3'},
    {   'id': 8169,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Вписанный угол 4',
        'text': 'Вписанный угол 25°. Найдите центральный угол.',
        'answer': '50°'},
    {   'id': 8170,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Центральный угол 4',
        'text': 'Центральный угол 140°. Найдите вписанный угол.',
        'answer': '70°'},
    {   'id': 8171,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Степени 6',
        'text': 'Вычислите: (3^-1 + 2^-2)^-2',
        'answer': '144/49'},
    {   'id': 8172,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Степени 7',
        'text': 'Вычислите: (4^-2 - 2^-3)^-1',
        'answer': '-16'},
    {   'id': 8173,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные корни 11',
        'text': 'Упростите: (√7 + √5)^2 - (√7 - √5)^2',
        'answer': '4√35'},
    {   'id': 8174,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные корни 12',
        'text': 'Упростите: √(9 - 4√5)',
        'answer': '√5 - 2'},
    {   'id': 8175,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадратные корни 13',
        'text': 'Упростите: √(14 + 6√5)',
        'answer': '3 + √5'},
    {   'id': 8176,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Теорема Пифагора 7',
        'text': 'Катет на 2 меньше гипотенузы, другой катет 6. Найдите гипотенузу.',
        'answer': '10'},
    {   'id': 8177,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Теорема Пифагора 8',
        'text': 'Гипотенуза на 4 больше одного катета и на 2 больше другого. Найдите стороны.',
        'answer': '6, 8, 10'},
    {   'id': 8178,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 3,
        'title': 'Простые числа 5',
        'text': 'Сколько простых чисел от 400 до 450?',
        'answer': '8'},
    {   'id': 8179,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 3,
        'title': 'Простые числа 6',
        'text': 'Сколько простых чисел от 500 до 550?',
        'answer': '8'},
    {   'id': 8180,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 3,
        'title': 'Перестановки 4',
        'text': "Сколько слов из букв слова 'МАТЕМАТИКА'?",
        'answer': '151200'},
    {   'id': 8181,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 3,
        'title': 'Сочетания 4',
        'text': 'Сколькими способами выбрать 3 из 12 и 2 из 8?',
        'answer': '6160'},
    {   'id': 8182,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 3,
        'title': 'Размещения 4',
        'text': 'Сколько пятизначных чисел из цифр 0-7 без повторений?',
        'answer': '5880'},
    {   'id': 8183,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Неравенства 9',
        'text': 'Решите неравенство: (x-2)(x+3) > 0',
        'answer': 'x < -3 или x > 2'},
    {   'id': 8184,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Неравенства 10',
        'text': 'Решите неравенство: (2x-5)(x+4) ≤ 0',
        'answer': '-4 ≤ x ≤ 2.5'},
    {   'id': 8185,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Неравенства 11',
        'text': 'Решите неравенство: (x-3)^2 > 0',
        'answer': 'x ≠ 3'},
    {   'id': 8186,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Подобие 7',
        'text': 'В треугольнике проведена средняя линия. Площадь маленького 10. Найдите площадь '
                'большого.',
        'answer': '40'},
    {   'id': 8187,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Подобие 8',
        'text': 'Сходственные стороны 3 и 5, разность площадей 64. Найдите площади.',
        'answer': '36 и 100'},
    {   'id': 8188,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Функции 7',
        'text': 'Найдите ось симметрии параболы y = 2x^2 - 8x + 5',
        'answer': 'x = 2'},
    {   'id': 8189,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Функции 8',
        'text': 'Найдите наибольшее значение функции y = -x^2 + 6x - 5',
        'answer': '4'},
    {   'id': 8190,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Касательная 4',
        'text': 'Из точки к окружности проведены касательная и секущая. Касательная 15, секущая '
                '25. Найдите внешнюю часть секущей.',
        'answer': '9'},
    {   'id': 8191,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Хорда 4',
        'text': 'Две хорды пересекаются. Произведение отрезков одной 20, другой 16 и 4. Найдите '
                'отрезки первой.',
        'answer': '10 и 2'},
    {   'id': 8192,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Секущая 4',
        'text': 'Две секущие из одной точки: внешние части 4 и 5, внутренние части одной 6. '
                'Найдите внутреннюю часть другой.',
        'answer': '8'},
    {   'id': 8193,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Системы уравнений 8',
        'text': 'Решите систему: {x^2 + y^2 = 25, xy = 12}',
        'answer': '(3,4) или (4,3) или (-3,-4) или (-4,-3)'},
    {   'id': 8194,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Системы уравнений 9',
        'text': 'Решите систему: {x^2 - xy + y^2 = 7, x + y = 5}',
        'answer': '(2,3) или (3,2)'},
    {   'id': 8195,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Параллелограмм 4',
        'text': 'Стороны 10 и 14, угол между диагоналями 60°, диагонали относятся как 3:4. Найдите '
                'диагонали.',
        'answer': '12 и 16'},
    {   'id': 8196,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Ромб 6',
        'text': 'Диагонали 16 и 30. Найдите радиус вписанной окружности.',
        'answer': '120/17'},
    {   'id': 8197,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Прямоугольник 6',
        'text': 'Диагональ 20, угол между диагоналями 120°. Найдите площадь.',
        'answer': '100√3'},
    {   'id': 8198,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Квадрат 6',
        'text': 'Радиус вписанной окружности квадрата 4√2. Найдите диагональ.',
        'answer': '16'},
    {   'id': 8199,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 3,
        'title': 'Трапеция 6',
        'text': 'Основания 8 и 18, диагонали 15 и 20. Найдите площадь.',
        'answer': '156'},
    {   'id': 8200,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 3,
        'title': 'Арифметическая прогрессия 7',
        'text': 'Сумма первых 10 членов 155, разность 3. Найдите a1.',
        'answer': '2'},
    {   'id': 8201,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные уравнения 25',
        'text': 'Решите уравнение: 3x^2 - 11x + 6 = 0',
        'answer': 'x1 = 3, x2 = 2/3'},
    {   'id': 8202,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные уравнения 26',
        'text': 'Решите уравнение: 4x^2 - 15x + 9 = 0',
        'answer': 'x1 = 3, x2 = 0.75'},
    {   'id': 8203,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные уравнения 27',
        'text': 'Решите уравнение: 5x^2 - 18x + 9 = 0',
        'answer': 'x1 = 3, x2 = 0.6'},
    {   'id': 8204,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные уравнения 28',
        'text': 'Решите уравнение: 6x^2 - 23x + 20 = 0',
        'answer': 'x1 = 2.5, x2 = 4/3'},
    {   'id': 8205,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные уравнения 29',
        'text': 'Решите уравнение: 7x^2 - 26x + 15 = 0',
        'answer': 'x1 = 3, x2 = 5/7'},
    {   'id': 8206,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Дробно-рациональные уравнения',
        'text': 'Решите: (x+2)/(x-1) = 3',
        'answer': 'x = 2.5'},
    {   'id': 8207,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Дробно-рациональные уравнения 2',
        'text': 'Решите: 1/x + 1/(x+3) = 1/2',
        'answer': 'x = 3 или x = -6'},
    {   'id': 8208,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Дробно-рациональные уравнения 3',
        'text': 'Решите: (2x+1)/(x-2) = (x-4)/(x+1)',
        'answer': 'x = 1 или x = -3'},
    {   'id': 8209,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Теорема Виета 7',
        'text': 'Разность корней уравнения x^2 - 8x + q = 0 равна 2. Найдите q.',
        'answer': '15'},
    {   'id': 8210,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Теорема Виета 8',
        'text': 'Сумма квадратов корней уравнения x^2 - 10x + q = 0 равна 58. Найдите q.',
        'answer': '21'},
    {   'id': 8211,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Дискриминант 7',
        'text': 'При каких a уравнение x^2 + (a+2)x + 9 = 0 имеет два различных корня?',
        'answer': 'a < -8 или a > 4'},
    {   'id': 8212,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Дискриминант 8',
        'text': 'При каких a уравнение 3x^2 + ax + 27 = 0 имеет один корень?',
        'answer': 'a = ±18'},
    {   'id': 8213,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Четырехугольники 4',
        'text': 'Найдите углы параллелограмма, если они относятся как 3:7.',
        'answer': '54°, 126°, 54°, 126°'},
    {   'id': 8214,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Прямоугольник 7',
        'text': 'Периметр прямоугольника 56, диагональ 20. Найдите стороны.',
        'answer': '16 и 12'},
    {   'id': 8215,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Ромб 7',
        'text': 'Сумма диагоналей 34, сторона 13. Найдите диагонали.',
        'answer': '24 и 10'},
    {   'id': 8216,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадрат 7',
        'text': 'Периметр квадрата 48. Найдите радиус описанной окружности.',
        'answer': '6√2'},
    {   'id': 8217,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Трапеция 7',
        'text': 'Основания 12 и 20, боковые стороны 7 и 9. Найдите площадь.',
        'answer': '96'},
    {   'id': 8218,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Окружность 6',
        'text': 'Хорда 16, расстояние до центра 6. Найдите радиус.',
        'answer': '10'},
    {   'id': 8219,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Вписанный угол 5',
        'text': 'Вписанный угол в 3 раза меньше центрального. Найдите углы.',
        'answer': '45° и 135°'},
    {   'id': 8220,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Центральный угол 5',
        'text': 'Центральный угол на 50° больше вписанного. Найдите углы.',
        'answer': '50° и 100°'},
    {   'id': 8221,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Степени 8',
        'text': 'Вычислите: (3^2 × 5^3) / (3^4 × 5^2)',
        'answer': '5/9'},
    {   'id': 8222,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Степени 9',
        'text': 'Вычислите: (2^5 × 3^-2) / (2^3 × 3^-4)',
        'answer': '36'},
    {   'id': 8223,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные корни 14',
        'text': 'Упростите: √(7 + 2√6)',
        'answer': '√6 + 1'},
    {   'id': 8224,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные корни 15',
        'text': 'Упростите: √(8 - 2√7)',
        'answer': '√7 - 1'},
    {   'id': 8225,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадратные корни 16',
        'text': 'Упростите: √(11 + 6√2)',
        'answer': '3 + √2'},
    {   'id': 8226,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Теорема Пифагора 9',
        'text': 'Катеты относятся как 8:15, гипотенуза 68. Найдите катеты.',
        'answer': '32 и 60'},
    {   'id': 8227,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Теорема Пифагора 10',
        'text': 'Периметр прямоугольного треугольника 84, гипотенуза 37. Найдите катеты.',
        'answer': '12 и 35'},
    {   'id': 8228,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 4,
        'title': 'Простые числа 7',
        'text': 'Сколько простых чисел от 600 до 650?',
        'answer': '7'},
    {   'id': 8229,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 4,
        'title': 'Простые числа 8',
        'text': 'Сколько простых чисел от 700 до 750?',
        'answer': '5'},
    {   'id': 8230,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 4,
        'title': 'Перестановки 5',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛОГРАММ'?",
        'answer': '908107200'},
    {   'id': 8231,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 4,
        'title': 'Сочетания 5',
        'text': 'Сколькими способами выбрать 4 из 15 и 3 из 12?',
        'answer': '225225'},
    {   'id': 8232,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 4,
        'title': 'Размещения 5',
        'text': 'Сколько шестизначных чисел из цифр 0-8 без повторений?',
        'answer': '60480'},
    {   'id': 8233,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Неравенства 12',
        'text': 'Решите неравенство: x^2 - 7x + 12 > 0',
        'answer': 'x < 3 или x > 4'},
    {   'id': 8234,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Неравенства 13',
        'text': 'Решите неравенство: -x^2 + 6x - 8 ≥ 0',
        'answer': '2 ≤ x ≤ 4'},
    {   'id': 8235,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Неравенства 14',
        'text': 'Решите неравенство: (x-4)(x+2) < 0',
        'answer': '-2 < x < 4'},
    {   'id': 8236,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Подобие 9',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 30. '
                'Найдите площадь треугольника.',
        'answer': '40'},
    {   'id': 8237,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Подобие 10',
        'text': 'Периметры подобных треугольников 25 и 35, разность площадей 48. Найдите площади.',
        'answer': '75 и 147'},
    {   'id': 8238,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Функции 9',
        'text': 'Найдите область значений функции y = x^2 - 4x + 3',
        'answer': 'y ≥ -1'},
    {   'id': 8239,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Функции 10',
        'text': 'Найдите область значений функции y = -2x^2 + 8x - 5',
        'answer': 'y ≤ 3'},
    {   'id': 8240,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Касательная 5',
        'text': 'Из точки к окружности проведены две касательные. Угол между ними 60°, расстояние '
                'до центра 12. Найдите радиус.',
        'answer': '6'},
    {   'id': 8241,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Хорда 5',
        'text': 'Две хорды пересекаются. Отрезки одной 6 и 8, отрезки другой 4 и 12. Проверьте, '
                'верно ли?',
        'answer': '6×8 = 48, 4×12 = 48, верно'},
    {   'id': 8242,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Секущая 5',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 4 и 5, внутренние '
                'части первой 6. Найдите внутреннюю часть второй.',
        'answer': '7'},
    {   'id': 8243,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Системы уравнений 10',
        'text': 'Решите систему: {x^2 - xy + y^2 = 19, x - y = 3}',
        'answer': '(5,2) или (-2,-5)'},
    {   'id': 8244,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Системы уравнений 11',
        'text': 'Решите систему: {x^2 + 2y^2 = 18, x - y = 0}',
        'answer': '(√6,√6) или (-√6,-√6)'},
    {   'id': 8245,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Параллелограмм 5',
        'text': 'Диагонали 12 и 16, угол между ними 90°. Найдите стороны.',
        'answer': '10 и 10 (ромб)'},
    {   'id': 8246,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Ромб 8',
        'text': 'Площадь ромба 240, одна диагональ 16. Найдите сторону и вторую диагональ.',
        'answer': '30, 17'},
    {   'id': 8247,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Прямоугольник 8',
        'text': 'Диагональ 26, периметр 68. Найдите стороны.',
        'answer': '24 и 10'},
    {   'id': 8248,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Квадрат 8',
        'text': 'Диагональ 12. Найдите радиус вписанной окружности.',
        'answer': '3√2'},
    {   'id': 8249,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 4,
        'title': 'Трапеция 8',
        'text': 'Основания 9 и 21, диагонали 17 и 25. Найдите площадь.',
        'answer': '180'},
    {   'id': 8250,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 4,
        'title': 'Арифметическая прогрессия 8',
        'text': 'Сумма первых 12 членов 222, a1 = 2. Найдите разность.',
        'answer': '3'},
    {   'id': 8251,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 30',
        'text': 'Решите уравнение: 2x^2 - 9x + 10 = 0',
        'answer': 'x1 = 2.5, x2 = 2'},
    {   'id': 8252,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 31',
        'text': 'Решите уравнение: 3x^2 - 14x + 15 = 0',
        'answer': 'x1 = 3, x2 = 5/3'},
    {   'id': 8253,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 32',
        'text': 'Решите уравнение: 4x^2 - 17x + 15 = 0',
        'answer': 'x1 = 3, x2 = 1.25'},
    {   'id': 8254,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 33',
        'text': 'Решите уравнение: 5x^2 - 21x + 18 = 0',
        'answer': 'x1 = 3, x2 = 1.2'},
    {   'id': 8255,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 34',
        'text': 'Решите уравнение: 6x^2 - 19x + 10 = 0',
        'answer': 'x1 = 2.5, x2 = 2/3'},
    {   'id': 8256,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 35',
        'text': 'Решите уравнение: 7x^2 - 22x + 15 = 0',
        'answer': 'x1 = 3, x2 = 5/7'},
    {   'id': 8257,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 36',
        'text': 'Решите уравнение: 8x^2 - 25x + 12 = 0',
        'answer': 'x1 = 2.5, x2 = 0.6'},
    {   'id': 8258,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 37',
        'text': 'Решите уравнение: 9x^2 - 28x + 15 = 0',
        'answer': 'x1 = 3, x2 = 5/9'},
    {   'id': 8259,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные уравнения 38',
        'text': 'Решите уравнение: 10x^2 - 31x + 15 = 0',
        'answer': 'x1 = 2.5, x2 = 0.6'},
    {   'id': 8260,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Дробно-рациональные уравнения 4',
        'text': 'Решите: (x+3)/(x-2) = (x+2)/(x-3)',
        'answer': 'x = 2.5'},
    {   'id': 8261,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Дробно-рациональные уравнения 5',
        'text': 'Решите: 1/(x-1) + 1/(x+2) = 3/4',
        'answer': 'x = 3 или x = -4'},
    {   'id': 8262,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Дробно-рациональные уравнения 6',
        'text': 'Решите: (2x+3)/(x+1) = (3x-4)/(x-2)',
        'answer': 'x = 5'},
    {   'id': 8263,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Теорема Виета 9',
        'text': 'Разность корней уравнения x^2 - 12x + q = 0 равна 4. Найдите q.',
        'answer': '32'},
    {   'id': 8264,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Теорема Виета 10',
        'text': 'Сумма квадратов корней уравнения x^2 - 14x + q = 0 равна 100. Найдите q.',
        'answer': '48'},
    {   'id': 8265,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Дискриминант 9',
        'text': 'При каких a уравнение x^2 + (a-4)x + 9 = 0 имеет два различных корня?',
        'answer': 'a < -2 или a > 10'},
    {   'id': 8266,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Дискриминант 10',
        'text': 'При каких a уравнение 2x^2 + ax + 18 = 0 имеет один корень?',
        'answer': 'a = ±12'},
    {   'id': 8267,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Четырехугольники 5',
        'text': 'Найдите углы параллелограмма, если они относятся как 5:13.',
        'answer': '50°, 130°, 50°, 130°'},
    {   'id': 8268,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Прямоугольник 9',
        'text': 'Периметр прямоугольника 84, диагональ 30. Найдите стороны.',
        'answer': '24 и 18'},
    {   'id': 8269,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Ромб 9',
        'text': 'Сумма диагоналей 46, сторона 17. Найдите диагонали.',
        'answer': '30 и 16'},
    {   'id': 8270,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадрат 9',
        'text': 'Периметр квадрата 64. Найдите радиус вписанной окружности.',
        'answer': '8'},
    {   'id': 8271,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Трапеция 9',
        'text': 'Основания 14 и 22, боковые стороны 9 и 13. Найдите площадь.',
        'answer': '144'},
    {   'id': 8272,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Окружность 7',
        'text': 'Хорда 18, расстояние до центра 12. Найдите радиус.',
        'answer': '15'},
    {   'id': 8273,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Вписанный угол 6',
        'text': 'Вписанный угол в 4 раза меньше центрального. Найдите углы.',
        'answer': '36° и 144°'},
    {   'id': 8274,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Центральный угол 6',
        'text': 'Центральный угол на 60° больше вписанного. Найдите углы.',
        'answer': '60° и 120°'},
    {   'id': 8275,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Степени 10',
        'text': 'Вычислите: (2^4 × 3^5) / (2^6 × 3^3)',
        'answer': '9/4'},
    {   'id': 8276,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Степени 11',
        'text': 'Вычислите: (5^3 × 4^4) / (5^2 × 4^2)',
        'answer': '80'},
    {   'id': 8277,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные корни 17',
        'text': 'Упростите: √(10 + 2√21)',
        'answer': '√7 + √3'},
    {   'id': 8278,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные корни 18',
        'text': 'Упростите: √(12 - 2√35)',
        'answer': '√7 - √5'},
    {   'id': 8279,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Квадратные корни 19',
        'text': 'Упростите: √(13 + 4√3)',
        'answer': '2√3 + 1'},
    {   'id': 8280,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Теорема Пифагора 11',
        'text': 'Катеты относятся как 12:35, гипотенуза 74. Найдите катеты.',
        'answer': '24 и 70'},
    {   'id': 8281,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Теорема Пифагора 12',
        'text': 'Периметр прямоугольного треугольника 90, гипотенуза 39. Найдите катеты.',
        'answer': '15 и 36'},
    {   'id': 8282,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 5,
        'title': 'Простые числа 9',
        'text': 'Сколько простых чисел от 800 до 850?',
        'answer': '5'},
    {   'id': 8283,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 5,
        'title': 'Простые числа 10',
        'text': 'Сколько простых чисел от 900 до 950?',
        'answer': '4'},
    {   'id': 8284,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 5,
        'title': 'Перестановки 6',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 8285,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 5,
        'title': 'Сочетания 6',
        'text': 'Сколькими способами выбрать 5 из 18 и 4 из 16?',
        'answer': '8568 × 1820 = 15593760'},
    {   'id': 8286,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 5,
        'title': 'Размещения 6',
        'text': 'Сколько семизначных чисел из цифр 0-8 без повторений?',
        'answer': '181440'},
    {   'id': 8287,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Неравенства 15',
        'text': 'Решите неравенство: x^2 - 9x + 20 > 0',
        'answer': 'x < 4 или x > 5'},
    {   'id': 8288,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Неравенства 16',
        'text': 'Решите неравенство: -x^2 + 8x - 15 ≥ 0',
        'answer': '3 ≤ x ≤ 5'},
    {   'id': 8289,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Неравенства 17',
        'text': 'Решите неравенство: (x-5)(x+3) < 0',
        'answer': '-3 < x < 5'},
    {   'id': 8290,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Подобие 11',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 45. '
                'Найдите площадь треугольника.',
        'answer': '60'},
    {   'id': 8291,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Подобие 12',
        'text': 'Периметры подобных треугольников 30 и 48, разность площадей 140. Найдите площади.',
        'answer': '100 и 240'},
    {   'id': 8292,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Функции 11',
        'text': 'Найдите область значений функции y = x^2 - 6x + 5',
        'answer': 'y ≥ -4'},
    {   'id': 8293,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Функции 12',
        'text': 'Найдите область значений функции y = -3x^2 + 12x - 7',
        'answer': 'y ≤ 5'},
    {   'id': 8294,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Касательная 6',
        'text': 'Из точки к окружности проведены две касательные. Угол между ними 90°, радиус 5. '
                'Найдите расстояние до центра.',
        'answer': '5√2'},
    {   'id': 8295,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Хорда 6',
        'text': 'Две хорды пересекаются. Отрезки одной 9 и 4, отрезки другой 6 и 6. Проверьте, '
                'верно ли?',
        'answer': '9×4 = 36, 6×6 = 36, верно'},
    {   'id': 8296,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Секущая 6',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 6 и 8, внутренние '
                'части первой 9. Найдите внутреннюю часть второй.',
        'answer': '7'},
    {   'id': 8297,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Системы уравнений 12',
        'text': 'Решите систему: {x^2 + xy + y^2 = 21, x + y = 5}',
        'answer': '(2,3) или (3,2)'},
    {   'id': 8298,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 5,
        'title': 'Системы уравнений 13',
        'text': 'Решите систему: {x^2 + y^2 = 34, xy = 15}',
        'answer': '(5,3) или (3,5) или (-5,-3) или (-3,-5)'},
    {   'id': 8299,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Параллелограмм 6',
        'text': 'Диагонали 14 и 18, угол между ними 120°. Найдите стороны.',
        'answer': '√(67) и √(139)'},
    {   'id': 8300,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 5,
        'title': 'Ромб 10',
        'text': 'Площадь ромба 384, одна диагональ 24. Найдите сторону и вторую диагональ.',
        'answer': '32, 20'},
    {   'id': 8301,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные уравнения 39',
        'text': 'Решите уравнение: 2x^2 - 11x + 12 = 0',
        'answer': 'x1 = 4, x2 = 1.5'},
    {   'id': 8302,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные уравнения 40',
        'text': 'Решите уравнение: 3x^2 - 16x + 16 = 0',
        'answer': 'x1 = 4, x2 = 4/3'},
    {   'id': 8303,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные уравнения 41',
        'text': 'Решите уравнение: 4x^2 - 19x + 12 = 0',
        'answer': 'x1 = 4, x2 = 0.75'},
    {   'id': 8304,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные уравнения 42',
        'text': 'Решите уравнение: 5x^2 - 22x + 21 = 0',
        'answer': 'x1 = 3, x2 = 1.4'},
    {   'id': 8305,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные уравнения 43',
        'text': 'Решите уравнение: 6x^2 - 25x + 21 = 0',
        'answer': 'x1 = 3, x2 = 7/6'},
    {   'id': 8306,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Дробно-рациональные уравнения 7',
        'text': 'Решите: 2/(x-2) + 3/(x+3) = 1',
        'answer': 'x = 4 или x = -5'},
    {   'id': 8307,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Дробно-рациональные уравнения 8',
        'text': 'Решите: (x+4)/(x-4) - (x-4)/(x+4) = 24/5',
        'answer': 'x = 6 или x = -6'},
    {   'id': 8308,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Дробно-рациональные уравнения 9',
        'text': 'Решите: 1/(x+1) + 1/(x+2) = 1/(x+3)',
        'answer': 'x = -1 ± √2'},
    {   'id': 8309,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Виета 11',
        'text': 'Разность корней уравнения x^2 - 16x + q = 0 равна 8. Найдите q.',
        'answer': '48'},
    {   'id': 8310,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Виета 12',
        'text': 'Сумма кубов корней уравнения x^2 - 8x + q = 0 равна 152. Найдите q.',
        'answer': '15'},
    {   'id': 8311,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Дискриминант 11',
        'text': 'При каких a уравнение x^2 + (a-5)x + 16 = 0 имеет два различных корня?',
        'answer': 'a < -3 или a > 13'},
    {   'id': 8312,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Дискриминант 12',
        'text': 'При каких a уравнение 3x^2 + ax + 48 = 0 имеет один корень?',
        'answer': 'a = ±24'},
    {   'id': 8313,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Четырехугольники 6',
        'text': 'Найдите углы параллелограмма, если они относятся как 7:17.',
        'answer': '52.5°, 127.5°, 52.5°, 127.5°'},
    {   'id': 8314,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Прямоугольник 10',
        'text': 'Периметр прямоугольника 92, диагональ 34. Найдите стороны.',
        'answer': '30 и 16'},
    {   'id': 8315,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Ромб 11',
        'text': 'Сумма диагоналей 58, сторона 20. Найдите диагонали.',
        'answer': '40 и 18'},
    {   'id': 8316,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадрат 10',
        'text': 'Площадь квадрата 128. Найдите радиус описанной окружности.',
        'answer': '8'},
    {   'id': 8317,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Трапеция 10',
        'text': 'Основания 16 и 24, боковые стороны 10 и 17. Найдите площадь.',
        'answer': '200'},
    {   'id': 8318,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Окружность 8',
        'text': 'Хорда 20, расстояние до центра 15. Найдите радиус.',
        'answer': '25'},
    {   'id': 8319,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Вписанный угол 7',
        'text': 'Вписанный угол в 5 раз меньше центрального. Найдите углы.',
        'answer': '30° и 150°'},
    {   'id': 8320,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Центральный угол 7',
        'text': 'Центральный угол на 70° больше вписанного. Найдите углы.',
        'answer': '70° и 140°'},
    {   'id': 8321,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Степени 12',
        'text': 'Вычислите: (2^6 × 3^4) / (2^4 × 3^6)',
        'answer': '4/9'},
    {   'id': 8322,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Степени 13',
        'text': 'Вычислите: (5^4 × 6^3) / (5^2 × 6^5)',
        'answer': '25/36'},
    {   'id': 8323,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 20',
        'text': 'Упростите: √(14 + 2√33)',
        'answer': '√11 + √3'},
    {   'id': 8324,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 21',
        'text': 'Упростите: √(15 - 2√56)',
        'answer': '√8 - √7'},
    {   'id': 8325,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 22',
        'text': 'Упростите: √(17 + 6√8)',
        'answer': '3 + √8'},
    {   'id': 8326,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Пифагора 13',
        'text': 'Катеты относятся как 16:63, гипотенуза 130. Найдите катеты.',
        'answer': '32 и 126'},
    {   'id': 8327,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Пифагора 14',
        'text': 'Периметр прямоугольного треугольника 120, гипотенуза 50. Найдите катеты.',
        'answer': '30 и 40'},
    {   'id': 8328,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 6,
        'title': 'Простые числа 11',
        'text': 'Сколько простых чисел от 1000 до 1050?',
        'answer': '5'},
    {   'id': 8329,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 6,
        'title': 'Простые числа 12',
        'text': 'Сколько простых чисел от 1100 до 1150?',
        'answer': '4'},
    {   'id': 8330,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Перестановки 7',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛОГРАММ'?",
        'answer': '908107200'},
    {   'id': 8331,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Сочетания 7',
        'text': 'Сколькими способами выбрать 6 из 20 и 5 из 18?',
        'answer': '38760 × 8568 = 332107680'},
    {   'id': 8332,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Размещения 7',
        'text': 'Сколько восьмизначных чисел из цифр 0-8 без повторений?',
        'answer': '403200'},
    {   'id': 8333,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 18',
        'text': 'Решите неравенство: x^2 - 11x + 30 > 0',
        'answer': 'x < 5 или x > 6'},
    {   'id': 8334,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 19',
        'text': 'Решите неравенство: -x^2 + 10x - 24 ≥ 0',
        'answer': '4 ≤ x ≤ 6'},
    {   'id': 8335,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 20',
        'text': 'Решите неравенство: (x-6)(x+4) < 0',
        'answer': '-4 < x < 6'},
    {   'id': 8336,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Подобие 13',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 63. '
                'Найдите площадь треугольника.',
        'answer': '84'},
    {   'id': 8337,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Подобие 14',
        'text': 'Периметры подобных треугольников 35 и 56, разность площадей 294. Найдите площади.',
        'answer': '150 и 444'},
    {   'id': 8338,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Функции 13',
        'text': 'Найдите область значений функции y = 2x^2 - 8x + 3',
        'answer': 'y ≥ -5'},
    {   'id': 8339,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Функции 14',
        'text': 'Найдите область значений функции y = -4x^2 + 16x - 11',
        'answer': 'y ≤ 5'},
    {   'id': 8340,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Касательная 7',
        'text': 'Из точки к окружности проведены две касательные. Угол между ними 120°, радиус 8. '
                'Найдите расстояние до центра.',
        'answer': '16'},
    {   'id': 8341,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Хорда 7',
        'text': 'Две хорды пересекаются. Отрезки одной 12 и 3, отрезки другой 9 и 4. Проверьте, '
                'верно ли?',
        'answer': '12×3 = 36, 9×4 = 36, верно'},
    {   'id': 8342,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Секущая 7',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 7 и 9, внутренние '
                'части первой 10. Найдите внутреннюю часть второй.',
        'answer': '8'},
    {   'id': 8343,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Системы уравнений 14',
        'text': 'Решите систему: {x^2 + xy + y^2 = 28, x + y = 6}',
        'answer': '(2,4) или (4,2)'},
    {   'id': 8344,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Системы уравнений 15',
        'text': 'Решите систему: {x^2 + y^2 = 41, xy = 20}',
        'answer': '(5,4) или (4,5) или (-5,-4) или (-4,-5)'},
    {   'id': 8345,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Параллелограмм 7',
        'text': 'Диагонали 16 и 20, угол между ними 60°. Найдите стороны.',
        'answer': '√(84) и √(196) = 14'},
    {   'id': 8346,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Ромб 12',
        'text': 'Площадь ромба 480, одна диагональ 30. Найдите сторону и вторую диагональ.',
        'answer': '32, 17'},
    {   'id': 8347,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Прямоугольник 11',
        'text': 'Диагональ 34, периметр 94. Найдите стороны.',
        'answer': '25 и 22? нет, 25 и 22 дают периметр 94'},
    {   'id': 8348,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадрат 11',
        'text': 'Радиус вписанной окружности квадрата 5√2. Найдите диагональ.',
        'answer': '20'},
    {   'id': 8349,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Трапеция 11',
        'text': 'Основания 18 и 26, диагонали 20 и 30. Найдите площадь.',
        'answer': '264'},
    {   'id': 8350,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 9',
        'text': 'Сумма первых 15 членов 300, a1 = 5. Найдите разность.',
        'answer': '2'},
    {   'id': 8351,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 10',
        'text': 'a5 = 20, a10 = 40. Найдите a1 и d.',
        'answer': 'a1 = 4, d = 4'},
    {   'id': 8352,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 7',
        'text': 'b2 = 12, b5 = 96. Найдите b1 и q.',
        'answer': 'b1 = 6, q = 2'},
    {   'id': 8353,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 8',
        'text': 'b3 = 18, b6 = 486. Найдите b1 и q.',
        'answer': 'b1 = 2, q = 3'},
    {   'id': 8354,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 4',
        'text': 'Решите: x^4 - 13x^2 + 36 = 0',
        'answer': 'x = ±2, ±3'},
    {   'id': 8355,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 5',
        'text': 'Решите: x^4 - 20x^2 + 64 = 0',
        'answer': 'x = ±2, ±4'},
    {   'id': 8356,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 6',
        'text': 'Решите: 2x^4 - 9x^2 + 4 = 0',
        'answer': 'x = ±2, ±1/√2'},
    {   'id': 8357,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Окружность 9',
        'text': 'Длина дуги 45° равна 3π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8358,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Окружность 10',
        'text': 'Площадь сектора 60° равна 24π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8359,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Вписанный угол 8',
        'text': 'Вписанный угол на 30° меньше центрального. Найдите углы.',
        'answer': '30° и 60°'},
    {   'id': 8360,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Центральный угол 8',
        'text': 'Центральный угол в 3 раза больше вписанного. Найдите углы.',
        'answer': '45° и 135°'},
    {   'id': 8361,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Степени 14',
        'text': 'Упростите: (2^3 × 3^4)^2 / (2^4 × 3^5)',
        'answer': '2^2 × 3^3 = 108'},
    {   'id': 8362,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Степени 15',
        'text': 'Упростите: (5^2 × 7^3)^3 / (5^3 × 7^4)',
        'answer': '5^3 × 7^5 = 125 × 16807 = 2100875'},
    {   'id': 8363,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 23',
        'text': 'Упростите: √(18 + 2√77)',
        'answer': '√11 + √7'},
    {   'id': 8364,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 24',
        'text': 'Упростите: √(21 - 2√108)',
        'answer': '√12 - √9 = 2√3 - 3'},
    {   'id': 8365,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадратные корни 25',
        'text': 'Упростите: √(19 + 8√3)',
        'answer': '4 + √3'},
    {   'id': 8366,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Пифагора 15',
        'text': 'Катеты относятся как 20:21, гипотенуза 58. Найдите катеты.',
        'answer': '40 и 42'},
    {   'id': 8367,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Теорема Пифагора 16',
        'text': 'Периметр прямоугольного треугольника 84, гипотенуза 35. Найдите катеты.',
        'answer': '21 и 28'},
    {   'id': 8368,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 6,
        'title': 'Простые числа 13',
        'text': 'Сколько простых чисел от 1200 до 1250?',
        'answer': '4'},
    {   'id': 8369,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 6,
        'title': 'Простые числа 14',
        'text': 'Сколько простых чисел от 1300 до 1350?',
        'answer': '4'},
    {   'id': 8370,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Перестановки 8',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 8371,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Сочетания 8',
        'text': 'Сколькими способами выбрать 7 из 22 и 6 из 20?',
        'answer': '170544 × 38760 = 6.61e+9'},
    {   'id': 8372,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 6,
        'title': 'Размещения 8',
        'text': 'Сколько девятизначных чисел из цифр 0-8 без повторений?',
        'answer': '1451520'},
    {   'id': 8373,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 21',
        'text': 'Решите неравенство: x^2 - 13x + 42 > 0',
        'answer': 'x < 6 или x > 7'}]
