PROBLEMS_DB = [   {   'id': 8374,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 22',
        'text': 'Решите неравенство: -x^2 + 12x - 35 ≥ 0',
        'answer': '5 ≤ x ≤ 7'},
    {   'id': 8375,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Неравенства 23',
        'text': 'Решите неравенство: (x-7)(x+5) < 0',
        'answer': '-5 < x < 7'},
    {   'id': 8376,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Подобие 15',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 81. '
                'Найдите площадь треугольника.',
        'answer': '108'},
    {   'id': 8377,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Подобие 16',
        'text': 'Периметры подобных треугольников 40 и 64, разность площадей 324. Найдите площади.',
        'answer': '225 и 549'},
    {   'id': 8378,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Функции 15',
        'text': 'Найдите область значений функции y = 3x^2 - 12x + 7',
        'answer': 'y ≥ -5'},
    {   'id': 8379,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Функции 16',
        'text': 'Найдите область значений функции y = -5x^2 + 20x - 15',
        'answer': 'y ≤ 5'},
    {   'id': 8380,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Касательная 8',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 13, радиус '
                '5. Найдите расстояние между точками касания.',
        'answer': '24'},
    {   'id': 8381,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Хорда 8',
        'text': 'Две хорды пересекаются. Отрезки одной 16 и 3, отрезки другой 12 и 4. Проверьте, '
                'верно ли?',
        'answer': '16×3 = 48, 12×4 = 48, верно'},
    {   'id': 8382,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Секущая 8',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 8 и 10, внутренние '
                'части первой 12. Найдите внутреннюю часть второй.',
        'answer': '9'},
    {   'id': 8383,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Системы уравнений 16',
        'text': 'Решите систему: {x^2 - xy + y^2 = 31, x - y = 3}',
        'answer': '(5,2) или (-2,-5)'},
    {   'id': 8384,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Системы уравнений 17',
        'text': 'Решите систему: {x^2 + y^2 = 52, x + y = 10}',
        'answer': '(6,4) или (4,6)'},
    {   'id': 8385,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Параллелограмм 8',
        'text': 'Диагонали 18 и 24, угол между ними 90°. Найдите стороны.',
        'answer': '15 и 15 (ромб)'},
    {   'id': 8386,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Ромб 13',
        'text': 'Площадь ромба 600, одна диагональ 40. Найдите сторону и вторую диагональ.',
        'answer': '30, 25'},
    {   'id': 8387,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Прямоугольник 12',
        'text': 'Диагональ 41, периметр 98. Найдите стороны.',
        'answer': '40 и 9'},
    {   'id': 8388,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Квадрат 12',
        'text': 'Радиус описанной окружности квадрата 8√2. Найдите сторону.',
        'answer': '16'},
    {   'id': 8389,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Трапеция 12',
        'text': 'Основания 20 и 28, диагонали 25 и 35. Найдите площадь.',
        'answer': '336'},
    {   'id': 8390,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 11',
        'text': 'Сумма первых 20 членов 430, a1 = 3. Найдите разность.',
        'answer': '2'},
    {   'id': 8391,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 12',
        'text': 'a6 = 25, a12 = 49. Найдите a1 и d.',
        'answer': 'a1 = 5, d = 4'},
    {   'id': 8392,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 9',
        'text': 'b3 = 24, b6 = 192. Найдите b1 и q.',
        'answer': 'b1 = 6, q = 2'},
    {   'id': 8393,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 10',
        'text': 'b4 = 54, b7 = 1458. Найдите b1 и q.',
        'answer': 'b1 = 2, q = 3'},
    {   'id': 8394,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 7',
        'text': 'Решите: x^4 - 25x^2 + 144 = 0',
        'answer': 'x = ±3, ±4'},
    {   'id': 8395,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 8',
        'text': 'Решите: 3x^4 - 28x^2 + 9 = 0',
        'answer': 'x = ±3, ±1/√3'},
    {   'id': 8396,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 6,
        'title': 'Биквадратные уравнения 9',
        'text': 'Решите: 4x^4 - 29x^2 + 25 = 0',
        'answer': 'x = ±2.5, ±1'},
    {   'id': 8397,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Окружность 11',
        'text': 'Длина дуги 30° равна 2π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8398,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Окружность 12',
        'text': 'Площадь сектора 120° равна 48π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8399,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Вписанный угол 9',
        'text': 'Вписанный угол на 20° больше центрального. Найдите углы.',
        'answer': '-20°? нет решения'},
    {   'id': 8400,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 6,
        'title': 'Центральный угол 9',
        'text': 'Центральный угол в 4 раза больше вписанного. Найдите углы.',
        'answer': '36° и 144°'},
    {   'id': 8401,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные уравнения 44',
        'text': 'Решите уравнение: 2x^2 - 13x + 15 = 0',
        'answer': 'x1 = 5, x2 = 1.5'},
    {   'id': 8402,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные уравнения 45',
        'text': 'Решите уравнение: 3x^2 - 17x + 20 = 0',
        'answer': 'x1 = 4, x2 = 5/3'},
    {   'id': 8403,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные уравнения 46',
        'text': 'Решите уравнение: 4x^2 - 21x + 20 = 0',
        'answer': 'x1 = 4, x2 = 1.25'},
    {   'id': 8404,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные уравнения 47',
        'text': 'Решите уравнение: 5x^2 - 24x + 27 = 0',
        'answer': 'x1 = 3, x2 = 1.8'},
    {   'id': 8405,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные уравнения 48',
        'text': 'Решите уравнение: 6x^2 - 29x + 30 = 0',
        'answer': 'x1 = 3, x2 = 5/3'},
    {   'id': 8406,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Дробно-рациональные уравнения 10',
        'text': 'Решите: 3/(x-3) + 4/(x+4) = 2',
        'answer': 'x = 5 или x = -6'},
    {   'id': 8407,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Дробно-рациональные уравнения 11',
        'text': 'Решите: (2x+5)/(x-2) - (x-3)/(x+5) = 1',
        'answer': 'x = 1 или x = -7'},
    {   'id': 8408,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Дробно-рациональные уравнения 12',
        'text': 'Решите: 1/(x+2) + 1/(x+3) = 1/(x+4)',
        'answer': 'x = -1 ± √3'},
    {   'id': 8409,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Виета 13',
        'text': 'Разность корней уравнения x^2 - 18x + q = 0 равна 10. Найдите q.',
        'answer': '56'},
    {   'id': 8410,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Виета 14',
        'text': 'Сумма кубов корней уравнения x^2 - 10x + q = 0 равна 280. Найдите q.',
        'answer': '24'},
    {   'id': 8411,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Дискриминант 13',
        'text': 'При каких a уравнение x^2 + (a-6)x + 25 = 0 имеет два различных корня?',
        'answer': 'a < -4 или a > 16'},
    {   'id': 8412,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Дискриминант 14',
        'text': 'При каких a уравнение 4x^2 + ax + 81 = 0 имеет один корень?',
        'answer': 'a = ±36'},
    {   'id': 8413,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Четырехугольники 7',
        'text': 'Найдите углы параллелограмма, если они относятся как 9:21.',
        'answer': '54°, 126°, 54°, 126°'},
    {   'id': 8414,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Прямоугольник 13',
        'text': 'Периметр прямоугольника 100, диагональ 41. Найдите стороны.',
        'answer': '40 и 9'},
    {   'id': 8415,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Ромб 14',
        'text': 'Сумма диагоналей 62, сторона 20. Найдите диагонали.',
        'answer': '42 и 20? нет, 42 и 20 сумма 62'},
    {   'id': 8416,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадрат 13',
        'text': 'Площадь квадрата 98. Найдите радиус описанной окружности.',
        'answer': '7'},
    {   'id': 8417,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Трапеция 13',
        'text': 'Основания 15 и 25, боковые стороны 13 и 21. Найдите площадь.',
        'answer': '240'},
    {   'id': 8418,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Окружность 13',
        'text': 'Хорда 24, расстояние до центра 10. Найдите радиус.',
        'answer': '13'},
    {   'id': 8419,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Вписанный угол 10',
        'text': 'Вписанный угол в 6 раз меньше центрального. Найдите углы.',
        'answer': '25.71° и 154.29°'},
    {   'id': 8420,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Центральный угол 10',
        'text': 'Центральный угол на 80° больше вписанного. Найдите углы.',
        'answer': '80° и 160°'},
    {   'id': 8421,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Степени 16',
        'text': 'Вычислите: (2^5 × 3^6)^2 / (2^4 × 3^7)',
        'answer': '2^6 × 3^5 = 64 × 243 = 15552'},
    {   'id': 8422,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Степени 17',
        'text': 'Вычислите: (5^3 × 7^4)^2 / (5^2 × 7^5)',
        'answer': '5^4 × 7^3 = 625 × 343 = 214375'},
    {   'id': 8423,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 26',
        'text': 'Упростите: √(22 + 2√117)',
        'answer': '√13 + √9 = √13 + 3'},
    {   'id': 8424,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 27',
        'text': 'Упростите: √(23 - 2√130)',
        'answer': '√13 - √10'},
    {   'id': 8425,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 28',
        'text': 'Упростите: √(24 + 6√15)',
        'answer': '√15 + 3'},
    {   'id': 8426,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Пифагора 17',
        'text': 'Катеты относятся как 24:7, гипотенуза 50. Найдите катеты.',
        'answer': '48 и 14'},
    {   'id': 8427,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Пифагора 18',
        'text': 'Периметр прямоугольного треугольника 132, гипотенуза 61. Найдите катеты.',
        'answer': '60 и 11? нет, 60+11+61=132'},
    {   'id': 8428,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 7,
        'title': 'Простые числа 15',
        'text': 'Сколько простых чисел от 1400 до 1450?',
        'answer': '4'},
    {   'id': 8429,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 7,
        'title': 'Простые числа 16',
        'text': 'Сколько простых чисел от 1500 до 1550?',
        'answer': '4'},
    {   'id': 8430,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Перестановки 9',
        'text': "Сколько слов из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 8431,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Сочетания 9',
        'text': 'Сколькими способами выбрать 8 из 24 и 7 из 22?',
        'answer': '735471 × 170544 = 1.25e+11'},
    {   'id': 8432,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Размещения 9',
        'text': 'Сколько десятизначных чисел из цифр 0-8 без повторений?',
        'answer': '5443200'},
    {   'id': 8433,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 24',
        'text': 'Решите неравенство: x^2 - 15x + 54 > 0',
        'answer': 'x < 6 или x > 9'},
    {   'id': 8434,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 25',
        'text': 'Решите неравенство: -x^2 + 14x - 48 ≥ 0',
        'answer': '6 ≤ x ≤ 8'},
    {   'id': 8435,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 26',
        'text': 'Решите неравенство: (x-8)(x+6) < 0',
        'answer': '-6 < x < 8'},
    {   'id': 8436,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Подобие 17',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 99. '
                'Найдите площадь треугольника.',
        'answer': '132'},
    {   'id': 8437,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Подобие 18',
        'text': 'Периметры подобных треугольников 45 и 72, разность площадей 567. Найдите площади.',
        'answer': '225 и 792'},
    {   'id': 8438,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Функции 17',
        'text': 'Найдите область значений функции y = 4x^2 - 16x + 7',
        'answer': 'y ≥ -9'},
    {   'id': 8439,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Функции 18',
        'text': 'Найдите область значений функции y = -6x^2 + 24x - 19',
        'answer': 'y ≤ 5'},
    {   'id': 8440,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Касательная 9',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 25, радиус '
                '7. Найдите расстояние между точками касания.',
        'answer': '48'},
    {   'id': 8441,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Хорда 9',
        'text': 'Две хорды пересекаются. Отрезки одной 18 и 2, отрезки другой 12 и 3. Проверьте, '
                'верно ли?',
        'answer': '18×2 = 36, 12×3 = 36, верно'},
    {   'id': 8442,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Секущая 9',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 9 и 11, внутренние '
                'части первой 14. Найдите внутреннюю часть второй.',
        'answer': '10'},
    {   'id': 8443,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Системы уравнений 18',
        'text': 'Решите систему: {x^2 - xy + y^2 = 37, x + y = 9}',
        'answer': '(5,4) или (4,5)'},
    {   'id': 8444,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Системы уравнений 19',
        'text': 'Решите систему: {x^2 + y^2 = 61, xy = 30}',
        'answer': '(6,5) или (5,6) или (-6,-5) или (-5,-6)'},
    {   'id': 8445,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Параллелограмм 9',
        'text': 'Диагонали 20 и 28, угол между ними 120°. Найдите стороны.',
        'answer': '√(144) и √(304) = 12 и 4√19'},
    {   'id': 8446,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Ромб 15',
        'text': 'Площадь ромба 720, одна диагональ 36. Найдите сторону и вторую диагональ.',
        'answer': '40, 26'},
    {   'id': 8447,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Прямоугольник 14',
        'text': 'Диагональ 45, периметр 126. Найдите стороны.',
        'answer': '36 и 27'},
    {   'id': 8448,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадрат 14',
        'text': 'Радиус вписанной окружности квадрата 6√2. Найдите диагональ.',
        'answer': '24'},
    {   'id': 8449,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Трапеция 14',
        'text': 'Основания 22 и 30, диагонали 28 и 40. Найдите площадь.',
        'answer': '416'},
    {   'id': 8450,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 13',
        'text': 'Сумма первых 18 членов 522, a1 = 4. Найдите разность.',
        'answer': '3'},
    {   'id': 8451,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 14',
        'text': 'a7 = 30, a13 = 54. Найдите a1 и d.',
        'answer': 'a1 = 6, d = 4'},
    {   'id': 8452,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 11',
        'text': 'b4 = 40, b7 = 320. Найдите b1 и q.',
        'answer': 'b1 = 5, q = 2'},
    {   'id': 8453,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 12',
        'text': 'b5 = 48, b8 = 384. Найдите b1 и q.',
        'answer': 'b1 = 3, q = 2'},
    {   'id': 8454,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 10',
        'text': 'Решите: x^4 - 29x^2 + 100 = 0',
        'answer': 'x = ±2, ±5'},
    {   'id': 8455,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 11',
        'text': 'Решите: 2x^4 - 17x^2 + 8 = 0',
        'answer': 'x = ±2√2, ±1/√2'},
    {   'id': 8456,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 12',
        'text': 'Решите: 3x^4 - 20x^2 + 12 = 0',
        'answer': 'x = ±√6, ±√(2/3)'},
    {   'id': 8457,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Окружность 14',
        'text': 'Длина дуги 36° равна 2π. Найдите радиус.',
        'answer': '10'},
    {   'id': 8458,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Окружность 15',
        'text': 'Площадь сектора 72° равна 20π. Найдите радиус.',
        'answer': '10'},
    {   'id': 8459,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Вписанный угол 11',
        'text': 'Вписанный угол на 25° меньше центрального. Найдите углы.',
        'answer': '25° и 50°'},
    {   'id': 8460,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Центральный угол 11',
        'text': 'Центральный угол в 5 раз больше вписанного. Найдите углы.',
        'answer': '30° и 150°'},
    {   'id': 8461,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Степени 18',
        'text': 'Упростите: (3^4 × 5^5)^2 / (3^3 × 5^4)',
        'answer': '3^5 × 5^6 = 243 × 15625 = 3796875'},
    {   'id': 8462,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Степени 19',
        'text': 'Упростите: (2^3 × 7^4)^3 / (2^2 × 7^3)',
        'answer': '2^7 × 7^9 = 128 × 40353607 = 5.16e+9'},
    {   'id': 8463,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 29',
        'text': 'Упростите: √(26 + 2√165)',
        'answer': '√15 + √11'},
    {   'id': 8464,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 30',
        'text': 'Упростите: √(27 - 2√182)',
        'answer': '√14 - √13'},
    {   'id': 8465,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадратные корни 31',
        'text': 'Упростите: √(28 + 10√3)',
        'answer': '5 + √3'},
    {   'id': 8466,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Пифагора 19',
        'text': 'Катеты относятся как 28:45, гипотенуза 106. Найдите катеты.',
        'answer': '56 и 90'},
    {   'id': 8467,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Теорема Пифагора 20',
        'text': 'Периметр прямоугольного треугольника 150, гипотенуза 65. Найдите катеты.',
        'answer': '60 и 25'},
    {   'id': 8468,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 7,
        'title': 'Простые числа 17',
        'text': 'Сколько простых чисел от 1600 до 1650?',
        'answer': '5'},
    {   'id': 8469,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 7,
        'title': 'Простые числа 18',
        'text': 'Сколько простых чисел от 1700 до 1750?',
        'answer': '4'},
    {   'id': 8470,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Перестановки 10',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛОГРАММ'?",
        'answer': '908107200'},
    {   'id': 8471,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Сочетания 10',
        'text': 'Сколькими способами выбрать 9 из 26 и 8 из 24?',
        'answer': '3124550 × 735471 = 2.3e+12'},
    {   'id': 8472,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 7,
        'title': 'Размещения 10',
        'text': 'Сколько одиннадцатизначных чисел из цифр 0-8 без повторений?',
        'answer': '21772800'},
    {   'id': 8473,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 27',
        'text': 'Решите неравенство: x^2 - 17x + 70 > 0',
        'answer': 'x < 7 или x > 10'},
    {   'id': 8474,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 28',
        'text': 'Решите неравенство: -x^2 + 16x - 63 ≥ 0',
        'answer': '7 ≤ x ≤ 9'},
    {   'id': 8475,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Неравенства 29',
        'text': 'Решите неравенство: (x-9)(x+7) < 0',
        'answer': '-7 < x < 9'},
    {   'id': 8476,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Подобие 19',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 117. '
                'Найдите площадь треугольника.',
        'answer': '156'},
    {   'id': 8477,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Подобие 20',
        'text': 'Периметры подобных треугольников 50 и 80, разность площадей 900. Найдите площади.',
        'answer': '400 и 1300'},
    {   'id': 8478,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Функции 19',
        'text': 'Найдите область значений функции y = 5x^2 - 20x + 11',
        'answer': 'y ≥ -9'},
    {   'id': 8479,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Функции 20',
        'text': 'Найдите область значений функции y = -7x^2 + 28x - 23',
        'answer': 'y ≤ 5'},
    {   'id': 8480,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Касательная 10',
        'text': 'Из точки к окружности проведены две касательные. Угол между ними 60°, расстояние '
                'до центра 12. Найдите длину касательной.',
        'answer': '6√3'},
    {   'id': 8481,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Хорда 10',
        'text': 'Две хорды пересекаются. Отрезки одной 20 и 3, отрезки другой 15 и 4. Проверьте, '
                'верно ли?',
        'answer': '20×3 = 60, 15×4 = 60, верно'},
    {   'id': 8482,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Секущая 10',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 10 и 12, внутренние '
                'части первой 16. Найдите внутреннюю часть второй.',
        'answer': '11'},
    {   'id': 8483,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Системы уравнений 20',
        'text': 'Решите систему: {x^2 + xy + y^2 = 43, x + y = 7}',
        'answer': '(4,3) или (3,4)'},
    {   'id': 8484,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Системы уравнений 21',
        'text': 'Решите систему: {x^2 + y^2 = 74, xy = 35}',
        'answer': '(7,5) или (5,7) или (-7,-5) или (-5,-7)'},
    {   'id': 8485,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Параллелограмм 10',
        'text': 'Диагонали 22 и 30, угол между ними 60°. Найдите стороны.',
        'answer': '√(169) = 13 и √(499)'},
    {   'id': 8486,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Ромб 16',
        'text': 'Площадь ромба 840, одна диагональ 40. Найдите сторону и вторую диагональ.',
        'answer': '42, 29'},
    {   'id': 8487,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Прямоугольник 15',
        'text': 'Диагональ 50, периметр 140. Найдите стороны.',
        'answer': '48 и 22? нет, 48+22=70 периметр 140'},
    {   'id': 8488,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Квадрат 15',
        'text': 'Радиус описанной окружности квадрата 7√2. Найдите сторону.',
        'answer': '14'},
    {   'id': 8489,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Трапеция 15',
        'text': 'Основания 24 и 32, диагонали 30 и 42. Найдите площадь.',
        'answer': '504'},
    {   'id': 8490,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 15',
        'text': 'Сумма первых 20 членов 620, a1 = 5. Найдите разность.',
        'answer': '3'},
    {   'id': 8491,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 16',
        'text': 'a8 = 35, a15 = 63. Найдите a1 и d.',
        'answer': 'a1 = 7, d = 4'},
    {   'id': 8492,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 13',
        'text': 'b3 = 45, b6 = 1215. Найдите b1 и q.',
        'answer': 'b1 = 5, q = 3'},
    {   'id': 8493,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 14',
        'text': 'b4 = 64, b7 = 512. Найдите b1 и q.',
        'answer': 'b1 = 8, q = 2'},
    {   'id': 8494,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 13',
        'text': 'Решите: x^4 - 34x^2 + 225 = 0',
        'answer': 'x = ±3, ±5'},
    {   'id': 8495,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 14',
        'text': 'Решите: 4x^4 - 37x^2 + 9 = 0',
        'answer': 'x = ±3, ±1/2'},
    {   'id': 8496,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 7,
        'title': 'Биквадратные уравнения 15',
        'text': 'Решите: 5x^4 - 26x^2 + 5 = 0',
        'answer': 'x = ±√5, ±1/√5'},
    {   'id': 8497,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Окружность 16',
        'text': 'Длина дуги 40° равна 2π. Найдите радиус.',
        'answer': '9'},
    {   'id': 8498,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Окружность 17',
        'text': 'Площадь сектора 80° равна 32π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8499,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Вписанный угол 12',
        'text': 'Вписанный угол на 15° больше центрального. Найдите углы.',
        'answer': '-15°? нет решения'},
    {   'id': 8500,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 7,
        'title': 'Центральный угол 12',
        'text': 'Центральный угол в 7 раз больше вписанного. Найдите углы.',
        'answer': '22.5° и 157.5°'},
    {   'id': 8501,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные уравнения 49',
        'text': 'Решите уравнение: 2x^2 - 15x + 22 = 0',
        'answer': 'x1 = 5.5, x2 = 2'},
    {   'id': 8502,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные уравнения 50',
        'text': 'Решите уравнение: 3x^2 - 19x + 28 = 0',
        'answer': 'x1 = 4, x2 = 7/3'},
    {   'id': 8503,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные уравнения 51',
        'text': 'Решите уравнение: 4x^2 - 23x + 25 = 0',
        'answer': 'x1 = 5, x2 = 1.25'},
    {   'id': 8504,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные уравнения 52',
        'text': 'Решите уравнение: 5x^2 - 26x + 33 = 0',
        'answer': 'x1 = 3, x2 = 2.2'},
    {   'id': 8505,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные уравнения 53',
        'text': 'Решите уравнение: 6x^2 - 31x + 35 = 0',
        'answer': 'x1 = 3.5, x2 = 5/3'},
    {   'id': 8506,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Дробно-рациональные уравнения 13',
        'text': 'Решите: 4/(x-4) + 5/(x+5) = 3',
        'answer': 'x = 6 или x = -7'},
    {   'id': 8507,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Дробно-рациональные уравнения 14',
        'text': 'Решите: (3x+7)/(x-3) - (2x-5)/(x+4) = 2',
        'answer': 'x = 2 или x = -8'},
    {   'id': 8508,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Дробно-рациональные уравнения 15',
        'text': 'Решите: 2/(x+3) + 3/(x+4) = 4/(x+5)',
        'answer': 'x = -1 ± √2'},
    {   'id': 8509,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Виета 15',
        'text': 'Разность корней уравнения x^2 - 20x + q = 0 равна 12. Найдите q.',
        'answer': '64'},
    {   'id': 8510,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Виета 16',
        'text': 'Сумма кубов корней уравнения x^2 - 12x + q = 0 равна 432. Найдите q.',
        'answer': '32'},
    {   'id': 8511,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Дискриминант 15',
        'text': 'При каких a уравнение x^2 + (a-7)x + 36 = 0 имеет два различных корня?',
        'answer': 'a < -5 или a > 19'},
    {   'id': 8512,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Дискриминант 16',
        'text': 'При каких a уравнение 5x^2 + ax + 45 = 0 имеет один корень?',
        'answer': 'a = ±30'},
    {   'id': 8513,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Четырехугольники 8',
        'text': 'Найдите углы параллелограмма, если они относятся как 11:25.',
        'answer': '55°, 125°, 55°, 125°'},
    {   'id': 8514,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Прямоугольник 16',
        'text': 'Периметр прямоугольника 108, диагональ 45. Найдите стороны.',
        'answer': '36 и 18? нет, 36+18=54 периметр 108'},
    {   'id': 8515,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Ромб 17',
        'text': 'Сумма диагоналей 70, сторона 25. Найдите диагонали.',
        'answer': '48 и 22? нет, 48+22=70'},
    {   'id': 8516,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадрат 16',
        'text': 'Площадь квадрата 162. Найдите радиус вписанной окружности.',
        'answer': '9/√2? нет, сторона = 9√2, радиус = 9√2/2'},
    {   'id': 8517,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Трапеция 16',
        'text': 'Основания 17 и 27, боковые стороны 14 и 22. Найдите площадь.',
        'answer': '264'},
    {   'id': 8518,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Окружность 18',
        'text': 'Хорда 26, расстояние до центра 12. Найдите радиус.',
        'answer': '√(169+144)=√313'},
    {   'id': 8519,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Вписанный угол 13',
        'text': 'Вписанный угол в 7 раз меньше центрального. Найдите углы.',
        'answer': '22.5° и 157.5°'},
    {   'id': 8520,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Центральный угол 13',
        'text': 'Центральный угол на 90° больше вписанного. Найдите углы.',
        'answer': '90° и 180°'},
    {   'id': 8521,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Степени 20',
        'text': 'Вычислите: (2^4 × 3^5)^3 / (2^3 × 3^4)',
        'answer': '2^9 × 3^11 = 512 × 177147 = 90720000'},
    {   'id': 8522,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Степени 21',
        'text': 'Вычислите: (5^2 × 7^3)^3 / (5^1 × 7^2)',
        'answer': '5^5 × 7^7 = 3125 × 823543 = 2.57e+9'},
    {   'id': 8523,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 32',
        'text': 'Упростите: √(29 + 2√198)',
        'answer': '√18 + √11 = 3√2 + √11'},
    {   'id': 8524,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 33',
        'text': 'Упростите: √(31 - 2√210)',
        'answer': '√15 - √14'},
    {   'id': 8525,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 34',
        'text': 'Упростите: √(32 + 12√7)',
        'answer': '2√7 + 2? нет, 2√7 + 2√2? не подходит'},
    {   'id': 8526,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Пифагора 21',
        'text': 'Катеты относятся как 32:15, гипотенуза 68. Найдите катеты.',
        'answer': '64 и 30'},
    {   'id': 8527,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Пифагора 22',
        'text': 'Периметр прямоугольного треугольника 168, гипотенуза 73. Найдите катеты.',
        'answer': '55 и 40? нет, 55+40+73=168'},
    {   'id': 8528,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 8,
        'title': 'Простые числа 19',
        'text': 'Сколько простых чисел от 1800 до 1850?',
        'answer': '4'},
    {   'id': 8529,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 8,
        'title': 'Простые числа 20',
        'text': 'Сколько простых чисел от 1900 до 1950?',
        'answer': '4'},
    {   'id': 8530,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Перестановки 11',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 8531,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Сочетания 11',
        'text': 'Сколькими способами выбрать 10 из 28 и 9 из 26?',
        'answer': '13123110 × 3124550 = 4.1e+13'},
    {   'id': 8532,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Размещения 11',
        'text': 'Сколько двенадцатизначных чисел из цифр 0-8 без повторений?',
        'answer': '79833600'},
    {   'id': 8533,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 30',
        'text': 'Решите неравенство: x^2 - 19x + 88 > 0',
        'answer': 'x < 8 или x > 11'},
    {   'id': 8534,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 31',
        'text': 'Решите неравенство: -x^2 + 18x - 80 ≥ 0',
        'answer': '8 ≤ x ≤ 10'},
    {   'id': 8535,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 32',
        'text': 'Решите неравенство: (x-10)(x+8) < 0',
        'answer': '-8 < x < 10'},
    {   'id': 8536,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Подобие 21',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 135. '
                'Найдите площадь треугольника.',
        'answer': '180'},
    {   'id': 8537,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Подобие 22',
        'text': 'Периметры подобных треугольников 55 и 88, разность площадей 1089. Найдите '
                'площади.',
        'answer': '625 и 1714'},
    {   'id': 8538,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Функции 21',
        'text': 'Найдите область значений функции y = 6x^2 - 24x + 15',
        'answer': 'y ≥ -9'},
    {   'id': 8539,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Функции 22',
        'text': 'Найдите область значений функции y = -8x^2 + 32x - 27',
        'answer': 'y ≤ 5'},
    {   'id': 8540,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Касательная 11',
        'text': 'Из точки к окружности проведены две касательные. Расстояние между точками касания '
                '30, радиус 8. Найдите расстояние до центра.',
        'answer': '17'},
    {   'id': 8541,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Хорда 11',
        'text': 'Две хорды пересекаются. Отрезки одной 22 и 3, отрезки другой 11 и 6. Проверьте, '
                'верно ли?',
        'answer': '22×3 = 66, 11×6 = 66, верно'},
    {   'id': 8542,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Секущая 11',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 11 и 13, внутренние '
                'части первой 18. Найдите внутреннюю часть второй.',
        'answer': '12'},
    {   'id': 8543,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Системы уравнений 22',
        'text': 'Решите систему: {x^2 - xy + y^2 = 49, x + y = 10}',
        'answer': '(6,4) или (4,6)'},
    {   'id': 8544,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Системы уравнений 23',
        'text': 'Решите систему: {x^2 + y^2 = 89, xy = 40}',
        'answer': '(8,5) или (5,8) или (-8,-5) или (-5,-8)'},
    {   'id': 8545,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Параллелограмм 11',
        'text': 'Диагонали 24 и 32, угол между ними 60°. Найдите стороны.',
        'answer': '√(208) и √(592) = 4√13 и 4√37'},
    {   'id': 8546,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Ромб 18',
        'text': 'Площадь ромба 960, одна диагональ 40. Найдите сторону и вторую диагональ.',
        'answer': '48, 34'},
    {   'id': 8547,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Прямоугольник 17',
        'text': 'Диагональ 53, периметр 146. Найдите стороны.',
        'answer': '44 и 29? нет, 44+29=73 периметр 146'},
    {   'id': 8548,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадрат 17',
        'text': 'Радиус вписанной окружности квадрата 8√2. Найдите диагональ.',
        'answer': '32'},
    {   'id': 8549,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Трапеция 17',
        'text': 'Основания 26 и 34, диагонали 32 и 44. Найдите площадь.',
        'answer': '600'},
    {   'id': 8550,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Арифметическая прогрессия 17',
        'text': 'Сумма первых 22 членов 792, a1 = 6. Найдите разность.',
        'answer': '3'},
    {   'id': 8551,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Арифметическая прогрессия 18',
        'text': 'a9 = 40, a17 = 72. Найдите a1 и d.',
        'answer': 'a1 = 8, d = 4'},
    {   'id': 8552,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Геометрическая прогрессия 15',
        'text': 'b3 = 54, b7 = 4374. Найдите b1 и q.',
        'answer': 'b1 = 6, q = 3'},
    {   'id': 8553,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Геометрическая прогрессия 16',
        'text': 'b4 = 80, b8 = 1280. Найдите b1 и q.',
        'answer': 'b1 = 10, q = 2'},
    {   'id': 8554,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 16',
        'text': 'Решите: x^4 - 37x^2 + 300 = 0',
        'answer': 'x = ±2, ±5√3? нет, x = ±5, ±2√3'},
    {   'id': 8555,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 17',
        'text': 'Решите: 2x^4 - 19x^2 + 24 = 0',
        'answer': 'x = ±2√2, ±√3'},
    {   'id': 8556,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 18',
        'text': 'Решите: 3x^4 - 22x^2 + 24 = 0',
        'answer': 'x = ±2, ±√6'},
    {   'id': 8557,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Окружность 19',
        'text': 'Длина дуги 48° равна 4π. Найдите радиус.',
        'answer': '15'},
    {   'id': 8558,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Окружность 20',
        'text': 'Площадь сектора 100° равна 40π. Найдите радиус.',
        'answer': '12'},
    {   'id': 8559,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Вписанный угол 14',
        'text': 'Вписанный угол на 35° меньше центрального. Найдите углы.',
        'answer': '35° и 70°'},
    {   'id': 8560,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Центральный угол 14',
        'text': 'Центральный угол в 8 раз больше вписанного. Найдите углы.',
        'answer': '20° и 160°'},
    {   'id': 8561,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Степени 22',
        'text': 'Упростите: (3^3 × 4^4)^2 / (3^2 × 4^3)',
        'answer': '3^4 × 4^5 = 81 × 1024 = 82944'},
    {   'id': 8562,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Степени 23',
        'text': 'Упростите: (2^5 × 5^5)^3 / (2^3 × 5^4)',
        'answer': '2^12 × 5^11 = 4096 × 48828125 = 2e+11'},
    {   'id': 8563,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 35',
        'text': 'Упростите: √(33 + 2√224)',
        'answer': '√7 + √32 = √7 + 4√2'},
    {   'id': 8564,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 36',
        'text': 'Упростите: √(35 - 2√300)',
        'answer': '√15 - √20 = √15 - 2√5'},
    {   'id': 8565,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадратные корни 37',
        'text': 'Упростите: √(37 + 12√10)',
        'answer': '2√10 + 3'},
    {   'id': 8566,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Пифагора 23',
        'text': 'Катеты относятся как 36:77, гипотенуза 170. Найдите катеты.',
        'answer': '72 и 154'},
    {   'id': 8567,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Теорема Пифагора 24',
        'text': 'Периметр прямоугольного треугольника 180, гипотенуза 78. Найдите катеты.',
        'answer': '48 и 54? нет, 48+54+78=180'},
    {   'id': 8568,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 8,
        'title': 'Простые числа 21',
        'text': 'Сколько простых чисел от 2000 до 2050?',
        'answer': '4'},
    {   'id': 8569,
        'subject': 'number_theory',
        'grade': 8,
        'difficulty': 8,
        'title': 'Простые числа 22',
        'text': 'Сколько простых чисел от 2100 до 2150?',
        'answer': '4'},
    {   'id': 8570,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Перестановки 12',
        'text': "Сколько слов из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 8571,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Сочетания 12',
        'text': 'Сколькими способами выбрать 11 из 30 и 10 из 28?',
        'answer': '54627300 × 13123110 = 7.17e+14'},
    {   'id': 8572,
        'subject': 'combinatorics',
        'grade': 8,
        'difficulty': 8,
        'title': 'Размещения 12',
        'text': 'Сколько тринадцатизначных чисел из цифр 0-8 без повторений?',
        'answer': '249080832'},
    {   'id': 8573,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 33',
        'text': 'Решите неравенство: x^2 - 21x + 108 > 0',
        'answer': 'x < 9 или x > 12'},
    {   'id': 8574,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 34',
        'text': 'Решите неравенство: -x^2 + 20x - 96 ≥ 0',
        'answer': '8 ≤ x ≤ 12'},
    {   'id': 8575,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Неравенства 35',
        'text': 'Решите неравенство: (x-11)(x+9) < 0',
        'answer': '-9 < x < 11'},
    {   'id': 8576,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Подобие 23',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 153. '
                'Найдите площадь треугольника.',
        'answer': '204'},
    {   'id': 8577,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Подобие 24',
        'text': 'Периметры подобных треугольников 60 и 96, разность площадей 1296. Найдите '
                'площади.',
        'answer': '900 и 2196'},
    {   'id': 8578,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Функции 23',
        'text': 'Найдите область значений функции y = 7x^2 - 28x + 19',
        'answer': 'y ≥ -9'},
    {   'id': 8579,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Функции 24',
        'text': 'Найдите область значений функции y = -9x^2 + 36x - 31',
        'answer': 'y ≤ 5'},
    {   'id': 8580,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Касательная 12',
        'text': 'Из точки к окружности проведены две касательные. Угол между ними 90°, расстояние '
                'до центра 13. Найдите длину касательной.',
        'answer': '12'},
    {   'id': 8581,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Хорда 12',
        'text': 'Две хорды пересекаются. Отрезки одной 24 и 3, отрезки другой 18 и 4. Проверьте, '
                'верно ли?',
        'answer': '24×3 = 72, 18×4 = 72, верно'},
    {   'id': 8582,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Секущая 12',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 12 и 14, внутренние '
                'части первой 20. Найдите внутреннюю часть второй.',
        'answer': '13'},
    {   'id': 8583,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Системы уравнений 24',
        'text': 'Решите систему: {x^2 - xy + y^2 = 57, x + y = 11}',
        'answer': '(7,4) или (4,7)'},
    {   'id': 8584,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Системы уравнений 25',
        'text': 'Решите систему: {x^2 + y^2 = 106, xy = 45}',
        'answer': '(9,5) или (5,9) или (-9,-5) или (-5,-9)'},
    {   'id': 8585,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Параллелограмм 12',
        'text': 'Диагонали 26 и 34, угол между ними 60°. Найдите стороны.',
        'answer': '√(247) и √(787)'},
    {   'id': 8586,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Ромб 19',
        'text': 'Площадь ромба 1080, одна диагональ 45. Найдите сторону и вторую диагональ.',
        'answer': '48, 39'},
    {   'id': 8587,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Прямоугольник 18',
        'text': 'Диагональ 58, периметр 164. Найдите стороны.',
        'answer': '40 и 42? нет, 40+42=82 периметр 164'},
    {   'id': 8588,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Квадрат 18',
        'text': 'Радиус описанной окружности квадрата 9√2. Найдите сторону.',
        'answer': '18'},
    {   'id': 8589,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Трапеция 18',
        'text': 'Основания 28 и 36, диагонали 34 и 46. Найдите площадь.',
        'answer': '704'},
    {   'id': 8590,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Арифметическая прогрессия 19',
        'text': 'Сумма первых 24 членов 1008, a1 = 7. Найдите разность.',
        'answer': '3'},
    {   'id': 8591,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Арифметическая прогрессия 20',
        'text': 'a10 = 45, a19 = 81. Найдите a1 и d.',
        'answer': 'a1 = 9, d = 4'},
    {   'id': 8592,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Геометрическая прогрессия 17',
        'text': 'b3 = 63, b7 = 5103. Найдите b1 и q.',
        'answer': 'b1 = 7, q = 3'},
    {   'id': 8593,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Геометрическая прогрессия 18',
        'text': 'b4 = 96, b8 = 1536. Найдите b1 и q.',
        'answer': 'b1 = 12, q = 2'},
    {   'id': 8594,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 19',
        'text': 'Решите: x^4 - 41x^2 + 400 = 0',
        'answer': 'x = ±4, ±5'},
    {   'id': 8595,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 20',
        'text': 'Решите: 2x^4 - 21x^2 + 27 = 0',
        'answer': 'x = ±3, ±√(4.5)'},
    {   'id': 8596,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 8,
        'title': 'Биквадратные уравнения 21',
        'text': 'Решите: 3x^4 - 25x^2 + 28 = 0',
        'answer': 'x = ±2, ±√(7/3)'},
    {   'id': 8597,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Окружность 21',
        'text': 'Длина дуги 54° равна 3π. Найдите радиус.',
        'answer': '10'},
    {   'id': 8598,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Окружность 22',
        'text': 'Площадь сектора 108° равна 27π. Найдите радиус.',
        'answer': '9'},
    {   'id': 8599,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Вписанный угол 15',
        'text': 'Вписанный угол на 40° меньше центрального. Найдите углы.',
        'answer': '40° и 80°'},
    {   'id': 8600,
        'subject': 'geometry',
        'grade': 8,
        'difficulty': 8,
        'title': 'Центральный угол 15',
        'text': 'Центральный угол в 9 раз больше вписанного. Найдите углы.',
        'answer': '18° и 162°'},
    {   'id': 8601,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 9,
        'title': 'Квадратные уравнения 54',
        'text': 'Решите уравнение: 2x^2 - 17x + 30 = 0',
        'answer': 'x1 = 6, x2 = 2.5'},
    {   'id': 8602,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 9,
        'title': 'Квадратные уравнения 55',
        'text': 'Решите уравнение: 3x^2 - 20x + 25 = 0',
        'answer': 'x1 = 5, x2 = 5/3'},
    {   'id': 8603,
        'subject': 'algebra',
        'grade': 8,
        'difficulty': 9,
        'title': 'Квадратные уравнения 56',
        'text': 'Решите уравнение: 4x^2 - 25x + 30 = 0',
        'answer': 'x1 = 5, x2 = 1.5? нет, D=625-480=145'}]
