PROBLEMS_DB = [   {   'id': 9064,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Корни 5',
        'text': 'Упростите: √50 - √18',
        'answer': '2√2'},
    {   'id': 9065,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 1,
        'title': 'Делимость',
        'text': 'Делится ли число 12345 на 15?',
        'answer': 'Да'},
    {   'id': 9066,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 1,
        'title': 'Делимость 2',
        'text': 'Делится ли число 123456 на 11?',
        'answer': 'Нет'},
    {   'id': 9067,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Перестановки 2',
        'text': "Сколько слов из букв слова 'КНИГА'?",
        'answer': '120'},
    {   'id': 9068,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Сочетания 2',
        'text': 'Сколькими способами выбрать 4 из 10?',
        'answer': '210'},
    {   'id': 9069,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Размещения 2',
        'text': 'Сколько трехзначных чисел из цифр 0-5 без повторений?',
        'answer': '100'},
    {   'id': 9070,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Прогрессии',
        'text': 'Найдите сумму первых 10 членов арифметической прогрессии: 2,5,8,...',
        'answer': '155'},
    {   'id': 9071,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Прогрессии 2',
        'text': 'Найдите сумму первых 5 членов геометрической прогрессии: 3,6,12,...',
        'answer': '93'},
    {   'id': 9072,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Окружность 3',
        'text': 'Хорда длиной 16 см удалена от центра на 6 см. Найдите радиус.',
        'answer': '10 см'},
    {   'id': 9073,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Окружность 4',
        'text': 'Радиус окружности 13 см, хорда 24 см. Найдите расстояние от центра до хорды.',
        'answer': '5 см'},
    {   'id': 9074,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Касательная 2',
        'text': 'Из точки к окружности проведена касательная длиной 12 см. Радиус 5 см. Найдите '
                'расстояние от точки до центра.',
        'answer': '13 см'},
    {   'id': 9075,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Неравенства 6',
        'text': 'Решите неравенство: 3x - 7 > 2x + 5',
        'answer': 'x > 12'},
    {   'id': 9076,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Неравенства 7',
        'text': 'Решите неравенство: 5x + 4 ≤ 7x - 2',
        'answer': 'x ≥ 3'},
    {   'id': 9077,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Модуль',
        'text': 'Решите уравнение: |x - 3| = 5',
        'answer': 'x = 8 или x = -2'},
    {   'id': 9078,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Модуль 2',
        'text': 'Решите уравнение: |2x + 1| = 7',
        'answer': 'x = 3 или x = -4'},
    {   'id': 9079,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Синус',
        'text': 'Найдите sin 30°',
        'answer': '0.5'},
    {   'id': 9080,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Косинус',
        'text': 'Найдите cos 60°',
        'answer': '0.5'},
    {   'id': 9081,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Тангенс',
        'text': 'Найдите tg 45°',
        'answer': '1'},
    {   'id': 9082,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Синус 2',
        'text': 'Найдите sin 60°',
        'answer': '√3/2'},
    {   'id': 9083,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Косинус 2',
        'text': 'Найдите cos 30°',
        'answer': '√3/2'},
    {   'id': 9084,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Тангенс 2',
        'text': 'Найдите tg 30°',
        'answer': '1/√3'},
    {   'id': 9085,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Рациональные уравнения',
        'text': 'Решите: (x+2)/3 = 5',
        'answer': 'x = 13'},
    {   'id': 9086,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Рациональные уравнения 2',
        'text': 'Решите: 2/(x-1) = 3',
        'answer': 'x = 5/3'},
    {   'id': 9087,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Рациональные уравнения 3',
        'text': 'Решите: 1/x + 1/2 = 1/3',
        'answer': 'x = -6'},
    {   'id': 9088,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Векторы',
        'text': 'Найдите длину вектора a(3,4)',
        'answer': '5'},
    {   'id': 9089,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Векторы 2',
        'text': 'Найдите скалярное произведение векторов a(2,3) и b(4,-1)',
        'answer': '5'},
    {   'id': 9090,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Векторы 3',
        'text': 'Найдите угол между векторами a(1,0) и b(0,1)',
        'answer': '90°'},
    {   'id': 9091,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Вероятность',
        'text': 'Бросают монету. Какова вероятность выпадения орла?',
        'answer': '0.5'},
    {   'id': 9092,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Вероятность 2',
        'text': 'Бросают кубик. Какова вероятность выпадения 6?',
        'answer': '1/6'},
    {   'id': 9093,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 1,
        'title': 'Вероятность 3',
        'text': 'Из колоды в 36 карт вытягивают одну. Какова вероятность, что это туз?',
        'answer': '1/9'},
    {   'id': 9094,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Квадратичная функция 6',
        'text': 'Найдите нули функции y = x^2 - 4x + 3',
        'answer': 'x = 1,3'},
    {   'id': 9095,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Квадратичная функция 7',
        'text': 'Найдите нули функции y = 2x^2 - 5x - 3',
        'answer': 'x = 3, -0.5'},
    {   'id': 9096,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 1,
        'title': 'Квадратичная функция 8',
        'text': 'Найдите ось симметрии параболы y = x^2 - 6x + 8',
        'answer': 'x = 3'},
    {   'id': 9097,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Площадь 2',
        'text': 'Найдите площадь ромба с диагоналями 10 и 14',
        'answer': '70'},
    {   'id': 9098,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Площадь 3',
        'text': 'Найдите площадь трапеции с основаниями 5 и 9 и высотой 4',
        'answer': '28'},
    {   'id': 9099,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Площадь 4',
        'text': 'Найдите площадь круга с радиусом 7',
        'answer': '49π'},
    {   'id': 9100,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 1,
        'title': 'Площадь 5',
        'text': 'Найдите площадь сектора с углом 60° и радиусом 6',
        'answer': '6π'},
    {   'id': 9101,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратичная функция 9',
        'text': 'Найдите область значений функции y = x^2 - 8x + 15',
        'answer': 'y ≥ -1'},
    {   'id': 9102,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратичная функция 10',
        'text': 'Найдите область значений функции y = -2x^2 + 12x - 17',
        'answer': 'y ≤ 1'},
    {   'id': 9103,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Неравенства 8',
        'text': 'Решите неравенство: x^2 - 9x + 18 > 0',
        'answer': 'x < 3 или x > 6'},
    {   'id': 9104,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Неравенства 9',
        'text': 'Решите неравенство: -x^2 + 8x - 15 ≥ 0',
        'answer': '3 ≤ x ≤ 5'},
    {   'id': 9105,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Неравенства 10',
        'text': 'Решите неравенство: 2x^2 - 11x + 12 < 0',
        'answer': '1.5 < x < 4'},
    {   'id': 9106,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Окружность 5',
        'text': 'Две хорды пересекаются. Отрезки одной 6 и 8, отрезки другой 4 и 12. Верно ли?',
        'answer': '6×8=48, 4×12=48, верно'},
    {   'id': 9107,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Окружность 6',
        'text': 'Из точки вне окружности проведены касательная и секущая. Касательная 12, секущая '
                '18. Найдите внешнюю часть секущей.',
        'answer': '8'},
    {   'id': 9108,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Окружность 7',
        'text': 'Длина дуги 60° равна 2π. Найдите радиус.',
        'answer': '6'},
    {   'id': 9109,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Арифметическая прогрессия 4',
        'text': 'Сумма первых 8 членов 120, a1 = 5. Найдите разность.',
        'answer': '2.5'},
    {   'id': 9110,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Арифметическая прогрессия 5',
        'text': 'a5 = 15, a9 = 27. Найдите a1 и d.',
        'answer': 'a1 = 3, d = 3'},
    {   'id': 9111,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Геометрическая прогрессия 4',
        'text': 'Сумма первых 5 членов 121, b1 = 1. Найдите q.',
        'answer': 'q = 3 или q = -4'},
    {   'id': 9112,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Геометрическая прогрессия 5',
        'text': 'b2 = 12, b5 = 324. Найдите b1 и q.',
        'answer': 'b1 = 4, q = 3'},
    {   'id': 9113,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Перестановки 3',
        'text': "Сколько слов из букв слова 'АББА'?",
        'answer': '6'},
    {   'id': 9114,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Сочетания 3',
        'text': 'Сколькими способами выбрать 5 из 15?',
        'answer': '3003'},
    {   'id': 9115,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Размещения 3',
        'text': 'Сколько четырехзначных чисел из цифр 0-7 без повторений?',
        'answer': '1470'},
    {   'id': 9116,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 4',
        'text': 'Бросают два кубика. Какова вероятность суммы 7?',
        'answer': '1/6'},
    {   'id': 9117,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 5',
        'text': 'Из колоды в 36 карт вытягивают две. Какова вероятность, что обе тузы?',
        'answer': '1/105'},
    {   'id': 9118,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Степени 5',
        'text': 'Вычислите: 2^5 × 2^-3',
        'answer': '4'},
    {   'id': 9119,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Степени 6',
        'text': 'Вычислите: (3^2 × 3^-1)^2',
        'answer': '9'},
    {   'id': 9120,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 6',
        'text': 'Упростите: √(8) + √(18) - √(32)',
        'answer': '√2'},
    {   'id': 9121,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 7',
        'text': 'Упростите: (√3 + √2)(√3 - √2)',
        'answer': '1'},
    {   'id': 9122,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 8',
        'text': 'Упростите: (√5 - √3)^2',
        'answer': '8 - 2√15'},
    {   'id': 9123,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Теорема Пифагора 3',
        'text': 'Катеты относятся как 5:12, гипотенуза 26. Найдите катеты.',
        'answer': '10 и 24'},
    {   'id': 9124,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Теорема Пифагора 4',
        'text': 'Гипотенуза 41, катет 9. Найдите другой катет.',
        'answer': '40'},
    {   'id': 9125,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Синус 3',
        'text': 'В прямоугольном треугольнике катет 5, гипотенуза 13. Найдите синус '
                'противолежащего угла.',
        'answer': '5/13'},
    {   'id': 9126,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Косинус 3',
        'text': 'В прямоугольном треугольнике катет 12, гипотенуза 13. Найдите косинус прилежащего '
                'угла.',
        'answer': '12/13'},
    {   'id': 9127,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Тангенс 3',
        'text': 'В прямоугольном треугольнике катеты 8 и 15. Найдите тангенс меньшего угла.',
        'answer': '8/15'},
    {   'id': 9128,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'Простые числа 3',
        'text': 'Сколько простых чисел от 100 до 150?',
        'answer': '10'},
    {   'id': 9129,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'Простые числа 4',
        'text': 'Сколько простых чисел от 200 до 250?',
        'answer': '9'},
    {   'id': 9130,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'НОД 2',
        'text': 'Найдите НОД(210, 315, 420)',
        'answer': '105'},
    {   'id': 9131,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'НОК 2',
        'text': 'Найдите НОК(15, 18, 20)',
        'answer': '180'},
    {   'id': 9132,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Системы уравнений 4',
        'text': 'Решите систему: {x^2 - y^2 = 16, x + y = 8}',
        'answer': '(6,2)'},
    {   'id': 9133,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Системы уравнений 5',
        'text': 'Решите систему: {x^2 + y^2 = 20, xy = 8}',
        'answer': '(4,2) или (2,4) или (-4,-2) или (-2,-4)'},
    {   'id': 9134,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Подобие 3',
        'text': 'Треугольники подобны. Стороны первого 6,8,10. Периметр второго 36. Найдите '
                'стороны второго.',
        'answer': '9,12,15'},
    {   'id': 9135,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Подобие 4',
        'text': 'Площади подобных треугольников 36 и 81. Найдите коэффициент подобия.',
        'answer': '2:3'},
    {   'id': 9136,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Средняя линия 2',
        'text': 'Средняя линия треугольника на 5 см меньше основания. Найдите основание.',
        'answer': '10 см'},
    {   'id': 9137,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Средняя линия трапеции 2',
        'text': 'Средняя линия трапеции 12, одно основание 8. Найдите другое.',
        'answer': '16'},
    {   'id': 9138,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Функции 3',
        'text': 'Найдите нули функции y = 3x^2 - 7x + 2',
        'answer': 'x = 2, x = 1/3'},
    {   'id': 9139,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Функции 4',
        'text': 'Найдите нули функции y = 4x^2 - 12x + 9',
        'answer': 'x = 1.5'},
    {   'id': 9140,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Графики 3',
        'text': 'Найдите точки пересечения графиков y = x^2 и y = 2x + 3',
        'answer': '(3,9) и (-1,1)'},
    {   'id': 9141,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Графики 4',
        'text': 'Найдите точки пересечения графиков y = x^2 - 2x и y = x',
        'answer': '(0,0) и (3,3)'},
    {   'id': 9142,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Факториал 3',
        'text': 'Вычислите: 8! / 6!',
        'answer': '56'},
    {   'id': 9143,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Факториал 4',
        'text': 'Вычислите: 9! / (6! × 3!)',
        'answer': '84'},
    {   'id': 9144,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 4',
        'text': 'Решите: 3x^2 - 10x + 3 = 0',
        'answer': 'x = 3, x = 1/3'},
    {   'id': 9145,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 5',
        'text': 'Решите: 5x^2 - 14x + 8 = 0',
        'answer': 'x = 2, x = 0.8'},
    {   'id': 9146,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 6',
        'text': 'Решите: 2x^2 - 11x + 15 = 0',
        'answer': 'x = 3, x = 2.5'},
    {   'id': 9147,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Параллелограмм 2',
        'text': 'Стороны параллелограмма 12 и 16, угол между ними 60°. Найдите площадь.',
        'answer': '96√3'},
    {   'id': 9148,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Ромб 2',
        'text': 'Диагонали ромба 18 и 24. Найдите периметр.',
        'answer': '60'},
    {   'id': 9149,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Прямоугольник 2',
        'text': 'Диагональ прямоугольника 20, угол между диагоналями 60°. Найдите площадь.',
        'answer': '100√3'},
    {   'id': 9150,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадрат 2',
        'text': 'Радиус вписанной окружности квадрата 5. Найдите сторону.',
        'answer': '10'},
    {   'id': 9151,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Трапеция 2',
        'text': 'Основания трапеции 10 и 16, боковые стороны 5 и 7. Найдите высоту.',
        'answer': '4'},
    {   'id': 9152,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Степени 7',
        'text': 'Вычислите: (2/3)^-2',
        'answer': '9/4'},
    {   'id': 9153,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Степени 8',
        'text': 'Вычислите: (3^-2 + 2^-3)^-1',
        'answer': '72/17'},
    {   'id': 9154,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 9',
        'text': 'Упростите: √(12 + 2√35)',
        'answer': '√7 + √5'},
    {   'id': 9155,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 10',
        'text': 'Упростите: √(8 - 2√15)',
        'answer': '√5 - √3'},
    {   'id': 9156,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 11',
        'text': 'Упростите: √(13 + 4√3)',
        'answer': '2√3 + 1'},
    {   'id': 9157,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'Делимость 3',
        'text': 'Найдите все трехзначные числа, кратные 17.',
        'answer': '102,119,...,986'},
    {   'id': 9158,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 2,
        'title': 'Делимость 4',
        'text': 'Найдите все трехзначные числа, кратные 19.',
        'answer': '114,133,...,988'},
    {   'id': 9159,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Перестановки 4',
        'text': "Сколько слов из букв слова 'МАТЕМАТИКА'?",
        'answer': '151200'},
    {   'id': 9160,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Сочетания 4',
        'text': 'Сколькими способами выбрать 4 из 12 и 3 из 10?',
        'answer': '495 × 120 = 59400'},
    {   'id': 9161,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Размещения 4',
        'text': 'Сколько пятизначных чисел из цифр 0-8 без повторений?',
        'answer': '15120'},
    {   'id': 9162,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 6',
        'text': 'Бросают три монеты. Какова вероятность, что выпадет ровно два орла?',
        'answer': '3/8'},
    {   'id': 9163,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 7',
        'text': 'Из колоды в 36 карт вытягивают две. Какова вероятность, что они одной масти?',
        'answer': '4×C(9,2)/C(36,2) = 144/630 = 8/35'},
    {   'id': 9164,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Прогрессии 3',
        'text': 'Найдите сумму первых 12 членов арифметической прогрессии: 3,7,11,...',
        'answer': '300'},
    {   'id': 9165,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Прогрессии 4',
        'text': 'Найдите сумму первых 6 членов геометрической прогрессии: 2,6,18,...',
        'answer': '728'},
    {   'id': 9166,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Окружность 8',
        'text': 'Хорда длиной 24 см удалена от центра на 5 см. Найдите радиус.',
        'answer': '13 см'},
    {   'id': 9167,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Окружность 9',
        'text': 'Радиус окружности 17 см, хорда 30 см. Найдите расстояние от центра до хорды.',
        'answer': '8 см'},
    {   'id': 9168,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Касательная 3',
        'text': 'Из точки к окружности проведены две касательные. Радиус 6, расстояние до точки '
                '10. Найдите длину касательной.',
        'answer': '8'},
    {   'id': 9169,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Неравенства 11',
        'text': 'Решите неравенство: 4x - 7 < 2x + 9',
        'answer': 'x < 8'},
    {   'id': 9170,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Неравенства 12',
        'text': 'Решите неравенство: 5x + 8 ≥ 3x - 4',
        'answer': 'x ≥ -6'},
    {   'id': 9171,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Модуль 3',
        'text': 'Решите уравнение: |x + 2| = |x - 4|',
        'answer': 'x = 1'},
    {   'id': 9172,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Модуль 4',
        'text': 'Решите уравнение: |2x - 5| = 3x - 1',
        'answer': 'x = 6 или x = -4/5'},
    {   'id': 9173,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Синус 4',
        'text': 'Найдите sin 120°',
        'answer': '√3/2'},
    {   'id': 9174,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Косинус 4',
        'text': 'Найдите cos 135°',
        'answer': '-√2/2'},
    {   'id': 9175,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Тангенс 4',
        'text': 'Найдите tg 150°',
        'answer': '-1/√3'},
    {   'id': 9176,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Рациональные уравнения 4',
        'text': 'Решите: 2/(x-2) + 3/(x+3) = 1',
        'answer': 'x = 4 или x = -5'},
    {   'id': 9177,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Рациональные уравнения 5',
        'text': 'Решите: (x+3)/(x-2) = (x+2)/(x-3)',
        'answer': 'x = 2.5'},
    {   'id': 9178,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Рациональные уравнения 6',
        'text': 'Решите: 1/(x-1) + 1/(x+2) = 3/4',
        'answer': 'x = 3 или x = -4'},
    {   'id': 9179,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Векторы 4',
        'text': 'Найдите длину вектора a(5,12)',
        'answer': '13'},
    {   'id': 9180,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Векторы 5',
        'text': 'Найдите скалярное произведение векторов a(3,-2) и b(4,5)',
        'answer': '2'},
    {   'id': 9181,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Векторы 6',
        'text': 'Найдите угол между векторами a(1,√3) и b(1,0)',
        'answer': '60°'},
    {   'id': 9182,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 8',
        'text': 'Бросают два кубика. Какова вероятность, что произведение очков равно 6?',
        'answer': '4/36 = 1/9'},
    {   'id': 9183,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 9',
        'text': 'Из урны с 5 белыми и 7 черными шарами вытягивают два. Какова вероятность, что они '
                'разного цвета?',
        'answer': '35/66'},
    {   'id': 9184,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 2,
        'title': 'Вероятность 10',
        'text': 'В классе 15 мальчиков и 10 девочек. Выбирают двух дежурных. Какова вероятность, '
                'что это мальчик и девочка?',
        'answer': '150/300 = 0.5'},
    {   'id': 9185,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратичная функция 11',
        'text': 'Найдите наибольшее значение функции y = -x^2 + 6x - 5',
        'answer': '4'},
    {   'id': 9186,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратичная функция 12',
        'text': 'Найдите наименьшее значение функции y = 2x^2 - 8x + 3',
        'answer': '-5'},
    {   'id': 9187,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Площадь 6',
        'text': 'Найдите площадь ромба со стороной 10 и углом 60°',
        'answer': '50√3'},
    {   'id': 9188,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Площадь 7',
        'text': 'Найдите площадь трапеции с основаниями 8 и 12 и боковыми сторонами 5 и 7',
        'answer': '20√6'},
    {   'id': 9189,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Площадь 8',
        'text': 'Найдите площадь круга, вписанного в квадрат со стороной 8',
        'answer': '16π'},
    {   'id': 9190,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Площадь 9',
        'text': 'Найдите площадь круга, описанного около квадрата со стороной 6',
        'answer': '18π'},
    {   'id': 9191,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 7',
        'text': 'Решите: 4x^2 - 17x + 15 = 0',
        'answer': 'x = 3, x = 1.25'},
    {   'id': 9192,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 8',
        'text': 'Решите: 6x^2 - 19x + 10 = 0',
        'answer': 'x = 2.5, x = 2/3'},
    {   'id': 9193,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадратные уравнения 9',
        'text': 'Решите: 7x^2 - 22x + 15 = 0',
        'answer': 'x = 3, x = 5/7'},
    {   'id': 9194,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Параллелограмм 3',
        'text': 'Диагонали параллелограмма 14 и 18, угол между ними 60°. Найдите стороны.',
        'answer': '√(67) и √(139)'},
    {   'id': 9195,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Ромб 3',
        'text': 'Площадь ромба 96, одна диагональ 12. Найдите сторону.',
        'answer': '10'},
    {   'id': 9196,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Прямоугольник 3',
        'text': 'Диагональ 17, периметр 46. Найдите стороны.',
        'answer': '15 и 8'},
    {   'id': 9197,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Квадрат 3',
        'text': 'Радиус описанной окружности квадрата 5√2. Найдите сторону.',
        'answer': '10'},
    {   'id': 9198,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 2,
        'title': 'Трапеция 3',
        'text': 'Основания 9 и 15, диагонали 13 и 20. Найдите площадь.',
        'answer': '96'},
    {   'id': 9199,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Степени 9',
        'text': 'Вычислите: (2^3 × 3^2)^2 / (2^2 × 3^3)',
        'answer': '2^4 × 3 = 48'},
    {   'id': 9200,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 2,
        'title': 'Корни 12',
        'text': 'Упростите: √(15 + 2√54)',
        'answer': '√9 + √6 = 3 + √6'},
    {   'id': 9201,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратичная функция 13',
        'text': 'Найдите область значений функции y = 3x^2 - 12x + 7',
        'answer': 'y ≥ -5'},
    {   'id': 9202,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратичная функция 14',
        'text': 'Найдите область значений функции y = -2x^2 + 8x - 5',
        'answer': 'y ≤ 3'},
    {   'id': 9203,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Неравенства 13',
        'text': 'Решите неравенство: x^2 - 10x + 21 > 0',
        'answer': 'x < 3 или x > 7'},
    {   'id': 9204,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Неравенства 14',
        'text': 'Решите неравенство: -x^2 + 8x - 12 ≥ 0',
        'answer': '2 ≤ x ≤ 6'},
    {   'id': 9205,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Неравенства 15',
        'text': 'Решите неравенство: 2x^2 - 13x + 15 < 0',
        'answer': '1.5 < x < 5'},
    {   'id': 9206,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Окружность 10',
        'text': 'Две хорды пересекаются. Отрезки одной 9 и 4, отрезки другой 6 и 6. Верно ли?',
        'answer': '9×4=36, 6×6=36, верно'},
    {   'id': 9207,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Окружность 11',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 6 и 8, внутренние '
                'части первой 10. Найдите внутреннюю часть второй.',
        'answer': '7.5'},
    {   'id': 9208,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Окружность 12',
        'text': 'Площадь сектора 90° равна 16π. Найдите радиус.',
        'answer': '8'},
    {   'id': 9209,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Арифметическая прогрессия 6',
        'text': 'Сумма первых 10 членов 155, a1 = 5. Найдите разность.',
        'answer': '2'},
    {   'id': 9210,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Арифметическая прогрессия 7',
        'text': 'a4 = 14, a9 = 29. Найдите a1 и d.',
        'answer': 'a1 = 5, d = 3'},
    {   'id': 9211,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Геометрическая прогрессия 6',
        'text': 'Сумма первых 4 членов 40, b1 = 1. Найдите q.',
        'answer': 'q = 3 или q = -2'},
    {   'id': 9212,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Геометрическая прогрессия 7',
        'text': 'b3 = 24, b6 = 192. Найдите b1 и q.',
        'answer': 'b1 = 6, q = 2'},
    {   'id': 9213,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Перестановки 5',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛОГРАММ'?",
        'answer': '908107200'},
    {   'id': 9214,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Сочетания 5',
        'text': 'Сколькими способами выбрать 6 из 20?',
        'answer': '38760'},
    {   'id': 9215,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Размещения 5',
        'text': 'Сколько шестизначных чисел из цифр 0-9 без повторений?',
        'answer': '151200'},
    {   'id': 9216,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 11',
        'text': 'Бросают три кубика. Какова вероятность, что сумма очков равна 10?',
        'answer': '27/216 = 1/8'},
    {   'id': 9217,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 12',
        'text': 'Из колоды в 52 карты вытягивают 5. Какова вероятность, что это флеш-рояль?',
        'answer': '4/C(52,5) ≈ 1.5e-6'},
    {   'id': 9218,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Степени 10',
        'text': 'Вычислите: (2^4 × 3^5) / (2^2 × 3^3)',
        'answer': '4 × 9 = 36'},
    {   'id': 9219,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Степени 11',
        'text': 'Вычислите: (5^3 × 4^4) / (5^2 × 4^2)',
        'answer': '5 × 16 = 80'},
    {   'id': 9220,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 13',
        'text': 'Упростите: √(14 + 2√33)',
        'answer': '√11 + √3'},
    {   'id': 9221,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 14',
        'text': 'Упростите: √(15 - 2√56)',
        'answer': '√8 - √7 = 2√2 - √7'},
    {   'id': 9222,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 15',
        'text': 'Упростите: √(17 + 6√8)',
        'answer': '3 + √8 = 3 + 2√2'},
    {   'id': 9223,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Теорема Пифагора 5',
        'text': 'Катеты относятся как 8:15, гипотенуза 34. Найдите катеты.',
        'answer': '16 и 30'},
    {   'id': 9224,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Теорема Пифагора 6',
        'text': 'Периметр прямоугольного треугольника 60, гипотенуза 26. Найдите катеты.',
        'answer': '10 и 24'},
    {   'id': 9225,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Синус 5',
        'text': 'В треугольнике стороны 5,6,7. Найдите синус наибольшего угла.',
        'answer': '(√6)/4? нет, по теореме косинусов'},
    {   'id': 9226,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Косинус 5',
        'text': 'В треугольнике стороны 7,8,9. Найдите косинус наименьшего угла.',
        'answer': '(64+81-49)/(2×8×9) = 96/144 = 2/3'},
    {   'id': 9227,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Тангенс 5',
        'text': 'В прямоугольном треугольнике катеты 5 и 12. Найдите тангенс угла против большего '
                'катета.',
        'answer': '12/5'},
    {   'id': 9228,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'Простые числа 5',
        'text': 'Сколько простых чисел от 300 до 350?',
        'answer': '6'},
    {   'id': 9229,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'Простые числа 6',
        'text': 'Сколько простых чисел от 400 до 450?',
        'answer': '8'},
    {   'id': 9230,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'НОД 3',
        'text': 'Найдите НОД(252, 315, 378)',
        'answer': '63'},
    {   'id': 9231,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'НОК 3',
        'text': 'Найдите НОК(16, 24, 36)',
        'answer': '144'},
    {   'id': 9232,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Системы уравнений 6',
        'text': 'Решите систему: {x^2 - xy + y^2 = 21, x + y = 7}',
        'answer': '(4,3) или (3,4)'},
    {   'id': 9233,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Системы уравнений 7',
        'text': 'Решите систему: {x^2 + y^2 = 34, xy = 15}',
        'answer': '(5,3) или (3,5) или (-5,-3) или (-3,-5)'},
    {   'id': 9234,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Подобие 5',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 36. '
                'Найдите площадь треугольника.',
        'answer': '48'},
    {   'id': 9235,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Подобие 6',
        'text': 'Периметры подобных треугольников 25 и 40, разность площадей 105. Найдите площади.',
        'answer': '125 и 245'},
    {   'id': 9236,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Средняя линия 3',
        'text': 'Средняя линия треугольника на 4 см меньше основания. Найдите основание.',
        'answer': '8 см'},
    {   'id': 9237,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Средняя линия трапеции 3',
        'text': 'Средняя линия трапеции 15, одно основание на 6 больше другого. Найдите основания.',
        'answer': '12 и 18'},
    {   'id': 9238,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Функции 5',
        'text': 'Найдите нули функции y = 5x^2 - 12x + 4',
        'answer': 'x = 2, x = 0.4'},
    {   'id': 9239,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Функции 6',
        'text': 'Найдите нули функции y = 6x^2 - 13x + 6',
        'answer': 'x = 1.5, x = 2/3'},
    {   'id': 9240,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Графики 5',
        'text': 'Найдите точки пересечения графиков y = x^2 - 4x и y = 2x - 3',
        'answer': '(1,-1) и (3,3)'},
    {   'id': 9241,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Графики 6',
        'text': 'Найдите точки пересечения графиков y = x^2 - 2x - 3 и y = x + 1',
        'answer': '(4,5) и (-1,0)'},
    {   'id': 9242,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Факториал 5',
        'text': 'Вычислите: 10! / 7!',
        'answer': '720'},
    {   'id': 9243,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Факториал 6',
        'text': 'Вычислите: 11! / (8! × 3!)',
        'answer': '165'},
    {   'id': 9244,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратные уравнения 10',
        'text': 'Решите: 3x^2 - 14x + 15 = 0',
        'answer': 'x = 3, x = 5/3'},
    {   'id': 9245,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратные уравнения 11',
        'text': 'Решите: 4x^2 - 21x + 20 = 0',
        'answer': 'x = 4, x = 1.25'},
    {   'id': 9246,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратные уравнения 12',
        'text': 'Решите: 5x^2 - 22x + 21 = 0',
        'answer': 'x = 3, x = 1.4'},
    {   'id': 9247,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Параллелограмм 4',
        'text': 'Стороны параллелограмма 10 и 14, угол между ними 45°. Найдите площадь.',
        'answer': '70√2'},
    {   'id': 9248,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Ромб 4',
        'text': 'Диагонали ромба 16 и 30. Найдите площадь и сторону.',
        'answer': '240, 17'},
    {   'id': 9249,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Прямоугольник 4',
        'text': 'Диагональ 25, периметр 70. Найдите стороны.',
        'answer': '24 и 11? нет, 24+11=35 периметр 70'},
    {   'id': 9250,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадрат 4',
        'text': 'Радиус вписанной окружности квадрата 6. Найдите диагональ.',
        'answer': '12√2'},
    {   'id': 9251,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Трапеция 4',
        'text': 'Основания 11 и 17, диагонали 15 и 22. Найдите площадь.',
        'answer': '126'},
    {   'id': 9252,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Степени 12',
        'text': 'Вычислите: (2^5 × 3^4)^2 / (2^3 × 3^5)',
        'answer': '2^7 × 3^3 = 128 × 27 = 3456'},
    {   'id': 9253,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Степени 13',
        'text': 'Вычислите: (5^2 × 7^3)^2 / (5^1 × 7^4)',
        'answer': '5^3 × 7^2 = 125 × 49 = 6125'},
    {   'id': 9254,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 16',
        'text': 'Упростите: √(18 + 2√77)',
        'answer': '√11 + √7'},
    {   'id': 9255,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 17',
        'text': 'Упростите: √(19 - 2√78)',
        'answer': '√13 - √6'},
    {   'id': 9256,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Корни 18',
        'text': 'Упростите: √(21 + 8√5)',
        'answer': '4 + √5'},
    {   'id': 9257,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'Делимость 5',
        'text': 'Найдите все трехзначные числа, кратные 23.',
        'answer': '115,138,...,989'},
    {   'id': 9258,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 3,
        'title': 'Делимость 6',
        'text': 'Найдите все трехзначные числа, кратные 29.',
        'answer': '116,145,...,986'},
    {   'id': 9259,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Перестановки 6',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 9260,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Сочетания 6',
        'text': 'Сколькими способами выбрать 7 из 24?',
        'answer': '346104'},
    {   'id': 9261,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Размещения 6',
        'text': 'Сколько семизначных чисел из цифр 0-9 без повторений?',
        'answer': '544320'},
    {   'id': 9262,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 13',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков меньше 5?',
        'answer': '6/36 = 1/6'},
    {   'id': 9263,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 14',
        'text': 'Из урны с 6 белыми и 9 черными шарами вытягивают 3. Какова вероятность, что все '
                'белые?',
        'answer': 'C(6,3)/C(15,3) = 20/455 = 4/91'},
    {   'id': 9264,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Прогрессии 5',
        'text': 'Найдите сумму первых 15 членов арифметической прогрессии: 5,9,13,...',
        'answer': '495'},
    {   'id': 9265,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Прогрессии 6',
        'text': 'Найдите сумму первых 7 членов геометрической прогрессии: 3,6,12,...',
        'answer': '381'},
    {   'id': 9266,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Окружность 13',
        'text': 'Хорда длиной 30 см удалена от центра на 8 см. Найдите радиус.',
        'answer': '17 см'},
    {   'id': 9267,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Окружность 14',
        'text': 'Радиус окружности 25 см, хорда 48 см. Найдите расстояние от центра до хорды.',
        'answer': '7 см'},
    {   'id': 9268,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Касательная 4',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 17, радиус '
                '8. Найдите длину касательной.',
        'answer': '15'},
    {   'id': 9269,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Неравенства 16',
        'text': 'Решите неравенство: 7x - 9 > 5x + 7',
        'answer': 'x > 8'},
    {   'id': 9270,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Неравенства 17',
        'text': 'Решите неравенство: 8x + 5 ≤ 6x - 3',
        'answer': 'x ≤ -4'},
    {   'id': 9271,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Модуль 5',
        'text': 'Решите уравнение: |3x - 2| = |x + 4|',
        'answer': 'x = 3 или x = -0.5'},
    {   'id': 9272,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Модуль 6',
        'text': 'Решите уравнение: |x - 3| + |x + 2| = 7',
        'answer': 'x = 4 или x = -3'},
    {   'id': 9273,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Синус 6',
        'text': 'Найдите sin 135°',
        'answer': '√2/2'},
    {   'id': 9274,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Косинус 6',
        'text': 'Найдите cos 150°',
        'answer': '-√3/2'},
    {   'id': 9275,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Тангенс 6',
        'text': 'Найдите tg 120°',
        'answer': '-√3'},
    {   'id': 9276,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Рациональные уравнения 7',
        'text': 'Решите: 3/(x-3) + 4/(x+4) = 2',
        'answer': 'x = 5 или x = -6'},
    {   'id': 9277,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Рациональные уравнения 8',
        'text': 'Решите: (2x+5)/(x-2) - (x-3)/(x+5) = 1',
        'answer': 'x = 1 или x = -7'},
    {   'id': 9278,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Рациональные уравнения 9',
        'text': 'Решите: 1/(x+2) + 1/(x+3) = 1/(x+4)',
        'answer': 'x = -1 ± √2'},
    {   'id': 9279,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Векторы 7',
        'text': 'Найдите длину вектора a(8,15)',
        'answer': '17'},
    {   'id': 9280,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Векторы 8',
        'text': 'Найдите скалярное произведение векторов a(5,-3) и b(2,7)',
        'answer': '-11'},
    {   'id': 9281,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Векторы 9',
        'text': 'Найдите угол между векторами a(2,2√3) и b(3,0)',
        'answer': '30°'},
    {   'id': 9282,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 15',
        'text': 'Бросают два кубика. Какова вероятность, что произведение очков четное?',
        'answer': '27/36 = 3/4'},
    {   'id': 9283,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 16',
        'text': 'Из колоды в 36 карт вытягивают две. Какова вероятность, что одна туз, а одна '
                'король?',
        'answer': '(4×4)/C(36,2) = 16/630 = 8/315'},
    {   'id': 9284,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 3,
        'title': 'Вероятность 17',
        'text': 'В классе 12 мальчиков и 8 девочек. Выбирают 3 дежурных. Какова вероятность, что '
                'все мальчики?',
        'answer': 'C(12,3)/C(20,3) = 220/1140 = 11/57'},
    {   'id': 9285,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратичная функция 15',
        'text': 'Найдите наибольшее значение функции y = -3x^2 + 12x - 7',
        'answer': '5'},
    {   'id': 9286,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 3,
        'title': 'Квадратичная функция 16',
        'text': 'Найдите наименьшее значение функции y = 4x^2 - 16x + 11',
        'answer': '-5'},
    {   'id': 9287,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Площадь 10',
        'text': 'Найдите площадь ромба со стороной 13 и разностью диагоналей 14',
        'answer': '120'},
    {   'id': 9288,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Площадь 11',
        'text': 'Найдите площадь трапеции с основаниями 10 и 20 и диагоналями 15 и 25',
        'answer': '150'},
    {   'id': 9289,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Площадь 12',
        'text': 'Найдите площадь круга, вписанного в равносторонний треугольник со стороной 12',
        'answer': '12π'},
    {   'id': 9290,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 3,
        'title': 'Площадь 13',
        'text': 'Найдите площадь круга, описанного около равностороннего треугольника со стороной '
                '6',
        'answer': '12π'},
    {   'id': 9301,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратичная функция 17',
        'text': 'При каких значениях k функция y = kx^2 - 4x + 3 не имеет нулей?',
        'answer': 'k > 4/3'},
    {   'id': 9302,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратичная функция 18',
        'text': 'При каких значениях k функция y = 2x^2 + kx + 8 имеет один нуль?',
        'answer': 'k = ±8'},
    {   'id': 9303,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Неравенства 18',
        'text': 'Решите неравенство: x^2 - 12x + 35 > 0',
        'answer': 'x < 5 или x > 7'}]
