PROBLEMS_DB = [   {   'id': 9304,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Неравенства 19',
        'text': 'Решите неравенство: -x^2 + 10x - 24 ≥ 0',
        'answer': '4 ≤ x ≤ 6'},
    {   'id': 9305,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Неравенства 20',
        'text': 'Решите неравенство: 3x^2 - 16x + 16 < 0',
        'answer': '4/3 < x < 4'},
    {   'id': 9306,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Окружность 15',
        'text': 'Две хорды пересекаются. Отрезки одной 12 и 3, отрезки другой 9 и 4. Верно ли?',
        'answer': '12×3=36, 9×4=36, верно'},
    {   'id': 9307,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Окружность 16',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 7 и 9, внутренние '
                'части первой 12. Найдите внутреннюю часть второй.',
        'answer': '8'},
    {   'id': 9308,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Окружность 17',
        'text': 'Площадь сектора 120° равна 48π. Найдите радиус.',
        'answer': '12'},
    {   'id': 9309,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Арифметическая прогрессия 8',
        'text': 'Сумма первых 12 членов 222, a1 = 2. Найдите разность.',
        'answer': '3'},
    {   'id': 9310,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Арифметическая прогрессия 9',
        'text': 'a6 = 20, a12 = 38. Найдите a1 и d.',
        'answer': 'a1 = 5, d = 3'},
    {   'id': 9311,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Геометрическая прогрессия 8',
        'text': 'Сумма первых 5 членов 93, b1 = 3. Найдите q.',
        'answer': 'q = 2 или q = -3'},
    {   'id': 9312,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Геометрическая прогрессия 9',
        'text': 'b4 = 40, b7 = 320. Найдите b1 и q.',
        'answer': 'b1 = 5, q = 2'},
    {   'id': 9313,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Перестановки 7',
        'text': "Сколько слов из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 9314,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Сочетания 7',
        'text': 'Сколькими способами выбрать 8 из 30?',
        'answer': '5852925'},
    {   'id': 9315,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Размещения 7',
        'text': 'Сколько восьмизначных чисел из цифр 0-9 без повторений?',
        'answer': '1632960'},
    {   'id': 9316,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 18',
        'text': 'Бросают три кубика. Какова вероятность, что сумма очков равна 9?',
        'answer': '25/216'},
    {   'id': 9317,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 19',
        'text': 'Из колоды в 52 карты вытягивают 5. Какова вероятность, что все красные?',
        'answer': 'C(26,5)/C(52,5)'},
    {   'id': 9318,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Степени 14',
        'text': 'Вычислите: (2^3 × 3^4)^3 / (2^2 × 3^3)',
        'answer': '2^7 × 3^9 = 128 × 19683 = 2519424'},
    {   'id': 9319,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Степени 15',
        'text': 'Вычислите: (5^2 × 7^3)^3 / (5^1 × 7^2)',
        'answer': '5^5 × 7^7 = 3125 × 823543 = 2.57e+9'},
    {   'id': 9320,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 19',
        'text': 'Упростите: √(22 + 2√105)',
        'answer': '√15 + √7'},
    {   'id': 9321,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 20',
        'text': 'Упростите: √(23 - 2√130)',
        'answer': '√13 - √10'},
    {   'id': 9322,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 21',
        'text': 'Упростите: √(24 + 6√15)',
        'answer': '√15 + 3'},
    {   'id': 9323,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Теорема Пифагора 7',
        'text': 'Катеты относятся как 12:35, гипотенуза 74. Найдите катеты.',
        'answer': '24 и 70'},
    {   'id': 9324,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Теорема Пифагора 8',
        'text': 'Периметр прямоугольного треугольника 84, гипотенуза 35. Найдите катеты.',
        'answer': '21 и 28'},
    {   'id': 9325,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Синус 7',
        'text': 'В треугольнике стороны 8,10,12. Найдите синус наименьшего угла.',
        'answer': '√(15)/4? нет, по теореме косинусов'},
    {   'id': 9326,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Косинус 7',
        'text': 'В треугольнике стороны 9,10,11. Найдите косинус наибольшего угла.',
        'answer': '(81+100-121)/(2×9×10) = 60/180 = 1/3'},
    {   'id': 9327,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Тангенс 7',
        'text': 'В прямоугольном треугольнике гипотенуза 25, катет 7. Найдите тангенс угла против '
                'другого катета.',
        'answer': '24/7'},
    {   'id': 9328,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'Простые числа 7',
        'text': 'Сколько простых чисел от 500 до 550?',
        'answer': '8'},
    {   'id': 9329,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'Простые числа 8',
        'text': 'Сколько простых чисел от 600 до 650?',
        'answer': '7'},
    {   'id': 9330,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'НОД 4',
        'text': 'Найдите НОД(330, 385, 440)',
        'answer': '55'},
    {   'id': 9331,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'НОК 4',
        'text': 'Найдите НОК(18, 24, 30)',
        'answer': '360'},
    {   'id': 9332,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Системы уравнений 8',
        'text': 'Решите систему: {x^2 - xy + y^2 = 31, x - y = 3}',
        'answer': '(5,2) или (-2,-5)'},
    {   'id': 9333,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Системы уравнений 9',
        'text': 'Решите систему: {x^2 + y^2 = 52, x + y = 10}',
        'answer': '(6,4) или (4,6)'},
    {   'id': 9334,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Подобие 7',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 45. '
                'Найдите площадь треугольника.',
        'answer': '60'},
    {   'id': 9335,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Подобие 8',
        'text': 'Периметры подобных треугольников 30 и 48, разность площадей 140. Найдите площади.',
        'answer': '100 и 240'},
    {   'id': 9336,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Средняя линия 4',
        'text': 'Средняя линия треугольника на 3 см меньше основания. Найдите основание.',
        'answer': '6 см'},
    {   'id': 9337,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Средняя линия трапеции 4',
        'text': 'Средняя линия трапеции 18, основания относятся как 2:3. Найдите основания.',
        'answer': '14.4 и 21.6'},
    {   'id': 9338,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Функции 7',
        'text': 'Найдите нули функции y = 7x^2 - 19x + 10',
        'answer': 'x = 2, x = 5/7'},
    {   'id': 9339,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Функции 8',
        'text': 'Найдите нули функции y = 8x^2 - 22x + 15',
        'answer': 'x = 1.5, x = 1.25'},
    {   'id': 9340,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Графики 7',
        'text': 'Найдите точки пересечения графиков y = x^2 - 5x и y = 3x - 8',
        'answer': '(2,-2) и (4,4)'},
    {   'id': 9341,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Графики 8',
        'text': 'Найдите точки пересечения графиков y = x^2 - 3x - 4 и y = x + 1',
        'answer': '(5,6) и (-1,0)'},
    {   'id': 9342,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Факториал 7',
        'text': 'Вычислите: 12! / 9!',
        'answer': '1320'},
    {   'id': 9343,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Факториал 8',
        'text': 'Вычислите: 13! / (9! × 4!)',
        'answer': '715'},
    {   'id': 9344,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 13',
        'text': 'Решите: 3x^2 - 17x + 20 = 0',
        'answer': 'x = 4, x = 5/3'},
    {   'id': 9345,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 14',
        'text': 'Решите: 4x^2 - 23x + 25 = 0',
        'answer': 'x = 5, x = 1.25'},
    {   'id': 9346,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 15',
        'text': 'Решите: 5x^2 - 26x + 24 = 0',
        'answer': 'x = 4, x = 1.2'},
    {   'id': 9347,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Параллелограмм 5',
        'text': 'Стороны параллелограмма 12 и 18, угол между ними 120°. Найдите площадь.',
        'answer': '108√3'},
    {   'id': 9348,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Ромб 5',
        'text': 'Диагонали ромба 20 и 48. Найдите площадь и сторону.',
        'answer': '480, 26'},
    {   'id': 9349,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Прямоугольник 5',
        'text': 'Диагональ 29, периметр 82. Найдите стороны.',
        'answer': '20 и 21? нет, 20+21=41 периметр 82'},
    {   'id': 9350,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадрат 5',
        'text': 'Радиус описанной окружности квадрата 7√2. Найдите сторону.',
        'answer': '14'},
    {   'id': 9351,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Трапеция 5',
        'text': 'Основания 13 и 19, диагонали 17 и 25. Найдите площадь.',
        'answer': '192'},
    {   'id': 9352,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Степени 16',
        'text': 'Вычислите: (2^4 × 3^5)^3 / (2^3 × 3^4)',
        'answer': '2^9 × 3^11 = 512 × 177147 = 90720000'},
    {   'id': 9353,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Степени 17',
        'text': 'Вычислите: (5^3 × 7^4)^2 / (5^2 × 7^3)',
        'answer': '5^4 × 7^5 = 625 × 16807 = 10504375'},
    {   'id': 9354,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 22',
        'text': 'Упростите: √(26 + 2√153)',
        'answer': '√17 + √9 = √17 + 3'},
    {   'id': 9355,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 23',
        'text': 'Упростите: √(27 - 2√182)',
        'answer': '√14 - √13'},
    {   'id': 9356,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 24',
        'text': 'Упростите: √(28 + 10√3)',
        'answer': '5 + √3'},
    {   'id': 9357,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'Делимость 7',
        'text': 'Найдите все трехзначные числа, кратные 31.',
        'answer': '124,155,...,992'},
    {   'id': 9358,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 4,
        'title': 'Делимость 8',
        'text': 'Найдите все трехзначные числа, кратные 37.',
        'answer': '111,148,...,999'},
    {   'id': 9359,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Перестановки 8',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛЕПИПЕД'?",
        'answer': '1089728640'},
    {   'id': 9360,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Сочетания 8',
        'text': 'Сколькими способами выбрать 9 из 32?',
        'answer': '28048800'},
    {   'id': 9361,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Размещения 8',
        'text': 'Сколько девятизначных чисел из цифр 0-9 без повторений?',
        'answer': '3265920'},
    {   'id': 9362,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 20',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков больше 9?',
        'answer': '6/36 = 1/6'},
    {   'id': 9363,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 21',
        'text': 'Из урны с 7 белыми и 8 черными шарами вытягивают 4. Какова вероятность, что 3 '
                'белых и 1 черный?',
        'answer': 'C(7,3)×C(8,1)/C(15,4)'},
    {   'id': 9364,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Прогрессии 7',
        'text': 'Найдите сумму первых 20 членов арифметической прогрессии: 7,11,15,...',
        'answer': '900'},
    {   'id': 9365,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Прогрессии 8',
        'text': 'Найдите сумму первых 8 членов геометрической прогрессии: 4,12,36,...',
        'answer': '13120'},
    {   'id': 9366,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Окружность 18',
        'text': 'Хорда длиной 32 см удалена от центра на 12 см. Найдите радиус.',
        'answer': '20 см'},
    {   'id': 9367,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Окружность 19',
        'text': 'Радиус окружности 29 см, хорда 40 см. Найдите расстояние от центра до хорды.',
        'answer': '21 см'},
    {   'id': 9368,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Касательная 5',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 25, радиус '
                '7. Найдите длину касательной.',
        'answer': '24'},
    {   'id': 9369,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Неравенства 21',
        'text': 'Решите неравенство: 9x - 11 > 7x + 13',
        'answer': 'x > 12'},
    {   'id': 9370,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Неравенства 22',
        'text': 'Решите неравенство: 10x + 7 ≤ 8x - 5',
        'answer': 'x ≤ -6'},
    {   'id': 9371,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Модуль 7',
        'text': 'Решите уравнение: |4x - 3| = |2x + 5|',
        'answer': 'x = 4 или x = -1/3'},
    {   'id': 9372,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Модуль 8',
        'text': 'Решите уравнение: |x - 4| + |x + 3| = 9',
        'answer': 'x = 5 или x = -4'},
    {   'id': 9373,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Синус 8',
        'text': 'Найдите sin 150°',
        'answer': '0.5'},
    {   'id': 9374,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Косинус 8',
        'text': 'Найдите cos 120°',
        'answer': '-0.5'},
    {   'id': 9375,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Тангенс 8',
        'text': 'Найдите tg 135°',
        'answer': '-1'},
    {   'id': 9376,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Рациональные уравнения 10',
        'text': 'Решите: 4/(x-4) + 5/(x+5) = 3',
        'answer': 'x = 6 или x = -7'},
    {   'id': 9377,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Рациональные уравнения 11',
        'text': 'Решите: (3x+7)/(x-3) - (2x-5)/(x+4) = 2',
        'answer': 'x = 2 или x = -8'},
    {   'id': 9378,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Рациональные уравнения 12',
        'text': 'Решите: 2/(x+3) + 3/(x+4) = 4/(x+5)',
        'answer': 'x = -1 ± √2'},
    {   'id': 9379,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Векторы 10',
        'text': 'Найдите длину вектора a(9,40)',
        'answer': '41'},
    {   'id': 9380,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Векторы 11',
        'text': 'Найдите скалярное произведение векторов a(6,-2) и b(3,9)',
        'answer': '0'},
    {   'id': 9381,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Векторы 12',
        'text': 'Найдите угол между векторами a(3,4) и b(5,12)',
        'answer': 'arccos(63/65)'},
    {   'id': 9382,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 22',
        'text': 'Бросают два кубика. Какова вероятность, что произведение очков нечетное?',
        'answer': '9/36 = 1/4'},
    {   'id': 9383,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 23',
        'text': 'Из колоды в 36 карт вытягивают три. Какова вероятность, что все одной масти?',
        'answer': '4×C(9,3)/C(36,3) = 336/7140 = 56/1190'},
    {   'id': 9384,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 4,
        'title': 'Вероятность 24',
        'text': 'В классе 15 мальчиков и 10 девочек. Выбирают 4 дежурных. Какова вероятность, что '
                'мальчиков и девочек поровну?',
        'answer': 'C(15,2)×C(10,2)/C(25,4)'},
    {   'id': 9385,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратичная функция 19',
        'text': 'При каких значениях k функция y = kx^2 - 6x + 2 имеет два нуля?',
        'answer': 'k < 9/2 и k ≠ 0'},
    {   'id': 9386,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратичная функция 20',
        'text': 'При каких значениях k функция y = 3x^2 + kx + 12 имеет один нуль?',
        'answer': 'k = ±12'},
    {   'id': 9387,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Площадь 14',
        'text': 'Найдите площадь ромба с диагоналями 24 и 32',
        'answer': '384'},
    {   'id': 9388,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Площадь 15',
        'text': 'Найдите площадь трапеции с основаниями 15 и 25 и высотой 12',
        'answer': '240'},
    {   'id': 9389,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Площадь 16',
        'text': 'Найдите площадь круга, вписанного в прямоугольный треугольник с катетами 5 и 12',
        'answer': '4π'},
    {   'id': 9390,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Площадь 17',
        'text': 'Найдите площадь круга, описанного около прямоугольного треугольника с катетами 9 '
                'и 12',
        'answer': '56.25π'},
    {   'id': 9391,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 16',
        'text': 'Решите: 6x^2 - 25x + 21 = 0',
        'answer': 'x = 3, x = 7/6'},
    {   'id': 9392,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 17',
        'text': 'Решите: 7x^2 - 29x + 22 = 0',
        'answer': 'x = 2, x = 11/7'},
    {   'id': 9393,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадратные уравнения 18',
        'text': 'Решите: 8x^2 - 30x + 25 = 0',
        'answer': 'x = 2.5, x = 1.25'},
    {   'id': 9394,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Параллелограмм 6',
        'text': 'Диагонали параллелограмма 16 и 20, угол между ними 60°. Найдите стороны.',
        'answer': '√(84) и √(196) = 2√21 и 14'},
    {   'id': 9395,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Ромб 6',
        'text': 'Площадь ромба 600, одна диагональ 30. Найдите сторону.',
        'answer': '25'},
    {   'id': 9396,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Прямоугольник 6',
        'text': 'Диагональ 41, периметр 98. Найдите стороны.',
        'answer': '40 и 9'},
    {   'id': 9397,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Квадрат 6',
        'text': 'Радиус вписанной окружности квадрата 7. Найдите диагональ.',
        'answer': '14√2'},
    {   'id': 9398,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 4,
        'title': 'Трапеция 6',
        'text': 'Основания 14 и 22, диагонали 18 и 26. Найдите площадь.',
        'answer': '216'},
    {   'id': 9399,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Степени 18',
        'text': 'Вычислите: (3^3 × 4^4)^2 / (3^2 × 4^3)',
        'answer': '3^4 × 4^5 = 81 × 1024 = 82944'},
    {   'id': 9400,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 4,
        'title': 'Корни 25',
        'text': 'Упростите: √(29 + 4√35)',
        'answer': '√20 + √9 = 2√5 + 3'},
    {   'id': 9401,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратичная функция 21',
        'text': 'При каких значениях k функция y = kx^2 - 8x + 4 не имеет нулей?',
        'answer': 'k > 4'},
    {   'id': 9402,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратичная функция 22',
        'text': 'При каких значениях k функция y = 5x^2 + kx + 20 имеет один нуль?',
        'answer': 'k = ±20'},
    {   'id': 9403,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Неравенства 23',
        'text': 'Решите неравенство: x^2 - 14x + 48 > 0',
        'answer': 'x < 6 или x > 8'},
    {   'id': 9404,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Неравенства 24',
        'text': 'Решите неравенство: -x^2 + 12x - 35 ≥ 0',
        'answer': '5 ≤ x ≤ 7'},
    {   'id': 9405,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Неравенства 25',
        'text': 'Решите неравенство: 4x^2 - 19x + 12 < 0',
        'answer': '0.75 < x < 4'},
    {   'id': 9406,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Окружность 20',
        'text': 'Две хорды пересекаются. Отрезки одной 15 и 2, отрезки другой 10 и 3. Верно ли?',
        'answer': '15×2=30, 10×3=30, верно'},
    {   'id': 9407,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Окружность 21',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 8 и 10, внутренние '
                'части первой 14. Найдите внутреннюю часть второй.',
        'answer': '9.2'},
    {   'id': 9408,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Окружность 22',
        'text': 'Площадь сектора 150° равна 60π. Найдите радиус.',
        'answer': '12'},
    {   'id': 9409,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Арифметическая прогрессия 10',
        'text': 'Сумма первых 15 членов 300, a1 = 3. Найдите разность.',
        'answer': '2'},
    {   'id': 9410,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Арифметическая прогрессия 11',
        'text': 'a7 = 25, a14 = 46. Найдите a1 и d.',
        'answer': 'a1 = 7, d = 3'},
    {   'id': 9411,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Геометрическая прогрессия 10',
        'text': 'Сумма первых 6 членов 189, b1 = 3. Найдите q.',
        'answer': 'q = 2 или q = -3'},
    {   'id': 9412,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Геометрическая прогрессия 11',
        'text': 'b3 = 45, b6 = 1215. Найдите b1 и q.',
        'answer': 'b1 = 5, q = 3'},
    {   'id': 9413,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Перестановки 9',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 9414,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Сочетания 9',
        'text': 'Сколькими способами выбрать 10 из 35?',
        'answer': '183579396'},
    {   'id': 9415,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Размещения 9',
        'text': 'Сколько десятизначных чисел из цифр 0-9 без повторений?',
        'answer': '3265920'},
    {   'id': 9416,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 25',
        'text': 'Бросают три кубика. Какова вероятность, что сумма очков равна 8?',
        'answer': '21/216 = 7/72'},
    {   'id': 9417,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 26',
        'text': 'Из колоды в 52 карты вытягивают 5. Какова вероятность, что все карты одной масти?',
        'answer': '4×C(13,5)/C(52,5)'},
    {   'id': 9418,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Степени 19',
        'text': 'Вычислите: (2^5 × 3^6)^2 / (2^3 × 3^4)',
        'answer': '2^7 × 3^8 = 128 × 6561 = 839808'},
    {   'id': 9419,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Степени 20',
        'text': 'Вычислите: (5^3 × 7^4)^2 / (5^2 × 7^3)',
        'answer': '5^4 × 7^5 = 625 × 16807 = 10504375'},
    {   'id': 9420,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 26',
        'text': 'Упростите: √(31 + 2√210)',
        'answer': '√15 + √14'},
    {   'id': 9421,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 27',
        'text': 'Упростите: √(33 - 2√288)',
        'answer': '√16 - √17? нет, 16×17=272'},
    {   'id': 9422,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 28',
        'text': 'Упростите: √(34 + 6√33)',
        'answer': '3 + √33'},
    {   'id': 9423,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Теорема Пифагора 9',
        'text': 'Катеты относятся как 20:21, гипотенуза 58. Найдите катеты.',
        'answer': '40 и 42'},
    {   'id': 9424,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Теорема Пифагора 10',
        'text': 'Периметр прямоугольного треугольника 90, гипотенуза 39. Найдите катеты.',
        'answer': '15 и 36'},
    {   'id': 9425,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Синус 9',
        'text': 'В треугольнике стороны 10,13,13. Найдите синус угла при основании.',
        'answer': '12/13'},
    {   'id': 9426,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Косинус 9',
        'text': 'В треугольнике стороны 7,24,25. Найдите косинус наименьшего угла.',
        'answer': '24/25'},
    {   'id': 9427,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Тангенс 9',
        'text': 'В прямоугольном треугольнике гипотенуза 17, катет 8. Найдите тангенс угла против '
                'другого катета.',
        'answer': '15/8'},
    {   'id': 9428,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'Простые числа 9',
        'text': 'Сколько простых чисел от 700 до 750?',
        'answer': '5'},
    {   'id': 9429,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'Простые числа 10',
        'text': 'Сколько простых чисел от 800 до 850?',
        'answer': '5'},
    {   'id': 9430,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'НОД 5',
        'text': 'Найдите НОД(420, 462, 504)',
        'answer': '42'},
    {   'id': 9431,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'НОК 5',
        'text': 'Найдите НОК(20, 24, 30)',
        'answer': '120'},
    {   'id': 9432,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Системы уравнений 10',
        'text': 'Решите систему: {x^2 - xy + y^2 = 43, x + y = 9}',
        'answer': '(5,4) или (4,5)'},
    {   'id': 9433,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Системы уравнений 11',
        'text': 'Решите систему: {x^2 + y^2 = 61, xy = 30}',
        'answer': '(6,5) или (5,6) или (-6,-5) или (-5,-6)'},
    {   'id': 9434,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Подобие 9',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 54. '
                'Найдите площадь треугольника.',
        'answer': '72'},
    {   'id': 9435,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Подобие 10',
        'text': 'Периметры подобных треугольников 35 и 56, разность площадей 294. Найдите площади.',
        'answer': '150 и 444'},
    {   'id': 9436,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Средняя линия 5',
        'text': 'Средняя линия треугольника на 5 см меньше основания. Найдите основание.',
        'answer': '10 см'},
    {   'id': 9437,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Средняя линия трапеции 5',
        'text': 'Средняя линия трапеции 20, основания относятся как 2:5. Найдите основания.',
        'answer': '11.43 и 28.57'},
    {   'id': 9438,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Функции 9',
        'text': 'Найдите нули функции y = 9x^2 - 31x + 22',
        'answer': 'x = 2, x = 11/9'},
    {   'id': 9439,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Функции 10',
        'text': 'Найдите нули функции y = 10x^2 - 33x + 20',
        'answer': 'x = 2.5, x = 0.8'},
    {   'id': 9440,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Графики 9',
        'text': 'Найдите точки пересечения графиков y = x^2 - 6x + 8 и y = 2x - 4',
        'answer': '(3,2) и (4,4)'},
    {   'id': 9441,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Графики 10',
        'text': 'Найдите точки пересечения графиков y = x^2 - 4x - 5 и y = x + 1',
        'answer': '(6,7) и (-1,0)'},
    {   'id': 9442,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Факториал 9',
        'text': 'Вычислите: 14! / 11!',
        'answer': '2184'},
    {   'id': 9443,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Факториал 10',
        'text': 'Вычислите: 15! / (10! × 5!)',
        'answer': '3003'},
    {   'id': 9444,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 19',
        'text': 'Решите: 3x^2 - 20x + 25 = 0',
        'answer': 'x = 5, x = 5/3'},
    {   'id': 9445,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 20',
        'text': 'Решите: 4x^2 - 25x + 30 = 0',
        'answer': 'x = 5, x = 1.5? нет, D=625-480=145'},
    {   'id': 9446,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 21',
        'text': 'Решите: 5x^2 - 28x + 32 = 0',
        'answer': 'x = 4, x = 1.6'},
    {   'id': 9447,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Параллелограмм 7',
        'text': 'Стороны параллелограмма 14 и 20, угол между ними 135°. Найдите площадь.',
        'answer': '140√2'},
    {   'id': 9448,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Ромб 7',
        'text': 'Диагонали ромба 24 и 32. Найдите площадь и сторону.',
        'answer': '384, 20'},
    {   'id': 9449,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Прямоугольник 7',
        'text': 'Диагональ 45, периметр 126. Найдите стороны.',
        'answer': '36 и 27'},
    {   'id': 9450,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадрат 7',
        'text': 'Радиус описанной окружности квадрата 8√2. Найдите сторону.',
        'answer': '16'},
    {   'id': 9451,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Трапеция 7',
        'text': 'Основания 16 и 24, диагонали 20 и 30. Найдите площадь.',
        'answer': '300'},
    {   'id': 9452,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Степени 21',
        'text': 'Вычислите: (2^4 × 3^5)^3 / (2^3 × 3^4)',
        'answer': '2^9 × 3^11 = 512 × 177147 = 90720000'},
    {   'id': 9453,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Степени 22',
        'text': 'Вычислите: (5^2 × 7^3)^3 / (5^1 × 7^2)',
        'answer': '5^5 × 7^7 = 3125 × 823543 = 2.57e+9'},
    {   'id': 9454,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 29',
        'text': 'Упростите: √(35 + 2√294)',
        'answer': '√14 + √21'},
    {   'id': 9455,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 30',
        'text': 'Упростите: √(37 - 2√300)',
        'answer': '√12 - √25 = 2√3 - 5? нет'},
    {   'id': 9456,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 31',
        'text': 'Упростите: √(38 + 12√10)',
        'answer': '2√10 + 3'},
    {   'id': 9457,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'Делимость 9',
        'text': 'Найдите все трехзначные числа, кратные 41.',
        'answer': '123,164,...,984'},
    {   'id': 9458,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 5,
        'title': 'Делимость 10',
        'text': 'Найдите все трехзначные числа, кратные 43.',
        'answer': '129,172,...,989'},
    {   'id': 9459,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Перестановки 10',
        'text': "Сколько слов из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 9460,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Сочетания 10',
        'text': 'Сколькими способами выбрать 11 из 36?',
        'answer': '600805296'},
    {   'id': 9461,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Размещения 10',
        'text': 'Сколько одиннадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '239500800'},
    {   'id': 9462,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 27',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков делится на 3?',
        'answer': '12/36 = 1/3'},
    {   'id': 9463,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 28',
        'text': 'Из урны с 8 белыми и 12 черными шарами вытягивают 5. Какова вероятность, что '
                'ровно 2 белых?',
        'answer': 'C(8,2)×C(12,3)/C(20,5)'},
    {   'id': 9464,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Прогрессии 9',
        'text': 'Найдите сумму первых 25 членов арифметической прогрессии: 9,13,17,...',
        'answer': '1425'},
    {   'id': 9465,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Прогрессии 10',
        'text': 'Найдите сумму первых 9 членов геометрической прогрессии: 5,10,20,...',
        'answer': '2555'},
    {   'id': 9466,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Окружность 23',
        'text': 'Хорда длиной 34 см удалена от центра на 15 см. Найдите радиус.',
        'answer': '√(289+225)=√514'},
    {   'id': 9467,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Окружность 24',
        'text': 'Радиус окружности 26 см, хорда 48 см. Найдите расстояние от центра до хорды.',
        'answer': '10 см'},
    {   'id': 9468,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Касательная 6',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 29, радиус '
                '20. Найдите длину касательной.',
        'answer': '21'},
    {   'id': 9469,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Неравенства 26',
        'text': 'Решите неравенство: 11x - 13 > 9x + 15',
        'answer': 'x > 14'},
    {   'id': 9470,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Неравенства 27',
        'text': 'Решите неравенство: 12x + 9 ≤ 10x - 7',
        'answer': 'x ≤ -8'},
    {   'id': 9471,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Модуль 9',
        'text': 'Решите уравнение: |5x - 4| = |3x + 6|',
        'answer': 'x = 5 или x = -0.25'},
    {   'id': 9472,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Модуль 10',
        'text': 'Решите уравнение: |x - 5| + |x + 4| = 11',
        'answer': 'x = 6 или x = -5'},
    {   'id': 9473,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Синус 10',
        'text': 'Найдите sin 165°',
        'answer': '(√6-√2)/4'},
    {   'id': 9474,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Косинус 10',
        'text': 'Найдите cos 105°',
        'answer': '(√2-√6)/4'},
    {   'id': 9475,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Тангенс 10',
        'text': 'Найдите tg 165°',
        'answer': '√3-2'},
    {   'id': 9476,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Рациональные уравнения 13',
        'text': 'Решите: 5/(x-5) + 6/(x+6) = 4',
        'answer': 'x = 7 или x = -8'},
    {   'id': 9477,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Рациональные уравнения 14',
        'text': 'Решите: (4x+9)/(x-4) - (3x-7)/(x+5) = 3',
        'answer': 'x = 3 или x = -9'},
    {   'id': 9478,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Рациональные уравнения 15',
        'text': 'Решите: 3/(x+4) + 4/(x+5) = 5/(x+6)',
        'answer': 'x = -2 ± √2'},
    {   'id': 9479,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Векторы 13',
        'text': 'Найдите длину вектора a(11,60)',
        'answer': '61'},
    {   'id': 9480,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Векторы 14',
        'text': 'Найдите скалярное произведение векторов a(7,-5) и b(3,4)',
        'answer': '1'},
    {   'id': 9481,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Векторы 15',
        'text': 'Найдите угол между векторами a(4,3) и b(8,15)',
        'answer': 'arccos(77/85)'},
    {   'id': 9482,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 29',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков простое число?',
        'answer': '15/36 = 5/12'},
    {   'id': 9483,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 30',
        'text': 'Из колоды в 36 карт вытягивают 4. Какова вероятность, что все тузы?',
        'answer': '1/C(36,4) = 1/58905'},
    {   'id': 9484,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 5,
        'title': 'Вероятность 31',
        'text': 'В классе 16 мальчиков и 12 девочек. Выбирают 5 дежурных. Какова вероятность, что '
                'мальчиков больше, чем девочек?',
        'answer': 'Сумма C(16,k)×C(12,5-k) для k>2.5'},
    {   'id': 9485,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратичная функция 23',
        'text': 'При каких значениях k функция y = kx^2 - 10x + 5 имеет два нуля?',
        'answer': 'k < 5'},
    {   'id': 9486,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратичная функция 24',
        'text': 'При каких значениях k функция y = 4x^2 + kx + 25 имеет один нуль?',
        'answer': 'k = ±20'},
    {   'id': 9487,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Площадь 18',
        'text': 'Найдите площадь ромба с диагоналями 30 и 40',
        'answer': '600'},
    {   'id': 9488,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Площадь 19',
        'text': 'Найдите площадь трапеции с основаниями 18 и 32 и высотой 15',
        'answer': '375'},
    {   'id': 9489,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Площадь 20',
        'text': 'Найдите площадь круга, вписанного в прямоугольный треугольник с катетами 7 и 24',
        'answer': '9π'},
    {   'id': 9490,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Площадь 21',
        'text': 'Найдите площадь круга, описанного около прямоугольного треугольника с катетами 15 '
                'и 20',
        'answer': '156.25π'},
    {   'id': 9491,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 22',
        'text': 'Решите: 6x^2 - 29x + 30 = 0',
        'answer': 'x = 3, x = 5/3'},
    {   'id': 9492,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 23',
        'text': 'Решите: 7x^2 - 31x + 24 = 0',
        'answer': 'x = 3, x = 8/7'},
    {   'id': 9493,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадратные уравнения 24',
        'text': 'Решите: 8x^2 - 33x + 27 = 0',
        'answer': 'x = 3, x = 9/8'},
    {   'id': 9494,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Параллелограмм 8',
        'text': 'Диагонали параллелограмма 18 и 24, угол между ними 60°. Найдите стороны.',
        'answer': '√(117) и √(333)'},
    {   'id': 9495,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Ромб 8',
        'text': 'Площадь ромба 840, одна диагональ 40. Найдите сторону.',
        'answer': '29'},
    {   'id': 9496,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Прямоугольник 8',
        'text': 'Диагональ 53, периметр 146. Найдите стороны.',
        'answer': '44 и 29? нет, 44+29=73 периметр 146'},
    {   'id': 9497,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Квадрат 8',
        'text': 'Радиус вписанной окружности квадрата 8. Найдите диагональ.',
        'answer': '16√2'},
    {   'id': 9498,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 5,
        'title': 'Трапеция 8',
        'text': 'Основания 15 и 25, диагонали 20 и 30. Найдите площадь.',
        'answer': '300'},
    {   'id': 9499,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Степени 23',
        'text': 'Вычислите: (3^4 × 4^5)^2 / (3^3 × 4^4)',
        'answer': '3^5 × 4^6 = 243 × 4096 = 995328'},
    {   'id': 9500,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 5,
        'title': 'Корни 32',
        'text': 'Упростите: √(41 + 12√11)',
        'answer': '√11 + 6? нет, (√11+6)^2 = 11+36+12√11=47+12√11'},
    {   'id': 9501,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратичная функция 25',
        'text': 'При каких значениях k функция y = kx^2 - 12x + 9 не имеет нулей?',
        'answer': 'k > 4'},
    {   'id': 9502,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратичная функция 26',
        'text': 'При каких значениях k функция y = 6x^2 + kx + 24 имеет один нуль?',
        'answer': 'k = ±24'},
    {   'id': 9503,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Неравенства 28',
        'text': 'Решите неравенство: x^2 - 16x + 63 > 0',
        'answer': 'x < 7 или x > 9'},
    {   'id': 9504,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Неравенства 29',
        'text': 'Решите неравенство: -x^2 + 14x - 48 ≥ 0',
        'answer': '6 ≤ x ≤ 8'},
    {   'id': 9505,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Неравенства 30',
        'text': 'Решите неравенство: 5x^2 - 21x + 18 < 0',
        'answer': '1.2 < x < 3'},
    {   'id': 9506,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Окружность 25',
        'text': 'Две хорды пересекаются. Отрезки одной 18 и 2, отрезки другой 12 и 3. Верно ли?',
        'answer': '18×2=36, 12×3=36, верно'},
    {   'id': 9507,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Окружность 26',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 9 и 11, внутренние '
                'части первой 16. Найдите внутреннюю часть второй.',
        'answer': '10.18'},
    {   'id': 9508,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Окружность 27',
        'text': 'Площадь сектора 135° равна 54π. Найдите радиус.',
        'answer': '12'},
    {   'id': 9509,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 12',
        'text': 'Сумма первых 18 членов 432, a1 = 4. Найдите разность.',
        'answer': '2.5'},
    {   'id': 9510,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Арифметическая прогрессия 13',
        'text': 'a8 = 30, a15 = 51. Найдите a1 и d.',
        'answer': 'a1 = 9, d = 3'},
    {   'id': 9511,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 12',
        'text': 'Сумма первых 5 членов 242, b1 = 2. Найдите q.',
        'answer': 'q = 3 или q = -4'},
    {   'id': 9512,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Геометрическая прогрессия 13',
        'text': 'b4 = 64, b7 = 512. Найдите b1 и q.',
        'answer': 'b1 = 8, q = 2'},
    {   'id': 9513,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Перестановки 11',
        'text': "Сколько слов из букв слова 'ПАРАЛЛЕЛЕПИПЕД'?",
        'answer': '1089728640'},
    {   'id': 9514,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Сочетания 11',
        'text': 'Сколькими способами выбрать 12 из 38?',
        'answer': '2.1e+9'},
    {   'id': 9515,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Размещения 11',
        'text': 'Сколько двенадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '239500800'},
    {   'id': 9516,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 32',
        'text': 'Бросают три кубика. Какова вероятность, что сумма очков равна 12?',
        'answer': '25/216'},
    {   'id': 9517,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 33',
        'text': 'Из колоды в 52 карты вытягивают 6. Какова вероятность, что все красные?',
        'answer': 'C(26,6)/C(52,6)'},
    {   'id': 9518,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Степени 24',
        'text': 'Вычислите: (2^5 × 3^6)^3 / (2^4 × 3^5)',
        'answer': '2^11 × 3^13 = 2048 × 1594323 = 3.26e+9'},
    {   'id': 9519,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Степени 25',
        'text': 'Вычислите: (5^3 × 7^4)^3 / (5^2 × 7^3)',
        'answer': '5^7 × 7^9 = 78125 × 40353607 = 3.15e+12'},
    {   'id': 9520,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 33',
        'text': 'Упростите: √(43 + 2√330)',
        'answer': '√15 + √28 = √15 + 2√7'},
    {   'id': 9521,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 34',
        'text': 'Упростите: √(44 - 2√375)',
        'answer': '√25 - √15 = 5 - √15'},
    {   'id': 9522,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 35',
        'text': 'Упростите: √(45 + 6√20)',
        'answer': '3√5 + 3? нет'},
    {   'id': 9523,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Теорема Пифагора 11',
        'text': 'Катеты относятся как 28:45, гипотенуза 106. Найдите катеты.',
        'answer': '56 и 90'},
    {   'id': 9524,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Теорема Пифагора 12',
        'text': 'Периметр прямоугольного треугольника 132, гипотенуза 61. Найдите катеты.',
        'answer': '60 и 11? нет, 60+11+61=132'},
    {   'id': 9525,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Синус 11',
        'text': 'В треугольнике стороны 13,14,15. Найдите синус наибольшего угла.',
        'answer': '12/13'},
    {   'id': 9526,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Косинус 11',
        'text': 'В треугольнике стороны 11,12,13. Найдите косинус среднего угла.',
        'answer': '(121+169-144)/(2×11×13) = 146/286 = 73/143'},
    {   'id': 9527,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Тангенс 11',
        'text': 'В прямоугольном треугольнике катеты 8 и 15. Найдите тангенс угла против меньшего '
                'катета.',
        'answer': '8/15'},
    {   'id': 9528,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'Простые числа 11',
        'text': 'Сколько простых чисел от 900 до 950?',
        'answer': '4'},
    {   'id': 9529,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'Простые числа 12',
        'text': 'Сколько простых чисел от 1000 до 1050?',
        'answer': '5'},
    {   'id': 9530,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'НОД 6',
        'text': 'Найдите НОД(504, 588, 672)',
        'answer': '84'},
    {   'id': 9531,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'НОК 6',
        'text': 'Найдите НОК(24, 28, 32)',
        'answer': '672'},
    {   'id': 9532,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Системы уравнений 12',
        'text': 'Решите систему: {x^2 - xy + y^2 = 57, x + y = 11}',
        'answer': '(7,4) или (4,7)'},
    {   'id': 9533,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Системы уравнений 13',
        'text': 'Решите систему: {x^2 + y^2 = 85, xy = 38}',
        'answer': '(7,5.43)? нет, дискриминант'}]
