PROBLEMS_DB = [   {   'id': 9534,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Подобие 11',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 63. '
                'Найдите площадь треугольника.',
        'answer': '84'},
    {   'id': 9535,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Подобие 12',
        'text': 'Периметры подобных треугольников 40 и 64, разность площадей 336. Найдите площади.',
        'answer': '300 и 636'},
    {   'id': 9536,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Средняя линия 6',
        'text': 'Средняя линия треугольника на 6 см меньше основания. Найдите основание.',
        'answer': '12 см'},
    {   'id': 9537,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Средняя линия трапеции 6',
        'text': 'Средняя линия трапеции 22, основания относятся как 3:8. Найдите основания.',
        'answer': '12 и 32'},
    {   'id': 9538,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Функции 11',
        'text': 'Найдите нули функции y = 11x^2 - 34x + 24',
        'answer': 'x = 2, x = 12/11'},
    {   'id': 9539,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Функции 12',
        'text': 'Найдите нули функции y = 12x^2 - 35x + 25',
        'answer': 'x = 1.25, x = 5/3'},
    {   'id': 9540,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Графики 11',
        'text': 'Найдите точки пересечения графиков y = x^2 - 7x + 10 и y = 2x - 2',
        'answer': '(3,4) и (4,6)'},
    {   'id': 9541,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Графики 12',
        'text': 'Найдите точки пересечения графиков y = x^2 - 5x - 6 и y = x - 2',
        'answer': '(7,5) и (-1,-3)'},
    {   'id': 9542,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Факториал 11',
        'text': 'Вычислите: 16! / 13!',
        'answer': '3360'},
    {   'id': 9543,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Факториал 12',
        'text': 'Вычислите: 17! / (12! × 5!)',
        'answer': '6188'},
    {   'id': 9544,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 25',
        'text': 'Решите: 3x^2 - 22x + 35 = 0',
        'answer': 'x = 5, x = 7/3'},
    {   'id': 9545,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 26',
        'text': 'Решите: 4x^2 - 27x + 35 = 0',
        'answer': 'x = 5, x = 1.75'},
    {   'id': 9546,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 27',
        'text': 'Решите: 5x^2 - 29x + 36 = 0',
        'answer': 'x = 4, x = 1.8'},
    {   'id': 9547,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Параллелограмм 9',
        'text': 'Стороны параллелограмма 16 и 24, угол между ними 150°. Найдите площадь.',
        'answer': '192'},
    {   'id': 9548,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Ромб 9',
        'text': 'Диагонали ромба 28 и 45. Найдите площадь и сторону.',
        'answer': '630, 26.5'},
    {   'id': 9549,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Прямоугольник 9',
        'text': 'Диагональ 50, периметр 140. Найдите стороны.',
        'answer': '48 и 22? нет, 48+22=70 периметр 140'},
    {   'id': 9550,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадрат 9',
        'text': 'Радиус описанной окружности квадрата 9√2. Найдите сторону.',
        'answer': '18'},
    {   'id': 9551,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Трапеция 9',
        'text': 'Основания 18 и 28, диагонали 22 и 32. Найдите площадь.',
        'answer': '368'},
    {   'id': 9552,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Степени 26',
        'text': 'Вычислите: (2^4 × 3^5)^4 / (2^3 × 3^4)',
        'answer': '2^13 × 3^16 = 8192 × 43046721 = 3.52e+11'},
    {   'id': 9553,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Степени 27',
        'text': 'Вычислите: (5^2 × 7^3)^4 / (5^1 × 7^2)',
        'answer': '5^7 × 7^10 = 78125 × 282475249 = 2.21e+13'},
    {   'id': 9554,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 36',
        'text': 'Упростите: √(46 + 2√385)',
        'answer': '√11 + √35'},
    {   'id': 9555,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 37',
        'text': 'Упростите: √(47 - 2√420)',
        'answer': '√20 - √21? нет'},
    {   'id': 9556,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 38',
        'text': 'Упростите: √(48 + 6√15)',
        'answer': '3√5 + 3? нет'},
    {   'id': 9557,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'Делимость 11',
        'text': 'Найдите все трехзначные числа, кратные 47.',
        'answer': '141,188,...,987'},
    {   'id': 9558,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 6,
        'title': 'Делимость 12',
        'text': 'Найдите все трехзначные числа, кратные 53.',
        'answer': '106,159,...,954'},
    {   'id': 9559,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Перестановки 12',
        'text': "Сколько слов из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 9560,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Сочетания 12',
        'text': 'Сколькими способами выбрать 13 из 40?',
        'answer': '1.2e+10'},
    {   'id': 9561,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Размещения 12',
        'text': 'Сколько тринадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '21794572800'},
    {   'id': 9562,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 34',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков больше 10?',
        'answer': '3/36 = 1/12'},
    {   'id': 9563,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 35',
        'text': 'Из урны с 9 белыми и 11 черными шарами вытягивают 4. Какова вероятность, что '
                'ровно 3 белых?',
        'answer': 'C(9,3)×C(11,1)/C(20,4)'},
    {   'id': 9564,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Прогрессии 11',
        'text': 'Найдите сумму первых 30 членов арифметической прогрессии: 11,15,19,...',
        'answer': '2010'},
    {   'id': 9565,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Прогрессии 12',
        'text': 'Найдите сумму первых 10 членов геометрической прогрессии: 6,12,24,...',
        'answer': '6138'},
    {   'id': 9566,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Окружность 28',
        'text': 'Хорда длиной 36 см удалена от центра на 15 см. Найдите радиус.',
        'answer': '√(324+225)=√549'},
    {   'id': 9567,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Окружность 29',
        'text': 'Радиус окружности 30 см, хорда 48 см. Найдите расстояние от центра до хорды.',
        'answer': '18 см'},
    {   'id': 9568,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Касательная 7',
        'text': 'Из точки к окружности проведены две касательные. Расстояние до центра 34, радиус '
                '16. Найдите длину касательной.',
        'answer': '30'},
    {   'id': 9569,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Неравенства 31',
        'text': 'Решите неравенство: 13x - 15 > 11x + 17',
        'answer': 'x > 16'},
    {   'id': 9570,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Неравенства 32',
        'text': 'Решите неравенство: 14x + 11 ≤ 12x - 9',
        'answer': 'x ≤ -10'},
    {   'id': 9571,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Модуль 11',
        'text': 'Решите уравнение: |6x - 5| = |4x + 7|',
        'answer': 'x = 6 или x = -0.2'},
    {   'id': 9572,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Модуль 12',
        'text': 'Решите уравнение: |x - 6| + |x + 5| = 13',
        'answer': 'x = 7 или x = -6'},
    {   'id': 9573,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Синус 12',
        'text': 'Найдите sin 105°',
        'answer': '(√6+√2)/4'},
    {   'id': 9574,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Косинус 12',
        'text': 'Найдите cos 75°',
        'answer': '(√6-√2)/4'},
    {   'id': 9575,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Тангенс 12',
        'text': 'Найдите tg 105°',
        'answer': '-2-√3'},
    {   'id': 9576,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Рациональные уравнения 16',
        'text': 'Решите: 6/(x-6) + 7/(x+7) = 5',
        'answer': 'x = 8 или x = -9'},
    {   'id': 9577,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Рациональные уравнения 17',
        'text': 'Решите: (5x+11)/(x-5) - (4x-9)/(x+6) = 4',
        'answer': 'x = 4 или x = -10'},
    {   'id': 9578,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Рациональные уравнения 18',
        'text': 'Решите: 4/(x+5) + 5/(x+6) = 6/(x+7)',
        'answer': 'x = -3 ± √3'},
    {   'id': 9579,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Векторы 16',
        'text': 'Найдите длину вектора a(13,84)',
        'answer': '85'},
    {   'id': 9580,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Векторы 17',
        'text': 'Найдите скалярное произведение векторов a(8,-7) и b(5,6)',
        'answer': '-2'},
    {   'id': 9581,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Векторы 18',
        'text': 'Найдите угол между векторами a(5,12) и b(15,8)',
        'answer': 'arccos(171/195)'},
    {   'id': 9582,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 36',
        'text': 'Бросают два кубика. Какова вероятность, что сумма очков четная?',
        'answer': '18/36 = 1/2'},
    {   'id': 9583,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 37',
        'text': 'Из колоды в 36 карт вытягивают 5. Какова вероятность, что ровно 2 туза?',
        'answer': 'C(4,2)×C(32,3)/C(36,5)'},
    {   'id': 9584,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 6,
        'title': 'Вероятность 38',
        'text': 'В классе 14 мальчиков и 14 девочек. Выбирают 6 дежурных. Какова вероятность, что '
                'мальчиков и девочек поровну?',
        'answer': 'C(14,3)×C(14,3)/C(28,6)'},
    {   'id': 9585,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратичная функция 27',
        'text': 'При каких значениях k функция y = kx^2 - 14x + 7 не имеет нулей?',
        'answer': 'k > 7'},
    {   'id': 9586,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратичная функция 28',
        'text': 'При каких значениях k функция y = 7x^2 + kx + 28 имеет один нуль?',
        'answer': 'k = ±28'},
    {   'id': 9587,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Площадь 22',
        'text': 'Найдите площадь ромба с диагоналями 32 и 48',
        'answer': '768'},
    {   'id': 9588,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Площадь 23',
        'text': 'Найдите площадь трапеции с основаниями 20 и 36 и высотой 18',
        'answer': '504'},
    {   'id': 9589,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Площадь 24',
        'text': 'Найдите площадь круга, вписанного в прямоугольный треугольник с катетами 9 и 40',
        'answer': '16π'},
    {   'id': 9590,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Площадь 25',
        'text': 'Найдите площадь круга, описанного около прямоугольного треугольника с катетами 20 '
                'и 21',
        'answer': '110.25π'},
    {   'id': 9591,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 28',
        'text': 'Решите: 6x^2 - 31x + 35 = 0',
        'answer': 'x = 3.5, x = 5/3'},
    {   'id': 9592,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 29',
        'text': 'Решите: 7x^2 - 33x + 36 = 0',
        'answer': 'x = 3, x = 12/7'},
    {   'id': 9593,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадратные уравнения 30',
        'text': 'Решите: 8x^2 - 34x + 30 = 0',
        'answer': 'x = 3, x = 1.25'},
    {   'id': 9594,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Параллелограмм 10',
        'text': 'Диагонали параллелограмма 20 и 28, угол между ними 60°. Найдите стороны.',
        'answer': '√(124) и √(364)'},
    {   'id': 9595,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Ромб 10',
        'text': 'Площадь ромба 960, одна диагональ 40. Найдите сторону.',
        'answer': '34'},
    {   'id': 9596,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Прямоугольник 10',
        'text': 'Диагональ 58, периметр 164. Найдите стороны.',
        'answer': '40 и 42? нет, 40+42=82 периметр 164'},
    {   'id': 9597,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Квадрат 10',
        'text': 'Радиус вписанной окружности квадрата 9. Найдите диагональ.',
        'answer': '18√2'},
    {   'id': 9598,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 6,
        'title': 'Трапеция 10',
        'text': 'Основания 17 и 29, диагонали 23 и 33. Найдите площадь.',
        'answer': '414'},
    {   'id': 9599,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Степени 28',
        'text': 'Вычислите: (3^4 × 4^5)^3 / (3^3 × 4^4)',
        'answer': '3^9 × 4^11 = 19683 × 4194304 = 8.26e+10'},
    {   'id': 9600,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 6,
        'title': 'Корни 39',
        'text': 'Упростите: √(51 + 14√8)',
        'answer': '7 + 2√2'},
    {   'id': 9601,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадратичная функция 29',
        'text': 'При каких значениях k функция y = kx^2 - 16x + 8 не имеет нулей?',
        'answer': 'k > 8'},
    {   'id': 9602,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадратичная функция 30',
        'text': 'При каких значениях k функция y = 8x^2 + kx + 32 имеет один нуль?',
        'answer': 'k = ±32'},
    {   'id': 9603,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Неравенства 33',
        'text': 'Решите неравенство: x^2 - 18x + 80 > 0',
        'answer': 'x < 8 или x > 10'},
    {   'id': 9604,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Неравенства 34',
        'text': 'Решите неравенство: -x^2 + 16x - 60 ≥ 0',
        'answer': '6 ≤ x ≤ 10'},
    {   'id': 9605,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Неравенства 35',
        'text': 'Решите неравенство: 6x^2 - 23x + 20 < 0',
        'answer': '1.25 < x < 2.67'},
    {   'id': 9606,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Окружность 30',
        'text': 'Две хорды пересекаются. Отрезки одной 20 и 3, отрезки другой 15 и 4. Верно ли?',
        'answer': '20×3=60, 15×4=60, верно'},
    {   'id': 9607,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Окружность 31',
        'text': 'Из точки вне окружности проведены две секущие. Внешние части 10 и 12, внутренние '
                'части первой 18. Найдите внутреннюю часть второй.',
        'answer': '11'},
    {   'id': 9608,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Окружность 32',
        'text': 'Площадь сектора 144° равна 40π. Найдите радиус.',
        'answer': '10'},
    {   'id': 9609,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 14',
        'text': 'Сумма первых 20 членов 500, a1 = 5. Найдите разность.',
        'answer': '2.1'},
    {   'id': 9610,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Арифметическая прогрессия 15',
        'text': 'a9 = 35, a17 = 59. Найдите a1 и d.',
        'answer': 'a1 = 11, d = 3'},
    {   'id': 9611,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 14',
        'text': 'Сумма первых 6 членов 364, b1 = 4. Найдите q.',
        'answer': 'q = 3 или q = -4'},
    {   'id': 9612,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Геометрическая прогрессия 15',
        'text': 'b5 = 96, b8 = 768. Найдите b1 и q.',
        'answer': 'b1 = 6, q = 2'},
    {   'id': 9613,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Перестановки 13',
        'text': "Сколько слов из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 9614,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Сочетания 13',
        'text': 'Сколькими способами выбрать 14 из 42?',
        'answer': '7.3e+10'},
    {   'id': 9615,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Размещения 13',
        'text': 'Сколько четырнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '21794572800'},
    {   'id': 9616,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Вероятность 39',
        'text': 'Бросают три кубика. Какова вероятность, что сумма очков равна 11?',
        'answer': '27/216 = 1/8'},
    {   'id': 9617,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Вероятность 40',
        'text': 'Из колоды в 52 карты вытягивают 7. Какова вероятность, что все карты одной масти?',
        'answer': '4×C(13,7)/C(52,7)'},
    {   'id': 9618,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Степени 29',
        'text': 'Вычислите: (2^5 × 3^6)^4 / (2^4 × 3^5)',
        'answer': '2^16 × 3^19 = 65536 × 1.16e+9 = 7.6e+13'},
    {   'id': 9619,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Степени 30',
        'text': 'Вычислите: (5^3 × 7^4)^4 / (5^2 × 7^3)',
        'answer': '5^10 × 7^13 = 9.76e+6 × 9.68e+10 = 9.45e+17'},
    {   'id': 9620,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 40',
        'text': 'Упростите: √(53 + 2√450)',
        'answer': '√18 + √25 = 3√2 + 5'},
    {   'id': 9621,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 41',
        'text': 'Упростите: √(54 - 2√480)',
        'answer': '√24 - √20 = 2√6 - 2√5'},
    {   'id': 9622,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 42',
        'text': 'Упростите: √(55 + 6√30)',
        'answer': '√30 + 5? нет'},
    {   'id': 9623,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Теорема Пифагора 13',
        'text': 'Катеты относятся как 32:15, гипотенуза 68. Найдите катеты.',
        'answer': '64 и 30'},
    {   'id': 9624,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Теорема Пифагора 14',
        'text': 'Периметр прямоугольного треугольника 150, гипотенуза 65. Найдите катеты.',
        'answer': '60 и 25'},
    {   'id': 9625,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Синус 13',
        'text': 'В треугольнике стороны 16,17,18. Найдите синус наименьшего угла.',
        'answer': '√(255)/16? нет'},
    {   'id': 9626,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Косинус 13',
        'text': 'В треугольнике стороны 13,14,15. Найдите косинус среднего угла.',
        'answer': '(169+225-196)/(2×13×15) = 198/390 = 33/65'},
    {   'id': 9627,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Тангенс 13',
        'text': 'В прямоугольном треугольнике гипотенуза 41, катет 40. Найдите тангенс угла против '
                'другого катета.',
        'answer': '9/40'},
    {   'id': 9628,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 7,
        'title': 'Простые числа 13',
        'text': 'Сколько простых чисел от 1100 до 1150?',
        'answer': '4'},
    {   'id': 9629,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 7,
        'title': 'Простые числа 14',
        'text': 'Сколько простых чисел от 1200 до 1250?',
        'answer': '4'},
    {   'id': 9630,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 7,
        'title': 'НОД 7',
        'text': 'Найдите НОД(588, 672, 756)',
        'answer': '84'},
    {   'id': 9631,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 7,
        'title': 'НОК 7',
        'text': 'Найдите НОК(28, 30, 32)',
        'answer': '3360'},
    {   'id': 9632,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Системы уравнений 14',
        'text': 'Решите систему: {x^2 - xy + y^2 = 73, x + y = 13}',
        'answer': '(8,5) или (5,8)'},
    {   'id': 9633,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Системы уравнений 15',
        'text': 'Решите систему: {x^2 + y^2 = 100, xy = 48}',
        'answer': '(8,6) или (6,8) или (-8,-6) или (-6,-8)'},
    {   'id': 9634,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Подобие 13',
        'text': 'В треугольнике проведена средняя линия, отсекающая трапецию с площадью 72. '
                'Найдите площадь треугольника.',
        'answer': '96'},
    {   'id': 9635,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Подобие 14',
        'text': 'Периметры подобных треугольников 45 и 72, разность площадей 567. Найдите площади.',
        'answer': '225 и 792'},
    {   'id': 9636,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Средняя линия 7',
        'text': 'Средняя линия треугольника на 7 см меньше основания. Найдите основание.',
        'answer': '14 см'},
    {   'id': 9637,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Средняя линия трапеции 7',
        'text': 'Средняя линия трапеции 24, основания относятся как 2:5. Найдите основания.',
        'answer': '13.71 и 34.29'},
    {   'id': 9638,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Функции 13',
        'text': 'Найдите нули функции y = 13x^2 - 37x + 24',
        'answer': 'x = 2, x = 12/13'},
    {   'id': 9639,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Функции 14',
        'text': 'Найдите нули функции y = 14x^2 - 39x + 25',
        'answer': 'x = 1.25, x = 10/7'},
    {   'id': 9640,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Графики 13',
        'text': 'Найдите точки пересечения графиков y = x^2 - 8x + 15 и y = 3x - 5',
        'answer': '(4,7) и (5,10)'},
    {   'id': 9641,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Графики 14',
        'text': 'Найдите точки пересечения графиков y = x^2 - 6x - 7 и y = x + 1',
        'answer': '(8,9) и (-1,0)'},
    {   'id': 9642,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Факториал 13',
        'text': 'Вычислите: 18! / 15!',
        'answer': '4896'},
    {   'id': 9643,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 7,
        'title': 'Факториал 14',
        'text': 'Вычислите: 19! / (14! × 5!)',
        'answer': '11628'},
    {   'id': 9644,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадратные уравнения 31',
        'text': 'Решите: 3x^2 - 23x + 36 = 0',
        'answer': 'x = 6.?? нет, D=529-432=97'},
    {   'id': 9645,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадратные уравнения 32',
        'text': 'Решите: 4x^2 - 29x + 40 = 0',
        'answer': 'x = 5, x = 2'},
    {   'id': 9646,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадратные уравнения 33',
        'text': 'Решите: 5x^2 - 31x + 42 = 0',
        'answer': 'x = 5, x = 1.68'},
    {   'id': 9647,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Параллелограмм 11',
        'text': 'Стороны параллелограмма 18 и 28, угол между ними 120°. Найдите площадь.',
        'answer': '252√3'},
    {   'id': 9648,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Ромб 11',
        'text': 'Диагонали ромба 30 и 40. Найдите площадь и сторону.',
        'answer': '600, 25'},
    {   'id': 9649,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Прямоугольник 11',
        'text': 'Диагональ 65, периметр 178. Найдите стороны.',
        'answer': '60 и 29? нет, 60+29=89 периметр 178'},
    {   'id': 9650,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Квадрат 11',
        'text': 'Радиус описанной окружности квадрата 10√2. Найдите сторону.',
        'answer': '20'},
    {   'id': 9651,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 7,
        'title': 'Трапеция 11',
        'text': 'Основания 19 и 31, диагонали 24 и 34. Найдите площадь.',
        'answer': '450'},
    {   'id': 9652,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Степени 31',
        'text': 'Вычислите: (2^4 × 3^5)^5 / (2^3 × 3^4)',
        'answer': '2^17 × 3^21 = 131072 × 1.05e+10 = 1.38e+15'},
    {   'id': 9653,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Степени 32',
        'text': 'Вычислите: (5^2 × 7^3)^5 / (5^1 × 7^2)',
        'answer': '5^9 × 7^13 = 1.95e+6 × 9.68e+10 = 1.89e+17'},
    {   'id': 9654,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 43',
        'text': 'Упростите: √(57 + 2√468)',
        'answer': '√13 + √44 = √13 + 2√11'},
    {   'id': 9655,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 44',
        'text': 'Упростите: √(58 - 2√525)',
        'answer': '√25 - √21 = 5 - √21'},
    {   'id': 9656,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 7,
        'title': 'Корни 45',
        'text': 'Упростите: √(59 + 6√38)',
        'answer': '√38 + 3? нет'},
    {   'id': 9701,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 8,
        'title': 'Олимпиадное уравнение 1',
        'text': 'Решите уравнение: x^4 - 5x^3 + 6x^2 - 5x + 1 = 0',
        'answer': 'x = 1, x = 1, x = (3±√5)/2'},
    {   'id': 9702,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 8,
        'title': 'Олимпиадная геометрия 1',
        'text': 'В треугольнике ABC угол A = 20°, AB = AC. Точка D на стороне AB такова, что AD = '
                'BC. Найдите угол BCD.',
        'answer': '10°'},
    {   'id': 9703,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 8,
        'title': 'Олимпиадная теория чисел 1',
        'text': 'Докажите, что n^5 - n делится на 30 при любом целом n.',
        'answer': 'n(n-1)(n+1)(n^2+1)'},
    {   'id': 9704,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 8,
        'title': 'Олимпиадная комбинаторика 1',
        'text': 'Сколько существует способов расставить на шахматной доске 8 ферзей так, чтобы они '
                'не били друг друга?',
        'answer': '92'},
    {   'id': 9801,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 9,
        'title': 'Олимпиадное неравенство 1',
        'text': 'Докажите, что для любых положительных a,b,c: a^3 + b^3 + c^3 + 3abc ≥ a^2b + a^2c '
                '+ b^2a + b^2c + c^2a + c^2b',
        'answer': 'Неравенство Шура'},
    {   'id': 9802,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 9,
        'title': 'Олимпиадная геометрия 2',
        'text': 'В треугольнике ABC угол A = 80°, угол B = 60°. Точка D на стороне AC такова, что '
                'AD = BC. Найдите угол DBC.',
        'answer': '20°'},
    {   'id': 9803,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 9,
        'title': 'Олимпиадная теория чисел 2',
        'text': 'Найдите все простые p, такие что p, p+10, p+20 простые.',
        'answer': 'p = 3'},
    {   'id': 9804,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 9,
        'title': 'Олимпиадная комбинаторика 2',
        'text': 'Сколько существует способов разбить 10 человек на 2 команды по 5 человек?',
        'answer': '126'},
    {   'id': 9901,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 2',
        'text': 'Решите в целых числах: x^2 + y^2 = 2z^2',
        'answer': 'x = y = z'},
    {   'id': 9902,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 3',
        'text': 'В треугольнике ABC угол A = 20°, угол B = 40°. Точка D на стороне AC такова, что '
                'BD = BA. Найдите угол CBD.',
        'answer': '60°'},
    {   'id': 9903,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 3',
        'text': 'Докажите, что n^3 + 2n делится на 3 при любом целом n.',
        'answer': 'n(n-1)(n+1)+3n'},
    {   'id': 9904,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 3',
        'text': 'Сколько существует способов расставить на шахматной доске 8 ладей так, чтобы они '
                'не били друг друга?',
        'answer': '40320'},
    {   'id': 9905,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 3',
        'text': 'Решите в целых числах: x^3 + y^3 = (x+y)^2',
        'answer': '(0,0), (1,2), (2,1)'},
    {   'id': 9906,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 4',
        'text': 'Решите в натуральных числах: 1/x + 1/y = 1/2',
        'answer': '(3,6), (4,4), (6,3)'},
    {   'id': 9907,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 5',
        'text': 'Решите в целых числах: x^2 + y^2 = 2009',
        'answer': '(28,35), (35,28)'},
    {   'id': 9908,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 6',
        'text': 'Решите в целых числах: x^3 + y^3 = 1729',
        'answer': '(12,1), (10,9), (9,10), (1,12)'},
    {   'id': 9909,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 7',
        'text': 'Решите в натуральных числах: x! + y! = z!',
        'answer': '(1,1,2), (1,2,3), (2,1,3)'},
    {   'id': 9910,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 8',
        'text': 'Решите в целых числах: 2^x + 1 = y^2',
        'answer': '(3,3)'},
    {   'id': 9911,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 9',
        'text': 'Решите в целых числах: 3^x + 4^x = 5^x',
        'answer': 'x = 2'},
    {   'id': 9912,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 10',
        'text': 'Решите в натуральных числах: x^y = y^x, x < y',
        'answer': '(2,4)'},
    {   'id': 9913,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 4',
        'text': 'В треугольнике ABC угол A = 30°, угол B = 50°. Точка D на стороне AC такова, что '
                'BD = BA. Найдите угол CBD.',
        'answer': '40°'},
    {   'id': 9914,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 5',
        'text': 'В треугольнике ABC угол A = 40°, угол B = 60°. Точка D на стороне AB такова, что '
                'AD = BC. Найдите угол BCD.',
        'answer': '20°'},
    {   'id': 9915,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 6',
        'text': 'В треугольнике ABC угол A = 50°, угол B = 70°. Точка D на стороне AC такова, что '
                'BD = BC. Найдите угол ABD.',
        'answer': '30°'},
    {   'id': 9916,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 7',
        'text': 'В треугольнике ABC угол A = 60°, угол B = 80°. Точка D на стороне AB такова, что '
                'AD = AC. Найдите угол BCD.',
        'answer': '20°'},
    {   'id': 9917,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 8',
        'text': 'В треугольнике ABC угол A = 70°, угол B = 50°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '30°'},
    {   'id': 9918,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 9',
        'text': 'В треугольнике ABC угол A = 80°, угол B = 40°. Точка D на стороне AC такова, что '
                'AD = BC. Найдите угол ABD.',
        'answer': '30°'},
    {   'id': 9919,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 10',
        'text': 'В треугольнике ABC угол A = 100°, угол B = 30°. Точка D на стороне AB такова, что '
                'AD = BC. Найдите угол ACD.',
        'answer': '25°'},
    {   'id': 9920,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 11',
        'text': 'В равнобедренном треугольнике ABC с основанием AC проведена биссектриса AD. '
                'Найдите угол B, если AD = AC.',
        'answer': '100°'},
    {   'id': 9921,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 12',
        'text': 'В равнобедренном треугольнике ABC с основанием AC проведена биссектриса AD. '
                'Найдите угол B, если AD = AB.',
        'answer': '36°'},
    {   'id': 9922,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 13',
        'text': 'В равнобедренном треугольнике ABC с основанием AC проведена медиана BM. Найдите '
                'угол ABC, если BM = AB.',
        'answer': '90°'},
    {   'id': 9923,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 14',
        'text': 'В треугольнике ABC медиана BM равна стороне BC. Найдите угол ABC, если угол A = '
                '60°.',
        'answer': '90°'},
    {   'id': 9924,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 15',
        'text': 'В треугольнике ABC высота CH равна стороне AC. Найдите угол C, если угол A = 45°.',
        'answer': '90°'},
    {   'id': 9925,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 16',
        'text': 'В треугольнике ABC высота CH равна медиане BM. Найдите угол C, если угол A = 30°.',
        'answer': '60°'},
    {   'id': 9926,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 4',
        'text': 'Докажите, что n^5 - 5n^3 + 4n делится на 120 при любом целом n.',
        'answer': '(n-2)(n-1)n(n+1)(n+2)'},
    {   'id': 9927,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 5',
        'text': 'Докажите, что n^7 - n делится на 7 при любом целом n.',
        'answer': 'Малая теорема Ферма'},
    {   'id': 9928,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 6',
        'text': 'Докажите, что n^13 - n делится на 2,3,5,7,13 при любом целом n.',
        'answer': 'Малая теорема Ферма'},
    {   'id': 9929,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 7',
        'text': 'Найдите все простые p, такие что 2p + 1 тоже простое.',
        'answer': 'p = 2, 3, 5, 11, 23, 29, 41, 53, 83, 89, ...'},
    {   'id': 9930,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 8',
        'text': 'Найдите все простые p, такие что p^2 + 2 тоже простое.',
        'answer': 'p = 3'},
    {   'id': 9931,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 9',
        'text': 'Докажите, что существует бесконечно много простых чисел вида 4k+3.',
        'answer': 'От противного'},
    {   'id': 9932,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 10',
        'text': 'Докажите, что существует бесконечно много простых чисел вида 6k+5.',
        'answer': 'От противного'},
    {   'id': 9933,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 4',
        'text': 'Сколько существует способов разбить 8 человек на 4 пары?',
        'answer': '105'},
    {   'id': 9934,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 5',
        'text': 'Сколько существует способов разбить 12 человек на 6 пар?',
        'answer': '10395'},
    {   'id': 9935,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 6',
        'text': 'Сколько существует способов выбрать 3 книги из 10 так, чтобы среди них не было '
                'двух соседних?',
        'answer': '56'},
    {   'id': 9936,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 7',
        'text': 'Сколько существует способов выбрать 4 книги из 12 так, чтобы среди них не было '
                'двух соседних?',
        'answer': '126'},
    {   'id': 9937,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 8',
        'text': 'Сколько существует шестизначных чисел, у которых сумма цифр равна 3?',
        'answer': '56'},
    {   'id': 9938,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 9',
        'text': 'Сколько существует семизначных чисел, у которых сумма цифр равна 3?',
        'answer': '84'},
    {   'id': 9939,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 10',
        'text': 'Сколькими способами можно расставить 5 мальчиков и 5 девочек в ряд так, чтобы '
                'мальчики и девочки чередовались?',
        'answer': '28800'},
    {   'id': 9940,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 11',
        'text': 'Сколькими способами можно расставить 7 мальчиков и 3 девочек в ряд так, чтобы '
                'никакие две девочки не стояли рядом?',
        'answer': '8! × C(8,3) × 3! = 1693440'},
    {   'id': 9941,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 2',
        'text': 'Докажите, что для любых положительных a,b,c: a^2 + b^2 + c^2 ≥ ab + bc + ca',
        'answer': '2(a^2+b^2+c^2) ≥ 2(ab+bc+ca)'},
    {   'id': 9942,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 3',
        'text': 'Докажите, что для любых положительных a,b,c: a^3 + b^3 + c^3 ≥ 3abc',
        'answer': 'Неравенство Коши'},
    {   'id': 9943,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 4',
        'text': 'Докажите, что для любых положительных a,b: (a+b)/2 ≥ √(ab)',
        'answer': 'Неравенство Коши'},
    {   'id': 9944,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 5',
        'text': 'Докажите, что для любых положительных a,b,c: (a+b)(b+c)(c+a) ≥ 8abc',
        'answer': 'a+b ≥ 2√ab'},
    {   'id': 9945,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 6',
        'text': 'Докажите, что для любых положительных a,b,c: a/b + b/c + c/a ≥ 3',
        'answer': 'По неравенству Коши'},
    {   'id': 9946,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 7',
        'text': 'Докажите, что для любых положительных a,b,c: (a+b+c)(1/a + 1/b + 1/c) ≥ 9',
        'answer': 'По неравенству Коши'},
    {   'id': 9947,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 8',
        'text': 'Докажите, что для любых положительных a,b,c: a^2/b + b^2/c + c^2/a ≥ a + b + c',
        'answer': 'По неравенству Коши'},
    {   'id': 9948,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 9',
        'text': 'Докажите, что для любых положительных a,b: a^3 + b^3 ≥ a^2b + ab^2',
        'answer': '(a-b)^2(a+b) ≥ 0'},
    {   'id': 9949,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное неравенство 10',
        'text': 'Докажите, что для любых положительных a,b,c: a^4 + b^4 + c^4 ≥ abc(a+b+c)',
        'answer': 'a^4+b^4 ≥ a^2b^2'},
    {   'id': 9950,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 17',
        'text': 'В треугольнике ABC угол A = 20°, угол B = 80°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '30°'},
    {   'id': 9951,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 18',
        'text': 'В треугольнике ABC угол A = 30°, угол B = 70°. Точка D на стороне AC такова, что '
                'CD = CB. Найдите угол ABD.',
        'answer': '40°'},
    {   'id': 9952,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 19',
        'text': 'В треугольнике ABC угол A = 40°, угол B = 80°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '20°'},
    {   'id': 9953,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 20',
        'text': 'В треугольнике ABC угол A = 50°, угол B = 60°. Точка D на стороне AC такова, что '
                'AD = AB. Найдите угол DBC.',
        'answer': '10°'},
    {   'id': 9954,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 21',
        'text': 'В треугольнике ABC угол A = 60°, угол B = 40°. Точка D на стороне BC такова, что '
                'CD = CA. Найдите угол ABD.',
        'answer': '20°'},
    {   'id': 9955,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 22',
        'text': 'В треугольнике ABC угол A = 70°, угол B = 30°. Точка D на стороне AC такова, что '
                'AD = AB. Найдите угол DBC.',
        'answer': '25°'},
    {   'id': 9956,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 23',
        'text': 'В треугольнике ABC угол A = 80°, угол B = 20°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '30°'},
    {   'id': 9957,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 24',
        'text': 'В треугольнике ABC угол A = 90°, угол B = 30°. Точка D на стороне AC такова, что '
                'AD = BC. Найдите угол DBC.',
        'answer': '15°'},
    {   'id': 9958,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 25',
        'text': 'В равнобедренном треугольнике ABC с основанием AC проведена биссектриса AD. '
                'Найдите угол B, если AD = 2BC.',
        'answer': '36°? нет, сложно'},
    {   'id': 9959,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 11',
        'text': 'Найдите все целые n, при которых n^2 + n + 41 является простым.',
        'answer': 'n = 0,...,39'},
    {   'id': 9960,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 12',
        'text': 'Найдите все целые n, при которых n^4 + 4 является простым.',
        'answer': 'n = ±1'},
    {   'id': 9961,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 13',
        'text': 'Докажите, что n^2 + n + 1 не является точным квадратом ни при каком n>0.',
        'answer': 'Между n^2 и (n+1)^2'},
    {   'id': 9962,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 14',
        'text': 'Докажите, что n^3 + 3n^2 + 2n делится на 6 при любом целом n.',
        'answer': 'n(n+1)(n+2)'},
    {   'id': 9963,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 15',
        'text': 'Докажите, что n^5 - n делится на 5 при любом целом n.',
        'answer': 'Малая теорема Ферма'},
    {   'id': 9964,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 12',
        'text': 'Сколько существует способов расставить на шахматной доске 8 слонов так, чтобы они '
                'не били друг друга?',
        'answer': '128'},
    {   'id': 9965,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 13',
        'text': 'Сколько существует способов расставить на шахматной доске 8 коней так, чтобы они '
                'не били друг друга?',
        'answer': 'Зависит от расположения'},
    {   'id': 9966,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 14',
        'text': 'Сколько существует способов разбить 7 человек на группы 2,2,3?',
        'answer': '105'},
    {   'id': 9967,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 15',
        'text': 'Сколько существует способов разбить 9 человек на группы 3,3,3?',
        'answer': '280'},
    {   'id': 9968,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 16',
        'text': 'Сколько существует пятизначных чисел, у которых все цифры четные и различные?',
        'answer': '120'},
    {   'id': 9969,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 17',
        'text': 'Сколько существует шестизначных чисел, у которых все цифры нечетные и различные?',
        'answer': '720'},
    {   'id': 9970,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 11',
        'text': 'Решите в целых числах: x^2 + 2y^2 = 2z^2',
        'answer': '(2,1,2), (2,-1,2)'},
    {   'id': 9971,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 12',
        'text': 'Решите в целых числах: x^2 + y^2 + z^2 = 2xyz',
        'answer': '(0,0,0), (1,1,1), (-1,-1,-1)'},
    {   'id': 9972,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 13',
        'text': 'Решите в натуральных числах: x^2 + y^2 = 1997',
        'answer': 'Нет решений'},
    {   'id': 9973,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 14',
        'text': 'Решите в целых числах: x^3 + y^3 = z^3 + 1',
        'answer': '(9,10,12), (10,9,12)'},
    {   'id': 9974,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 15',
        'text': 'Решите в целых числах: x^4 + y^4 = z^2',
        'answer': 'Нет нетривиальных решений'},
    {   'id': 9975,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 26',
        'text': 'В треугольнике ABC угол A = 20°, угол B = 60°. Точка D на стороне AB такова, что '
                'AD = BC. Найдите угол ACD.',
        'answer': '30°'},
    {   'id': 9976,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 27',
        'text': 'В треугольнике ABC угол A = 30°, угол B = 50°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '25°'},
    {   'id': 9977,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 28',
        'text': 'В треугольнике ABC угол A = 40°, угол B = 70°. Точка D на стороне AC такова, что '
                'AD = AB. Найдите угол DBC.',
        'answer': '15°'},
    {   'id': 9978,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 29',
        'text': 'В треугольнике ABC угол A = 50°, угол B = 80°. Точка D на стороне BC такова, что '
                'CD = CA. Найдите угол ABD.',
        'answer': '15°'},
    {   'id': 9979,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 30',
        'text': 'В треугольнике ABC угол A = 60°, угол B = 70°. Точка D на стороне AB такова, что '
                'AD = AC. Найдите угол BCD.',
        'answer': '20°'},
    {   'id': 9980,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 16',
        'text': 'Найдите все простые p, такие что p, p+6, p+12, p+18 простые.',
        'answer': 'p = 5'},
    {   'id': 9981,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 17',
        'text': 'Найдите все простые p, такие что p, p+2, p+4 простые.',
        'answer': 'p = 3'},
    {   'id': 9982,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 18',
        'text': 'Докажите, что 2^p - 1 составное для составного p.',
        'answer': 'Разложение'},
    {   'id': 9983,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 19',
        'text': 'Докажите, что 2^105 + 3^105 составное.',
        'answer': 'Делится на 5'},
    {   'id': 9984,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 18',
        'text': 'Сколько существует способов выбрать 5 книг из 15 так, чтобы среди них не было '
                'трех подряд?',
        'answer': '618'},
    {   'id': 9985,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 19',
        'text': 'Сколько существует восьмизначных чисел, у которых сумма цифр равна 4?',
        'answer': '330'},
    {   'id': 9986,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 20',
        'text': 'Сколько существует восьмизначных чисел, у которых сумма цифр равна 5?',
        'answer': '792'},
    {   'id': 9987,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 16',
        'text': 'Решите в натуральных числах: 2^x + 3^y = 5^z',
        'answer': '(1,1,1)'},
    {   'id': 9988,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 17',
        'text': 'Решите в натуральных числах: x! + y! = 10^z',
        'answer': '(4,4,2)'},
    {   'id': 9989,
        'subject': 'algebra',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадное уравнение 18',
        'text': 'Решите в целых числах: x^2 - 2y^2 = 1',
        'answer': '(3,2), (17,12), ...'},
    {   'id': 9990,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 31',
        'text': 'В треугольнике ABC угол A = 10°, угол B = 70°. Точка D на стороне BC такова, что '
                'BD = BA. Найдите угол CAD.',
        'answer': '35°'},
    {   'id': 9991,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 32',
        'text': 'В треугольнике ABC угол A = 20°, угол B = 90°. Точка D на стороне AC такова, что '
                'CD = CB. Найдите угол ABD.',
        'answer': '35°'},
    {   'id': 9992,
        'subject': 'geometry',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная геометрия 33',
        'text': 'В треугольнике ABC угол A = 30°, угол B = 100°. Точка D на стороне AB такова, что '
                'AD = BC. Найдите угол BCD.',
        'answer': '20°'},
    {   'id': 9993,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 20',
        'text': 'Найдите все целые n, при которых n^2 + 3n + 4 является точным квадратом.',
        'answer': 'n = 0, -3'},
    {   'id': 9994,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 21',
        'text': 'Найдите все целые n, при которых n^2 + 5n + 6 является точным квадратом.',
        'answer': 'n = 1, -6'},
    {   'id': 9995,
        'subject': 'number_theory',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная теория чисел 22',
        'text': 'Докажите, что n^2 + n + 1 не делится на 5 ни при каком целом n.',
        'answer': 'Проверка остатков'},
    {   'id': 9996,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 21',
        'text': 'Сколько существует способов выбрать 6 книг из 20 так, чтобы среди них не было '
                'двух подряд?',
        'answer': 'C(15,6) = 5005'},
    {   'id': 9997,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 22',
        'text': 'Сколько существует способов разбить 10 человек на 5 пар?',
        'answer': '945'},
    {   'id': 9998,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Олимпиадная комбинаторика 23',
        'text': 'Сколько существует девятизначных чисел, у которых все цифры различны?',
        'answer': '3265920'},
    {   'id': 9999,
        'subject': 'combinatorics',
        'grade': 9,
        'difficulty': 10,
        'title': 'Суперзадача 9 класс',
        'text': 'Сколько существует способов расставить на шахматной доске 8 ладей так, чтобы они '
                'не били друг друга?',
        'answer': '40320'}]
