PROBLEMS_DB = [   {   'id': 5924,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Делимость 34',
        'text': 'Найдите все трехзначные числа, которые делятся на 113 и оканчиваются на 9.',
        'answer': '113×3=339, 113×13=1469 (нет)'},
    {   'id': 5925,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Делимость 35',
        'text': 'Найдите все трехзначные числа, которые делятся на 127 и оканчиваются на 1.',
        'answer': '127'},
    {   'id': 5926,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Размещения 42',
        'text': 'Сколько четырехзначных чисел можно составить из цифр 0-9, если цифры могут '
                'повторяться?',
        'answer': '9000'},
    {   'id': 5927,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Размещения 43',
        'text': 'Сколько пятизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '59049'},
    {   'id': 5928,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Размещения 44',
        'text': 'Сколько шестизначных чисел можно составить из цифр 0-7, если цифры могут '
                'повторяться?',
        'answer': '1075648'},
    {   'id': 5929,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Проценты 35',
        'text': 'Цена товара сначала повысилась на 45%, затем повысилась еще на 55%. На сколько '
                'процентов повысилась цена?',
        'answer': '124.75%'},
    {   'id': 5930,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Проценты 36',
        'text': 'Цена товара сначала снизилась на 40%, затем снизилась еще на 50%. На сколько '
                'процентов снизилась цена?',
        'answer': '70%'},
    {   'id': 5931,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Проценты 37',
        'text': 'Цена товара сначала повысилась на 70%, затем снизилась на 70%. На сколько '
                'процентов изменилась цена?',
        'answer': 'Снизилась на 49%'},
    {   'id': 5932,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Объем 66',
        'text': 'Куб с ребром 30 см покрасили и распилили на кубики с ребром 2 см. Сколько кубиков '
                'имеют ровно две окрашенные грани?',
        'answer': '48'},
    {   'id': 5933,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Объем 67',
        'text': 'Куб с ребром 36 см покрасили и распилили на кубики с ребром 3 см. Сколько кубиков '
                'имеют ровно одну окрашенную грань?',
        'answer': '384'},
    {   'id': 5934,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Объем 68',
        'text': 'Куб с ребром 42 см покрасили и распилили на кубики с ребром 6 см. Сколько кубиков '
                'не имеют окрашенных граней?',
        'answer': '64'},
    {   'id': 5935,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Простые числа 51',
        'text': 'Сколько простых чисел в промежутке от 1300 до 1350?',
        'answer': '4 (1301,1303,1307,1319)'},
    {   'id': 5936,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Простые числа 52',
        'text': 'Сколько простых чисел в промежутке от 1350 до 1400?',
        'answer': '3 (1361,1367,1373)'},
    {   'id': 5937,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Простые числа 53',
        'text': 'Сколько простых чисел в промежутке от 1400 до 1450?',
        'answer': '4 (1409,1423,1427,1429)'},
    {   'id': 5938,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Дроби 62',
        'text': 'Вычислите: (8/9 + 7/8 - 5/6) × 72/41',
        'answer': '1'},
    {   'id': 5939,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Дроби 63',
        'text': 'Вычислите: (9/10 - 8/9 + 7/8) × 360/97',
        'answer': '1'},
    {   'id': 5940,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 9,
        'title': 'Дроби 64',
        'text': 'Вычислите: (10/11 - 9/10 + 8/9) × 990/101',
        'answer': '1'},
    {   'id': 5941,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Перестановки 28',
        'text': "Сколько слов можно составить из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 5942,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Перестановки 29',
        'text': "Сколько слов можно составить из букв слова 'ПАРАЛЛЕЛЕПИПЕД'?",
        'answer': '1089728640'},
    {   'id': 5943,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 9,
        'title': 'Перестановки 30',
        'text': "Сколько слов можно составить из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 5944,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Углы 28',
        'text': 'Один угол треугольника на 80° больше второго и на 60° больше третьего. Найдите '
                'углы.',
        'answer': '120°, 40°, 20°'},
    {   'id': 5945,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Углы 29',
        'text': 'Второй угол треугольника в 8 раз больше первого и на 70° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 160°, -? нет решения'},
    {   'id': 5946,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 9,
        'title': 'Углы 30',
        'text': 'Третий угол треугольника в 7 раз больше первого и на 60° больше второго. Найдите '
                'углы.',
        'answer': '20°, 80°, 80°'},
    {   'id': 5947,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Остатки 55',
        'text': 'Найдите остаток от деления 34^100 на 10',
        'answer': '6'},
    {   'id': 5948,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Остатки 56',
        'text': 'Найдите остаток от деления 35^100 на 10',
        'answer': '5'},
    {   'id': 5949,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Остатки 57',
        'text': 'Найдите остаток от деления 36^100 на 10',
        'answer': '6'},
    {   'id': 5950,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 9,
        'title': 'Остатки 58',
        'text': 'Найдите остаток от деления 37^100 на 10',
        'answer': '1'},
    {   'id': 5951,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делители 39',
        'text': 'Сколько делителей у числа 10080?',
        'answer': '72'},
    {   'id': 5952,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делители 40',
        'text': 'Сколько делителей у числа 12600?',
        'answer': '72'},
    {   'id': 5953,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делители 41',
        'text': 'Сколько делителей у числа 15120?',
        'answer': '80'},
    {   'id': 5954,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делители 42',
        'text': 'Сколько делителей у числа 18480?',
        'answer': '80'},
    {   'id': 5955,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Задача 73',
        'text': 'Сумма трех чисел 900. Первое число в 7 раз больше второго, а третье на 140 больше '
                'первого. Найдите числа.',
        'answer': '280, 40, 580'},
    {   'id': 5956,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Задача 74',
        'text': 'Сумма трех чисел 1200. Второе число в 8 раз меньше первого, а третье на 200 '
                'больше второго. Найдите числа.',
        'answer': '600, 75, 525'},
    {   'id': 5957,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Задача 75',
        'text': 'Сумма трех чисел 1500. Первое число на 100 больше второго, а третье в 7 раз '
                'больше первого. Найдите числа.',
        'answer': '200, 100, 1200'},
    {   'id': 5958,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Периметр 51',
        'text': 'Периметр прямоугольника 500 см. Длина на 80 см больше ширины. Найдите площадь.',
        'answer': '14700 см²'},
    {   'id': 5959,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Периметр 52',
        'text': 'Периметр прямоугольника 520 см. Длина в 9 раз больше ширины. Найдите площадь.',
        'answer': '6084 см²'},
    {   'id': 5960,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Периметр 53',
        'text': 'Периметр прямоугольника 540 см. Ширина в 8 раз меньше длины. Найдите площадь.',
        'answer': '9600 см²'},
    {   'id': 5961,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Сочетания 67',
        'text': 'Сколькими способами можно выбрать 8 книг из 40?',
        'answer': '76904685'},
    {   'id': 5962,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Сочетания 68',
        'text': 'Сколькими способами можно выбрать 9 книг из 42?',
        'answer': '445891810'},
    {   'id': 5963,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Сочетания 69',
        'text': 'Сколькими способами можно выбрать 10 книг из 45?',
        'answer': '3190187286'},
    {   'id': 5964,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'НОД 35',
        'text': 'Найдите НОД(8736, 9282, 9828)',
        'answer': '546'},
    {   'id': 5965,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'НОД 36',
        'text': 'Найдите НОД(9282, 9828, 10374)',
        'answer': '546'},
    {   'id': 5966,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'НОК 35',
        'text': 'Найдите НОК(120, 126, 132)',
        'answer': '27720'},
    {   'id': 5967,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'НОК 36',
        'text': 'Найдите НОК(132, 144, 156)',
        'answer': '41184'},
    {   'id': 5968,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Уравнение 71',
        'text': '10(8x - 9) - 8(9x - 10) = 7(10x - 11) - 6(9x - 10)',
        'answer': 'x = 3'},
    {   'id': 5969,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Уравнение 72',
        'text': '11(9x - 10) - 9(10x - 11) = 8(11x - 12) - 7(10x - 11)',
        'answer': 'x = 2'},
    {   'id': 5970,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Уравнение 73',
        'text': '12(10x - 11) - 10(11x - 12) = 9(12x - 13) - 8(11x - 12)',
        'answer': 'x = 1'},
    {   'id': 5971,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Площадь 71',
        'text': 'Площадь прямоугольника 1500 см². Длина в 5 раз больше ширины. Найдите периметр.',
        'answer': '240 см'},
    {   'id': 5972,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Площадь 72',
        'text': 'Площадь прямоугольника 1600 см². Ширина в 2 раза меньше длины. Найдите периметр.',
        'answer': '160 см'},
    {   'id': 5973,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Площадь 73',
        'text': 'Площадь прямоугольника 1800 см². Длина на 60 см больше ширины. Найдите периметр.',
        'answer': '180 см'},
    {   'id': 5974,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делимость 36',
        'text': 'Найдите все трехзначные числа, которые делятся на 131 и оканчиваются на 7.',
        'answer': '131×7=917'},
    {   'id': 5975,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Делимость 37',
        'text': 'Найдите все трехзначные числа, которые делятся на 137 и оканчиваются на 9.',
        'answer': '137×7=959'},
    {   'id': 5976,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Размещения 45',
        'text': 'Сколько четырехзначных чисел можно составить из цифр 0-9, если цифры не '
                'повторяются?',
        'answer': '4536'},
    {   'id': 5977,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Размещения 46',
        'text': 'Сколько пятизначных чисел можно составить из цифр 1-9, если цифры не повторяются?',
        'answer': '15120'},
    {   'id': 5978,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Размещения 47',
        'text': 'Сколько шестизначных чисел можно составить из цифр 0-7, если цифры не '
                'повторяются?',
        'answer': '11760'},
    {   'id': 5979,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Проценты 38',
        'text': 'Цена товара сначала повысилась на 50%, затем повысилась еще на 60%. На сколько '
                'процентов повысилась цена?',
        'answer': '140%'},
    {   'id': 5980,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Проценты 39',
        'text': 'Цена товара сначала снизилась на 45%, затем снизилась еще на 55%. На сколько '
                'процентов снизилась цена?',
        'answer': '75.25%'},
    {   'id': 5981,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Проценты 40',
        'text': 'Цена товара сначала повысилась на 80%, затем снизилась на 80%. На сколько '
                'процентов изменилась цена?',
        'answer': 'Снизилась на 64%'},
    {   'id': 5982,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Объем 69',
        'text': 'Куб с ребром 36 см покрасили и распилили на кубики с ребром 2 см. Сколько кубиков '
                'имеют ровно две окрашенные грани?',
        'answer': '48'},
    {   'id': 5983,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Объем 70',
        'text': 'Куб с ребром 40 см покрасили и распилили на кубики с ребром 4 см. Сколько кубиков '
                'имеют ровно одну окрашенную грань?',
        'answer': '384'},
    {   'id': 5984,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Объем 71',
        'text': 'Куб с ребром 48 см покрасили и распилили на кубики с ребром 6 см. Сколько кубиков '
                'не имеют окрашенных граней?',
        'answer': '343'},
    {   'id': 5985,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Простые числа 54',
        'text': 'Сколько простых чисел в промежутке от 1500 до 1550?',
        'answer': '4 (1511,1523,1531,1543)'},
    {   'id': 5986,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Простые числа 55',
        'text': 'Сколько простых чисел в промежутке от 1550 до 1600?',
        'answer': '4 (1553,1559,1567,1571)'},
    {   'id': 5987,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Простые числа 56',
        'text': 'Сколько простых чисел в промежутке от 1600 до 1650?',
        'answer': '5 (1601,1607,1609,1613,1619)'},
    {   'id': 5988,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Дроби 65',
        'text': 'Вычислите: (9/10 + 8/9 - 7/8) × 720/241',
        'answer': '1'},
    {   'id': 5989,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Дроби 66',
        'text': 'Вычислите: (10/11 - 9/10 + 8/9) × 990/101',
        'answer': '1'},
    {   'id': 5990,
        'subject': 'algebra',
        'grade': 5,
        'difficulty': 10,
        'title': 'Дроби 67',
        'text': 'Вычислите: (11/12 - 10/11 + 9/10) × 1320/131',
        'answer': '1'},
    {   'id': 5991,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Перестановки 31',
        'text': "Сколько слов можно составить из букв слова 'МАТЕМАТИЧЕСКИЙ'?",
        'answer': '10897286400'},
    {   'id': 5992,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Перестановки 32',
        'text': "Сколько слов можно составить из букв слова 'ПАРАЛЛЕЛЕПИПЕД'?",
        'answer': '1089728640'},
    {   'id': 5993,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Перестановки 33',
        'text': "Сколько слов можно составить из букв слова 'КОНСТАНТИНОПОЛЬ'?",
        'answer': '18162144000'},
    {   'id': 5994,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Углы 31',
        'text': 'Один угол треугольника на 90° больше второго и на 70° больше третьего. Найдите '
                'углы.',
        'answer': '130°, 40°, 10°'},
    {   'id': 5995,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Углы 32',
        'text': 'Второй угол треугольника в 9 раз больше первого и на 80° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 180°, -20° нет решения'},
    {   'id': 5996,
        'subject': 'geometry',
        'grade': 5,
        'difficulty': 10,
        'title': 'Углы 33',
        'text': 'Третий угол треугольника в 8 раз больше первого и на 70° больше второго. Найдите '
                'углы.',
        'answer': '20°, 90°, 70°'},
    {   'id': 5997,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Остатки 59',
        'text': 'Найдите остаток от деления 38^100 на 10',
        'answer': '6'},
    {   'id': 5998,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Остатки 60',
        'text': 'Найдите остаток от деления 39^100 на 10',
        'answer': '1'},
    {   'id': 5999,
        'subject': 'number_theory',
        'grade': 5,
        'difficulty': 10,
        'title': 'Остатки 61',
        'text': 'Найдите остаток от деления 40^100 на 10',
        'answer': '0'},
    {   'id': 6000,
        'subject': 'combinatorics',
        'grade': 5,
        'difficulty': 10,
        'title': 'Суперзадача',
        'text': 'Сколько существует пятизначных чисел, у которых все цифры нечетные и различные?',
        'answer': '5! = 120'},
    {   'id': 6001,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Пропорция 1',
        'text': 'Решите пропорцию: 3/4 = 9/x',
        'answer': 'x = 12'},
    {   'id': 6002,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Пропорция 2',
        'text': 'Решите пропорцию: 5/8 = x/24',
        'answer': 'x = 15'},
    {   'id': 6003,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Масштаб карты',
        'text': 'На карте масштаба 1:50000 расстояние между городами 8 см. Каково расстояние на '
                'местности (в км)?',
        'answer': '4 км'},
    {   'id': 6004,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Масштаб 2',
        'text': 'Расстояние на местности 15 км изображено отрезком 3 см. Каков масштаб карты?',
        'answer': '1:500000'},
    {   'id': 6005,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 2',
        'text': 'Какие из чисел 123, 246, 357, 468 делятся на 2?',
        'answer': '246, 468'},
    {   'id': 6006,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 3',
        'text': 'Какие из чисел 111, 222, 333, 444 делятся на 3?',
        'answer': 'Все'},
    {   'id': 6007,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 5',
        'text': 'Какие из чисел 105, 210, 315, 420 оканчиваются на 0 или 5?',
        'answer': 'Все'},
    {   'id': 6008,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 9',
        'text': 'Делится ли число 123456789 на 9?',
        'answer': 'Да (сумма цифр 45)'},
    {   'id': 6009,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 10',
        'text': 'Какие из чисел 100, 205, 310, 415 делятся на 10?',
        'answer': '100, 310'},
    {   'id': 6010,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 1',
        'text': 'Найдите 30% от 250',
        'answer': '75'},
    {   'id': 6011,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 2',
        'text': 'Сколько процентов составляет 40 от 200?',
        'answer': '20%'},
    {   'id': 6012,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 3',
        'text': 'Цена товара 500 руб. Снизилась на 15%. Сколько стал стоить?',
        'answer': '425 руб.'},
    {   'id': 6013,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 4',
        'text': 'Товар стоил 400 руб. Повысился на 20%. Новая цена?',
        'answer': '480 руб.'},
    {   'id': 6014,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь прямоугольника',
        'text': 'Длина прямоугольника 15 см, ширина 8 см. Найдите площадь.',
        'answer': '120 см²'},
    {   'id': 6015,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Периметр прямоугольника',
        'text': 'Стороны прямоугольника 7 см и 12 см. Найдите периметр.',
        'answer': '38 см'},
    {   'id': 6016,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь квадрата',
        'text': 'Сторона квадрата 9 см. Найдите площадь.',
        'answer': '81 см²'},
    {   'id': 6017,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Объем прямоугольного параллелепипеда',
        'text': 'Измерения 3 см, 4 см, 5 см. Найдите объем.',
        'answer': '60 см³'},
    {   'id': 6018,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Объем куба',
        'text': 'Ребро куба 6 см. Найдите объем.',
        'answer': '216 см³'},
    {   'id': 6019,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Перестановки 1',
        'text': 'Сколькими способами можно расставить 4 разные книги на полке?',
        'answer': '24'},
    {   'id': 6020,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Перестановки 2',
        'text': "Сколько слов можно составить из букв слова 'КУБ' (буквы не повторяются)?",
        'answer': '6'},
    {   'id': 6021,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Сочетания',
        'text': 'Сколькими способами можно выбрать 2 дежурных из 5 человек?',
        'answer': '10'},
    {   'id': 6022,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Размещения',
        'text': 'Сколько двузначных чисел можно составить из цифр 1,2,3,4, если цифры не '
                'повторяются?',
        'answer': '12'},
    {   'id': 6023,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 1',
        'text': 'Сократите дробь 12/18',
        'answer': '2/3'},
    {   'id': 6024,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 2',
        'text': 'Сравните дроби 5/8 и 3/5',
        'answer': '5/8 > 3/5'},
    {   'id': 6025,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 3',
        'text': 'Вычислите: 2/3 + 1/6',
        'answer': '5/6'},
    {   'id': 6026,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 4',
        'text': 'Вычислите: 7/8 - 3/4',
        'answer': '1/8'},
    {   'id': 6027,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 5',
        'text': 'Вычислите: 4/9 × 3/8',
        'answer': '1/6'},
    {   'id': 6028,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 6',
        'text': 'Вычислите: 2/5 : 3/10',
        'answer': '4/3'},
    {   'id': 6029,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Десятичные дроби',
        'text': 'Запишите 7/20 в виде десятичной дроби.',
        'answer': '0,35'},
    {   'id': 6030,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Десятичные дроби 2',
        'text': 'Запишите 3/8 в виде десятичной дроби.',
        'answer': '0,375'},
    {   'id': 6031,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Округление',
        'text': 'Округлите число 3,14159 до сотых.',
        'answer': '3,14'},
    {   'id': 6032,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Среднее арифметическое',
        'text': 'Найдите среднее арифметическое чисел 12, 15, 18, 21.',
        'answer': '16,5'},
    {   'id': 6033,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Углы треугольника',
        'text': 'В треугольнике углы относятся как 2:3:4. Найдите больший угол.',
        'answer': '80°'},
    {   'id': 6034,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Смежные углы',
        'text': 'Один из смежных углов на 30° больше другого. Найдите эти углы.',
        'answer': '75° и 105°'},
    {   'id': 6035,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Вертикальные углы',
        'text': 'Один из вертикальных углов равен 50°. Найдите остальные углы.',
        'answer': '50°, 130°, 130°'},
    {   'id': 6036,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОД',
        'text': 'Найдите НОД(54, 72)',
        'answer': '18'},
    {   'id': 6037,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОК',
        'text': 'Найдите НОК(15, 20)',
        'answer': '60'},
    {   'id': 6038,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Простые числа',
        'text': 'Разложите на простые множители число 210.',
        'answer': '2·3·5·7'},
    {   'id': 6039,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Делители',
        'text': 'Сколько делителей у числа 48?',
        'answer': '10'},
    {   'id': 6040,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Правило суммы',
        'text': 'В классе 10 мальчиков и 12 девочек. Сколькими способами можно выбрать одного '
                'дежурного?',
        'answer': '22'},
    {   'id': 6041,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Правило произведения',
        'text': 'Сколько пар (мальчик, девочка) можно составить?',
        'answer': '120'},
    {   'id': 6042,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Уравнение 1',
        'text': 'Решите уравнение: 5x - 8 = 22',
        'answer': 'x = 6'},
    {   'id': 6043,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Уравнение 2',
        'text': 'Решите уравнение: 3(x + 4) = 27',
        'answer': 'x = 5'},
    {   'id': 6044,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Уравнение 3',
        'text': 'Решите уравнение: 2x/3 = 8',
        'answer': 'x = 12'},
    {   'id': 6045,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Задача на части',
        'text': 'Для варенья берут 3 части ягод и 2 части сахара. Сколько сахара нужно на 6 кг '
                'ягод?',
        'answer': '4 кг'},
    {   'id': 6046,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Задача на движение',
        'text': 'Пешеход прошёл 10 км за 2 часа. С какой скоростью он шёл?',
        'answer': '5 км/ч'},
    {   'id': 6047,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Задача на работу',
        'text': 'Мастер делает 15 деталей в час. Сколько деталей он сделает за 8 часов?',
        'answer': '120'},
    {   'id': 6048,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь треугольника',
        'text': 'Основание треугольника 12 см, высота 5 см. Найдите площадь.',
        'answer': '30 см²'},
    {   'id': 6049,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Длина окружности',
        'text': 'Радиус окружности 7 см. Найдите длину окружности (π≈3,14).',
        'answer': '43,96 см'},
    {   'id': 6050,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь круга',
        'text': 'Радиус круга 5 см. Найдите площадь круга (π≈3,14).',
        'answer': '78,5 см²'},
    {   'id': 6051,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Пропорция 3',
        'text': 'Решите пропорцию: 7/8 = 21/x',
        'answer': 'x = 24'},
    {   'id': 6052,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Масштаб 3',
        'text': 'На карте масштаба 1:200000 расстояние 5 см. Сколько км на местности?',
        'answer': '10 км'},
    {   'id': 6053,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Признак делимости на 4',
        'text': 'Какие из чисел 124, 234, 344, 454 делятся на 4?',
        'answer': '124, 344'},
    {   'id': 6054,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 5',
        'text': 'Найдите 45% от 400',
        'answer': '180'},
    {   'id': 6055,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 6',
        'text': 'Сколько процентов составляет 75 от 300?',
        'answer': '25%'},
    {   'id': 6056,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь прямоугольника 2',
        'text': 'Длина 18 см, ширина 9 см. Найдите площадь.',
        'answer': '162 см²'},
    {   'id': 6057,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Периметр прямоугольника 2',
        'text': 'Стороны 11 см и 14 см. Найдите периметр.',
        'answer': '50 см'},
    {   'id': 6058,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь квадрата 2',
        'text': 'Сторона квадрата 12 см. Найдите площадь.',
        'answer': '144 см²'},
    {   'id': 6059,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Перестановки 3',
        'text': 'Сколькими способами можно расставить 5 разных книг?',
        'answer': '120'},
    {   'id': 6060,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Сочетания 2',
        'text': 'Сколькими способами выбрать 3 дежурных из 8?',
        'answer': '56'},
    {   'id': 6061,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 7',
        'text': '2/5 + 3/10 = ?',
        'answer': '7/10'},
    {   'id': 6062,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 8',
        'text': '5/6 - 2/3 = ?',
        'answer': '1/6'},
    {   'id': 6063,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 9',
        'text': '3/4 × 8/9 = ?',
        'answer': '2/3'},
    {   'id': 6064,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 10',
        'text': '4/7 : 8/21 = ?',
        'answer': '3/2'},
    {   'id': 6065,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОД 2',
        'text': 'Найдите НОД(36, 60)',
        'answer': '12'},
    {   'id': 6066,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОК 2',
        'text': 'Найдите НОК(12, 16)',
        'answer': '48'},
    {   'id': 6067,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Углы 2',
        'text': 'Один угол треугольника 35°, другой 75°. Найдите третий.',
        'answer': '70°'},
    {   'id': 6068,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Смежные углы 2',
        'text': 'Один из смежных углов 110°. Найдите другой.',
        'answer': '70°'},
    {   'id': 6069,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Вертикальные углы 2',
        'text': 'Сумма двух вертикальных углов 100°. Найдите эти углы.',
        'answer': '50° и 50°'},
    {   'id': 6070,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Уравнение 4',
        'text': '4x - 7 = 2x + 9',
        'answer': 'x = 8'},
    {   'id': 6071,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Уравнение 5',
        'text': '6x + 5 = 4x + 13',
        'answer': 'x = 4'},
    {   'id': 6072,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Задача 2',
        'text': 'В двух корзинах 120 яблок. В первой в 2 раза больше. Сколько в каждой?',
        'answer': '80 и 40'},
    {   'id': 6073,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Задача 3',
        'text': 'Сумма двух чисел 75, разность 25. Найдите числа.',
        'answer': '50 и 25'},
    {   'id': 6074,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Объем 2',
        'text': 'Объем куба 64 см³. Найдите ребро.',
        'answer': '4 см'},
    {   'id': 6075,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Объем 3',
        'text': 'Измерения параллелепипеда 4, 5, 6 см. Найдите объем.',
        'answer': '120 см³'},
    {   'id': 6076,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Простые числа 2',
        'text': 'Сколько простых чисел от 1 до 30?',
        'answer': '10 (2,3,5,7,11,13,17,19,23,29)'},
    {   'id': 6077,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Разложение',
        'text': 'Разложите 180 на простые множители.',
        'answer': '2²×3²×5'},
    {   'id': 6078,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Количество чисел',
        'text': 'Сколько двузначных чисел можно составить из цифр 5,6,7,8,9?',
        'answer': '25'},
    {   'id': 6079,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Количество чисел 2',
        'text': 'Сколько трехзначных чисел можно составить из цифр 1,2,3,4?',
        'answer': '64'},
    {   'id': 6080,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Среднее арифметическое 2',
        'text': 'Среднее пяти чисел 20. Четыре числа 15, 20, 25, 18. Найдите пятое.',
        'answer': '22'},
    {   'id': 6081,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Окружность',
        'text': 'Диаметр окружности 24 см. Найдите радиус.',
        'answer': '12 см'},
    {   'id': 6082,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Круг',
        'text': 'Радиус круга 8 см. Найдите площадь (π≈3,14).',
        'answer': '200,96 см²'},
    {   'id': 6083,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 7',
        'text': 'Число 120 увеличили на 15%. Какое число получили?',
        'answer': '138'},
    {   'id': 6084,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Проценты 8',
        'text': 'Число 200 уменьшили на 25%. Какое число получили?',
        'answer': '150'},
    {   'id': 6085,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Четные числа',
        'text': 'Сколько четных трехзначных чисел?',
        'answer': '450'},
    {   'id': 6086,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'Нечетные числа',
        'text': 'Сколько нечетных трехзначных чисел?',
        'answer': '450'},
    {   'id': 6087,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Масштаб 4',
        'text': 'Длина детали 20 см, на чертеже 4 см. Каков масштаб?',
        'answer': '1:5'},
    {   'id': 6088,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Пропорция 4',
        'text': 'Решите пропорцию: x/8 = 15/12',
        'answer': 'x = 10'},
    {   'id': 6089,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Периметр 3',
        'text': 'Периметр прямоугольника 48 см, ширина 8 см. Найдите длину.',
        'answer': '16 см'},
    {   'id': 6090,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Площадь 3',
        'text': 'Площадь прямоугольника 84 см², длина 12 см. Найдите ширину.',
        'answer': '7 см'},
    {   'id': 6091,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Перестановки 4',
        'text': "Сколько слов можно составить из букв слова 'МАМА'?",
        'answer': '6'},
    {   'id': 6092,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 1,
        'title': 'Сочетания 3',
        'text': 'Сколькими способами выбрать 4 из 10?',
        'answer': '210'},
    {   'id': 6093,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 11',
        'text': '3/7 + 2/5 = ?',
        'answer': '29/35'},
    {   'id': 6094,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 12',
        'text': '5/8 - 1/3 = ?',
        'answer': '7/24'},
    {   'id': 6095,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 13',
        'text': '4/5 × 10/11 = ?',
        'answer': '8/11'},
    {   'id': 6096,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 1,
        'title': 'Дроби 14',
        'text': '6/7 : 3/14 = ?',
        'answer': '4'},
    {   'id': 6097,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОД 3',
        'text': 'Найдите НОД(42, 56)',
        'answer': '14'},
    {   'id': 6098,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 1,
        'title': 'НОК 3',
        'text': 'Найдите НОК(18, 24)',
        'answer': '72'},
    {   'id': 6099,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Углы 3',
        'text': 'Углы треугольника относятся как 3:4:5. Найдите углы.',
        'answer': '45°, 60°, 75°'},
    {   'id': 6100,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 1,
        'title': 'Объем 4',
        'text': 'Объем параллелепипеда 240 см³, длина 8 см, ширина 5 см. Найдите высоту.',
        'answer': '6 см'},
    {   'id': 6101,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Пропорция 5',
        'text': 'Решите пропорцию: (x+2)/5 = 3/4',
        'answer': 'x = 1,75'},
    {   'id': 6102,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Масштаб 5',
        'text': 'Длина детали на чертеже 12 см, масштаб 1:5. Какова реальная длина?',
        'answer': '60 см'},
    {   'id': 6103,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 1',
        'text': 'Вместо звёздочки поставьте цифру так, чтобы число 5*7 делилось на 3.',
        'answer': '0,3,6,9'},
    {   'id': 6104,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 9',
        'text': 'Число увеличили на 20%, получили 240. Найдите исходное.',
        'answer': '200'},
    {   'id': 6105,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр сложной фигуры',
        'text': 'Прямоугольник со сторонами 8 и 6 разрезали на два прямоугольника. Найдите сумму '
                'периметров получившихся прямоугольников.',
        'answer': 'Если разрез параллелен стороне 8, то 28+16=44; если параллелен 6, то 28+12=40'},
    {   'id': 6106,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Комбинаторика 1',
        'text': 'Сколько трёхзначных чисел можно составить из цифр 0,1,2,3, если цифры не '
                'повторяются?',
        'answer': '18'},
    {   'id': 6107,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 15',
        'text': 'Найдите значение выражения: 2 1/3 + 1 3/4',
        'answer': '4 1/12'},
    {   'id': 6108,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 6',
        'text': '4(2x - 3) = 20',
        'answer': 'x = 4'},
    {   'id': 6109,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 4',
        'text': 'Один из углов, образованных при пересечении двух прямых, равен 35°. Найдите '
                'остальные.',
        'answer': '35°, 145°, 145°'},
    {   'id': 6110,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД и НОК 1',
        'text': 'НОД(a,b)=6, НОК(a,b)=72. Найдите a и b.',
        'answer': '6 и 72 или 12 и 36 или 18 и 24'},
    {   'id': 6111,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 4',
        'text': 'В первой корзине в 3 раза больше яблок, чем во второй. Если из первой переложить '
                '12 яблок во вторую, станет поровну. Сколько яблок в каждой?',
        'answer': '36 и 12'},
    {   'id': 6112,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 5',
        'text': 'Сумма двух чисел 48, а разность 12. Найдите числа.',
        'answer': '30 и 18'},
    {   'id': 6113,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Площадь 4',
        'text': 'Площадь прямоугольника 96 см². Длина 12 см. Найдите периметр.',
        'answer': '40 см'},
    {   'id': 6114,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр 4',
        'text': 'Периметр прямоугольника 56 см. Длина на 6 см больше ширины. Найдите площадь.',
        'answer': '187 см²'},
    {   'id': 6115,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Простые числа 3',
        'text': 'Сколько простых чисел от 30 до 50?',
        'answer': '5 (31,37,41,43,47)'},
    {   'id': 6116,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Разложение 2',
        'text': 'Разложите 420 на простые множители.',
        'answer': '2²×3×5×7'},
    {   'id': 6117,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Сочетания 4',
        'text': 'Сколькими способами выбрать 3 человек из 10?',
        'answer': '120'},
    {   'id': 6118,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Размещения 2',
        'text': 'Сколько трехзначных чисел из цифр 1,2,3,4,5 без повторений?',
        'answer': '60'},
    {   'id': 6119,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 16',
        'text': '5/6 - (1/3 + 1/4) = ?',
        'answer': '1/4'},
    {   'id': 6120,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 10',
        'text': 'Число уменьшили на 15%, получили 170. Найдите исходное.',
        'answer': '200'},
    {   'id': 6121,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 5',
        'text': 'Один угол треугольника в 2 раза больше второго и на 20° меньше третьего. Найдите '
                'углы.',
        'answer': '40°, 20°, 120°'},
    {   'id': 6122,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Объем 5',
        'text': 'Куб с ребром 8 см распилили на кубики с ребром 2 см. Сколько кубиков получили?',
        'answer': '64'},
    {   'id': 6123,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 2',
        'text': 'Найдите все числа вида 3x5y, которые делятся на 9.',
        'answer': '3150, 3456, 3753, 3159?'},
    {   'id': 6124,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД 4',
        'text': 'Найдите НОД(84, 126)',
        'answer': '42'},
    {   'id': 6125,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОК 4',
        'text': 'Найдите НОК(24, 30)',
        'answer': '120'},
    {   'id': 6126,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 7',
        'text': '5(3x - 2) - 4(2x - 5) = 23',
        'answer': 'x = 3'},
    {   'id': 6127,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 8',
        'text': '3(4x - 1) - 2(5x - 3) = 10',
        'answer': 'x = 2,5'},
    {   'id': 6128,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 6',
        'text': 'В двух бидонах 80 л молока. Если из первого перелить 10 л во второй, то в первом '
                'станет в 3 раза больше. Сколько в каждом?',
        'answer': '65 и 15'},
    {   'id': 6129,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Площадь 5',
        'text': 'Площадь квадрата равна площади прямоугольника со сторонами 8 см и 18 см. Найдите '
                'сторону квадрата.',
        'answer': '12 см'},
    {   'id': 6130,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр 5',
        'text': 'Периметр квадрата равен периметру прямоугольника со сторонами 10 см и 14 см. '
                'Найдите сторону квадрата.',
        'answer': '12 см'},
    {   'id': 6131,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Перестановки 5',
        'text': "Сколько слов можно составить из букв слова 'ПАПА'?",
        'answer': '6'},
    {   'id': 6132,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Сочетания 5',
        'text': 'Сколькими способами выбрать 5 из 12?',
        'answer': '792'},
    {   'id': 6133,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 17',
        'text': '3/4 - 2/3 + 1/2 = ?',
        'answer': '7/12'},
    {   'id': 6134,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 18',
        'text': '2/5 × 3/4 × 5/6 = ?',
        'answer': '1/4'},
    {   'id': 6135,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Простые числа 4',
        'text': 'Сколько простых чисел от 50 до 70?',
        'answer': '3 (53,59,61)'},
    {   'id': 6136,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Разложение 3',
        'text': 'Разложите 504 на простые множители.',
        'answer': '2³×3²×7'},
    {   'id': 6137,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 6',
        'text': 'Углы треугольника относятся как 2:5:8. Найдите углы.',
        'answer': '24°, 60°, 96°'},
    {   'id': 6138,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Объем 6',
        'text': 'Из кубиков с ребром 1 см сложили прямоугольный параллелепипед 5×4×3. Сколько '
                'кубиков использовали?',
        'answer': '60'},
    {   'id': 6139,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 11',
        'text': 'Сколько процентов составляет 36 от 240?',
        'answer': '15%'},
    {   'id': 6140,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 12',
        'text': 'Цена товара повысилась с 250 до 300 руб. На сколько процентов повысилась?',
        'answer': '20%'},
    {   'id': 6141,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 3',
        'text': 'Найдите наименьшее число, которое делится на 2,3,4,5,6 с остатком 1.',
        'answer': '61'},
    {   'id': 6142,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД 5',
        'text': 'Найдите НОД(105, 165)',
        'answer': '15'},
    {   'id': 6143,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОК 5',
        'text': 'Найдите НОК(15, 18, 20)',
        'answer': '180'},
    {   'id': 6144,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 9',
        'text': '7(2x - 3) - 3(4x - 5) = 11',
        'answer': 'x = 4'},
    {   'id': 6145,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 10',
        'text': '2(5x - 4) - 3(3x - 2) = 5',
        'answer': 'x = 3'},
    {   'id': 6146,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 7',
        'text': 'Трое рабочих заработали 900 руб. Первый работал 5 дней, второй 4 дня, третий 3 '
                'дня. Сколько получал каждый в день, если второй за 2 дня заработал столько же, '
                'сколько первый за 1 день?',
        'answer': '60, 30, 40'},
    {   'id': 6147,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Площадь 6',
        'text': 'Прямоугольник разрезали на 4 квадрата. Периметр одного квадрата 24 см. Найдите '
                'площадь прямоугольника.',
        'answer': '144 см²'},
    {   'id': 6148,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр 6',
        'text': 'Прямоугольник разрезали на 6 квадратов. Периметр прямоугольника 70 см. Найдите '
                'сторону квадрата.',
        'answer': '5 см'},
    {   'id': 6149,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Сочетания 6',
        'text': 'Сколькими способами выбрать 2 из 7 и 3 из 8?',
        'answer': '980'},
    {   'id': 6150,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Размещения 3',
        'text': 'Сколько четырехзначных чисел из цифр 0,1,2,3,4 без повторений?',
        'answer': '96'},
    {   'id': 6151,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 19',
        'text': '4/5 - (1/2 + 1/4) = ?',
        'answer': '1/20'},
    {   'id': 6152,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 20',
        'text': '3/7 × 14/15 × 5/6 = ?',
        'answer': '1/3'},
    {   'id': 6153,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Простые числа 5',
        'text': 'Сколько простых чисел от 70 до 90?',
        'answer': '3 (71,73,79,83,89?) 5'},
    {   'id': 6154,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Разложение 4',
        'text': 'Разложите 840 на простые множители.',
        'answer': '2³×3×5×7'}]
