PROBLEMS_DB = [   {   'id': 6155,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 7',
        'text': 'Один угол треугольника 50°, другой на 20° больше. Найдите третий.',
        'answer': '60°'},
    {   'id': 6156,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Объем 7',
        'text': 'Объем куба 216 см³. Найдите ребро.',
        'answer': '6 см'},
    {   'id': 6157,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 13',
        'text': 'Число увеличили на 25%, получили 300. Найдите исходное.',
        'answer': '240'},
    {   'id': 6158,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 14',
        'text': 'Число уменьшили на 30%, получили 210. Найдите исходное.',
        'answer': '300'},
    {   'id': 6159,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 4',
        'text': 'Найдите все двузначные числа, которые делятся на 17.',
        'answer': '17,34,51,68,85'},
    {   'id': 6160,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД 6',
        'text': 'Найдите НОД(126, 189)',
        'answer': '63'},
    {   'id': 6161,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОК 6',
        'text': 'Найдите НОК(12, 18, 24)',
        'answer': '72'},
    {   'id': 6162,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 11',
        'text': '6(2x - 3) - 5(3x - 4) = 17',
        'answer': 'x = -3'},
    {   'id': 6163,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 12',
        'text': '4(3x - 2) - 3(4x - 5) = 7',
        'answer': 'x = 0'},
    {   'id': 6164,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 8',
        'text': 'В трех корзинах 120 яблок. Во второй в 2 раза больше, чем в первой, а в третьей '
                'на 20 больше, чем во второй. Сколько в каждой?',
        'answer': '20, 40, 60'},
    {   'id': 6165,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Площадь 7',
        'text': 'Площадь прямоугольника 108 см². Длина в 3 раза больше ширины. Найдите периметр.',
        'answer': '48 см'},
    {   'id': 6166,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр 7',
        'text': 'Периметр прямоугольника 60 см. Длина на 6 см больше ширины. Найдите площадь.',
        'answer': '216 см²'},
    {   'id': 6167,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Перестановки 6',
        'text': "Сколько слов можно составить из букв слова 'МАТЕМАТИКА'?",
        'answer': '151200'},
    {   'id': 6168,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Сочетания 7',
        'text': 'Сколькими способами выбрать 4 из 15?',
        'answer': '1365'},
    {   'id': 6169,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 21',
        'text': '1/2 + 1/3 + 1/6 = ?',
        'answer': '1'},
    {   'id': 6170,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 22',
        'text': '5/8 - (1/4 + 1/8) = ?',
        'answer': '1/4'},
    {   'id': 6171,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Простые числа 6',
        'text': 'Сколько простых чисел от 90 до 100?',
        'answer': '1 (97)'},
    {   'id': 6172,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Разложение 5',
        'text': 'Разложите 990 на простые множители.',
        'answer': '2×3²×5×11'},
    {   'id': 6173,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 8',
        'text': 'В треугольнике углы относятся как 1:2:6. Найдите углы.',
        'answer': '20°, 40°, 120°'},
    {   'id': 6174,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Объем 8',
        'text': 'Аквариум 60×40×50 см заполнен водой наполовину. Сколько литров воды?',
        'answer': '60 л'},
    {   'id': 6175,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 15',
        'text': 'Сколько процентов составляет 63 от 420?',
        'answer': '15%'},
    {   'id': 6176,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 16',
        'text': 'Цена снизилась с 400 до 320 руб. На сколько процентов снизилась?',
        'answer': '20%'},
    {   'id': 6177,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 5',
        'text': 'Найдите все двузначные числа, кратные 23.',
        'answer': '23,46,69,92'},
    {   'id': 6178,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД 7',
        'text': 'Найдите НОД(144, 216)',
        'answer': '72'},
    {   'id': 6179,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОК 7',
        'text': 'Найдите НОК(16, 24, 36)',
        'answer': '144'},
    {   'id': 6180,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 13',
        'text': '8(3x - 4) - 6(4x - 5) = 31',
        'answer': 'x = -2,5'},
    {   'id': 6181,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 14',
        'text': '5(2x - 3) - 3(3x - 4) = 8',
        'answer': 'x = 5'},
    {   'id': 6182,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 9',
        'text': 'Сумма трех чисел 180. Первое в 2 раза больше второго, третье на 20 меньше '
                'первого. Найдите числа.',
        'answer': '80, 40, 60'},
    {   'id': 6183,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Площадь 8',
        'text': 'Площадь прямоугольника 150 см². Ширина в 2 раза меньше длины. Найдите периметр.',
        'answer': '50 см'},
    {   'id': 6184,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Периметр 8',
        'text': 'Периметр прямоугольника 72 см. Длина в 2 раза больше ширины. Найдите площадь.',
        'answer': '288 см²'},
    {   'id': 6185,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Сочетания 8',
        'text': 'Сколькими способами выбрать 3 из 9 и 2 из 7?',
        'answer': '1260'},
    {   'id': 6186,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 2,
        'title': 'Размещения 4',
        'text': 'Сколько трехзначных чисел из цифр 0-5 без повторений?',
        'answer': '100'},
    {   'id': 6187,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 23',
        'text': '2/3 + 3/5 - 4/15 = ?',
        'answer': '1'},
    {   'id': 6188,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Дроби 24',
        'text': '5/6 - 2/3 + 1/4 = ?',
        'answer': '5/12'},
    {   'id': 6189,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Простые числа 7',
        'text': 'Сколько простых чисел от 100 до 120?',
        'answer': '5 (101,103,107,109,113)'},
    {   'id': 6190,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Разложение 6',
        'text': 'Разложите 1260 на простые множители.',
        'answer': '2²×3²×5×7'},
    {   'id': 6191,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Углы 9',
        'text': 'Один угол треугольника 40°, другой в 2 раза больше. Найдите третий.',
        'answer': '60°'},
    {   'id': 6192,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 2,
        'title': 'Объем 9',
        'text': 'Бассейн 25×10×2 м заполнен водой на 3/4. Сколько кубометров воды?',
        'answer': '375 м³'},
    {   'id': 6193,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 17',
        'text': 'Число 80 увеличили на 25%, затем результат увеличили на 20%. Какое число '
                'получили?',
        'answer': '120'},
    {   'id': 6194,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Проценты 18',
        'text': 'Число 200 уменьшили на 30%, затем результат уменьшили на 20%. Какое число '
                'получили?',
        'answer': '112'},
    {   'id': 6195,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'Делимость 6',
        'text': 'Найдите все трехзначные числа, кратные 37.',
        'answer': '111,148,185,222,259,296,333,370,407,444,481,518,555,592,629,666,703,740,777,814,851,888,925,962,999'},
    {   'id': 6196,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОД 8',
        'text': 'Найдите НОД(168, 252)',
        'answer': '84'},
    {   'id': 6197,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 2,
        'title': 'НОК 8',
        'text': 'Найдите НОК(18, 27, 36)',
        'answer': '108'},
    {   'id': 6198,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 15',
        'text': '9(4x - 5) - 7(5x - 6) = 19',
        'answer': 'x = 4'},
    {   'id': 6199,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Уравнение 16',
        'text': '6(5x - 4) - 4(6x - 5) = 22',
        'answer': 'x = -2'},
    {   'id': 6200,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 2,
        'title': 'Задача 10',
        'text': 'В первом бидоне в 3 раза больше молока, чем во втором. Когда из первого перелили '
                '8 л во второй, в бидонах стало поровну. Сколько было в каждом?',
        'answer': '24 и 8'},
    {   'id': 6301,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 10',
        'text': 'Решите пропорцию: (6x-5)/4 = (8x+3)/5',
        'answer': 'x = -18.5'},
    {   'id': 6302,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Масштаб 7',
        'text': 'На карте масштаба 1:200000 расстояние 12 см. Сколько км на местности?',
        'answer': '24 км'},
    {   'id': 6303,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 10',
        'text': 'Найдите все числа вида 3x7y, которые делятся на 18.',
        'answer': '3276, 3570, 3870?'},
    {   'id': 6304,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 23',
        'text': 'Число увеличили на 25%, получили 300. Найдите исходное.',
        'answer': '240'},
    {   'id': 6305,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 13',
        'text': 'Площадь прямоугольника 320 см². Длина 20 см. Найдите периметр.',
        'answer': '72 см'},
    {   'id': 6306,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 13',
        'text': 'Периметр прямоугольника 108 см. Длина в 3 раза больше ширины. Найдите площадь.',
        'answer': '729 см²'},
    {   'id': 6307,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Комбинаторика 3',
        'text': 'Сколько четырехзначных чисел можно составить из цифр 1,2,3,4,5,6, если цифры не '
                'повторяются?',
        'answer': '360'},
    {   'id': 6308,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 23',
        'text': '5/6 - 2/3 + 3/4 = ?',
        'answer': '11/12'},
    {   'id': 6309,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 21',
        'text': '7(4x - 5) - 5(5x - 6) = 3(6x - 7) - 2(5x - 6)',
        'answer': 'x = 4'},
    {   'id': 6310,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 13',
        'text': 'Найдите НОД(336, 420, 504)',
        'answer': '84'},
    {   'id': 6311,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 13',
        'text': 'Найдите НОК(24, 30, 42)',
        'answer': '840'},
    {   'id': 6312,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 14',
        'text': 'В трех корзинах 180 яблок. Во второй в 2 раза больше, чем в первой, а в третьей '
                'на 30 больше, чем во второй. Сколько в каждой?',
        'answer': '30, 60, 90'},
    {   'id': 6313,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 13',
        'text': 'Один угол треугольника 40°, другой в 3 раза больше. Найдите третий.',
        'answer': '20°'},
    {   'id': 6314,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 13',
        'text': 'Аквариум 50×30×40 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '45 л'},
    {   'id': 6315,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Сочетания 11',
        'text': 'Сколькими способами выбрать 3 из 10 и 4 из 12?',
        'answer': '59400'},
    {   'id': 6316,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 24',
        'text': 'Сколько процентов составляет 135 от 450?',
        'answer': '30%'},
    {   'id': 6317,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 11',
        'text': 'Решите пропорцию: (7x+3)/5 = (9x-2)/6',
        'answer': 'x = 28/3'},
    {   'id': 6318,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 11',
        'text': 'Найдите все трехзначные числа, кратные 31.',
        'answer': '124,155,186,217,248,279,310,341,372,403,434,465,496,527,558,589,620,651,682,713,744,775,806,837,868,899,930,961,992'},
    {   'id': 6319,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 14',
        'text': 'Площадь прямоугольника 360 см². Ширина 15 см. Найдите периметр.',
        'answer': '78 см'},
    {   'id': 6320,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 14',
        'text': 'Периметр прямоугольника 120 см. Длина на 10 см больше ширины. Найдите площадь.',
        'answer': '875 см²'},
    {   'id': 6321,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 24',
        'text': '7/8 - 5/12 + 1/3 = ?',
        'answer': '13/24'},
    {   'id': 6322,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 22',
        'text': '8(5x - 6) - 6(6x - 7) = 4(7x - 8) - 3(6x - 7)',
        'answer': 'x = 3'},
    {   'id': 6323,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 14',
        'text': 'Найдите НОД(396, 462, 528)',
        'answer': '66'},
    {   'id': 6324,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 14',
        'text': 'Найдите НОК(32, 40, 48)',
        'answer': '480'},
    {   'id': 6325,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 15',
        'text': 'В первом бидоне в 4 раза больше молока, чем во втором. Если из первого перелить '
                '12 л во второй, то в первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '48 и 12'},
    {   'id': 6326,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 14',
        'text': 'Второй угол треугольника в 5 раз больше первого и на 20° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 100°, 60°'},
    {   'id': 6327,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 14',
        'text': 'Бассейн 20×10×2.5 м заполнен водой наполовину. Сколько кубометров воды?',
        'answer': '250 м³'},
    {   'id': 6328,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Размещения 4',
        'text': 'Сколько четырехзначных чисел из цифр 0-5 без повторений?',
        'answer': '300'},
    {   'id': 6329,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 25',
        'text': 'Число 240 уменьшили на 45%. Какое число получили?',
        'answer': '132'},
    {   'id': 6330,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 12',
        'text': 'Решите пропорцию: (8x-7)/3 = (10x+1)/4',
        'answer': 'x = -15.5'},
    {   'id': 6331,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 12',
        'text': 'Найдите все трехзначные числа, кратные 37.',
        'answer': '111,148,185,222,259,296,333,370,407,444,481,518,555,592,629,666,703,740,777,814,851,888,925,962,999'},
    {   'id': 6332,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 15',
        'text': 'Площадь прямоугольника 400 см². Длина 25 см. Найдите периметр.',
        'answer': '82 см'},
    {   'id': 6333,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 15',
        'text': 'Периметр прямоугольника 132 см. Длина в 2 раза больше ширины. Найдите площадь.',
        'answer': '968 см²'},
    {   'id': 6334,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 25',
        'text': '8/9 - 3/4 + 5/6 = ?',
        'answer': '29/36'},
    {   'id': 6335,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 23',
        'text': '9(6x - 7) - 7(7x - 8) = 5(8x - 9) - 4(7x - 8)',
        'answer': 'x = 2'},
    {   'id': 6336,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 15',
        'text': 'Найдите НОД(468, 546, 624)',
        'answer': '78'},
    {   'id': 6337,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 15',
        'text': 'Найдите НОК(36, 45, 48)',
        'answer': '720'},
    {   'id': 6338,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 16',
        'text': 'Сумма трех чисел 240. Первое число в 3 раза больше второго, а третье на 40 больше '
                'первого. Найдите числа.',
        'answer': '120, 40, 80'},
    {   'id': 6339,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 15',
        'text': 'Третий угол треугольника в 6 раз больше первого и на 30° больше второго. Найдите '
                'углы.',
        'answer': '30°, 120°, 30°'},
    {   'id': 6340,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 15',
        'text': 'Куб с ребром 12 см распилили на кубики с ребром 2 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6341,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Сочетания 12',
        'text': 'Сколькими способами выбрать 4 из 15 и 3 из 10?',
        'answer': '163800'},
    {   'id': 6342,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 26',
        'text': 'Сколько процентов составляет 126 от 420?',
        'answer': '30%'},
    {   'id': 6343,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 13',
        'text': 'Решите пропорцию: (9x-8)/5 = (11x+2)/6',
        'answer': 'x = -58'},
    {   'id': 6344,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 13',
        'text': 'Найдите все трехзначные числа, кратные 41.',
        'answer': '123,164,205,246,287,328,369,410,451,492,533,574,615,656,697,738,779,820,861,902,943,984'},
    {   'id': 6345,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 16',
        'text': 'Площадь прямоугольника 480 см². Ширина в 3 раза меньше длины. Найдите периметр.',
        'answer': '88 см'},
    {   'id': 6346,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 16',
        'text': 'Периметр прямоугольника 160 см. Длина в 5 раз больше ширины. Найдите площадь.',
        'answer': '1333.33 см²'},
    {   'id': 6347,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 26',
        'text': '9/10 - 5/8 + 3/5 = ?',
        'answer': '43/40'},
    {   'id': 6348,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 24',
        'text': '10(7x - 8) - 8(8x - 9) = 6(9x - 10) - 5(8x - 9)',
        'answer': 'x = 1'},
    {   'id': 6349,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 16',
        'text': 'Найдите НОД(540, 630, 720)',
        'answer': '90'},
    {   'id': 6350,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 16',
        'text': 'Найдите НОК(40, 48, 56)',
        'answer': '1680'},
    {   'id': 6351,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 17',
        'text': 'В двух бидонах 100 л молока. Если из первого перелить 5 л во второй, то в первом '
                'станет в 3 раза больше. Сколько в каждом?',
        'answer': '80 и 20'},
    {   'id': 6352,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 16',
        'text': 'Первый угол треугольника в 4 раза больше второго и на 30° больше третьего. '
                'Найдите углы.',
        'answer': '120°, 30°, 30°'},
    {   'id': 6353,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 16',
        'text': 'Комната 8×6×3 м. Сколько кубометров воздуха в комнате?',
        'answer': '144 м³'},
    {   'id': 6354,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Размещения 5',
        'text': 'Сколько пятизначных чисел из цифр 0-7 без повторений?',
        'answer': '5880'},
    {   'id': 6355,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 27',
        'text': 'Число 300 увеличили на 40%, потом результат увеличили на 30%. Какое число '
                'получили?',
        'answer': '546'},
    {   'id': 6356,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 14',
        'text': 'Решите пропорцию: (10x-9)/4 = (12x+5)/5',
        'answer': 'x = -65/2'},
    {   'id': 6357,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 14',
        'text': 'Найдите все трехзначные числа, кратные 43.',
        'answer': '129,172,215,258,301,344,387,430,473,516,559,602,645,688,731,774,817,860,903,946,989'},
    {   'id': 6358,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 17',
        'text': 'Площадь прямоугольника 540 см². Длина 30 см. Найдите периметр.',
        'answer': '96 см'},
    {   'id': 6359,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 17',
        'text': 'Периметр прямоугольника 144 см. Ширина в 5 раз меньше длины. Найдите площадь.',
        'answer': '1440 см²'},
    {   'id': 6360,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 27',
        'text': '10/11 - 7/9 + 4/5 = ?',
        'answer': '223/495'},
    {   'id': 6361,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 25',
        'text': '11(8x - 9) - 9(9x - 10) = 7(10x - 11) - 6(9x - 10)',
        'answer': 'x = 0'},
    {   'id': 6362,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 17',
        'text': 'Найдите НОД(630, 735, 840)',
        'answer': '105'},
    {   'id': 6363,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 17',
        'text': 'Найдите НОК(45, 54, 63)',
        'answer': '1890'},
    {   'id': 6364,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 18',
        'text': 'Сумма трех чисел 300. Первое число в 5 раз больше второго, а третье на 60 больше '
                'первого. Найдите числа.',
        'answer': '200, 40, 60'},
    {   'id': 6365,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 17',
        'text': 'Второй угол треугольника в 7 раз больше первого и на 50° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 140°, 20°'},
    {   'id': 6366,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 17',
        'text': 'Куб с ребром 15 см распилили на кубики с ребром 3 см. Сколько кубиков получили?',
        'answer': '125'},
    {   'id': 6367,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Сочетания 13',
        'text': 'Сколькими способами выбрать 5 из 20 и 4 из 15?',
        'answer': '1395360'},
    {   'id': 6368,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 28',
        'text': 'Сколько процентов составляет 168 от 480?',
        'answer': '35%'},
    {   'id': 6369,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 15',
        'text': 'Решите пропорцию: (11x-10)/3 = (13x+7)/4',
        'answer': 'x = -61'},
    {   'id': 6370,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 15',
        'text': 'Найдите все трехзначные числа, кратные 47.',
        'answer': '141,188,235,282,329,376,423,470,517,564,611,658,705,752,799,846,893,940,987'},
    {   'id': 6371,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 18',
        'text': 'Площадь прямоугольника 600 см². Ширина 20 см. Найдите периметр.',
        'answer': '100 см'},
    {   'id': 6372,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 18',
        'text': 'Периметр прямоугольника 168 см. Длина в 2 раза больше ширины. Найдите площадь.',
        'answer': '1568 см²'},
    {   'id': 6373,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 28',
        'text': '11/12 - 8/9 + 5/6 = ?',
        'answer': '25/36'},
    {   'id': 6374,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 26',
        'text': '12(9x - 10) - 10(10x - 11) = 8(11x - 12) - 7(10x - 11)',
        'answer': 'x = -1'},
    {   'id': 6375,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 18',
        'text': 'Найдите НОД(756, 882, 1008)',
        'answer': '126'},
    {   'id': 6376,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 18',
        'text': 'Найдите НОК(50, 60, 72)',
        'answer': '1800'},
    {   'id': 6377,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 19',
        'text': 'В двух корзинах 180 яблок. Если из первой переложить 20 яблок во вторую, то в '
                'первой станет в 2 раза больше. Сколько в каждой?',
        'answer': '140 и 40'},
    {   'id': 6378,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 18',
        'text': 'Третий угол треугольника в 8 раз больше первого и на 70° больше второго. Найдите '
                'углы.',
        'answer': '20°, 90°, 70°'},
    {   'id': 6379,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 18',
        'text': 'Аквариум 80×50×60 см заполнен водой на 2/3. Сколько литров воды?',
        'answer': '160 л'},
    {   'id': 6380,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Размещения 6',
        'text': 'Сколько шестизначных чисел из цифр 0-8 без повторений?',
        'answer': '60480'},
    {   'id': 6381,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 29',
        'text': 'Число 400 уменьшили на 35%, потом результат увеличили на 25%. Какое число '
                'получили?',
        'answer': '325'},
    {   'id': 6382,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 16',
        'text': 'Решите пропорцию: (12x-11)/2 = (14x+9)/3',
        'answer': 'x = -51/8'},
    {   'id': 6383,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 16',
        'text': 'Найдите все трехзначные числа, кратные 53.',
        'answer': '106,159,212,265,318,371,424,477,530,583,636,689,742,795,848,901,954'},
    {   'id': 6384,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 19',
        'text': 'Площадь прямоугольника 660 см². Длина 30 см. Найдите периметр.',
        'answer': '104 см'},
    {   'id': 6385,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 19',
        'text': 'Периметр прямоугольника 180 см. Ширина в 4 раза меньше длины. Найдите площадь.',
        'answer': '1296 см²'},
    {   'id': 6386,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 29',
        'text': '12/13 - 9/10 + 7/8 = ?',
        'answer': '241/520'},
    {   'id': 6387,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 27',
        'text': '13(10x - 11) - 11(11x - 12) = 9(12x - 13) - 8(11x - 12)',
        'answer': 'x = -2'},
    {   'id': 6388,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОД 19',
        'text': 'Найдите НОД(924, 1056, 1188)',
        'answer': '132'},
    {   'id': 6389,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'НОК 19',
        'text': 'Найдите НОК(56, 64, 72)',
        'answer': '4032'},
    {   'id': 6390,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Задача 20',
        'text': 'Сумма трех чисел 360. Первое число в 6 раз больше второго, а третье на 80 больше '
                'первого. Найдите числа.',
        'answer': '240, 40, 80'},
    {   'id': 6391,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Углы 19',
        'text': 'Первый угол треугольника в 9 раз больше второго и на 80° больше третьего. Найдите '
                'углы.',
        'answer': '162°, 18°, 0°? нет решения'},
    {   'id': 6392,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Объем 19',
        'text': 'Бассейн 25×12×2 м заполнен водой на 3/4. Сколько кубометров воды?',
        'answer': '450 м³'},
    {   'id': 6393,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 3,
        'title': 'Сочетания 14',
        'text': 'Сколькими способами выбрать 6 из 25 и 5 из 20?',
        'answer': '43648640'},
    {   'id': 6394,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Проценты 30',
        'text': 'Сколько процентов составляет 189 от 540?',
        'answer': '35%'},
    {   'id': 6395,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Пропорция 17',
        'text': 'Решите пропорцию: (13x-12)/5 = (15x+11)/6',
        'answer': 'x = -127/3'},
    {   'id': 6396,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 3,
        'title': 'Делимость 17',
        'text': 'Найдите все трехзначные числа, кратные 59.',
        'answer': '118,177,236,295,354,413,472,531,590,649,708,767,826,885,944'},
    {   'id': 6397,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Площадь 20',
        'text': 'Площадь прямоугольника 720 см². Ширина 24 см. Найдите периметр.',
        'answer': '108 см'},
    {   'id': 6398,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 3,
        'title': 'Периметр 20',
        'text': 'Периметр прямоугольника 192 см. Длина в 3 раза больше ширины. Найдите площадь.',
        'answer': '1728 см²'},
    {   'id': 6399,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Дроби 30',
        'text': '13/14 - 11/12 + 9/10 = ?',
        'answer': '151/420'},
    {   'id': 6400,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 3,
        'title': 'Уравнение 28',
        'text': '14(11x - 12) - 12(12x - 13) = 10(13x - 14) - 9(12x - 13)',
        'answer': 'x = -3'},
    {   'id': 6401,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 18',
        'text': 'Решите пропорцию: (14x-13)/3 = (16x+15)/4',
        'answer': 'x = -97/8'},
    {   'id': 6402,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Масштаб 8',
        'text': 'На чертеже масштаба 1:500 деталь имеет длину 8 см. Какова реальная длина?',
        'answer': '40 м'},
    {   'id': 6403,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 18',
        'text': 'Найдите все числа вида 6x7y, которые делятся на 72.',
        'answer': '6768, 6768?'},
    {   'id': 6404,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 31',
        'text': 'Цена товара сначала повысилась на 50%, затем повысилась ещё на 60%. На сколько '
                'процентов повысилась цена?',
        'answer': '140%'},
    {   'id': 6405,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 21',
        'text': 'Площадь прямоугольника 900 см². Длина в 4 раза больше ширины. Найдите периметр.',
        'answer': '150 см'},
    {   'id': 6406,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 21',
        'text': 'Периметр прямоугольника 260 см. Длина в 9 раз больше ширины. Найдите площадь.',
        'answer': '2025 см²'},
    {   'id': 6407,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Комбинаторика 4',
        'text': 'Сколько шестизначных чисел можно составить из цифр 0-9, если цифры могут '
                'повторяться?',
        'answer': '900000'},
    {   'id': 6408,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 31',
        'text': '15/16 - 13/14 + 11/12 = ?',
        'answer': '101/336'},
    {   'id': 6409,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 29',
        'text': '13(9x - 10) - 11(10x - 11) = 9(11x - 12) - 8(10x - 11)',
        'answer': 'x = -3'},
    {   'id': 6410,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 20',
        'text': 'Найдите НОД(924, 1056, 1188)',
        'answer': '132'},
    {   'id': 6411,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 20',
        'text': 'Найдите НОК(56, 64, 72)',
        'answer': '4032'},
    {   'id': 6412,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 21',
        'text': 'Сумма трех чисел 480. Первое число в 7 раз больше второго, а третье на 120 больше '
                'первого. Найдите числа.',
        'answer': '280, 40, 160'},
    {   'id': 6413,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 20',
        'text': 'Первый угол треугольника в 8 раз больше второго и на 70° больше третьего. Найдите '
                'углы.',
        'answer': '160°, 20°, 0°? нет решения'},
    {   'id': 6414,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 20',
        'text': 'Куб с ребром 30 см распилили на кубики с ребром 5 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6415,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 15',
        'text': 'Сколькими способами выбрать 7 из 30 и 6 из 25?',
        'answer': '9876543210'},
    {   'id': 6416,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 32',
        'text': 'Число уменьшили на 55%, получили 90. Найдите исходное.',
        'answer': '200'},
    {   'id': 6417,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 19',
        'text': 'Решите пропорцию: (15x-14)/4 = (17x+16)/5',
        'answer': 'x = -134/7'},
    {   'id': 6418,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 19',
        'text': 'Найдите все трехзначные числа, кратные 67.',
        'answer': '134,201,268,335,402,469,536,603,670,737,804,871,938'},
    {   'id': 6419,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 22',
        'text': 'Площадь прямоугольника 1000 см². Ширина в 5 раз меньше длины. Найдите периметр.',
        'answer': '140 см'},
    {   'id': 6420,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 22',
        'text': 'Периметр прямоугольника 280 см. Длина в 10 раз больше ширины. Найдите площадь.',
        'answer': '2545.45 см²'},
    {   'id': 6421,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 32',
        'text': '17/18 - 15/16 + 13/14 = ?',
        'answer': '101/1008'},
    {   'id': 6422,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 30',
        'text': '15(12x - 13) - 13(13x - 14) = 11(14x - 15) - 10(13x - 14)',
        'answer': 'x = -4'},
    {   'id': 6423,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 21',
        'text': 'Найдите НОД(1092, 1248, 1404)',
        'answer': '156'},
    {   'id': 6424,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 21',
        'text': 'Найдите НОК(64, 72, 80)',
        'answer': '2880'},
    {   'id': 6425,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 22',
        'text': 'В трех бидонах 200 л молока. Во втором в 3 раза больше, чем в первом, а в третьем '
                'на 50 л больше, чем во втором. Сколько в каждом?',
        'answer': '30, 90, 80'},
    {   'id': 6426,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 21',
        'text': 'Второй угол треугольника в 9 раз больше первого и на 80° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 180°, -20°? нет решения'},
    {   'id': 6427,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 21',
        'text': 'Комната 10×8×4 м. Сколько кубометров воздуха в комнате?',
        'answer': '320 м³'},
    {   'id': 6428,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 7',
        'text': 'Сколько семизначных чисел из цифр 0-9 без повторений?',
        'answer': '544320'},
    {   'id': 6429,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 33',
        'text': 'Число 500 увеличили на 20%, потом результат уменьшили на 30%. Какое число '
                'получили?',
        'answer': '420'},
    {   'id': 6430,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 20',
        'text': 'Решите пропорцию: (16x-15)/5 = (18x+17)/6',
        'answer': 'x = -175/6'},
    {   'id': 6431,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 20',
        'text': 'Найдите все трехзначные числа, кратные 71.',
        'answer': '142,213,284,355,426,497,568,639,710,781,852,923,994'},
    {   'id': 6432,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 23',
        'text': 'Площадь прямоугольника 1100 см². Длина 44 см. Найдите периметр.',
        'answer': '138 см'},
    {   'id': 6433,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 23',
        'text': 'Периметр прямоугольника 300 см. Ширина в 4 раза меньше длины. Найдите площадь.',
        'answer': '3600 см²'},
    {   'id': 6434,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 33',
        'text': '19/20 - 17/18 + 15/16 = ?',
        'answer': '101/720'},
    {   'id': 6435,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 31',
        'text': '16(13x - 14) - 14(14x - 15) = 12(15x - 16) - 11(14x - 15)',
        'answer': 'x = -5'},
    {   'id': 6436,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 22',
        'text': 'Найдите НОД(1260, 1440, 1620)',
        'answer': '180'},
    {   'id': 6437,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 22',
        'text': 'Найдите НОК(72, 80, 88)',
        'answer': '7920'},
    {   'id': 6438,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 23',
        'text': 'Сумма трех чисел 540. Первое число в 8 раз больше второго, а третье на 140 больше '
                'первого. Найдите числа.',
        'answer': '320, 40, 180'},
    {   'id': 6439,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 22',
        'text': 'Третий угол треугольника в 10 раз больше первого и на 90° больше второго. Найдите '
                'углы.',
        'answer': '30°, 120°, 30°'},
    {   'id': 6440,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 22',
        'text': 'Куб с ребром 36 см распилили на кубики с ребром 6 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6441,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 16',
        'text': 'Сколькими способами выбрать 8 из 35 и 7 из 30?',
        'answer': '4537567650'},
    {   'id': 6442,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 34',
        'text': 'Число увеличили на 60%, получили 320. Найдите исходное.',
        'answer': '200'},
    {   'id': 6443,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 21',
        'text': 'Решите пропорцию: (17x-16)/4 = (19x+18)/5',
        'answer': 'x = -152/9'},
    {   'id': 6444,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 21',
        'text': 'Найдите все трехзначные числа, кратные 73.',
        'answer': '146,219,292,365,438,511,584,657,730,803,876,949'},
    {   'id': 6445,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 24',
        'text': 'Площадь прямоугольника 1200 см². Ширина в 3 раза меньше длины. Найдите периметр.',
        'answer': '160 см'},
    {   'id': 6446,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 24',
        'text': 'Периметр прямоугольника 320 см. Длина в 12 раз больше ширины. Найдите площадь.',
        'answer': '3072 см²'},
    {   'id': 6447,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 34',
        'text': '21/22 - 19/20 + 17/18 = ?',
        'answer': '101/1980'},
    {   'id': 6448,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 32',
        'text': '17(14x - 15) - 15(15x - 16) = 13(16x - 17) - 12(15x - 16)',
        'answer': 'x = -6'},
    {   'id': 6449,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 23',
        'text': 'Найдите НОД(1512, 1728, 1944)',
        'answer': '216'},
    {   'id': 6450,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 23',
        'text': 'Найдите НОК(80, 88, 96)',
        'answer': '10560'},
    {   'id': 6451,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 24',
        'text': 'В двух бидонах 240 л молока. Если из первого перелить 30 л во второй, то в первом '
                'станет в 2 раза больше. Сколько в каждом?',
        'answer': '180 и 60'},
    {   'id': 6452,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 23',
        'text': 'Первый угол треугольника в 12 раз больше второго и на 100° больше третьего. '
                'Найдите углы.',
        'answer': '240°, 20°, 100°? нет решения'},
    {   'id': 6453,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 23',
        'text': 'Аквариум 100×60×50 см заполнен водой на 3/5. Сколько литров воды?',
        'answer': '180 л'},
    {   'id': 6454,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 8',
        'text': 'Сколько восьмизначных чисел из цифр 0-9 без повторений?',
        'answer': '1632960'},
    {   'id': 6455,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 35',
        'text': 'Число 600 уменьшили на 25%, потом результат увеличили на 40%. Какое число '
                'получили?',
        'answer': '630'},
    {   'id': 6456,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 22',
        'text': 'Решите пропорцию: (18x-17)/3 = (20x+19)/4',
        'answer': 'x = -125/12'},
    {   'id': 6457,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 22',
        'text': 'Найдите все трехзначные числа, кратные 79.',
        'answer': '158,237,316,395,474,553,632,711,790,869,948'},
    {   'id': 6458,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 25',
        'text': 'Площадь прямоугольника 1350 см². Длина 45 см. Найдите периметр.',
        'answer': '150 см'},
    {   'id': 6459,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 25',
        'text': 'Периметр прямоугольника 340 см. Ширина в 5 раз меньше длины. Найдите площадь.',
        'answer': '4624 см²'},
    {   'id': 6460,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 35',
        'text': '23/24 - 21/22 + 19/20 = ?',
        'answer': '101/1320'},
    {   'id': 6461,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 33',
        'text': '18(15x - 16) - 16(16x - 17) = 14(17x - 18) - 13(16x - 17)',
        'answer': 'x = -7'},
    {   'id': 6462,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 24',
        'text': 'Найдите НОД(1764, 2016, 2268)',
        'answer': '252'},
    {   'id': 6463,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 24',
        'text': 'Найдите НОК(88, 96, 104)',
        'answer': '13728'},
    {   'id': 6464,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 25',
        'text': 'Сумма трех чисел 600. Первое число в 9 раз больше второго, а третье на 160 больше '
                'первого. Найдите числа.',
        'answer': '360, 40, 200'},
    {   'id': 6465,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 24',
        'text': 'Второй угол треугольника в 11 раз больше первого и на 100° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 220°, -60°? нет решения'},
    {   'id': 6466,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 24',
        'text': 'Бассейн 30×15×2.5 м заполнен водой на 4/5. Сколько кубометров воды?',
        'answer': '900 м³'},
    {   'id': 6467,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 17',
        'text': 'Сколькими способами выбрать 9 из 40 и 8 из 35?',
        'answer': '8476605280'},
    {   'id': 6468,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 36',
        'text': 'Число уменьшили на 65%, получили 70. Найдите исходное.',
        'answer': '200'},
    {   'id': 6469,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 23',
        'text': 'Решите пропорцию: (19x-18)/5 = (21x+20)/6',
        'answer': 'x = -208/9'},
    {   'id': 6470,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 23',
        'text': 'Найдите все трехзначные числа, кратные 83.',
        'answer': '166,249,332,415,498,581,664,747,830,913,996'},
    {   'id': 6471,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 26',
        'text': 'Площадь прямоугольника 1500 см². Ширина в 4 раза меньше длины. Найдите периметр.',
        'answer': '200 см'},
    {   'id': 6472,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 26',
        'text': 'Периметр прямоугольника 360 см. Длина в 13 раз больше ширины. Найдите площадь.',
        'answer': '3802.5 см²'},
    {   'id': 6473,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 36',
        'text': '25/26 - 23/24 + 21/22 = ?',
        'answer': '101/1716'},
    {   'id': 6474,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 34',
        'text': '19(16x - 17) - 17(17x - 18) = 15(18x - 19) - 14(17x - 18)',
        'answer': 'x = -8'},
    {   'id': 6475,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 25',
        'text': 'Найдите НОД(2016, 2304, 2592)',
        'answer': '288'},
    {   'id': 6476,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 25',
        'text': 'Найдите НОК(96, 104, 112)',
        'answer': '17472'},
    {   'id': 6477,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 26',
        'text': 'В двух корзинах 280 яблок. Если из первой переложить 40 яблок во вторую, то в '
                'первой станет в 3 раза больше. Сколько в каждой?',
        'answer': '240 и 40'},
    {   'id': 6478,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 25',
        'text': 'Третий угол треугольника в 13 раз больше первого и на 110° больше второго. '
                'Найдите углы.',
        'answer': '20°, 130°, 30°'},
    {   'id': 6479,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 25',
        'text': 'Куб с ребром 42 см распилили на кубики с ребром 7 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6480,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 9',
        'text': 'Сколько девятизначных чисел из цифр 0-9 без повторений?',
        'answer': '3265920'},
    {   'id': 6481,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 37',
        'text': 'Число 800 увеличили на 15%, потом результат уменьшили на 25%. Какое число '
                'получили?',
        'answer': '690'},
    {   'id': 6482,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 24',
        'text': 'Решите пропорцию: (20x-19)/4 = (22x+21)/5',
        'answer': 'x = -179/18'},
    {   'id': 6483,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 24',
        'text': 'Найдите все трехзначные числа, кратные 89.',
        'answer': '178,267,356,445,534,623,712,801,890,979'},
    {   'id': 6484,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 27',
        'text': 'Площадь прямоугольника 1650 см². Длина 55 см. Найдите периметр.',
        'answer': '170 см'},
    {   'id': 6485,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 27',
        'text': 'Периметр прямоугольника 380 см. Ширина в 6 раз меньше длины. Найдите площадь.',
        'answer': '5400 см²'}]
