PROBLEMS_DB = [   {   'id': 6486,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 37',
        'text': '27/28 - 25/26 + 23/24 = ?',
        'answer': '101/2184'},
    {   'id': 6487,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 35',
        'text': '20(17x - 18) - 18(18x - 19) = 16(19x - 20) - 15(18x - 19)',
        'answer': 'x = -9'},
    {   'id': 6488,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 26',
        'text': 'Найдите НОД(2268, 2592, 2916)',
        'answer': '324'},
    {   'id': 6489,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 26',
        'text': 'Найдите НОК(104, 112, 120)',
        'answer': '21840'},
    {   'id': 6490,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 27',
        'text': 'Сумма трех чисел 660. Первое число в 10 раз больше второго, а третье на 180 '
                'больше первого. Найдите числа.',
        'answer': '400, 40, 220'},
    {   'id': 6491,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 26',
        'text': 'Первый угол треугольника в 14 раз больше второго и на 120° больше третьего. '
                'Найдите углы.',
        'answer': '280°, 20°, 140°? нет решения'},
    {   'id': 6492,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 26',
        'text': 'Комната 12×8×3.5 м. Сколько кубометров воздуха в комнате?',
        'answer': '336 м³'},
    {   'id': 6493,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 18',
        'text': 'Сколькими способами выбрать 10 из 45 и 9 из 40?',
        'answer': '31901872860'},
    {   'id': 6494,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 38',
        'text': 'Число увеличили на 70%, получили 340. Найдите исходное.',
        'answer': '200'},
    {   'id': 6495,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 25',
        'text': 'Решите пропорцию: (21x-20)/5 = (23x+22)/6',
        'answer': 'x = -212/19'},
    {   'id': 6496,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 25',
        'text': 'Найдите все трехзначные числа, кратные 97.',
        'answer': '194,291,388,485,582,679,776,873,970'},
    {   'id': 6497,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 28',
        'text': 'Площадь прямоугольника 1800 см². Ширина в 2 раза меньше длины. Найдите периметр.',
        'answer': '180 см'},
    {   'id': 6498,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 28',
        'text': 'Периметр прямоугольника 400 см. Длина в 14 раз больше ширины. Найдите площадь.',
        'answer': '5376 см²'},
    {   'id': 6499,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 38',
        'text': '29/30 - 27/28 + 25/26 = ?',
        'answer': '101/2730'},
    {   'id': 6500,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 36',
        'text': '21(18x - 19) - 19(19x - 20) = 17(20x - 21) - 16(19x - 20)',
        'answer': 'x = -10'},
    {   'id': 6401,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 18',
        'text': 'Решите пропорцию: (14x-13)/3 = (16x+15)/4',
        'answer': 'x = -97/8'},
    {   'id': 6402,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Масштаб 8',
        'text': 'На чертеже масштаба 1:500 деталь имеет длину 8 см. Какова реальная длина?',
        'answer': '40 м'},
    {   'id': 6403,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 18',
        'text': 'Найдите все числа вида 6x7y, которые делятся на 72.',
        'answer': '6768, 6768?'},
    {   'id': 6404,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 31',
        'text': 'Цена товара сначала повысилась на 50%, затем повысилась ещё на 60%. На сколько '
                'процентов повысилась цена?',
        'answer': '140%'},
    {   'id': 6405,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 21',
        'text': 'Площадь прямоугольника 900 см². Длина в 4 раза больше ширины. Найдите периметр.',
        'answer': '150 см'},
    {   'id': 6406,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 21',
        'text': 'Периметр прямоугольника 260 см. Длина в 9 раз больше ширины. Найдите площадь.',
        'answer': '2025 см²'},
    {   'id': 6407,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Комбинаторика 4',
        'text': 'Сколько шестизначных чисел можно составить из цифр 0-9, если цифры могут '
                'повторяться?',
        'answer': '900000'},
    {   'id': 6408,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 31',
        'text': '15/16 - 13/14 + 11/12 = ?',
        'answer': '101/336'},
    {   'id': 6409,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 29',
        'text': '13(9x - 10) - 11(10x - 11) = 9(11x - 12) - 8(10x - 11)',
        'answer': 'x = -3'},
    {   'id': 6410,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 20',
        'text': 'Найдите НОД(924, 1056, 1188)',
        'answer': '132'},
    {   'id': 6411,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 20',
        'text': 'Найдите НОК(56, 64, 72)',
        'answer': '4032'},
    {   'id': 6412,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 21',
        'text': 'Сумма трех чисел 480. Первое число в 7 раз больше второго, а третье на 120 больше '
                'первого. Найдите числа.',
        'answer': '280, 40, 160'},
    {   'id': 6413,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 20',
        'text': 'Первый угол треугольника в 8 раз больше второго и на 70° больше третьего. Найдите '
                'углы.',
        'answer': '160°, 20°, 0°? нет решения'},
    {   'id': 6414,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 20',
        'text': 'Куб с ребром 30 см распилили на кубики с ребром 5 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6415,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 15',
        'text': 'Сколькими способами выбрать 7 из 30 и 6 из 25?',
        'answer': '9876543210'},
    {   'id': 6416,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 32',
        'text': 'Число уменьшили на 55%, получили 90. Найдите исходное.',
        'answer': '200'},
    {   'id': 6417,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 19',
        'text': 'Решите пропорцию: (15x-14)/4 = (17x+16)/5',
        'answer': 'x = -134/7'},
    {   'id': 6418,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 19',
        'text': 'Найдите все трехзначные числа, кратные 67.',
        'answer': '134,201,268,335,402,469,536,603,670,737,804,871,938'},
    {   'id': 6419,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 22',
        'text': 'Площадь прямоугольника 1000 см². Ширина в 5 раз меньше длины. Найдите периметр.',
        'answer': '140 см'},
    {   'id': 6420,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 22',
        'text': 'Периметр прямоугольника 280 см. Длина в 10 раз больше ширины. Найдите площадь.',
        'answer': '2545.45 см²'},
    {   'id': 6421,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 32',
        'text': '17/18 - 15/16 + 13/14 = ?',
        'answer': '101/1008'},
    {   'id': 6422,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 30',
        'text': '15(12x - 13) - 13(13x - 14) = 11(14x - 15) - 10(13x - 14)',
        'answer': 'x = -4'},
    {   'id': 6423,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 21',
        'text': 'Найдите НОД(1092, 1248, 1404)',
        'answer': '156'},
    {   'id': 6424,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 21',
        'text': 'Найдите НОК(64, 72, 80)',
        'answer': '2880'},
    {   'id': 6425,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 22',
        'text': 'В трех бидонах 200 л молока. Во втором в 3 раза больше, чем в первом, а в третьем '
                'на 50 л больше, чем во втором. Сколько в каждом?',
        'answer': '30, 90, 80'},
    {   'id': 6426,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 21',
        'text': 'Второй угол треугольника в 9 раз больше первого и на 80° больше третьего. Найдите '
                'углы.',
        'answer': '20°, 180°, -20°? нет решения'},
    {   'id': 6427,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 21',
        'text': 'Комната 10×8×4 м. Сколько кубометров воздуха в комнате?',
        'answer': '320 м³'},
    {   'id': 6428,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 7',
        'text': 'Сколько семизначных чисел из цифр 0-9 без повторений?',
        'answer': '544320'},
    {   'id': 6429,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 33',
        'text': 'Число 500 увеличили на 20%, потом результат уменьшили на 30%. Какое число '
                'получили?',
        'answer': '420'},
    {   'id': 6430,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 20',
        'text': 'Решите пропорцию: (16x-15)/5 = (18x+17)/6',
        'answer': 'x = -175/6'},
    {   'id': 6431,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 20',
        'text': 'Найдите все трехзначные числа, кратные 71.',
        'answer': '142,213,284,355,426,497,568,639,710,781,852,923,994'},
    {   'id': 6432,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 23',
        'text': 'Площадь прямоугольника 1100 см². Длина 44 см. Найдите периметр.',
        'answer': '138 см'},
    {   'id': 6433,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 23',
        'text': 'Периметр прямоугольника 300 см. Ширина в 4 раза меньше длины. Найдите площадь.',
        'answer': '3600 см²'},
    {   'id': 6434,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 33',
        'text': '19/20 - 17/18 + 15/16 = ?',
        'answer': '101/720'},
    {   'id': 6435,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 31',
        'text': '16(13x - 14) - 14(14x - 15) = 12(15x - 16) - 11(14x - 15)',
        'answer': 'x = -5'},
    {   'id': 6436,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 22',
        'text': 'Найдите НОД(1260, 1440, 1620)',
        'answer': '180'},
    {   'id': 6437,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 22',
        'text': 'Найдите НОК(72, 80, 88)',
        'answer': '7920'},
    {   'id': 6438,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 23',
        'text': 'Сумма трех чисел 540. Первое число в 8 раз больше второго, а третье на 140 больше '
                'первого. Найдите числа.',
        'answer': '320, 40, 180'},
    {   'id': 6439,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 22',
        'text': 'Третий угол треугольника в 10 раз больше первого и на 90° больше второго. Найдите '
                'углы.',
        'answer': '30°, 120°, 30°'},
    {   'id': 6440,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 22',
        'text': 'Куб с ребром 36 см распилили на кубики с ребром 6 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6441,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 16',
        'text': 'Сколькими способами выбрать 8 из 35 и 7 из 30?',
        'answer': '4537567650'},
    {   'id': 6442,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 34',
        'text': 'Число увеличили на 60%, получили 320. Найдите исходное.',
        'answer': '200'},
    {   'id': 6443,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 21',
        'text': 'Решите пропорцию: (17x-16)/4 = (19x+18)/5',
        'answer': 'x = -152/9'},
    {   'id': 6444,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 21',
        'text': 'Найдите все трехзначные числа, кратные 73.',
        'answer': '146,219,292,365,438,511,584,657,730,803,876,949'},
    {   'id': 6445,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 24',
        'text': 'Площадь прямоугольника 1200 см². Ширина в 3 раза меньше длины. Найдите периметр.',
        'answer': '160 см'},
    {   'id': 6446,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 24',
        'text': 'Периметр прямоугольника 320 см. Длина в 12 раз больше ширины. Найдите площадь.',
        'answer': '3072 см²'},
    {   'id': 6447,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 34',
        'text': '21/22 - 19/20 + 17/18 = ?',
        'answer': '101/1980'},
    {   'id': 6448,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 32',
        'text': '17(14x - 15) - 15(15x - 16) = 13(16x - 17) - 12(15x - 16)',
        'answer': 'x = -6'},
    {   'id': 6449,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 23',
        'text': 'Найдите НОД(1512, 1728, 1944)',
        'answer': '216'},
    {   'id': 6450,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 23',
        'text': 'Найдите НОК(80, 88, 96)',
        'answer': '10560'},
    {   'id': 6451,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 24',
        'text': 'В двух бидонах 240 л молока. Если из первого перелить 30 л во второй, то в первом '
                'станет в 2 раза больше. Сколько в каждом?',
        'answer': '180 и 60'},
    {   'id': 6452,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 23',
        'text': 'Первый угол треугольника в 12 раз больше второго и на 100° больше третьего. '
                'Найдите углы.',
        'answer': '240°, 20°, 100°? нет решения'},
    {   'id': 6453,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 23',
        'text': 'Аквариум 100×60×50 см заполнен водой на 3/5. Сколько литров воды?',
        'answer': '180 л'},
    {   'id': 6454,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 8',
        'text': 'Сколько восьмизначных чисел из цифр 0-9 без повторений?',
        'answer': '1632960'},
    {   'id': 6455,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 35',
        'text': 'Число 600 уменьшили на 25%, потом результат увеличили на 40%. Какое число '
                'получили?',
        'answer': '630'},
    {   'id': 6456,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 22',
        'text': 'Решите пропорцию: (18x-17)/3 = (20x+19)/4',
        'answer': 'x = -125/12'},
    {   'id': 6457,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 22',
        'text': 'Найдите все трехзначные числа, кратные 79.',
        'answer': '158,237,316,395,474,553,632,711,790,869,948'},
    {   'id': 6458,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 25',
        'text': 'Площадь прямоугольника 1350 см². Длина 45 см. Найдите периметр.',
        'answer': '150 см'},
    {   'id': 6459,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 25',
        'text': 'Периметр прямоугольника 340 см. Ширина в 5 раз меньше длины. Найдите площадь.',
        'answer': '4624 см²'},
    {   'id': 6460,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 35',
        'text': '23/24 - 21/22 + 19/20 = ?',
        'answer': '101/1320'},
    {   'id': 6461,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 33',
        'text': '18(15x - 16) - 16(16x - 17) = 14(17x - 18) - 13(16x - 17)',
        'answer': 'x = -7'},
    {   'id': 6462,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 24',
        'text': 'Найдите НОД(1764, 2016, 2268)',
        'answer': '252'},
    {   'id': 6463,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 24',
        'text': 'Найдите НОК(88, 96, 104)',
        'answer': '13728'},
    {   'id': 6464,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 25',
        'text': 'Сумма трех чисел 600. Первое число в 9 раз больше второго, а третье на 160 больше '
                'первого. Найдите числа.',
        'answer': '360, 40, 200'},
    {   'id': 6465,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 24',
        'text': 'Второй угол треугольника в 11 раз больше первого и на 100° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 220°, -60°? нет решения'},
    {   'id': 6466,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 24',
        'text': 'Бассейн 30×15×2.5 м заполнен водой на 4/5. Сколько кубометров воды?',
        'answer': '900 м³'},
    {   'id': 6467,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 17',
        'text': 'Сколькими способами выбрать 9 из 40 и 8 из 35?',
        'answer': '8476605280'},
    {   'id': 6468,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 36',
        'text': 'Число уменьшили на 65%, получили 70. Найдите исходное.',
        'answer': '200'},
    {   'id': 6469,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 23',
        'text': 'Решите пропорцию: (19x-18)/5 = (21x+20)/6',
        'answer': 'x = -208/9'},
    {   'id': 6470,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 23',
        'text': 'Найдите все трехзначные числа, кратные 83.',
        'answer': '166,249,332,415,498,581,664,747,830,913,996'},
    {   'id': 6471,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 26',
        'text': 'Площадь прямоугольника 1500 см². Ширина в 4 раза меньше длины. Найдите периметр.',
        'answer': '200 см'},
    {   'id': 6472,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 26',
        'text': 'Периметр прямоугольника 360 см. Длина в 13 раз больше ширины. Найдите площадь.',
        'answer': '3802.5 см²'},
    {   'id': 6473,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 36',
        'text': '25/26 - 23/24 + 21/22 = ?',
        'answer': '101/1716'},
    {   'id': 6474,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 34',
        'text': '19(16x - 17) - 17(17x - 18) = 15(18x - 19) - 14(17x - 18)',
        'answer': 'x = -8'},
    {   'id': 6475,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 25',
        'text': 'Найдите НОД(2016, 2304, 2592)',
        'answer': '288'},
    {   'id': 6476,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 25',
        'text': 'Найдите НОК(96, 104, 112)',
        'answer': '17472'},
    {   'id': 6477,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 26',
        'text': 'В двух корзинах 280 яблок. Если из первой переложить 40 яблок во вторую, то в '
                'первой станет в 3 раза больше. Сколько в каждой?',
        'answer': '240 и 40'},
    {   'id': 6478,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 25',
        'text': 'Третий угол треугольника в 13 раз больше первого и на 110° больше второго. '
                'Найдите углы.',
        'answer': '20°, 130°, 30°'},
    {   'id': 6479,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 25',
        'text': 'Куб с ребром 42 см распилили на кубики с ребром 7 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6480,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Размещения 9',
        'text': 'Сколько девятизначных чисел из цифр 0-9 без повторений?',
        'answer': '3265920'},
    {   'id': 6481,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 37',
        'text': 'Число 800 увеличили на 15%, потом результат уменьшили на 25%. Какое число '
                'получили?',
        'answer': '690'},
    {   'id': 6482,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 24',
        'text': 'Решите пропорцию: (20x-19)/4 = (22x+21)/5',
        'answer': 'x = -179/18'},
    {   'id': 6483,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 24',
        'text': 'Найдите все трехзначные числа, кратные 89.',
        'answer': '178,267,356,445,534,623,712,801,890,979'},
    {   'id': 6484,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 27',
        'text': 'Площадь прямоугольника 1650 см². Длина 55 см. Найдите периметр.',
        'answer': '170 см'},
    {   'id': 6485,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 27',
        'text': 'Периметр прямоугольника 380 см. Ширина в 6 раз меньше длины. Найдите площадь.',
        'answer': '5400 см²'},
    {   'id': 6486,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 37',
        'text': '27/28 - 25/26 + 23/24 = ?',
        'answer': '101/2184'},
    {   'id': 6487,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 35',
        'text': '20(17x - 18) - 18(18x - 19) = 16(19x - 20) - 15(18x - 19)',
        'answer': 'x = -9'},
    {   'id': 6488,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОД 26',
        'text': 'Найдите НОД(2268, 2592, 2916)',
        'answer': '324'},
    {   'id': 6489,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'НОК 26',
        'text': 'Найдите НОК(104, 112, 120)',
        'answer': '21840'},
    {   'id': 6490,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Задача 27',
        'text': 'Сумма трех чисел 660. Первое число в 10 раз больше второго, а третье на 180 '
                'больше первого. Найдите числа.',
        'answer': '400, 40, 220'},
    {   'id': 6491,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Углы 26',
        'text': 'Первый угол треугольника в 14 раз больше второго и на 120° больше третьего. '
                'Найдите углы.',
        'answer': '280°, 20°, 140°? нет решения'},
    {   'id': 6492,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Объем 26',
        'text': 'Комната 12×8×3.5 м. Сколько кубометров воздуха в комнате?',
        'answer': '336 м³'},
    {   'id': 6493,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 4,
        'title': 'Сочетания 18',
        'text': 'Сколькими способами выбрать 10 из 45 и 9 из 40?',
        'answer': '31901872860'},
    {   'id': 6494,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Проценты 38',
        'text': 'Число увеличили на 70%, получили 340. Найдите исходное.',
        'answer': '200'},
    {   'id': 6495,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Пропорция 25',
        'text': 'Решите пропорцию: (21x-20)/5 = (23x+22)/6',
        'answer': 'x = -212/19'},
    {   'id': 6496,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 4,
        'title': 'Делимость 25',
        'text': 'Найдите все трехзначные числа, кратные 97.',
        'answer': '194,291,388,485,582,679,776,873,970'},
    {   'id': 6497,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Площадь 28',
        'text': 'Площадь прямоугольника 1800 см². Ширина в 2 раза меньше длины. Найдите периметр.',
        'answer': '180 см'},
    {   'id': 6498,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 4,
        'title': 'Периметр 28',
        'text': 'Периметр прямоугольника 400 см. Длина в 14 раз больше ширины. Найдите площадь.',
        'answer': '5376 см²'},
    {   'id': 6499,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Дроби 38',
        'text': '29/30 - 27/28 + 25/26 = ?',
        'answer': '101/2730'},
    {   'id': 6500,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 4,
        'title': 'Уравнение 36',
        'text': '21(18x - 19) - 19(19x - 20) = 17(20x - 21) - 16(19x - 20)',
        'answer': 'x = -10'},
    {   'id': 6501,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 26',
        'text': 'Решите пропорцию: (22x-21)/3 = (24x+23)/4',
        'answer': 'x = -149/20'},
    {   'id': 6502,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Масштаб 10',
        'text': 'На карте масштаба 1:2000000 расстояние 10 см. Сколько км на местности?',
        'answer': '200 км'},
    {   'id': 6503,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 26',
        'text': 'Найдите все числа вида 8x9y, которые делятся на 36.',
        'answer': '8892, 8892?'},
    {   'id': 6504,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 39',
        'text': 'Цена товара сначала повысилась на 60%, затем повысилась ещё на 70%. На сколько '
                'процентов повысилась цена?',
        'answer': '172%'},
    {   'id': 6505,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 29',
        'text': 'Площадь прямоугольника 2000 см². Длина в 5 раз больше ширины. Найдите периметр.',
        'answer': '240 см'},
    {   'id': 6506,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 29',
        'text': 'Периметр прямоугольника 420 см. Длина в 15 раз больше ширины. Найдите площадь.',
        'answer': '4950 см²'},
    {   'id': 6507,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Комбинаторика 6',
        'text': 'Сколько восьмизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '43046721'},
    {   'id': 6508,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 39',
        'text': '31/32 - 29/30 + 27/28 = ?',
        'answer': '101/3360'},
    {   'id': 6509,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 37',
        'text': '22(19x - 20) - 20(20x - 21) = 18(21x - 22) - 17(20x - 21)',
        'answer': 'x = -11'},
    {   'id': 6510,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 27',
        'text': 'Найдите НОД(2520, 2880, 3240)',
        'answer': '360'},
    {   'id': 6511,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 27',
        'text': 'Найдите НОК(90, 100, 110)',
        'answer': '9900'},
    {   'id': 6512,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 28',
        'text': 'Сумма трех чисел 720. Первое число в 11 раз больше второго, а третье на 200 '
                'больше первого. Найдите числа.',
        'answer': '440, 40, 240'},
    {   'id': 6513,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 27',
        'text': 'Второй угол треугольника в 13 раз больше первого и на 120° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 260°, -100°? нет решения'},
    {   'id': 6514,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 27',
        'text': 'Куб с ребром 48 см распилили на кубики с ребром 8 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6515,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Сочетания 19',
        'text': 'Сколькими способами выбрать 9 из 40 и 8 из 35?',
        'answer': '8476605280'},
    {   'id': 6516,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 40',
        'text': 'Число уменьшили на 75%, получили 50. Найдите исходное.',
        'answer': '200'},
    {   'id': 6517,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 27',
        'text': 'Решите пропорцию: (23x-22)/4 = (25x+24)/5',
        'answer': 'x = -206/15'},
    {   'id': 6518,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 27',
        'text': 'Найдите все трехзначные числа, кратные 101.',
        'answer': '101,202,303,404,505,606,707,808,909'},
    {   'id': 6519,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 30',
        'text': 'Площадь прямоугольника 2200 см². Ширина в 5 раз меньше длины. Найдите периметр.',
        'answer': '240 см'},
    {   'id': 6520,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 30',
        'text': 'Периметр прямоугольника 440 см. Длина в 16 раз больше ширины. Найдите площадь.',
        'answer': '6400 см²'},
    {   'id': 6521,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 40',
        'text': '33/34 - 31/32 + 29/30 = ?',
        'answer': '101/4080'},
    {   'id': 6522,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 38',
        'text': '23(20x - 21) - 21(21x - 22) = 19(22x - 23) - 18(21x - 22)',
        'answer': 'x = -12'},
    {   'id': 6523,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 28',
        'text': 'Найдите НОД(2772, 3168, 3564)',
        'answer': '396'},
    {   'id': 6524,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 28',
        'text': 'Найдите НОК(100, 110, 120)',
        'answer': '6600'},
    {   'id': 6525,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 29',
        'text': 'В двух бидонах 320 л молока. Если из первого перелить 50 л во второй, то в первом '
                'станет в 3 раза больше. Сколько в каждом?',
        'answer': '270 и 50'},
    {   'id': 6526,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 28',
        'text': 'Третий угол треугольника в 15 раз больше первого и на 130° больше второго. '
                'Найдите углы.',
        'answer': '20°, 140°, 20°'},
    {   'id': 6527,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 28',
        'text': 'Аквариум 120×60×50 см заполнен водой на 2/3. Сколько литров воды?',
        'answer': '240 л'},
    {   'id': 6528,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Размещения 10',
        'text': 'Сколько десятизначных чисел из цифр 0-9 без повторений?',
        'answer': '3265920'},
    {   'id': 6529,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 41',
        'text': 'Число 900 увеличили на 10%, потом результат уменьшили на 20%. Какое число '
                'получили?',
        'answer': '792'},
    {   'id': 6530,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 28',
        'text': 'Решите пропорцию: (24x-23)/5 = (26x+25)/6',
        'answer': 'x = -263/14'},
    {   'id': 6531,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 28',
        'text': 'Найдите все трехзначные числа, кратные 103.',
        'answer': '103,206,309,412,515,618,721,824,927'},
    {   'id': 6532,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 31',
        'text': 'Площадь прямоугольника 2400 см². Длина 60 см. Найдите периметр.',
        'answer': '200 см'},
    {   'id': 6533,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 31',
        'text': 'Периметр прямоугольника 460 см. Ширина в 7 раз меньше длины. Найдите площадь.',
        'answer': '7350 см²'},
    {   'id': 6534,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 41',
        'text': '35/36 - 33/34 + 31/32 = ?',
        'answer': '101/4896'},
    {   'id': 6535,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 39',
        'text': '24(21x - 22) - 22(22x - 23) = 20(23x - 24) - 19(22x - 23)',
        'answer': 'x = -13'},
    {   'id': 6536,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 29',
        'text': 'Найдите НОД(3024, 3456, 3888)',
        'answer': '432'},
    {   'id': 6537,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 29',
        'text': 'Найдите НОК(108, 120, 132)',
        'answer': '11880'},
    {   'id': 6538,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 30',
        'text': 'Сумма трех чисел 780. Первое число в 12 раз больше второго, а третье на 220 '
                'больше первого. Найдите числа.',
        'answer': '480, 40, 260'},
    {   'id': 6539,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 29',
        'text': 'Первый угол треугольника в 16 раз больше второго и на 140° больше третьего. '
                'Найдите углы.',
        'answer': '320°, 20°, 140°? нет решения'},
    {   'id': 6540,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 29',
        'text': 'Бассейн 40×20×3 м заполнен водой на 3/4. Сколько кубометров воды?',
        'answer': '1800 м³'},
    {   'id': 6541,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Сочетания 20',
        'text': 'Сколькими способами выбрать 10 из 45 и 9 из 40?',
        'answer': '31901872860'},
    {   'id': 6542,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 42',
        'text': 'Число увеличили на 80%, получили 360. Найдите исходное.',
        'answer': '200'},
    {   'id': 6543,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 29',
        'text': 'Решите пропорцию: (25x-24)/4 = (27x+26)/5',
        'answer': 'x = -226/17'},
    {   'id': 6544,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 29',
        'text': 'Найдите все трехзначные числа, кратные 107.',
        'answer': '107,214,321,428,535,642,749,856,963'},
    {   'id': 6545,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 32',
        'text': 'Площадь прямоугольника 2600 см². Ширина в 4 раза меньше длины. Найдите периметр.',
        'answer': '260 см'},
    {   'id': 6546,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 32',
        'text': 'Периметр прямоугольника 480 см. Длина в 17 раз больше ширины. Найдите площадь.',
        'answer': '8160 см²'},
    {   'id': 6547,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 42',
        'text': '37/38 - 35/36 + 33/34 = ?',
        'answer': '101/5814'},
    {   'id': 6548,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 40',
        'text': '25(22x - 23) - 23(23x - 24) = 21(24x - 25) - 20(23x - 24)',
        'answer': 'x = -14'},
    {   'id': 6549,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 30',
        'text': 'Найдите НОД(3276, 3744, 4212)',
        'answer': '468'},
    {   'id': 6550,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 30',
        'text': 'Найдите НОК(112, 126, 140)',
        'answer': '5040'},
    {   'id': 6551,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 31',
        'text': 'В двух корзинах 360 яблок. Если из первой переложить 60 яблок во вторую, то в '
                'первой станет в 2 раза больше. Сколько в каждой?',
        'answer': '280 и 80'},
    {   'id': 6552,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 30',
        'text': 'Второй угол треугольника в 17 раз больше первого и на 150° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 340°, -180°? нет решения'},
    {   'id': 6553,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 30',
        'text': 'Куб с ребром 54 см распилили на кубики с ребром 9 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6554,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Размещения 11',
        'text': 'Сколько одиннадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '239500800'},
    {   'id': 6555,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 43',
        'text': 'Число 1000 уменьшили на 30%, потом результат увеличили на 50%. Какое число '
                'получили?',
        'answer': '1050'},
    {   'id': 6556,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 30',
        'text': 'Решите пропорцию: (26x-25)/5 = (28x+27)/6',
        'answer': 'x = -297/16'},
    {   'id': 6557,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 30',
        'text': 'Найдите все трехзначные числа, кратные 109.',
        'answer': '109,218,327,436,545,654,763,872,981'},
    {   'id': 6558,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 33',
        'text': 'Площадь прямоугольника 2800 см². Длина 70 см. Найдите периметр.',
        'answer': '220 см'},
    {   'id': 6559,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 33',
        'text': 'Периметр прямоугольника 500 см. Ширина в 8 раз меньше длины. Найдите площадь.',
        'answer': '9600 см²'},
    {   'id': 6560,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 43',
        'text': '39/40 - 37/38 + 35/36 = ?',
        'answer': '101/6840'},
    {   'id': 6561,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 41',
        'text': '26(23x - 24) - 24(24x - 25) = 22(25x - 26) - 21(24x - 25)',
        'answer': 'x = -15'},
    {   'id': 6562,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 31',
        'text': 'Найдите НОД(3528, 4032, 4536)',
        'answer': '504'},
    {   'id': 6563,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 31',
        'text': 'Найдите НОК(120, 132, 144)',
        'answer': '7920'},
    {   'id': 6564,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 32',
        'text': 'Сумма трех чисел 840. Первое число в 13 раз больше второго, а третье на 240 '
                'больше первого. Найдите числа.',
        'answer': '520, 40, 280'},
    {   'id': 6565,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 31',
        'text': 'Третий угол треугольника в 18 раз больше первого и на 160° больше второго. '
                'Найдите углы.',
        'answer': '20°, 180°, 0°? нет решения'},
    {   'id': 6566,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 31',
        'text': 'Комната 15×10×4 м. Сколько кубометров воздуха в комнате?',
        'answer': '600 м³'},
    {   'id': 6567,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Сочетания 21',
        'text': 'Сколькими способами выбрать 11 из 50 и 10 из 45?',
        'answer': '3.73e+12'},
    {   'id': 6568,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 44',
        'text': 'Число уменьшили на 85%, получили 30. Найдите исходное.',
        'answer': '200'},
    {   'id': 6569,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 31',
        'text': 'Решите пропорцию: (27x-26)/4 = (29x+28)/5',
        'answer': 'x = -242/19'},
    {   'id': 6570,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 31',
        'text': 'Найдите все трехзначные числа, кратные 113.',
        'answer': '113,226,339,452,565,678,791,904'},
    {   'id': 6571,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 34',
        'text': 'Площадь прямоугольника 3000 см². Ширина в 6 раз меньше длины. Найдите периметр.',
        'answer': '280 см'},
    {   'id': 6572,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 34',
        'text': 'Периметр прямоугольника 520 см. Длина в 18 раз больше ширины. Найдите площадь.',
        'answer': '11700 см²'},
    {   'id': 6573,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 44',
        'text': '41/42 - 39/40 + 37/38 = ?',
        'answer': '101/7980'},
    {   'id': 6574,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 42',
        'text': '27(24x - 25) - 25(25x - 26) = 23(26x - 27) - 22(25x - 26)',
        'answer': 'x = -16'},
    {   'id': 6575,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 32',
        'text': 'Найдите НОД(3780, 4320, 4860)',
        'answer': '540'},
    {   'id': 6576,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 32',
        'text': 'Найдите НОК(126, 140, 154)',
        'answer': '13860'},
    {   'id': 6577,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 33',
        'text': 'В двух бидонах 400 л молока. Если из первого перелить 80 л во второй, то в первом '
                'станет в 2 раза больше. Сколько в каждом?',
        'answer': '320 и 80'},
    {   'id': 6578,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 32',
        'text': 'Первый угол треугольника в 19 раз больше второго и на 170° больше третьего. '
                'Найдите углы.',
        'answer': '380°, 20°, 210°? нет решения'},
    {   'id': 6579,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 32',
        'text': 'Аквариум 150×80×60 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '540 л'},
    {   'id': 6580,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Размещения 12',
        'text': 'Сколько двенадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '239500800'},
    {   'id': 6581,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 45',
        'text': 'Число 1200 увеличили на 15%, потом результат уменьшили на 35%. Какое число '
                'получили?',
        'answer': '897'},
    {   'id': 6582,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 32',
        'text': 'Решите пропорцию: (28x-27)/5 = (30x+29)/6',
        'answer': 'x = -317/18'},
    {   'id': 6583,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 32',
        'text': 'Найдите все трехзначные числа, кратные 127.',
        'answer': '127,254,381,508,635,762,889'},
    {   'id': 6584,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 35',
        'text': 'Площадь прямоугольника 3200 см². Длина 80 см. Найдите периметр.',
        'answer': '240 см'},
    {   'id': 6585,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 35',
        'text': 'Периметр прямоугольника 540 см. Ширина в 9 раз меньше длины. Найдите площадь.',
        'answer': '11664 см²'},
    {   'id': 6586,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 45',
        'text': '43/44 - 41/42 + 39/40 = ?',
        'answer': '101/9240'},
    {   'id': 6587,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 43',
        'text': '28(25x - 26) - 26(26x - 27) = 24(27x - 28) - 23(26x - 27)',
        'answer': 'x = -17'},
    {   'id': 6588,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОД 33',
        'text': 'Найдите НОД(4032, 4608, 5184)',
        'answer': '576'},
    {   'id': 6589,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'НОК 33',
        'text': 'Найдите НОК(132, 144, 156)',
        'answer': '10296'},
    {   'id': 6590,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Задача 34',
        'text': 'Сумма трех чисел 900. Первое число в 14 раз больше второго, а третье на 260 '
                'больше первого. Найдите числа.',
        'answer': '560, 40, 300'},
    {   'id': 6591,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Углы 33',
        'text': 'Второй угол треугольника в 20 раз больше первого и на 180° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 400°, -240°? нет решения'},
    {   'id': 6592,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Объем 33',
        'text': 'Бассейн 50×25×4 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '3333.33 м³'},
    {   'id': 6593,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 5,
        'title': 'Сочетания 22',
        'text': 'Сколькими способами выбрать 12 из 55 и 11 из 50?',
        'answer': '1.25e+14'},
    {   'id': 6594,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Проценты 46',
        'text': 'Число увеличили на 90%, получили 380. Найдите исходное.',
        'answer': '200'},
    {   'id': 6595,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Пропорция 33',
        'text': 'Решите пропорцию: (29x-28)/4 = (31x+30)/5',
        'answer': 'x = -260/21'},
    {   'id': 6596,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 5,
        'title': 'Делимость 33',
        'text': 'Найдите все трехзначные числа, кратные 131.',
        'answer': '131,262,393,524,655,786,917'},
    {   'id': 6597,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Площадь 36',
        'text': 'Площадь прямоугольника 3400 см². Ширина в 5 раз меньше длины. Найдите периметр.',
        'answer': '340 см'},
    {   'id': 6598,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 5,
        'title': 'Периметр 36',
        'text': 'Периметр прямоугольника 560 см. Длина в 19 раз больше ширины. Найдите площадь.',
        'answer': '15200 см²'},
    {   'id': 6599,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Дроби 46',
        'text': '45/46 - 43/44 + 41/42 = ?',
        'answer': '101/10626'},
    {   'id': 6600,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 5,
        'title': 'Уравнение 44',
        'text': '29(26x - 27) - 27(27x - 28) = 25(28x - 29) - 24(27x - 28)',
        'answer': 'x = -18'},
    {   'id': 6601,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 34',
        'text': 'Решите пропорцию: (30x-29)/3 = (32x+31)/4',
        'answer': 'x = -203/24'},
    {   'id': 6602,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Масштаб 11',
        'text': 'На карте масштаба 1:2500000 расстояние 8 см. Сколько км на местности?',
        'answer': '200 км'},
    {   'id': 6603,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 34',
        'text': 'Найдите все числа вида 9x1y, которые делятся на 45.',
        'answer': '9315, 9810?'},
    {   'id': 6604,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 47',
        'text': 'Цена товара сначала повысилась на 70%, затем повысилась ещё на 80%. На сколько '
                'процентов повысилась цена?',
        'answer': '206%'},
    {   'id': 6605,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 37',
        'text': 'Площадь прямоугольника 3600 см². Длина в 6 раз больше ширины. Найдите периметр.',
        'answer': '280 см'},
    {   'id': 6606,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 37',
        'text': 'Периметр прямоугольника 580 см. Длина в 20 раз больше ширины. Найдите площадь.',
        'answer': '19000 см²'},
    {   'id': 6607,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Комбинаторика 7',
        'text': 'Сколько девятизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '387420489'},
    {   'id': 6608,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 47',
        'text': '47/48 - 45/46 + 43/44 = ?',
        'answer': '101/12144'},
    {   'id': 6609,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 45',
        'text': '30(27x - 28) - 28(28x - 29) = 26(29x - 30) - 25(28x - 29)',
        'answer': 'x = -19'},
    {   'id': 6610,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 34',
        'text': 'Найдите НОД(4284, 4896, 5508)',
        'answer': '612'},
    {   'id': 6611,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 34',
        'text': 'Найдите НОК(144, 156, 168)',
        'answer': '13104'},
    {   'id': 6612,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 35',
        'text': 'Сумма трех чисел 960. Первое число в 15 раз больше второго, а третье на 280 '
                'больше первого. Найдите числа.',
        'answer': '600, 40, 320'},
    {   'id': 6613,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 34',
        'text': 'Третий угол треугольника в 21 раз больше первого и на 190° больше второго. '
                'Найдите углы.',
        'answer': '20°, 210°, -50°? нет решения'},
    {   'id': 6614,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 34',
        'text': 'Куб с ребром 60 см распилили на кубики с ребром 10 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6615,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Сочетания 23',
        'text': 'Сколькими способами выбрать 12 из 50 и 11 из 45?',
        'answer': '1.25e+14'},
    {   'id': 6616,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 48',
        'text': 'Число уменьшили на 95%, получили 10. Найдите исходное.',
        'answer': '200'}]
