PROBLEMS_DB = [   {   'id': 6617,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 35',
        'text': 'Решите пропорцию: (31x-30)/5 = (33x+32)/6',
        'answer': 'x = -332/21'},
    {   'id': 6618,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 35',
        'text': 'Найдите все трехзначные числа, кратные 137.',
        'answer': '137,274,411,548,685,822,959'},
    {   'id': 6619,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 38',
        'text': 'Площадь прямоугольника 3800 см². Ширина в 5 раз меньше длины. Найдите периметр.',
        'answer': '360 см'},
    {   'id': 6620,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 38',
        'text': 'Периметр прямоугольника 600 см. Длина в 21 раз больше ширины. Найдите площадь.',
        'answer': '21000 см²'},
    {   'id': 6621,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 48',
        'text': '49/50 - 47/48 + 45/46 = ?',
        'answer': '101/13800'},
    {   'id': 6622,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 46',
        'text': '31(28x - 29) - 29(29x - 30) = 27(30x - 31) - 26(29x - 30)',
        'answer': 'x = -20'},
    {   'id': 6623,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 35',
        'text': 'Найдите НОД(4536, 5184, 5832)',
        'answer': '648'},
    {   'id': 6624,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 35',
        'text': 'Найдите НОК(150, 160, 170)',
        'answer': '40800'},
    {   'id': 6625,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 36',
        'text': 'В двух бидонах 480 л молока. Если из первого перелить 100 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '380 и 100'},
    {   'id': 6626,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 35',
        'text': 'Первый угол треугольника в 22 раза больше второго и на 200° больше третьего. '
                'Найдите углы.',
        'answer': '440°, 20°, 240°? нет решения'},
    {   'id': 6627,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 35',
        'text': 'Аквариум 180×80×60 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '648 л'},
    {   'id': 6628,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Размещения 13',
        'text': 'Сколько тринадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '6227020800'},
    {   'id': 6629,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 49',
        'text': 'Число 1400 увеличили на 10%, потом результат уменьшили на 40%. Какое число '
                'получили?',
        'answer': '924'},
    {   'id': 6630,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 36',
        'text': 'Решите пропорцию: (32x-31)/4 = (34x+33)/5',
        'answer': 'x = -287/22'},
    {   'id': 6631,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 36',
        'text': 'Найдите все трехзначные числа, кратные 139.',
        'answer': '139,278,417,556,695,834,973'},
    {   'id': 6632,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 39',
        'text': 'Площадь прямоугольника 4000 см². Длина 100 см. Найдите периметр.',
        'answer': '280 см'},
    {   'id': 6633,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 39',
        'text': 'Периметр прямоугольника 620 см. Ширина в 10 раз меньше длины. Найдите площадь.',
        'answer': '17600 см²'},
    {   'id': 6634,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 49',
        'text': '51/52 - 49/50 + 47/48 = ?',
        'answer': '101/15600'},
    {   'id': 6635,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 47',
        'text': '32(29x - 30) - 30(30x - 31) = 28(31x - 32) - 27(30x - 31)',
        'answer': 'x = -21'},
    {   'id': 6636,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 36',
        'text': 'Найдите НОД(4788, 5472, 6156)',
        'answer': '684'},
    {   'id': 6637,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 36',
        'text': 'Найдите НОК(156, 168, 180)',
        'answer': '16380'},
    {   'id': 6638,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 37',
        'text': 'Сумма трех чисел 1020. Первое число в 16 раз больше второго, а третье на 300 '
                'больше первого. Найдите числа.',
        'answer': '640, 40, 340'},
    {   'id': 6639,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 36',
        'text': 'Второй угол треугольника в 23 раза больше первого и на 210° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 460°, -300°? нет решения'},
    {   'id': 6640,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 36',
        'text': 'Бассейн 60×30×5 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '6000 м³'},
    {   'id': 6641,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Сочетания 24',
        'text': 'Сколькими способами выбрать 13 из 55 и 12 из 50?',
        'answer': '4.12e+14'},
    {   'id': 6642,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 50',
        'text': 'Число увеличили на 100%, получили 400. Найдите исходное.',
        'answer': '200'},
    {   'id': 6643,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 37',
        'text': 'Решите пропорцию: (33x-32)/5 = (35x+34)/6',
        'answer': 'x = -356/23'},
    {   'id': 6644,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 37',
        'text': 'Найдите все трехзначные числа, кратные 149.',
        'answer': '149,298,447,596,745,894'},
    {   'id': 6645,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 40',
        'text': 'Площадь прямоугольника 4200 см². Ширина в 7 раз меньше длины. Найдите периметр.',
        'answer': '400 см'},
    {   'id': 6646,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 40',
        'text': 'Периметр прямоугольника 640 см. Длина в 22 раза больше ширины. Найдите площадь.',
        'answer': '25600 см²'},
    {   'id': 6647,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 50',
        'text': '53/54 - 51/52 + 49/50 = ?',
        'answer': '101/17550'},
    {   'id': 6648,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 48',
        'text': '33(30x - 31) - 31(31x - 32) = 29(32x - 33) - 28(31x - 32)',
        'answer': 'x = -22'},
    {   'id': 6649,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 37',
        'text': 'Найдите НОД(5040, 5760, 6480)',
        'answer': '720'},
    {   'id': 6650,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 37',
        'text': 'Найдите НОК(162, 176, 190)',
        'answer': '1354320'},
    {   'id': 6651,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 38',
        'text': 'В двух корзинах 540 яблок. Если из первой переложить 120 яблок во вторую, то в '
                'первой станет в 2 раза больше. Сколько в каждой?',
        'answer': '440 и 100'},
    {   'id': 6652,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 37',
        'text': 'Третий угол треугольника в 24 раза больше первого и на 220° больше второго. '
                'Найдите углы.',
        'answer': '20°, 240°, -80°? нет решения'},
    {   'id': 6653,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 37',
        'text': 'Куб с ребром 66 см распилили на кубики с ребром 11 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6654,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Размещения 14',
        'text': 'Сколько четырнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '87178291200'},
    {   'id': 6655,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 51',
        'text': 'Число 1600 уменьшили на 20%, потом результат увеличили на 60%. Какое число '
                'получили?',
        'answer': '1792'},
    {   'id': 6656,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 38',
        'text': 'Решите пропорцию: (34x-33)/4 = (36x+35)/5',
        'answer': 'x = -305/24'},
    {   'id': 6657,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 38',
        'text': 'Найдите все трехзначные числа, кратные 151.',
        'answer': '151,302,453,604,755,906'},
    {   'id': 6658,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 41',
        'text': 'Площадь прямоугольника 4400 см². Длина 110 см. Найдите периметр.',
        'answer': '300 см'},
    {   'id': 6659,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 41',
        'text': 'Периметр прямоугольника 660 см. Ширина в 11 раз меньше длины. Найдите площадь.',
        'answer': '21780 см²'},
    {   'id': 6660,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 51',
        'text': '55/56 - 53/54 + 51/52 = ?',
        'answer': '101/19656'},
    {   'id': 6661,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 49',
        'text': '34(31x - 32) - 32(32x - 33) = 30(33x - 34) - 29(32x - 33)',
        'answer': 'x = -23'},
    {   'id': 6662,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 38',
        'text': 'Найдите НОД(5292, 6048, 6804)',
        'answer': '756'},
    {   'id': 6663,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 38',
        'text': 'Найдите НОК(168, 180, 192)',
        'answer': '20160'},
    {   'id': 6664,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 39',
        'text': 'Сумма трех чисел 1080. Первое число в 17 раз больше второго, а третье на 320 '
                'больше первого. Найдите числа.',
        'answer': '680, 40, 360'},
    {   'id': 6665,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 38',
        'text': 'Первый угол треугольника в 25 раз больше второго и на 230° больше третьего. '
                'Найдите углы.',
        'answer': '500°, 20°, 280°? нет решения'},
    {   'id': 6666,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 38',
        'text': 'Аквариум 200×100×80 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '1200 л'},
    {   'id': 6667,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Сочетания 25',
        'text': 'Сколькими способами выбрать 14 из 60 и 13 из 55?',
        'answer': '1.45e+15'},
    {   'id': 6668,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 52',
        'text': 'Число уменьшили на 90%, получили 20. Найдите исходное.',
        'answer': '200'},
    {   'id': 6669,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 39',
        'text': 'Решите пропорцию: (35x-34)/5 = (37x+36)/6',
        'answer': 'x = -392/25'},
    {   'id': 6670,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 39',
        'text': 'Найдите все трехзначные числа, кратные 157.',
        'answer': '157,314,471,628,785,942'},
    {   'id': 6671,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 42',
        'text': 'Площадь прямоугольника 4600 см². Ширина в 8 раз меньше длины. Найдите периметр.',
        'answer': '460 см'},
    {   'id': 6672,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 42',
        'text': 'Периметр прямоугольника 680 см. Длина в 23 раза больше ширины. Найдите площадь.',
        'answer': '29900 см²'},
    {   'id': 6673,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 52',
        'text': '57/58 - 55/56 + 53/54 = ?',
        'answer': '101/21924'},
    {   'id': 6674,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 50',
        'text': '35(32x - 33) - 33(33x - 34) = 31(34x - 35) - 30(33x - 34)',
        'answer': 'x = -24'},
    {   'id': 6675,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 39',
        'text': 'Найдите НОД(5544, 6336, 7128)',
        'answer': '792'},
    {   'id': 6676,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 39',
        'text': 'Найдите НОК(176, 190, 204)',
        'answer': '1705440'},
    {   'id': 6677,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 40',
        'text': 'В двух бидонах 600 л молока. Если из первого перелить 150 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '500 и 100'},
    {   'id': 6678,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 39',
        'text': 'Второй угол треугольника в 26 раз больше первого и на 240° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 520°, -360°? нет решения'},
    {   'id': 6679,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 39',
        'text': 'Бассейн 70×35×6 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '9800 м³'},
    {   'id': 6680,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Размещения 15',
        'text': 'Сколько пятнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '1307674368000'},
    {   'id': 6681,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 53',
        'text': 'Число 1800 увеличили на 15%, потом результат уменьшили на 45%. Какое число '
                'получили?',
        'answer': '1138.5'},
    {   'id': 6682,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 40',
        'text': 'Решите пропорцию: (36x-35)/4 = (38x+37)/5',
        'answer': 'x = -323/26'},
    {   'id': 6683,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 40',
        'text': 'Найдите все трехзначные числа, кратные 163.',
        'answer': '163,326,489,652,815,978'},
    {   'id': 6684,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 43',
        'text': 'Площадь прямоугольника 4800 см². Длина 120 см. Найдите периметр.',
        'answer': '320 см'},
    {   'id': 6685,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 43',
        'text': 'Периметр прямоугольника 700 см. Ширина в 12 раз меньше длины. Найдите площадь.',
        'answer': '30000 см²'},
    {   'id': 6686,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 53',
        'text': '59/60 - 57/58 + 55/56 = ?',
        'answer': '101/24360'},
    {   'id': 6687,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 51',
        'text': '36(33x - 34) - 34(34x - 35) = 32(35x - 36) - 31(34x - 35)',
        'answer': 'x = -25'},
    {   'id': 6688,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОД 40',
        'text': 'Найдите НОД(5796, 6624, 7452)',
        'answer': '828'},
    {   'id': 6689,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'НОК 40',
        'text': 'Найдите НОК(180, 192, 204)',
        'answer': '195840'},
    {   'id': 6690,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Задача 41',
        'text': 'Сумма трех чисел 1140. Первое число в 18 раз больше второго, а третье на 340 '
                'больше первого. Найдите числа.',
        'answer': '720, 40, 380'},
    {   'id': 6691,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Углы 40',
        'text': 'Третий угол треугольника в 27 раз больше первого и на 250° больше второго. '
                'Найдите углы.',
        'answer': '20°, 260°, -100°? нет решения'},
    {   'id': 6692,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Объем 40',
        'text': 'Куб с ребром 72 см распилили на кубики с ребром 12 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6693,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 6,
        'title': 'Сочетания 26',
        'text': 'Сколькими способами выбрать 15 из 65 и 14 из 60?',
        'answer': '5.67e+15'},
    {   'id': 6694,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Проценты 54',
        'text': 'Число увеличили на 120%, получили 440. Найдите исходное.',
        'answer': '200'},
    {   'id': 6695,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Пропорция 41',
        'text': 'Решите пропорцию: (37x-36)/5 = (39x+38)/6',
        'answer': 'x = -428/27'},
    {   'id': 6696,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 6,
        'title': 'Делимость 41',
        'text': 'Найдите все трехзначные числа, кратные 167.',
        'answer': '167,334,501,668,835'},
    {   'id': 6697,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Площадь 44',
        'text': 'Площадь прямоугольника 5000 см². Ширина в 9 раз меньше длины. Найдите периметр.',
        'answer': '500 см'},
    {   'id': 6698,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 6,
        'title': 'Периметр 44',
        'text': 'Периметр прямоугольника 720 см. Длина в 24 раза больше ширины. Найдите площадь.',
        'answer': '34560 см²'},
    {   'id': 6699,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Дроби 54',
        'text': '61/62 - 59/60 + 57/58 = ?',
        'answer': '101/26970'},
    {   'id': 6700,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 6,
        'title': 'Уравнение 52',
        'text': '37(34x - 35) - 35(35x - 36) = 33(36x - 37) - 32(35x - 36)',
        'answer': 'x = -26'},
    {   'id': 6701,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 42',
        'text': 'Решите пропорцию: (38x-37)/3 = (40x+39)/4',
        'answer': 'x = -255/28'},
    {   'id': 6702,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Масштаб 12',
        'text': 'На карте масштаба 1:3000000 расстояние 9 см. Сколько км на местности?',
        'answer': '270 км'},
    {   'id': 6703,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 42',
        'text': 'Найдите все числа вида 2x3y, которые делятся на 72.',
        'answer': '2232, 2736?'},
    {   'id': 6704,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 55',
        'text': 'Цена товара сначала повысилась на 80%, затем повысилась ещё на 90%. На сколько '
                'процентов повысилась цена?',
        'answer': '242%'},
    {   'id': 6705,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 45',
        'text': 'Площадь прямоугольника 5200 см². Длина в 8 раз больше ширины. Найдите периметр.',
        'answer': '520 см'},
    {   'id': 6706,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 45',
        'text': 'Периметр прямоугольника 740 см. Длина в 25 раз больше ширины. Найдите площадь.',
        'answer': '39062.5 см²'},
    {   'id': 6707,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Комбинаторика 8',
        'text': 'Сколько десятизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '3486784401'},
    {   'id': 6708,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 55',
        'text': '63/64 - 61/62 + 59/60 = ?',
        'answer': '101/29760'},
    {   'id': 6709,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 53',
        'text': '38(35x - 36) - 36(36x - 37) = 34(37x - 38) - 33(36x - 37)',
        'answer': 'x = -27'},
    {   'id': 6710,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 41',
        'text': 'Найдите НОД(6048, 6912, 7776)',
        'answer': '864'},
    {   'id': 6711,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 41',
        'text': 'Найдите НОК(190, 204, 218)',
        'answer': '10519620'},
    {   'id': 6712,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 42',
        'text': 'Сумма трех чисел 1200. Первое число в 19 раз больше второго, а третье на 360 '
                'больше первого. Найдите числа.',
        'answer': '760, 40, 400'},
    {   'id': 6713,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 41',
        'text': 'Первый угол треугольника в 28 раз больше второго и на 250° больше третьего. '
                'Найдите углы.',
        'answer': '560°, 20°, 310°? нет решения'},
    {   'id': 6714,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 41',
        'text': 'Куб с ребром 78 см распилили на кубики с ребром 13 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6715,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Сочетания 27',
        'text': 'Сколькими способами выбрать 16 из 70 и 15 из 65?',
        'answer': '2.34e+16'},
    {   'id': 6716,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 56',
        'text': 'Число уменьшили на 92%, получили 16. Найдите исходное.',
        'answer': '200'},
    {   'id': 6717,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 43',
        'text': 'Решите пропорцию: (39x-38)/5 = (41x+40)/6',
        'answer': 'x = -452/29'},
    {   'id': 6718,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 43',
        'text': 'Найдите все трехзначные числа, кратные 173.',
        'answer': '173,346,519,692,865'},
    {   'id': 6719,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 46',
        'text': 'Площадь прямоугольника 5400 см². Ширина в 10 раз меньше длины. Найдите периметр.',
        'answer': '580 см'},
    {   'id': 6720,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 46',
        'text': 'Периметр прямоугольника 760 см. Длина в 26 раз больше ширины. Найдите площадь.',
        'answer': '43350 см²'},
    {   'id': 6721,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 56',
        'text': '65/66 - 63/64 + 61/62 = ?',
        'answer': '101/32736'},
    {   'id': 6722,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 54',
        'text': '39(36x - 37) - 37(37x - 38) = 35(38x - 39) - 34(37x - 38)',
        'answer': 'x = -28'},
    {   'id': 6723,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 42',
        'text': 'Найдите НОД(6300, 7200, 8100)',
        'answer': '900'},
    {   'id': 6724,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 42',
        'text': 'Найдите НОК(192, 204, 216)',
        'answer': '44064'},
    {   'id': 6725,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 43',
        'text': 'В двух бидонах 660 л молока. Если из первого перелить 180 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '560 и 100'},
    {   'id': 6726,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 42',
        'text': 'Второй угол треугольника в 29 раз больше первого и на 260° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 580°, -420°? нет решения'},
    {   'id': 6727,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 42',
        'text': 'Аквариум 220×100×80 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '1320 л'},
    {   'id': 6728,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Размещения 16',
        'text': 'Сколько шестнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '20922789888000'},
    {   'id': 6729,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 57',
        'text': 'Число 2000 увеличили на 12%, потом результат уменьшили на 48%. Какое число '
                'получили?',
        'answer': '1164.8'},
    {   'id': 6730,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 44',
        'text': 'Решите пропорцию: (40x-39)/4 = (42x+41)/5',
        'answer': 'x = -359/30'},
    {   'id': 6731,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 44',
        'text': 'Найдите все трехзначные числа, кратные 179.',
        'answer': '179,358,537,716,895'},
    {   'id': 6732,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 47',
        'text': 'Площадь прямоугольника 5600 см². Длина 140 см. Найдите периметр.',
        'answer': '360 см'},
    {   'id': 6733,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 47',
        'text': 'Периметр прямоугольника 780 см. Ширина в 13 раз меньше длины. Найдите площадь.',
        'answer': '38000 см²'},
    {   'id': 6734,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 57',
        'text': '67/68 - 65/66 + 63/64 = ?',
        'answer': '101/35904'},
    {   'id': 6735,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 55',
        'text': '40(37x - 38) - 38(38x - 39) = 36(39x - 40) - 35(38x - 39)',
        'answer': 'x = -29'},
    {   'id': 6736,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 43',
        'text': 'Найдите НОД(6552, 7488, 8424)',
        'answer': '936'},
    {   'id': 6737,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 43',
        'text': 'Найдите НОК(204, 216, 228)',
        'answer': '87768'},
    {   'id': 6738,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 44',
        'text': 'Сумма трех чисел 1260. Первое число в 20 раз больше второго, а третье на 380 '
                'больше первого. Найдите числа.',
        'answer': '800, 40, 420'},
    {   'id': 6739,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 43',
        'text': 'Третий угол треугольника в 30 раз больше первого и на 270° больше второго. '
                'Найдите углы.',
        'answer': '20°, 300°, -140°? нет решения'},
    {   'id': 6740,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 43',
        'text': 'Бассейн 80×40×6 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '12800 м³'},
    {   'id': 6741,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Сочетания 28',
        'text': 'Сколькими способами выбрать 17 из 75 и 16 из 70?',
        'answer': '1.02e+17'},
    {   'id': 6742,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 58',
        'text': 'Число увеличили на 140%, получили 480. Найдите исходное.',
        'answer': '200'},
    {   'id': 6743,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 45',
        'text': 'Решите пропорцию: (41x-40)/5 = (43x+42)/6',
        'answer': 'x = -488/31'},
    {   'id': 6744,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 45',
        'text': 'Найдите все трехзначные числа, кратные 181.',
        'answer': '181,362,543,724,905'},
    {   'id': 6745,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 48',
        'text': 'Площадь прямоугольника 5800 см². Ширина в 12 раз меньше длины. Найдите периметр.',
        'answer': '680 см'},
    {   'id': 6746,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 48',
        'text': 'Периметр прямоугольника 800 см. Длина в 27 раз больше ширины. Найдите площадь.',
        'answer': '47600 см²'},
    {   'id': 6747,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 58',
        'text': '69/70 - 67/68 + 65/66 = ?',
        'answer': '101/39270'},
    {   'id': 6748,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 56',
        'text': '41(38x - 39) - 39(39x - 40) = 37(40x - 41) - 36(39x - 40)',
        'answer': 'x = -30'},
    {   'id': 6749,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 44',
        'text': 'Найдите НОД(6804, 7776, 8748)',
        'answer': '972'},
    {   'id': 6750,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 44',
        'text': 'Найдите НОК(216, 228, 240)',
        'answer': '41040'},
    {   'id': 6751,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 45',
        'text': 'В двух корзинах 720 яблок. Если из первой переложить 200 яблок во вторую, то в '
                'первой станет в 2 раза больше. Сколько в каждой?',
        'answer': '613.33 и 106.67? нет'},
    {   'id': 6752,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 44',
        'text': 'Первый угол треугольника в 31 раз больше второго и на 280° больше третьего. '
                'Найдите углы.',
        'answer': '620°, 20°, 360°? нет решения'},
    {   'id': 6753,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 44',
        'text': 'Куб с ребром 84 см распилили на кубики с ребром 14 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6754,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Размещения 17',
        'text': 'Сколько семнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '355687428096000'},
    {   'id': 6755,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 59',
        'text': 'Число 2200 уменьшили на 18%, потом результат увеличили на 55%. Какое число '
                'получили?',
        'answer': '1681.9'},
    {   'id': 6756,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 46',
        'text': 'Решите пропорцию: (42x-41)/4 = (44x+43)/5',
        'answer': 'x = -395/32'},
    {   'id': 6757,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 46',
        'text': 'Найдите все трехзначные числа, кратные 191.',
        'answer': '191,382,573,764,955'},
    {   'id': 6758,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 49',
        'text': 'Площадь прямоугольника 6000 см². Длина 150 см. Найдите периметр.',
        'answer': '380 см'},
    {   'id': 6759,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 49',
        'text': 'Периметр прямоугольника 820 см. Ширина в 14 раз меньше длины. Найдите площадь.',
        'answer': '46410 см²'},
    {   'id': 6760,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 59',
        'text': '71/72 - 69/70 + 67/68 = ?',
        'answer': '101/42840'},
    {   'id': 6761,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 57',
        'text': '42(39x - 40) - 40(40x - 41) = 38(41x - 42) - 37(40x - 41)',
        'answer': 'x = -31'},
    {   'id': 6762,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 45',
        'text': 'Найдите НОД(7056, 8064, 9072)',
        'answer': '1008'},
    {   'id': 6763,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 45',
        'text': 'Найдите НОК(228, 240, 252)',
        'answer': '95760'},
    {   'id': 6764,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 46',
        'text': 'Сумма трех чисел 1320. Первое число в 21 раз больше второго, а третье на 400 '
                'больше первого. Найдите числа.',
        'answer': '840, 40, 440'},
    {   'id': 6765,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 45',
        'text': 'Второй угол треугольника в 32 раза больше первого и на 290° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 640°, -480°? нет решения'},
    {   'id': 6766,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 45',
        'text': 'Аквариум 240×120×100 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '2160 л'},
    {   'id': 6767,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Сочетания 29',
        'text': 'Сколькими способами выбрать 18 из 80 и 17 из 75?',
        'answer': '4.76e+17'},
    {   'id': 6768,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 60',
        'text': 'Число уменьшили на 94%, получили 12. Найдите исходное.',
        'answer': '200'},
    {   'id': 6769,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 47',
        'text': 'Решите пропорцию: (43x-42)/5 = (45x+44)/6',
        'answer': 'x = -524/33'},
    {   'id': 6770,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 47',
        'text': 'Найдите все трехзначные числа, кратные 193.',
        'answer': '193,386,579,772,965'},
    {   'id': 6771,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 50',
        'text': 'Площадь прямоугольника 6200 см². Ширина в 13 раз меньше длины. Найдите периметр.',
        'answer': '760 см'},
    {   'id': 6772,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 50',
        'text': 'Периметр прямоугольника 840 см. Длина в 28 раз больше ширины. Найдите площадь.',
        'answer': '55125 см²'},
    {   'id': 6773,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 60',
        'text': '73/74 - 71/72 + 69/70 = ?',
        'answer': '101/46620'},
    {   'id': 6774,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 58',
        'text': '43(40x - 41) - 41(41x - 42) = 39(42x - 43) - 38(41x - 42)',
        'answer': 'x = -32'},
    {   'id': 6775,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 46',
        'text': 'Найдите НОД(7308, 8352, 9396)',
        'answer': '1044'},
    {   'id': 6776,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 46',
        'text': 'Найдите НОК(240, 252, 264)',
        'answer': '110880'},
    {   'id': 6777,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 47',
        'text': 'В двух бидонах 780 л молока. Если из первого перелить 220 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '660 и 120'},
    {   'id': 6778,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 46',
        'text': 'Третий угол треугольника в 33 раза больше первого и на 300° больше второго. '
                'Найдите углы.',
        'answer': '20°, 340°, -180°? нет решения'},
    {   'id': 6779,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 46',
        'text': 'Бассейн 90×45×7 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '18900 м³'},
    {   'id': 6780,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Размещения 18',
        'text': 'Сколько восемнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '6402373705728000'},
    {   'id': 6781,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 61',
        'text': 'Число 2400 увеличили на 14%, потом результат уменьшили на 52%. Какое число '
                'получили?',
        'answer': '1297.92'},
    {   'id': 6782,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 48',
        'text': 'Решите пропорцию: (44x-43)/4 = (46x+45)/5',
        'answer': 'x = -431/34'},
    {   'id': 6783,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 48',
        'text': 'Найдите все трехзначные числа, кратные 197.',
        'answer': '197,394,591,788,985'},
    {   'id': 6784,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 51',
        'text': 'Площадь прямоугольника 6400 см². Длина 160 см. Найдите периметр.',
        'answer': '400 см'},
    {   'id': 6785,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 51',
        'text': 'Периметр прямоугольника 860 см. Ширина в 15 раз меньше длины. Найдите площадь.',
        'answer': '54740 см²'},
    {   'id': 6786,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 61',
        'text': '75/76 - 73/74 + 71/72 = ?',
        'answer': '101/50616'},
    {   'id': 6787,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 59',
        'text': '44(41x - 42) - 42(42x - 43) = 40(43x - 44) - 39(42x - 43)',
        'answer': 'x = -33'},
    {   'id': 6788,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОД 47',
        'text': 'Найдите НОД(7560, 8640, 9720)',
        'answer': '1080'},
    {   'id': 6789,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'НОК 47',
        'text': 'Найдите НОК(252, 264, 276)',
        'answer': '127512'},
    {   'id': 6790,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Задача 48',
        'text': 'Сумма трех чисел 1380. Первое число в 22 раза больше второго, а третье на 420 '
                'больше первого. Найдите числа.',
        'answer': '880, 40, 460'},
    {   'id': 6791,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Углы 47',
        'text': 'Первый угол треугольника в 34 раза больше второго и на 310° больше третьего. '
                'Найдите углы.',
        'answer': '680°, 20°, 370°? нет решения'},
    {   'id': 6792,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Объем 47',
        'text': 'Куб с ребром 90 см распилили на кубики с ребром 15 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6793,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 7,
        'title': 'Сочетания 30',
        'text': 'Сколькими способами выбрать 19 из 85 и 18 из 80?',
        'answer': '2.36e+18'},
    {   'id': 6794,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Проценты 62',
        'text': 'Число увеличили на 160%, получили 520. Найдите исходное.',
        'answer': '200'},
    {   'id': 6795,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Пропорция 49',
        'text': 'Решите пропорцию: (45x-44)/5 = (47x+46)/6',
        'answer': 'x = -560/35 = -16'},
    {   'id': 6796,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 7,
        'title': 'Делимость 49',
        'text': 'Найдите все трехзначные числа, кратные 199.',
        'answer': '199,398,597,796,995'},
    {   'id': 6797,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Площадь 52',
        'text': 'Площадь прямоугольника 6600 см². Ширина в 14 раз меньше длины. Найдите периметр.',
        'answer': '860 см'},
    {   'id': 6798,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 7,
        'title': 'Периметр 52',
        'text': 'Периметр прямоугольника 880 см. Длина в 29 раз больше ширины. Найдите площадь.',
        'answer': '63800 см²'},
    {   'id': 6799,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Дроби 62',
        'text': '77/78 - 75/76 + 73/74 = ?',
        'answer': '101/54834'},
    {   'id': 6800,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 7,
        'title': 'Уравнение 60',
        'text': '45(42x - 43) - 43(43x - 44) = 41(44x - 45) - 40(43x - 44)',
        'answer': 'x = -34'},
    {   'id': 6801,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 50',
        'text': 'Решите пропорцию: (46x-45)/3 = (48x+47)/4',
        'answer': 'x = -303/32'},
    {   'id': 6802,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Масштаб 13',
        'text': 'На карте масштаба 1:3500000 расстояние 10 см. Сколько км на местности?',
        'answer': '350 км'},
    {   'id': 6803,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 50',
        'text': 'Найдите все числа вида 3x4y, которые делятся на 45.',
        'answer': '3240, 3645, 3840?'},
    {   'id': 6804,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 63',
        'text': 'Цена товара сначала повысилась на 90%, затем повысилась ещё на 100%. На сколько '
                'процентов повысилась цена?',
        'answer': '280%'},
    {   'id': 6805,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 53',
        'text': 'Площадь прямоугольника 6800 см². Длина в 9 раз больше ширины. Найдите периметр.',
        'answer': '680 см'},
    {   'id': 6806,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 53',
        'text': 'Периметр прямоугольника 900 см. Длина в 30 раз больше ширины. Найдите площадь.',
        'answer': '67500 см²'},
    {   'id': 6807,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Комбинаторика 9',
        'text': 'Сколько одиннадцатизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '31381059609'},
    {   'id': 6808,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 63',
        'text': '79/80 - 77/78 + 75/76 = ?',
        'answer': '101/59280'},
    {   'id': 6809,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 61',
        'text': '46(43x - 44) - 44(44x - 45) = 42(45x - 46) - 41(44x - 45)',
        'answer': 'x = -35'},
    {   'id': 6810,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 48',
        'text': 'Найдите НОД(7812, 8928, 10044)',
        'answer': '1116'},
    {   'id': 6811,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 48',
        'text': 'Найдите НОК(264, 276, 288)',
        'answer': '145728'},
    {   'id': 6812,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 49',
        'text': 'Сумма трех чисел 1440. Первое число в 23 раза больше второго, а третье на 440 '
                'больше первого. Найдите числа.',
        'answer': '920, 40, 480'},
    {   'id': 6813,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 48',
        'text': 'Второй угол треугольника в 35 раз больше первого и на 320° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 700°, -540°? нет решения'},
    {   'id': 6814,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 48',
        'text': 'Куб с ребром 96 см распилили на кубики с ребром 16 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6815,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Сочетания 31',
        'text': 'Сколькими способами выбрать 20 из 90 и 19 из 85?',
        'answer': '1.17e+19'},
    {   'id': 6816,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 64',
        'text': 'Число уменьшили на 96%, получили 8. Найдите исходное.',
        'answer': '200'},
    {   'id': 6817,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 51',
        'text': 'Решите пропорцию: (47x-46)/5 = (49x+48)/6',
        'answer': 'x = -596/37'},
    {   'id': 6818,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 51',
        'text': 'Найдите все трехзначные числа, кратные 211.',
        'answer': '211,422,633,844'},
    {   'id': 6819,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 54',
        'text': 'Площадь прямоугольника 7000 см². Ширина в 15 раз меньше длины. Найдите периметр.',
        'answer': '920 см'},
    {   'id': 6820,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 54',
        'text': 'Периметр прямоугольника 920 см. Длина в 31 раз больше ширины. Найдите площадь.',
        'answer': '71400 см²'},
    {   'id': 6821,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 64',
        'text': '81/82 - 79/80 + 77/78 = ?',
        'answer': '101/63960'},
    {   'id': 6822,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 62',
        'text': '47(44x - 45) - 45(45x - 46) = 43(46x - 47) - 42(45x - 46)',
        'answer': 'x = -36'},
    {   'id': 6823,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 49',
        'text': 'Найдите НОД(8064, 9216, 10368)',
        'answer': '1152'},
    {   'id': 6824,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 49',
        'text': 'Найдите НОК(276, 288, 300)',
        'answer': '165600'},
    {   'id': 6825,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 50',
        'text': 'В двух бидонах 840 л молока. Если из первого перелить 240 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '720 и 120'},
    {   'id': 6826,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 49',
        'text': 'Третий угол треугольника в 36 раз больше первого и на 330° больше второго. '
                'Найдите углы.',
        'answer': '20°, 370°, -210°? нет решения'},
    {   'id': 6827,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 49',
        'text': 'Аквариум 260×130×100 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '2535 л'},
    {   'id': 6828,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Размещения 19',
        'text': 'Сколько девятнадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '121645100408832000'},
    {   'id': 6829,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 65',
        'text': 'Число 2600 увеличили на 16%, потом результат уменьшили на 54%. Какое число '
                'получили?',
        'answer': '1449.44'},
    {   'id': 6830,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 52',
        'text': 'Решите пропорцию: (48x-47)/4 = (50x+49)/5',
        'answer': 'x = -467/36'},
    {   'id': 6831,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 52',
        'text': 'Найдите все трехзначные числа, кратные 223.',
        'answer': '223,446,669,892'},
    {   'id': 6832,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 55',
        'text': 'Площадь прямоугольника 7200 см². Длина 180 см. Найдите периметр.',
        'answer': '440 см'},
    {   'id': 6833,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 55',
        'text': 'Периметр прямоугольника 940 см. Ширина в 16 раз меньше длины. Найдите площадь.',
        'answer': '76076 см²'},
    {   'id': 6834,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 65',
        'text': '83/84 - 81/82 + 79/80 = ?',
        'answer': '101/68880'},
    {   'id': 6835,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 63',
        'text': '48(45x - 46) - 46(46x - 47) = 44(47x - 48) - 43(46x - 47)',
        'answer': 'x = -37'},
    {   'id': 6836,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 50',
        'text': 'Найдите НОД(8316, 9504, 10692)',
        'answer': '1188'},
    {   'id': 6837,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 50',
        'text': 'Найдите НОК(288, 300, 312)',
        'answer': '187200'},
    {   'id': 6838,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 51',
        'text': 'Сумма трех чисел 1500. Первое число в 24 раза больше второго, а третье на 460 '
                'больше первого. Найдите числа.',
        'answer': '960, 40, 500'},
    {   'id': 6839,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 50',
        'text': 'Первый угол треугольника в 37 раз больше второго и на 340° больше третьего. '
                'Найдите углы.',
        'answer': '740°, 20°, 400°? нет решения'},
    {   'id': 6840,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 50',
        'text': 'Бассейн 100×50×8 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '26666.67 м³'},
    {   'id': 6841,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Сочетания 32',
        'text': 'Сколькими способами выбрать 21 из 95 и 20 из 90?',
        'answer': '6.15e+19'},
    {   'id': 6842,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 66',
        'text': 'Число увеличили на 180%, получили 560. Найдите исходное.',
        'answer': '200'},
    {   'id': 6843,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 53',
        'text': 'Решите пропорцию: (49x-48)/5 = (51x+50)/6',
        'answer': 'x = -632/39'},
    {   'id': 6844,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 53',
        'text': 'Найдите все трехзначные числа, кратные 227.',
        'answer': '227,454,681,908'},
    {   'id': 6845,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 56',
        'text': 'Площадь прямоугольника 7400 см². Ширина в 16 раз меньше длины. Найдите периметр.',
        'answer': '1020 см'},
    {   'id': 6846,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 56',
        'text': 'Периметр прямоугольника 960 см. Длина в 32 раза больше ширины. Найдите площадь.',
        'answer': '80850 см²'},
    {   'id': 6847,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 66',
        'text': '85/86 - 83/84 + 81/82 = ?',
        'answer': '101/74046'}]
