PROBLEMS_DB = [   {   'id': 6848,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 64',
        'text': '49(46x - 47) - 47(47x - 48) = 45(48x - 49) - 44(47x - 48)',
        'answer': 'x = -38'},
    {   'id': 6849,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 51',
        'text': 'Найдите НОД(8568, 9792, 11016)',
        'answer': '1224'},
    {   'id': 6850,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 51',
        'text': 'Найдите НОК(300, 312, 324)',
        'answer': '210600'},
    {   'id': 6851,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 52',
        'text': 'В двух корзинах 900 яблок. Если из первой переложить 260 яблок во вторую, то в '
                'первой станет в 2 раза больше. Сколько в каждой?',
        'answer': '773.33 и 126.67? нет'},
    {   'id': 6852,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 51',
        'text': 'Второй угол треугольника в 38 раз больше первого и на 350° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 760°, -600°? нет решения'},
    {   'id': 6853,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 51',
        'text': 'Куб с ребром 102 см распилили на кубики с ребром 17 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6854,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Размещения 20',
        'text': 'Сколько двадцатизначных чисел из цифр 0-9 без повторений?',
        'answer': '2294425328025600000'},
    {   'id': 6855,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 67',
        'text': 'Число 2800 уменьшили на 22%, потом результат увеличили на 58%. Какое число '
                'получили?',
        'answer': '2076.48'},
    {   'id': 6856,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 54',
        'text': 'Решите пропорцию: (50x-49)/4 = (52x+51)/5',
        'answer': 'x = -503/38'},
    {   'id': 6857,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 54',
        'text': 'Найдите все трехзначные числа, кратные 229.',
        'answer': '229,458,687,916'},
    {   'id': 6858,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 57',
        'text': 'Площадь прямоугольника 7600 см². Длина 190 см. Найдите периметр.',
        'answer': '460 см'},
    {   'id': 6859,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 57',
        'text': 'Периметр прямоугольника 980 см. Ширина в 17 раз меньше длины. Найдите площадь.',
        'answer': '87652 см²'},
    {   'id': 6860,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 67',
        'text': '87/88 - 85/86 + 83/84 = ?',
        'answer': '101/79464'},
    {   'id': 6861,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 65',
        'text': '50(47x - 48) - 48(48x - 49) = 46(49x - 50) - 45(48x - 49)',
        'answer': 'x = -39'},
    {   'id': 6862,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 52',
        'text': 'Найдите НОД(8820, 10080, 11340)',
        'answer': '1260'},
    {   'id': 6863,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 52',
        'text': 'Найдите НОК(312, 324, 336)',
        'answer': '235872'},
    {   'id': 6864,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 53',
        'text': 'Сумма трех чисел 1560. Первое число в 25 раз больше второго, а третье на 480 '
                'больше первого. Найдите числа.',
        'answer': '1000, 40, 520'},
    {   'id': 6865,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 52',
        'text': 'Третий угол треугольника в 39 раз больше первого и на 360° больше второго. '
                'Найдите углы.',
        'answer': '20°, 400°, -240°? нет решения'},
    {   'id': 6866,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 52',
        'text': 'Аквариум 280×140×120 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '3528 л'},
    {   'id': 6867,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Сочетания 33',
        'text': 'Сколькими способами выбрать 22 из 100 и 21 из 95?',
        'answer': '3.42e+20'},
    {   'id': 6868,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 68',
        'text': 'Число уменьшили на 97%, получили 6. Найдите исходное.',
        'answer': '200'},
    {   'id': 6869,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 55',
        'text': 'Решите пропорцию: (51x-50)/5 = (53x+52)/6',
        'answer': 'x = -668/41'},
    {   'id': 6870,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 55',
        'text': 'Найдите все трехзначные числа, кратные 233.',
        'answer': '233,466,699,932'},
    {   'id': 6871,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 58',
        'text': 'Площадь прямоугольника 7800 см². Ширина в 17 раз меньше длины. Найдите периметр.',
        'answer': '1100 см'},
    {   'id': 6872,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 58',
        'text': 'Периметр прямоугольника 1000 см. Длина в 33 раза больше ширины. Найдите площадь.',
        'answer': '93750 см²'},
    {   'id': 6873,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 68',
        'text': '89/90 - 87/88 + 85/86 = ?',
        'answer': '101/85140'},
    {   'id': 6874,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 66',
        'text': '51(48x - 49) - 49(49x - 50) = 47(50x - 51) - 46(49x - 50)',
        'answer': 'x = -40'},
    {   'id': 6875,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 53',
        'text': 'Найдите НОД(9072, 10368, 11664)',
        'answer': '1296'},
    {   'id': 6876,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 53',
        'text': 'Найдите НОК(324, 336, 348)',
        'answer': '263088'},
    {   'id': 6877,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 54',
        'text': 'В двух бидонах 960 л молока. Если из первого перелить 280 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '826.67 и 133.33? нет'},
    {   'id': 6878,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 53',
        'text': 'Первый угол треугольника в 40 раз больше второго и на 370° больше третьего. '
                'Найдите углы.',
        'answer': '800°, 20°, 430°? нет решения'},
    {   'id': 6879,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 53',
        'text': 'Бассейн 110×55×9 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '36300 м³'},
    {   'id': 6880,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Размещения 21',
        'text': 'Сколько двадцатиоднозначных чисел из цифр 0-9 без повторений?',
        'answer': '4.32e+19'},
    {   'id': 6881,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 69',
        'text': 'Число 3000 увеличили на 18%, потом результат уменьшили на 56%. Какое число '
                'получили?',
        'answer': '1677.6'},
    {   'id': 6882,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 56',
        'text': 'Решите пропорцию: (52x-51)/4 = (54x+53)/5',
        'answer': 'x = -539/40'},
    {   'id': 6883,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 56',
        'text': 'Найдите все трехзначные числа, кратные 239.',
        'answer': '239,478,717,956'},
    {   'id': 6884,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 59',
        'text': 'Площадь прямоугольника 8000 см². Длина 200 см. Найдите периметр.',
        'answer': '480 см'},
    {   'id': 6885,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 59',
        'text': 'Периметр прямоугольника 1020 см. Ширина в 18 раз меньше длины. Найдите площадь.',
        'answer': '100980 см²'},
    {   'id': 6886,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 69',
        'text': '91/92 - 89/90 + 87/88 = ?',
        'answer': '101/91080'},
    {   'id': 6887,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 67',
        'text': '52(49x - 50) - 50(50x - 51) = 48(51x - 52) - 47(50x - 51)',
        'answer': 'x = -41'},
    {   'id': 6888,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОД 54',
        'text': 'Найдите НОД(9324, 10656, 11988)',
        'answer': '1332'},
    {   'id': 6889,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'НОК 54',
        'text': 'Найдите НОК(336, 348, 360)',
        'answer': '292320'},
    {   'id': 6890,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Задача 55',
        'text': 'Сумма трех чисел 1620. Первое число в 26 раз больше второго, а третье на 500 '
                'больше первого. Найдите числа.',
        'answer': '1040, 40, 540'},
    {   'id': 6891,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Углы 54',
        'text': 'Второй угол треугольника в 41 раз больше первого и на 380° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 820°, -660°? нет решения'},
    {   'id': 6892,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Объем 54',
        'text': 'Куб с ребром 108 см распилили на кубики с ребром 18 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6893,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 8,
        'title': 'Сочетания 34',
        'text': 'Сколькими способами выбрать 23 из 105 и 22 из 100?',
        'answer': '2.03e+21'},
    {   'id': 6894,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Проценты 70',
        'text': 'Число увеличили на 200%, получили 600. Найдите исходное.',
        'answer': '200'},
    {   'id': 6895,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Пропорция 57',
        'text': 'Решите пропорцию: (53x-52)/5 = (55x+54)/6',
        'answer': 'x = -704/43'},
    {   'id': 6896,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 8,
        'title': 'Делимость 57',
        'text': 'Найдите все трехзначные числа, кратные 241.',
        'answer': '241,482,723,964'},
    {   'id': 6897,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Площадь 60',
        'text': 'Площадь прямоугольника 8200 см². Ширина в 18 раз меньше длины. Найдите периметр.',
        'answer': '1180 см'},
    {   'id': 6898,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 8,
        'title': 'Периметр 60',
        'text': 'Периметр прямоугольника 1040 см. Длина в 34 раза больше ширины. Найдите площадь.',
        'answer': '108800 см²'},
    {   'id': 6899,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Дроби 70',
        'text': '93/94 - 91/92 + 89/90 = ?',
        'answer': '101/97290'},
    {   'id': 6900,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 8,
        'title': 'Уравнение 68',
        'text': '53(50x - 51) - 51(51x - 52) = 49(52x - 53) - 48(51x - 52)',
        'answer': 'x = -42'},
    {   'id': 6901,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Пропорция 58',
        'text': 'Решите пропорцию: (54x-53)/3 = (56x+55)/4',
        'answer': 'x = -351/34'},
    {   'id': 6902,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Масштаб 14',
        'text': 'На карте масштаба 1:4000000 расстояние 12 см. Сколько км на местности?',
        'answer': '480 км'},
    {   'id': 6903,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'Делимость 58',
        'text': 'Найдите все числа вида 4x5y, которые делятся на 45.',
        'answer': '4455, 4950?'},
    {   'id': 6904,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Проценты 71',
        'text': 'Цена товара сначала повысилась на 100%, затем повысилась ещё на 110%. На сколько '
                'процентов повысилась цена?',
        'answer': '320%'},
    {   'id': 6905,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Площадь 61',
        'text': 'Площадь прямоугольника 8400 см². Длина в 10 раз больше ширины. Найдите периметр.',
        'answer': '840 см'},
    {   'id': 6906,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Периметр 61',
        'text': 'Периметр прямоугольника 1060 см. Длина в 35 раз больше ширины. Найдите площадь.',
        'answer': '117600 см²'},
    {   'id': 6907,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 9,
        'title': 'Комбинаторика 10',
        'text': 'Сколько двенадцатизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '282429536481'},
    {   'id': 6908,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Дроби 71',
        'text': '95/96 - 93/94 + 91/92 = ?',
        'answer': '101/103776'},
    {   'id': 6909,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Уравнение 69',
        'text': '54(51x - 52) - 52(52x - 53) = 50(53x - 54) - 49(52x - 53)',
        'answer': 'x = -43'},
    {   'id': 6910,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОД 55',
        'text': 'Найдите НОД(9576, 10944, 12312)',
        'answer': '1368'},
    {   'id': 6911,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОК 55',
        'text': 'Найдите НОК(348, 360, 372)',
        'answer': '323640'},
    {   'id': 6912,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Задача 56',
        'text': 'Сумма трех чисел 1680. Первое число в 27 раз больше второго, а третье на 520 '
                'больше первого. Найдите числа.',
        'answer': '1080, 40, 560'},
    {   'id': 6913,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Углы 55',
        'text': 'Третий угол треугольника в 42 раза больше первого и на 390° больше второго. '
                'Найдите углы.',
        'answer': '20°, 430°, -270°? нет решения'},
    {   'id': 6914,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Объем 55',
        'text': 'Куб с ребром 114 см распилили на кубики с ребром 19 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6915,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 9,
        'title': 'Сочетания 35',
        'text': 'Сколькими способами выбрать 24 из 110 и 23 из 105?',
        'answer': '1.28e+22'},
    {   'id': 6916,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Проценты 72',
        'text': 'Число уменьшили на 98%, получили 4. Найдите исходное.',
        'answer': '200'},
    {   'id': 6917,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Пропорция 59',
        'text': 'Решите пропорцию: (55x-54)/5 = (57x+56)/6',
        'answer': 'x = -740/45 = -16.44'},
    {   'id': 6918,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'Делимость 59',
        'text': 'Найдите все трехзначные числа, кратные 251.',
        'answer': '251,502,753'},
    {   'id': 6919,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Площадь 62',
        'text': 'Площадь прямоугольника 8600 см². Ширина в 19 раз меньше длины. Найдите периметр.',
        'answer': '1260 см'},
    {   'id': 6920,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Периметр 62',
        'text': 'Периметр прямоугольника 1080 см. Длина в 36 раз больше ширины. Найдите площадь.',
        'answer': '129600 см²'},
    {   'id': 6921,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Дроби 72',
        'text': '97/98 - 95/96 + 93/94 = ?',
        'answer': '101/110544'},
    {   'id': 6922,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Уравнение 70',
        'text': '55(52x - 53) - 53(53x - 54) = 51(54x - 55) - 50(53x - 54)',
        'answer': 'x = -44'},
    {   'id': 6923,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОД 56',
        'text': 'Найдите НОД(9828, 11232, 12636)',
        'answer': '1404'},
    {   'id': 6924,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОК 56',
        'text': 'Найдите НОК(360, 372, 384)',
        'answer': '356160'},
    {   'id': 6925,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Задача 57',
        'text': 'В двух бидонах 1020 л молока. Если из первого перелить 300 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '880 и 140'},
    {   'id': 6926,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Углы 56',
        'text': 'Первый угол треугольника в 43 раза больше второго и на 400° больше третьего. '
                'Найдите углы.',
        'answer': '860°, 20°, 440°? нет решения'},
    {   'id': 6927,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Объем 56',
        'text': 'Аквариум 300×150×120 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '4050 л'},
    {   'id': 6928,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 9,
        'title': 'Размещения 22',
        'text': 'Сколько двадцатидвухзначных чисел из цифр 0-9 без повторений?',
        'answer': '1.12e+21'},
    {   'id': 6929,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Проценты 73',
        'text': 'Число 3200 увеличили на 20%, потом результат уменьшили на 58%. Какое число '
                'получили?',
        'answer': '1814.4'},
    {   'id': 6930,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Пропорция 60',
        'text': 'Решите пропорцию: (56x-55)/4 = (58x+57)/5',
        'answer': 'x = -575/42'},
    {   'id': 6931,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'Делимость 60',
        'text': 'Найдите все трехзначные числа, кратные 257.',
        'answer': '257,514,771'},
    {   'id': 6932,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Площадь 63',
        'text': 'Площадь прямоугольника 8800 см². Длина 220 см. Найдите периметр.',
        'answer': '520 см'},
    {   'id': 6933,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Периметр 63',
        'text': 'Периметр прямоугольника 1100 см. Ширина в 19 раз меньше длины. Найдите площадь.',
        'answer': '120175 см²'},
    {   'id': 6934,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Дроби 73',
        'text': '99/100 - 97/98 + 95/96 = ?',
        'answer': '101/117600'},
    {   'id': 6935,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Уравнение 71',
        'text': '56(53x - 54) - 54(54x - 55) = 52(55x - 56) - 51(54x - 55)',
        'answer': 'x = -45'},
    {   'id': 6936,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОД 57',
        'text': 'Найдите НОД(10080, 11520, 12960)',
        'answer': '1440'},
    {   'id': 6937,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОК 57',
        'text': 'Найдите НОК(372, 384, 396)',
        'answer': '389376'},
    {   'id': 6938,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Задача 58',
        'text': 'Сумма трех чисел 1740. Первое число в 28 раз больше второго, а третье на 540 '
                'больше первого. Найдите числа.',
        'answer': '1120, 40, 580'},
    {   'id': 6939,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Углы 57',
        'text': 'Второй угол треугольника в 44 раза больше первого и на 410° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 880°, -720°? нет решения'},
    {   'id': 6940,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Объем 57',
        'text': 'Бассейн 120×60×10 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '48000 м³'},
    {   'id': 6941,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 9,
        'title': 'Сочетания 36',
        'text': 'Сколькими способами выбрать 25 из 115 и 24 из 110?',
        'answer': '8.57e+22'},
    {   'id': 6942,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Проценты 74',
        'text': 'Число увеличили на 220%, получили 640. Найдите исходное.',
        'answer': '200'},
    {   'id': 6943,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Пропорция 61',
        'text': 'Решите пропорцию: (57x-56)/5 = (59x+58)/6',
        'answer': 'x = -788/47'},
    {   'id': 6944,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'Делимость 61',
        'text': 'Найдите все трехзначные числа, кратные 263.',
        'answer': '263,526,789'},
    {   'id': 6945,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Площадь 64',
        'text': 'Площадь прямоугольника 9000 см². Ширина в 20 раз меньше длины. Найдите периметр.',
        'answer': '1380 см'},
    {   'id': 6946,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 9,
        'title': 'Периметр 64',
        'text': 'Периметр прямоугольника 1120 см. Длина в 37 раз больше ширины. Найдите площадь.',
        'answer': '147000 см²'},
    {   'id': 6947,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Дроби 74',
        'text': '101/102 - 99/100 + 97/98 = ?',
        'answer': '101/124950'},
    {   'id': 6948,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 9,
        'title': 'Уравнение 72',
        'text': '57(54x - 55) - 55(55x - 56) = 53(56x - 57) - 52(55x - 56)',
        'answer': 'x = -46'},
    {   'id': 6949,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОД 58',
        'text': 'Найдите НОД(10332, 11808, 13284)',
        'answer': '1476'},
    {   'id': 6950,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 9,
        'title': 'НОК 58',
        'text': 'Найдите НОК(384, 396, 408)',
        'answer': '424512'},
    {   'id': 6951,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Пропорция 62',
        'text': 'Решите пропорцию: (58x-57)/3 = (60x+59)/4',
        'answer': 'x = -399/38'},
    {   'id': 6952,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Масштаб 15',
        'text': 'На карте масштаба 1:4500000 расстояние 14 см. Сколько км на местности?',
        'answer': '630 км'},
    {   'id': 6953,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'Делимость 62',
        'text': 'Найдите все числа вида 5x6y, которые делятся на 45.',
        'answer': '5265, 5760?'},
    {   'id': 6954,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Проценты 75',
        'text': 'Цена товара сначала повысилась на 110%, затем повысилась ещё на 120%. На сколько '
                'процентов повысилась цена?',
        'answer': '362%'},
    {   'id': 6955,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Площадь 65',
        'text': 'Площадь прямоугольника 9200 см². Длина в 11 раз больше ширины. Найдите периметр.',
        'answer': '920 см'},
    {   'id': 6956,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Периметр 65',
        'text': 'Периметр прямоугольника 1140 см. Длина в 38 раз больше ширины. Найдите площадь.',
        'answer': '158400 см²'},
    {   'id': 6957,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 10,
        'title': 'Комбинаторика 11',
        'text': 'Сколько тринадцатизначных чисел можно составить из цифр 1-9, если цифры могут '
                'повторяться?',
        'answer': '2541865828329'},
    {   'id': 6958,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Дроби 75',
        'text': '103/104 - 101/102 + 99/100 = ?',
        'answer': '101/132600'},
    {   'id': 6959,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Уравнение 73',
        'text': '58(55x - 56) - 56(56x - 57) = 54(57x - 58) - 53(56x - 57)',
        'answer': 'x = -47'},
    {   'id': 6960,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОД 59',
        'text': 'Найдите НОД(10584, 12096, 13608)',
        'answer': '1512'},
    {   'id': 6961,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОК 59',
        'text': 'Найдите НОК(396, 408, 420)',
        'answer': '458640'},
    {   'id': 6962,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Задача 59',
        'text': 'Сумма трех чисел 1800. Первое число в 29 раз больше второго, а третье на 560 '
                'больше первого. Найдите числа.',
        'answer': '1160, 40, 600'},
    {   'id': 6963,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Углы 58',
        'text': 'Третий угол треугольника в 45 раз больше первого и на 420° больше второго. '
                'Найдите углы.',
        'answer': '20°, 460°, -300°? нет решения'},
    {   'id': 6964,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Объем 58',
        'text': 'Куб с ребром 120 см распилили на кубики с ребром 20 см. Сколько кубиков получили?',
        'answer': '216'},
    {   'id': 6965,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 10,
        'title': 'Сочетания 37',
        'text': 'Сколькими способами выбрать 26 из 120 и 25 из 115?',
        'answer': '6.09e+23'},
    {   'id': 6966,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Проценты 76',
        'text': 'Число уменьшили на 99%, получили 2. Найдите исходное.',
        'answer': '200'},
    {   'id': 6967,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Пропорция 63',
        'text': 'Решите пропорцию: (59x-58)/5 = (61x+60)/6',
        'answer': 'x = -836/49'},
    {   'id': 6968,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'Делимость 63',
        'text': 'Найдите все трехзначные числа, кратные 269.',
        'answer': '269,538,807'},
    {   'id': 6969,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Площадь 66',
        'text': 'Площадь прямоугольника 9400 см². Ширина в 21 раз меньше длины. Найдите периметр.',
        'answer': '1460 см'},
    {   'id': 6970,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Периметр 66',
        'text': 'Периметр прямоугольника 1160 см. Длина в 39 раз больше ширины. Найдите площадь.',
        'answer': '171600 см²'},
    {   'id': 6971,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Дроби 76',
        'text': '105/106 - 103/104 + 101/102 = ?',
        'answer': '101/140556'},
    {   'id': 6972,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Уравнение 74',
        'text': '59(56x - 57) - 57(57x - 58) = 55(58x - 59) - 54(57x - 58)',
        'answer': 'x = -48'},
    {   'id': 6973,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОД 60',
        'text': 'Найдите НОД(10836, 12384, 13932)',
        'answer': '1548'},
    {   'id': 6974,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОК 60',
        'text': 'Найдите НОК(408, 420, 432)',
        'answer': '493920'},
    {   'id': 6975,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Задача 60',
        'text': 'В двух бидонах 1080 л молока. Если из первого перелить 320 л во второй, то в '
                'первом станет в 2 раза больше. Сколько в каждом?',
        'answer': '933.33 и 146.67? нет'},
    {   'id': 6976,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Углы 59',
        'text': 'Первый угол треугольника в 46 раз больше второго и на 430° больше третьего. '
                'Найдите углы.',
        'answer': '920°, 20°, 470°? нет решения'},
    {   'id': 6977,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Объем 59',
        'text': 'Аквариум 320×160×140 см заполнен водой на 3/4. Сколько литров воды?',
        'answer': '5376 л'},
    {   'id': 6978,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 10,
        'title': 'Размещения 23',
        'text': 'Сколько двадцатитрехзначных чисел из цифр 0-9 без повторений?',
        'answer': '2.58e+22'},
    {   'id': 6979,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Проценты 77',
        'text': 'Число 3400 увеличили на 22%, потом результат уменьшили на 60%. Какое число '
                'получили?',
        'answer': '1958.4'},
    {   'id': 6980,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Пропорция 64',
        'text': 'Решите пропорцию: (60x-59)/4 = (62x+61)/5',
        'answer': 'x = -611/44'},
    {   'id': 6981,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'Делимость 64',
        'text': 'Найдите все трехзначные числа, кратные 271.',
        'answer': '271,542,813'},
    {   'id': 6982,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Площадь 67',
        'text': 'Площадь прямоугольника 9600 см². Длина 240 см. Найдите периметр.',
        'answer': '560 см'},
    {   'id': 6983,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Периметр 67',
        'text': 'Периметр прямоугольника 1180 см. Ширина в 20 раз меньше длины. Найдите площадь.',
        'answer': '167200 см²'},
    {   'id': 6984,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Дроби 77',
        'text': '107/108 - 105/106 + 103/104 = ?',
        'answer': '101/148824'},
    {   'id': 6985,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Уравнение 75',
        'text': '60(57x - 58) - 58(58x - 59) = 56(59x - 60) - 55(58x - 59)',
        'answer': 'x = -49'},
    {   'id': 6986,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОД 61',
        'text': 'Найдите НОД(11088, 12672, 14256)',
        'answer': '1584'},
    {   'id': 6987,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОК 61',
        'text': 'Найдите НОК(420, 432, 444)',
        'answer': '529200'},
    {   'id': 6988,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Задача 61',
        'text': 'Сумма трех чисел 1860. Первое число в 30 раз больше второго, а третье на 580 '
                'больше первого. Найдите числа.',
        'answer': '1200, 40, 620'},
    {   'id': 6989,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Углы 60',
        'text': 'Второй угол треугольника в 47 раз больше первого и на 440° больше третьего. '
                'Найдите углы.',
        'answer': '20°, 940°, -780°? нет решения'},
    {   'id': 6990,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Объем 60',
        'text': 'Бассейн 130×65×11 м заполнен водой на 2/3. Сколько кубометров воды?',
        'answer': '61966.67 м³'},
    {   'id': 6991,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 10,
        'title': 'Сочетания 38',
        'text': 'Сколькими способами выбрать 27 из 125 и 26 из 120?',
        'answer': '4.58e+24'},
    {   'id': 6992,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Проценты 78',
        'text': 'Число увеличили на 240%, получили 680. Найдите исходное.',
        'answer': '200'},
    {   'id': 6993,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Пропорция 65',
        'text': 'Решите пропорцию: (61x-60)/5 = (63x+62)/6',
        'answer': 'x = -884/51'},
    {   'id': 6994,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'Делимость 65',
        'text': 'Найдите все трехзначные числа, кратные 277.',
        'answer': '277,554,831'},
    {   'id': 6995,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Площадь 68',
        'text': 'Площадь прямоугольника 9800 см². Ширина в 22 раза меньше длины. Найдите периметр.',
        'answer': '1580 см'},
    {   'id': 6996,
        'subject': 'geometry',
        'grade': 6,
        'difficulty': 10,
        'title': 'Периметр 68',
        'text': 'Периметр прямоугольника 1200 см. Длина в 40 раз больше ширины. Найдите площадь.',
        'answer': '184320 см²'},
    {   'id': 6997,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Дроби 78',
        'text': '109/110 - 107/108 + 105/106 = ?',
        'answer': '101/157410'},
    {   'id': 6998,
        'subject': 'algebra',
        'grade': 6,
        'difficulty': 10,
        'title': 'Уравнение 76',
        'text': '61(58x - 59) - 59(59x - 60) = 57(60x - 61) - 56(59x - 60)',
        'answer': 'x = -50'},
    {   'id': 6999,
        'subject': 'number_theory',
        'grade': 6,
        'difficulty': 10,
        'title': 'НОД 62',
        'text': 'Найдите НОД(11340, 12960, 14580)',
        'answer': '1620'},
    {   'id': 7000,
        'subject': 'combinatorics',
        'grade': 6,
        'difficulty': 10,
        'title': 'Суперзадача 6 класс',
        'text': 'Сколько существует шестизначных чисел, в которых каждая следующая цифра больше '
                'предыдущей?',
        'answer': 'C(9,6) = 84'},
    {   'id': 7001,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ квадрат суммы',
        'text': 'Раскройте скобки: (a + 5)^2',
        'answer': 'a^2 + 10a + 25'},
    {   'id': 7002,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ квадрат разности',
        'text': 'Раскройте скобки: (x - 3)^2',
        'answer': 'x^2 - 6x + 9'},
    {   'id': 7003,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ квадрат суммы 2',
        'text': 'Раскройте скобки: (2a + 1)^2',
        'answer': '4a^2 + 4a + 1'},
    {   'id': 7004,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ квадрат разности 2',
        'text': 'Раскройте скобки: (3x - 2)^2',
        'answer': '9x^2 - 12x + 4'},
    {   'id': 7005,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разность квадратов',
        'text': 'Раскройте скобки: (a + 4)(a - 4)',
        'answer': 'a^2 - 16'},
    {   'id': 7006,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разность квадратов 2',
        'text': 'Раскройте скобки: (2x + 3)(2x - 3)',
        'answer': '4x^2 - 9'},
    {   'id': 7007,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ куб суммы',
        'text': 'Раскройте скобки: (a + 2)^3',
        'answer': 'a^3 + 6a^2 + 12a + 8'},
    {   'id': 7008,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ куб разности',
        'text': 'Раскройте скобки: (x - 1)^3',
        'answer': 'x^3 - 3x^2 + 3x - 1'},
    {   'id': 7009,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ сумма кубов',
        'text': 'Разложите на множители: x^3 + 8',
        'answer': '(x + 2)(x^2 - 2x + 4)'},
    {   'id': 7010,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разность кубов',
        'text': 'Разложите на множители: 27 - a^3',
        'answer': '(3 - a)(9 + 3a + a^2)'},
    {   'id': 7011,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Линейное уравнение',
        'text': 'Решите уравнение: 3x - 7 = 14',
        'answer': 'x = 7'},
    {   'id': 7012,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Линейное уравнение 2',
        'text': 'Решите уравнение: 5x + 12 = 3x - 4',
        'answer': 'x = -8'},
    {   'id': 7013,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Линейное уравнение 3',
        'text': 'Решите уравнение: 2(x - 3) = 10',
        'answer': 'x = 8'},
    {   'id': 7014,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Линейное уравнение 4',
        'text': 'Решите уравнение: 4(2x + 1) = 20',
        'answer': 'x = 2'},
    {   'id': 7015,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Линейное уравнение 5',
        'text': 'Решите уравнение: 3x + 5 = 2x - 7',
        'answer': 'x = -12'},
    {   'id': 7016,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Смежные углы',
        'text': 'Один из смежных углов равен 70°. Найдите другой угол.',
        'answer': '110°'},
    {   'id': 7017,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Смежные углы 2',
        'text': 'Один из смежных углов на 40° больше другого. Найдите эти углы.',
        'answer': '70° и 110°'},
    {   'id': 7018,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Вертикальные углы',
        'text': 'Один из вертикальных углов равен 120°. Найдите остальные углы.',
        'answer': '120°, 60°, 60°'},
    {   'id': 7019,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Вертикальные углы 2',
        'text': 'Сумма двух вертикальных углов равна 100°. Найдите эти углы.',
        'answer': '50° и 50°'},
    {   'id': 7020,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Сумма углов треугольника',
        'text': 'В треугольнике два угла равны 40° и 70°. Найдите третий угол.',
        'answer': '70°'},
    {   'id': 7021,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Сумма углов треугольника 2',
        'text': 'В треугольнике углы относятся как 2:3:4. Найдите углы.',
        'answer': '40°, 60°, 80°'},
    {   'id': 7022,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Равнобедренный треугольник',
        'text': 'В равнобедренном треугольнике угол при вершине равен 80°. Найдите углы при '
                'основании.',
        'answer': '50°, 50°'},
    {   'id': 7023,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Равнобедренный треугольник 2',
        'text': 'В равнобедренном треугольнике угол при основании равен 65°. Найдите угол при '
                'вершине.',
        'answer': '50°'},
    {   'id': 7024,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Внешний угол',
        'text': 'Внешний угол треугольника равен 120°, а внутренние не смежные с ним относятся как '
                '2:3. Найдите углы треугольника.',
        'answer': '48°, 72°, 60°'},
    {   'id': 7025,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Внешний угол 2',
        'text': 'Внешний угол треугольника равен 140°, а один из внутренних не смежных с ним 80°. '
                'Найдите остальные углы.',
        'answer': '60°, 40°, 80°'},
    {   'id': 7026,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Признак делимости на 3',
        'text': 'Делится ли число 12345 на 3?',
        'answer': 'Да, сумма цифр 15 делится на 3'},
    {   'id': 7027,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Признак делимости на 9',
        'text': 'Делится ли число 123456789 на 9?',
        'answer': 'Да, сумма цифр 45 делится на 9'},
    {   'id': 7028,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Простые числа',
        'text': 'Является ли число 131 простым?',
        'answer': 'Да'},
    {   'id': 7029,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Простые числа 2',
        'text': 'Является ли число 143 простым?',
        'answer': 'Нет, 143 = 11 × 13'},
    {   'id': 7030,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'НОД',
        'text': 'Найдите НОД(84, 126)',
        'answer': '42'},
    {   'id': 7031,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'НОД 2',
        'text': 'Найдите НОД(105, 165)',
        'answer': '15'},
    {   'id': 7032,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'НОК',
        'text': 'Найдите НОК(24, 30)',
        'answer': '120'},
    {   'id': 7033,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'НОК 2',
        'text': 'Найдите НОК(18, 24)',
        'answer': '72'},
    {   'id': 7034,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Перестановки',
        'text': 'Сколькими способами можно расставить 6 разных книг?',
        'answer': '720'},
    {   'id': 7035,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Перестановки 2',
        'text': "Сколько слов можно составить из букв слова 'КНИГА'?",
        'answer': '120'},
    {   'id': 7036,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Сочетания',
        'text': 'Сколькими способами выбрать 3 из 10?',
        'answer': '120'},
    {   'id': 7037,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Сочетания 2',
        'text': 'Сколькими способами выбрать 4 из 12?',
        'answer': '495'},
    {   'id': 7038,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Размещения',
        'text': 'Сколько трехзначных чисел из цифр 1-5 без повторений?',
        'answer': '60'},
    {   'id': 7039,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Размещения 2',
        'text': 'Сколько четырехзначных чисел из цифр 0-5 без повторений?',
        'answer': '300'},
    {   'id': 7040,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Степени',
        'text': 'Вычислите: 2^5 × 2^3',
        'answer': '256'},
    {   'id': 7041,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Степени 2',
        'text': 'Вычислите: (3^2)^3',
        'answer': '729'},
    {   'id': 7042,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Степени 3',
        'text': 'Вычислите: 5^3 × 5^2',
        'answer': '3125'},
    {   'id': 7043,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Степени 4',
        'text': 'Вычислите: 7^0 + 8^1',
        'answer': '9'},
    {   'id': 7044,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Одночлены',
        'text': 'Упростите: 3a × 4a^2',
        'answer': '12a^3'},
    {   'id': 7045,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Одночлены 2',
        'text': 'Упростите: 2x^2 × 5x^3',
        'answer': '10x^5'},
    {   'id': 7046,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Многочлены',
        'text': 'Сложите: (2x + 5) + (3x - 2)',
        'answer': '5x + 3'},
    {   'id': 7047,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Многочлены 2',
        'text': 'Вычтите: (5x - 3) - (2x + 4)',
        'answer': '3x - 7'},
    {   'id': 7048,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Многочлены 3',
        'text': 'Умножьте: 2x(3x - 5)',
        'answer': '6x^2 - 10x'},
    {   'id': 7049,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Многочлены 4',
        'text': 'Умножьте: (x + 2)(x + 3)',
        'answer': 'x^2 + 5x + 6'},
    {   'id': 7050,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Многочлены 5',
        'text': 'Умножьте: (x - 4)(x + 5)',
        'answer': 'x^2 + x - 20'},
    {   'id': 7051,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Периметр',
        'text': 'Найдите периметр треугольника со сторонами 7, 8, 9 см.',
        'answer': '24 см'},
    {   'id': 7052,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Периметр 2',
        'text': 'Найдите периметр прямоугольника со сторонами 12 и 15 см.',
        'answer': '54 см'},
    {   'id': 7053,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Площадь',
        'text': 'Найдите площадь прямоугольника со сторонами 12 и 15 см.',
        'answer': '180 см²'},
    {   'id': 7054,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Площадь 2',
        'text': 'Найдите площадь квадрата со стороной 9 см.',
        'answer': '81 см²'},
    {   'id': 7055,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Площадь 3',
        'text': 'Найдите площадь треугольника с основанием 10 см и высотой 6 см.',
        'answer': '30 см²'},
    {   'id': 7056,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Окружность',
        'text': 'Радиус окружности 10 см. Найдите длину окружности (π=3,14).',
        'answer': '62,8 см'},
    {   'id': 7057,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Окружность 2',
        'text': 'Диаметр окружности 20 см. Найдите длину окружности (π=3,14).',
        'answer': '62,8 см'},
    {   'id': 7058,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Круг',
        'text': 'Радиус круга 7 см. Найдите площадь круга (π=3,14).',
        'answer': '153,86 см²'},
    {   'id': 7059,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Круг 2',
        'text': 'Диаметр круга 14 см. Найдите площадь круга (π=3,14).',
        'answer': '153,86 см²'},
    {   'id': 7060,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Уравнение с дробями',
        'text': 'Решите: x/3 + x/4 = 7',
        'answer': 'x = 12'},
    {   'id': 7061,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Уравнение с дробями 2',
        'text': 'Решите: x/2 - x/5 = 3',
        'answer': 'x = 10'},
    {   'id': 7062,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Уравнение с дробями 3',
        'text': 'Решите: (x-2)/3 = 5',
        'answer': 'x = 17'},
    {   'id': 7063,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Уравнение с дробями 4',
        'text': 'Решите: (x+3)/4 = 7',
        'answer': 'x = 25'},
    {   'id': 7064,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Признаки делимости',
        'text': 'Вместо * поставьте цифру: 5*8 делится на 3',
        'answer': '2,5,8'},
    {   'id': 7065,
        'subject': 'number_theory',
        'grade': 7,
        'difficulty': 1,
        'title': 'Признаки делимости 2',
        'text': 'Вместо * поставьте цифру: 3*7 делится на 9',
        'answer': '8'},
    {   'id': 7066,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Правило произведения',
        'text': 'Сколько трехзначных чисел можно составить из цифр 1,2,3,4?',
        'answer': '64'},
    {   'id': 7067,
        'subject': 'combinatorics',
        'grade': 7,
        'difficulty': 1,
        'title': 'Правило произведения 2',
        'text': 'Сколько четырехзначных чисел из цифр 1,2,3,4,5?',
        'answer': '625'},
    {   'id': 7068,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разложение',
        'text': 'Разложите на множители: x^2 - 25',
        'answer': '(x-5)(x+5)'},
    {   'id': 7069,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разложение 2',
        'text': 'Разложите на множители: 4a^2 - 9',
        'answer': '(2a-3)(2a+3)'},
    {   'id': 7070,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разложение 3',
        'text': 'Разложите на множители: x^2 + 6x + 9',
        'answer': '(x+3)^2'},
    {   'id': 7071,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'ФСУ разложение 4',
        'text': 'Разложите на множители: 4x^2 - 12x + 9',
        'answer': '(2x-3)^2'},
    {   'id': 7072,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Медиана',
        'text': 'В треугольнике медиана равна половине стороны. Какой это треугольник?',
        'answer': 'Прямоугольный'},
    {   'id': 7073,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Биссектриса',
        'text': 'В треугольнике биссектриса делит угол 80° на два равных. Чему равны эти углы?',
        'answer': '40° и 40°'},
    {   'id': 7074,
        'subject': 'geometry',
        'grade': 7,
        'difficulty': 1,
        'title': 'Высота',
        'text': 'В треугольнике высота образует со стороной угол 90°. Что это означает?',
        'answer': 'Высота перпендикулярна стороне'},
    {   'id': 7075,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Задача на движение',
        'text': 'Пешеход прошел 15 км за 3 часа. С какой скоростью он шел?',
        'answer': '5 км/ч'},
    {   'id': 7076,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Задача на движение 2',
        'text': 'Велосипедист проехал 48 км за 3 часа. Найдите его скорость.',
        'answer': '16 км/ч'},
    {   'id': 7077,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Задача на работу',
        'text': 'Мастер делает 20 деталей в час. Сколько деталей он сделает за 8 часов?',
        'answer': '160'},
    {   'id': 7078,
        'subject': 'algebra',
        'grade': 7,
        'difficulty': 1,
        'title': 'Задача на работу 2',
        'text': 'Рабочий делает 15 деталей в час. За сколько часов он сделает 120 деталей?',
        'answer': '8 часов'}]
