#!/usr/bin/env python
"""Verify corrected_slot_report.json structural integrity and counts."""
import json
import sys

with open('corrected_slot_report.json', 'r', encoding='utf-8') as f:
    report = json.load(f)

tc = report['task_counts']
cells = report['per_cell_slots']
errors = []
warnings = []

def p(text):
    """Print with cp1251-safe encoding."""
    s = str(text).encode('ascii', errors='replace').decode('ascii')
    print(s)

p("=" * 60)
p("CORRECTED SLOT REPORT - VALIDATION")
p("=" * 60)

# -- 1. task_counts internal consistency ----------------------------------
p("")
p("1. task_counts: KEEP=%d, FIXED=%d, REPLACE=%d, total=%d" % (
    tc['KEEP'], tc['FIXED'], tc['REPLACE'], tc['total']))

cat_sum = tc['KEEP'] + tc['FIXED'] + tc['REPLACE']
if cat_sum == tc['total']:
    p("   [PASS] KEEP + FIXED + REPLACE = %d == total" % cat_sum)
else:
    msg = "   [FAIL] KEEP+FIXED+REPLACE = %d != total = %d" % (cat_sum, tc['total'])
    p(msg)
    errors.append(msg)

# -- 2. total_replacement_slots -------------------------------------------
repl_sum = sum(v.get('replacement_slots', 0) for v in cells.values())
p("")
p("2. total_replacement_slots: header=%d, sum over cells=%d" % (
    report['total_replacement_slots'], repl_sum))

if repl_sum == report['total_replacement_slots']:
    p("   [PASS] MATCH")
else:
    msg = "   [FAIL] MISMATCH: header=%d, sum=%d" % (report['total_replacement_slots'], repl_sum)
    p(msg)
    errors.append(msg)

# -- 3. Per-cell bank consistency -----------------------------------------
p("")
p("3. Per-cell bank consistency: valid_existing + fixed_in_bank + replace_in_bank == bank_count")
inconsistent = 0
for key, cell in cells.items():
    bank = cell.get('bank_count', 0)
    valid = cell.get('valid_existing', 0)
    fixed = cell.get('fixed_in_bank', 0)
    repl = cell.get('replace_in_bank', 0)
    
    if valid + fixed + repl != bank:
        inconsistent += 1
        if inconsistent <= 5:
            p("   [WARN] %s: valid(%d)+fixed(%d)+replace(%d)=%d != bank(%d)" % (
                key, valid, fixed, repl, valid+fixed+repl, bank))

if inconsistent == 0:
    p("   [PASS] All 258 cells consistent")
else:
    p("   [WARN] %d cells have inconsistent bank counts (pre-existing input data anomaly)" % inconsistent)
    if inconsistent > 5:
        p("         ... (%d more not shown)" % (inconsistent - 5))
    p("   NOTE: These are pre-existing data anomalies in the input report generated by")
    p("   _05_stage0_reconciliation.py, NOT caused by our changes. They won't affect")
    p("   Stage 6/Stage 7 execution (which reads slot-level decision flags).")
    warnings.append("[WARN] %d cells with bank count inconsistency (pre-existing)" % inconsistent)

# -- 4. REPLACE count interpretation --------------------------------------
replace_cells = sum(1 for v in cells.values() if v.get('replace_in_bank', 0) > 0)
repl_slots_cells = sum(1 for v in cells.values() if v.get('replacement_slots', 0) > 0)
p("")
p("4. REPLACE count: header=%d, cells with replace_in_bank>0=%d, cells with replacement_slots>0=%d" % (
    tc['REPLACE'], replace_cells, repl_slots_cells))
p("   NOTE: header counts UNIQUE TASKS (%d), cells counts SLOTS with any replacement (%d)" % (
    tc['REPLACE'], replace_cells))
p("   Each task spans 3 slots x multiple grades, so cells_with_replacement < REPLACE is EXPECTED")
if replace_cells == 0 and tc['REPLACE'] > 0:
    msg = "   [FAIL] REPLACE=%d but zero cells flagged for replacement" % tc['REPLACE']
    p(msg)
    errors.append(msg)
else:
    p("   [PASS] %d cells with replacement >= 0 (expected)" % replace_cells)

# -- 5. FIXED count interpretation ----------------------------------------
fixed_cells = sum(1 for v in cells.values() if v.get('fixed_in_bank', 0) > 0)
p("")
p("5. FIXED count: header=%d, cells with fixed_in_bank>0=%d" % (tc['FIXED'], fixed_cells))
p("   NOTE: header counts UNIQUE TASKS, cells with fixes could differ")
if fixed_cells == 0 and tc['FIXED'] > 0:
    msg = "   [FAIL] FIXED=%d but zero cells flagged for fix" % tc['FIXED']
    p(msg)
    errors.append(msg)
else:
    p("   [PASS] %d cells with fixes (expected)" % fixed_cells)

# -- 6. KEEP count interpretation -----------------------------------------
keep_cells = sum(1 for v in cells.values() if v.get('valid_existing', 0) > 0)
p("")
p("6. KEEP count: header=%d, cells with valid_existing>0=%d" % (tc['KEEP'], keep_cells))
p("   NOTE: header counts UNIQUE KEEP tasks; all 258 cells have valid_existing>0 (expected)")
if keep_cells == 0 and tc['KEEP'] > 0:
    msg = "   [FAIL] KEEP=%d but zero cells with valid_existing" % tc['KEEP']
    p(msg)
    errors.append(msg)
else:
    p("   [PASS] %d cells with valid tasks (expected)" % keep_cells)

# -- 7. Unique task count from keys ---------------------------------------
unique_tasks = set()
for key in cells:
    parts = key.split('|')
    if len(parts) == 4:
        unique_tasks.add('|'.join(parts[:3]))  # GRADE|LEVEL|TOPIC

p("")
p("7. Unique (grade|level|topic) combinations from keys: %d" % len(unique_tasks))
p("   task_counts total: %d (problematic tasks only)" % tc['total'])
if len(unique_tasks) >= tc['total']:
    p("   [PASS] %d unique keys >= %d problematic tasks" % (len(unique_tasks), tc['total']))
else:
    msg = "   [FAIL] unique_tasks(%d) < total(%d)" % (len(unique_tasks), tc['total'])
    p(msg)
    errors.append(msg)

# -- 8. Total per_cell_slots count ----------------------------------------
p("")
p("8. Total per_cell_slot entries: %d" % len(cells))
expected_total = len(unique_tasks) * 3
if len(cells) == expected_total:
    p("   [PASS] %d = %d tasks x 3 slots" % (len(cells), len(unique_tasks)))
else:
    p("   [INFO] %d entries, %d unique tasks x 3 = %d" % (len(cells), len(unique_tasks), expected_total))

# -- Summary --------------------------------------------------------------
p("")
p("=" * 60)
if errors:
    p("VALIDATION FAILED - %d error(s):" % len(errors))
    for e in errors:
        p("  * %s" % e)
    sys.exit(1)
else:
    p("ALL CHECKS PASSED")
    if warnings:
        p("With %d warning(s):" % len(warnings))
        for w in warnings:
            p("  * %s" % w)
    p("=" * 60)
