# -*- coding: utf-8 -*-
"""TASK 6: Inventory of all .db files in the project."""
import os, datetime

BASE = r'c:\Users\Redmi\Desktop\Новая папка (2)'
EXCLUDE = ['.git', '__pycache__', '.venv', 'node_modules']

files = []
for dp, dns, fns in os.walk(BASE):
    # skip excluded dirs
    dns[:] = [d for d in dns if d not in EXCLUDE]
    for f in fns:
        if f.endswith('.db') or f.endswith('.db-shm') or f.endswith('.db-wal') or f.endswith('.bak'):
            full = os.path.join(dp, f)
            size = os.path.getsize(full)
            mtime = datetime.datetime.fromtimestamp(os.path.getmtime(full)).strftime('%Y-%m-%d %H:%M')
            rel = os.path.relpath(full, BASE)
            files.append((rel, full, size, mtime))

files.sort(key=lambda x: x[0])

# Determine purpose heuristically
def classify(path):
    p = path.lower()
    if '-shm' in p or '-wal' in p:
        return 'WAL/SHM journal (auto-generated by SQLite)'
    if 'backup' in p or '.bak' in p:
        return 'Backup copy'
    if 'instance\\formyla.db' == p.replace('/', '\\'):
        return 'CANONICAL active app database'
    if 'instance\\' in p:
        if 'formyla' in p:
            return 'Instance backup (pre-migration snapshot)'
        return 'Instance auxiliary/test db'
    if 'formyla.db' == p.replace('/', '\\'):
        return 'Root pool DB (canonical source, not used by app)'
    if '_recon\\' in p:
        return 'Recon copy (created during P5_MERGE)'
    if 'database.db' in p:
        return 'Generic/dev database'
    if 'olympiads.db' in p:
        return 'Olympiad-specific database'
    if 'flask_session' in p:
        return 'Flask session storage'
    if 'test' in p or 'smoke' in p or 'diag' in p:
        return 'Test/diagnostic database'
    if 'app.db' in p or 'formula.db' in p or 'database.db' in p:
        return 'Legacy/dev database'
    return 'Unknown'

print(f"{'Path':<90} {'Size':>12} {'Date':<16} {'Purpose':<50} {'Delete?':<10}")
print("-" * 180)

for rel, full, size, mtime in files:
    purpose = classify(rel)
    # Categorize delete-candidate
    candidate = 'NO'
    if 'WAL/SHM' in purpose:
        candidate = 'NO (auto)'
    elif 'CANONICAL' in purpose:
        candidate = 'NO (active)'
    elif 'Root pool DB' in purpose:
        candidate = 'NO (canon)'
    elif 'Recon copy' in purpose:
        candidate = 'YES'
    elif 'Test' in purpose or 'smoke' in purpose or 'diag' in purpose:
        candidate = 'YES'
    elif 'Legacy' in purpose:
        candidate = 'PROBABLY'
    elif 'Backup' in purpose and '_recon' in rel:
        candidate = 'YES'
    elif 'Backup' in purpose:
        candidate = 'PROBABLY'
    
    sz = f"{size:,} B" if size < 1024*1024 else f"{size/(1024*1024):.1f} MB"
    print(f"{rel:<90} {sz:>12} {mtime:<16} {purpose:<50} {candidate:<10}")

print(f"\nTotal: {len(files)} files")
