# -*- coding: utf-8 -*-
"""Build templates/drawing.html with fullscreen whiteboard design (side panels)."""
import os, sys

OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'templates', 'drawing.html'))
CHUNKS = []
def add(s): CHUNKS.append(s)

# ─── Part 1: opening + tabs (top bar) ───
add('{% extends "base.html" %}\n')
add('{% block title %}Чертёж — FORMYLA{% endblock %}\n\n')
add('{% block content %}\n')

# Generator pane (existing functionality) — shown above whiteboard pane,
# only one is visible at a time. Generator pane uses normal page flow,
# whiteboard pane uses fullscreen fixed layout when active.
add('<div id="drw-pane-generator" class="drw-pane drw-pane-normal">\n')
add('    <section class="drawing-page-inner">\n')
add('        <div class="board-tabs board-tabs--inline" role="tablist">\n')
add('            <button class="tab tab--active drw-tab" data-tab="generator" role="tab">✨ Сгенерировать чертёж</button>\n')
add('            <button class="tab drw-tab" data-tab="whiteboard" role="tab">🎨 Доска</button>\n')
add('        </div>\n')
add('        <header class="board-header">\n')
add('            <h1 class="board-title">📐 Чертёж по условию</h1>\n')
add('            <p class="board-hint">Введи условие геометрической задачи — нейросеть нарисует базовый чертёж.</p>\n')
add('        </header>\n')
add('        <div class="drawing-form glass">\n')
add('            <label for="problemText" class="dform-label">Условие задачи</label>\n')
add('            <textarea id="problemText" rows="6" maxlength="2000"\n')
add('                placeholder="Например: В треугольнике ABC угол A = 60°, AB = 5, AC = 7. Точка M — середина BC."\n')
add('                class="dform-textarea"></textarea>\n')
add('            <div class="dform-row">\n')
add('                <span id="charCounter" class="dform-counter">0 / 2000 символов</span>\n')
add('                <button id="generateBtn" type="button" class="dform-btn-primary">✨ Сгенерировать чертёж</button>\n')
add('            </div>\n')
add('            <p class="dform-note">Лимит: 10 чертежей в час. Генерация занимает около 10–20 секунд.</p>\n')
add('        </div>\n')
add('        <div id="drawingLoader" hidden class="drawing-loader">\n')
add('            <div class="drawing-spinner"></div>\n')
add('            <p class="dform-hint">Рисуем чертёж… Обычно это занимает 10–20 секунд.</p>\n')
add('        </div>\n')
add('        <div id="drawingError" hidden class="drawing-error"></div>\n')
add('        <div id="drawingResultWrap" hidden class="drawing-result-wrap glass">\n')
add('            <h3 class="dform-h3">Готовый чертёж</h3>\n')
add('            <div class="drawing-image-frame"><img id="drawing-result" alt="Чертёж к задаче"></div>\n')
add('            <div class="drawing-actions">\n')
add('                <a id="downloadBtn" href="#" download="drawing.png" class="btn-soft btn-accent">⬇️ Скачать PNG</a>\n')
add('                <button id="regenerateBtn" type="button" class="btn-soft">🔄 Перегенерировать</button>\n')
add("                <button type=\"button\" class=\"btn-soft btn-violet\"\n")
add("                    onclick=\"document.querySelector('.drw-tab[data-tab=whiteboard]').click(); setTimeout(() => window.WB && window.WB.importImage(document.getElementById('drawing-result').src), 300);\">\n")
add('                    🎨 Открыть на доске\n')
add('                </button>\n')
add('            </div>\n')
add('            <p id="drawingMeta" class="dform-note"></p>\n')
add('        </div>\n')
add('    </section>\n')
add('</div>\n\n')

# ─── Part 2: fullscreen whiteboard pane ───
add('<div id="drw-pane-whiteboard" class="drw-pane drw-pane-full board-app" hidden>\n')

# Top bar: tabs + title + zoom controls + status
add('    <div class="top-bar glass">\n')
add('        <div class="board-tabs" role="tablist">\n')
add('            <button class="tab drw-tab" data-tab="generator" role="tab">✨ Чертёж</button>\n')
add('            <button class="tab tab--active drw-tab" data-tab="whiteboard" role="tab">🎨 Доска</button>\n')
add('        </div>\n')
add('        <div class="top-bar-title">🎨 Бесконечная доска</div>\n')
add('        <div class="actions zoom">\n')
add('            <button class="icon-btn" id="wbZoomOut"   title="Уменьшить">−</button>\n')
add('            <button class="icon-btn" id="wbZoomReset" title="Сбросить масштаб">100%</button>\n')
add('            <button class="icon-btn" id="wbZoomIn"    title="Увеличить">+</button>\n')
add('            <button class="icon-btn" id="wbFit"       title="Подогнать">⊟</button>\n')
add('            <span class="divider"></span>\n')
add('            <button class="icon-btn" id="wbExport" title="Сохранить как PNG">💾</button>\n')
add('            <button class="icon-btn" id="wbImport" title="Импортировать">🖼️</button>\n')
add('            <input  type="file" hidden id="wbImportInput" accept="image/*">\n')
add('            <button class="icon-btn icon-btn--danger" id="wbClear" title="Очистить всё">🗑️</button>\n')
add('            <span class="canvas-status"><span id="wbStatus">Готово</span></span>\n')
add('        </div>\n')
add('    </div>\n\n')

# Left side panel: tools + undo/redo (wbToolbar lives here so JS still finds .wb-tool)
add('    <aside id="wbToolbar" class="side-panel side-panel--left glass">\n')
add('        <button class="tool tool--active wb-tool" data-tool="select"  title="Рука / выбрать (V)">✋</button>\n')
add('        <button class="tool wb-tool"              data-tool="pen"     title="Карандаш (P)">✏️</button>\n')
add('        <button class="tool wb-tool"              data-tool="eraser"  title="Ластик (E)">🧽</button>\n')
add('        <button class="tool wb-tool"              data-tool="rect"    title="Прямоугольник (R)">▭</button>\n')
add('        <button class="tool wb-tool"              data-tool="ellipse" title="Эллипс (O)">◯</button>\n')
add('        <button class="tool wb-tool"              data-tool="line"    title="Линия (L)">／</button>\n')
add('        <button class="tool wb-tool"              data-tool="arrow"   title="Стрелка (A)">→</button>\n')
add('        <button class="tool wb-tool"              data-tool="text"    title="Текст (T)">T</button>\n')
add('        <button class="tool wb-tool"              data-tool="sticky"  title="Стикер (S)">🗒️</button>\n')
add('        <div class="divider divider--h"></div>\n')
add('        <button class="icon-btn" id="wbUndo" title="Отменить (Ctrl+Z)">↶</button>\n')
add('        <button class="icon-btn" id="wbRedo" title="Повторить (Ctrl+Y)">↷</button>\n')
add('    </aside>\n\n')

# Canvas area in middle
add('    <div id="wbCanvasWrap" class="canvas-wrap">\n')
add('        <canvas id="wbCanvas" class="board-canvas"></canvas>\n')
add('        <textarea id="wbTextEditor" class="wb-text-editor" rows="3"></textarea>\n')
add('        <div id="wbHUD" class="canvas-hud">zoom 100%</div>\n')
add('    </div>\n\n')

# Right side panel: colors + thickness slider
add('    <aside class="side-panel side-panel--right glass">\n')
add('        <div class="palette palette--vert">\n')
add('            <button class="swatch swatch--active wb-color" data-color="#e6e8ff" style="--c:#e6e8ff" title="Светлый"></button>\n')
add('            <button class="swatch wb-color" data-color="#3b82f6" style="--c:#3b82f6" title="Синий"></button>\n')
add('            <button class="swatch wb-color" data-color="#8b5cf6" style="--c:#8b5cf6" title="Фиолет"></button>\n')
add('            <button class="swatch wb-color" data-color="#22c55e" style="--c:#22c55e" title="Зелёный"></button>\n')
add('            <button class="swatch wb-color" data-color="#f59e0b" style="--c:#f59e0b" title="Оранжевый"></button>\n')
add('            <button class="swatch wb-color" data-color="#ef4444" style="--c:#ef4444" title="Красный"></button>\n')
add('            <button class="swatch wb-color" data-color="#ec4899" style="--c:#ec4899" title="Розовый"></button>\n')
add('            <button class="swatch swatch--clear wb-color" data-color="#0f172a" style="--c:#0f172a" title="Тёмный"></button>\n')
add('        </div>\n')
add('        <div class="divider divider--h"></div>\n')
add('        <div class="thickness thickness--vert" title="Толщина линии">\n')
add('            <input type="range" id="wbThickness" min="1" max="30" value="3" class="slider slider--vert" orient="vertical">\n')
add('        </div>\n')
add('    </aside>\n')

add('</div>\n\n')

# ─── Part 3: CSS ───
add('<style>\n')
add(':root{\n')
add('    --bg-0:#0b0d12; --bg-1:#10131a; --bg-2:#161a23;\n')
add('    --accent:#8b5cf6; --accent-2:#4aa8ff;\n')
add('    --text:#e6e8ee; --muted:#9aa3b2;\n')
add('    --border:rgba(255,255,255,.10);\n')
add('    --glass:rgba(255,255,255,.04);\n')
add('}\n')
add('.glass{\n')
add('    background:var(--glass);\n')
add('    border:1px solid var(--border);\n')
add('    backdrop-filter:blur(10px);\n')
add('    -webkit-backdrop-filter:blur(10px);\n')
add('}\n')
add('.drw-pane[hidden]{ display:none !important; }\n\n')

# Normal page generator pane
add('.drw-pane-normal{ max-width:1280px; margin:0 auto; padding:24px 16px; color:var(--text); }\n')
add('.board-tabs--inline{ display:flex; gap:8px; margin-bottom:18px; border-bottom:1px solid var(--border); }\n')
add('.board-tabs--inline .tab{ padding:10px 18px; background:transparent; color:var(--muted); border:none; border-bottom:2px solid transparent; cursor:pointer; font-size:15px; font-weight:600; transition:.2s; }\n')
add('.board-tabs--inline .tab:hover{ color:var(--text); }\n')
add('.board-tabs--inline .tab--active{ color:var(--accent-2)!important; border-bottom-color:var(--accent-2)!important; }\n')
add('.board-header{ margin-bottom:16px; }\n')
add('.board-title{ font-size:2em; margin:0 0 8px; color:var(--text); }\n')
add('.board-hint{ color:var(--muted); margin:0; line-height:1.5; }\n\n')

# Generator form
add('.drawing-form{ padding:20px; margin-bottom:20px; border-radius:14px; }\n')
add('.dform-label{ display:block; font-weight:600; margin-bottom:8px; color:var(--text); }\n')
add('.dform-textarea{ width:100%; padding:12px; border-radius:10px; border:1px solid var(--border); background:var(--bg-1); color:var(--text); font:inherit; font-size:15px; line-height:1.5; resize:vertical; box-sizing:border-box; }\n')
add('.dform-textarea:focus{ outline:none; border-color:var(--accent-2); box-shadow:0 0 0 3px rgba(74,168,255,.18); }\n')
add('.dform-row{ display:flex; justify-content:space-between; align-items:center; margin-top:12px; gap:12px; flex-wrap:wrap; }\n')
add('.dform-counter{ color:var(--muted); font-size:13px; }\n')
add('.dform-note{ margin:12px 0 0; font-size:12px; color:var(--muted); }\n')
add('.dform-hint{ margin:16px 0 0; color:var(--muted); }\n')
add('.dform-h3{ margin:0 0 16px; font-size:1.15em; color:var(--text); }\n')
add('.dform-btn-primary{ padding:12px 28px; background:linear-gradient(135deg,var(--accent-2),var(--accent)); color:#fff; border:none; border-radius:10px; font-weight:600; font-size:15px; cursor:pointer; transition:.15s; box-shadow:0 2px 12px rgba(139,92,246,.3); }\n')
add('.dform-btn-primary:hover{ transform:translateY(-1px); box-shadow:0 6px 18px rgba(139,92,246,.45); }\n')
add('.dform-btn-primary:disabled{ opacity:.6; cursor:not-allowed; transform:none; box-shadow:none; }\n')
add('.drawing-loader{ text-align:center; padding:40px 20px; background:var(--glass); border:1px solid var(--border); border-radius:14px; margin-bottom:20px; }\n')
add('.drawing-spinner{ display:inline-block; width:48px; height:48px; border:4px solid rgba(74,168,255,.2); border-top-color:var(--accent-2); border-radius:50%; animation:drawing-spin .9s linear infinite; }\n')
add('@keyframes drawing-spin{ to{ transform:rotate(360deg); } }\n')
add('.drawing-error{ padding:14px 18px; margin-bottom:20px; background:rgba(239,68,68,.10); border:1px solid rgba(239,68,68,.35); border-radius:10px; color:#fca5a5; }\n')
add('.drawing-result-wrap{ padding:20px; border-radius:14px; }\n')
add('.drawing-image-frame{ background:#fff; padding:12px; border-radius:10px; display:flex; justify-content:center; align-items:center; }\n')
add('.drawing-image-frame img{ max-width:100%; height:auto; display:block; }\n')
add('.drawing-actions{ margin-top:16px; display:flex; gap:10px; flex-wrap:wrap; }\n')
add('.btn-soft{ padding:10px 20px; border-radius:10px; font-weight:600; font-size:14px; cursor:pointer; background:rgba(255,255,255,.05); color:var(--muted); border:1px solid var(--border); text-decoration:none; display:inline-flex; align-items:center; gap:6px; transition:.15s; }\n')
add('.btn-soft:hover{ color:var(--text); border-color:rgba(255,255,255,.18); }\n')
add('.btn-accent{ background:rgba(74,168,255,.15); color:var(--accent-2); border-color:rgba(74,168,255,.35); }\n')
add('.btn-violet{ background:rgba(139,92,246,.15); color:#a78bfa; border-color:rgba(139,92,246,.35); }\n\n')

# Fullscreen board layout (only when whiteboard pane is visible)
add('/* === Fullscreen whiteboard layout === */\n')
add('body.board-fullscreen{ overflow:hidden; }\n')
add('body.board-fullscreen .header,\n')
add('body.board-fullscreen .mobile-bottom-nav,\n')
add('body.board-fullscreen footer{ display:none !important; }\n')
add('.drw-pane-full.board-app{\n')
add('    position:fixed; inset:0; z-index:50;\n')
add('    display:grid;\n')
add('    grid-template-columns:72px 1fr 72px;\n')
add('    grid-template-rows:auto 1fr;\n')
add('    gap:12px; padding:12px;\n')
add('    color:var(--text);\n')
add('    background:\n')
add('        radial-gradient(900px 600px at 90% -10%, rgba(74,168,255,.10), transparent 60%),\n')
add('        radial-gradient(900px 600px at -10% 110%, rgba(139,92,246,.10), transparent 60%),\n')
add('        var(--bg-0);\n')
add('}\n\n')

# Top bar
add('.top-bar{\n')
add('    grid-column:1 / -1; grid-row:1 / 2;\n')
add('    display:flex; align-items:center; justify-content:space-between;\n')
add('    padding:10px 16px; border-radius:14px;\n')
add('    gap:12px;\n')
add('}\n')
add('.top-bar .board-tabs{ display:flex; gap:6px; }\n')
add('.top-bar .tab{ padding:8px 14px; background:transparent; color:var(--muted); border:1px solid transparent; border-radius:10px; cursor:pointer; font-size:13px; font-weight:600; transition:.15s; }\n')
add('.top-bar .tab:hover{ color:var(--text); background:rgba(255,255,255,.04); }\n')
add('.top-bar .tab--active{ color:#fff !important; background:linear-gradient(135deg,var(--accent-2),var(--accent)) !important; border-color:transparent !important; box-shadow:0 0 14px rgba(139,92,246,.35); }\n')
add('.top-bar-title{ font-size:15px; font-weight:600; color:var(--text); opacity:.9; }\n\n')

# Side panels
add('.side-panel{\n')
add('    grid-row:2 / 3;\n')
add('    display:flex; flex-direction:column; align-items:center; gap:8px;\n')
add('    padding:12px 8px; border-radius:18px;\n')
add('    height:fit-content; align-self:center;\n')
add('    max-height:calc(100vh - 80px); overflow-y:auto;\n')
add('}\n')
add('.side-panel--left{ grid-column:1 / 2; }\n')
add('.side-panel--right{ grid-column:3 / 4; }\n')
add('.divider{ width:1px; height:24px; background:var(--border); }\n')
add('.divider--h{ width:28px; height:1px; background:var(--border); margin:4px 0; }\n\n')

# Tool / icon-btn
add('.tool, .icon-btn{\n')
add('    width:42px; height:42px;\n')
add('    display:inline-flex; align-items:center; justify-content:center;\n')
add('    background:rgba(255,255,255,.04);\n')
add('    border:1px solid var(--border);\n')
add('    color:var(--text); border-radius:12px;\n')
add('    font-size:17px; font-weight:600; cursor:pointer; padding:0;\n')
add('    transition:background .15s, border-color .15s, transform .1s, box-shadow .15s;\n')
add('}\n')
add('.tool:hover, .icon-btn:hover{ background:rgba(139,92,246,.16); border-color:rgba(139,92,246,.45); }\n')
add('.tool--active{ background:linear-gradient(135deg,var(--accent-2),var(--accent)); color:#fff; border-color:transparent; box-shadow:0 0 14px rgba(139,92,246,.45); }\n')
add('.icon-btn--danger:hover{ background:rgba(239,68,68,.18); border-color:rgba(239,68,68,.45); }\n')
add('#wbZoomReset{ width:auto; padding:0 10px; font-size:13px; }\n\n')

# Palette + swatches
add('.palette{ display:inline-flex; gap:6px; align-items:center; }\n')
add('.palette--vert{ flex-direction:column; }\n')
add('.swatch{\n')
add('    width:28px; height:28px; border-radius:50%;\n')
add('    border:2px solid transparent;\n')
add('    background:var(--c, #fff); cursor:pointer; padding:0;\n')
add('    transition:transform .12s, box-shadow .15s;\n')
add('}\n')
add('.swatch:hover{ transform:scale(1.15); }\n')
add('.swatch--active{ border-color:#fff; box-shadow:0 0 10px rgba(255,255,255,.4); }\n')
add('.swatch--clear{ border:1px solid #475569; }\n\n')

# Thickness slider
add('.thickness{ display:inline-flex; flex-direction:column; gap:2px; padding:6px; align-items:center; }\n')
add('.thickness--vert{ height:140px; }\n')
add('.slider{ accent-color:var(--accent); }\n')
add('.slider--vert{\n')
add('    -webkit-appearance:slider-vertical;\n')
add('    appearance:slider-vertical;\n')
add('    writing-mode:bt-lr;\n')
add('    width:8px; height:120px;\n')
add('}\n\n')

# Canvas wrap
add('.canvas-wrap{\n')
add('    grid-column:2 / 3; grid-row:2 / 3;\n')
add('    position:relative;\n')
add('    width:100%; height:100%;\n')
add('    background:\n')
add('        radial-gradient(1200px 800px at 50% 50%, rgba(74,168,255,.05), transparent 60%),\n')
add('        var(--bg-0);\n')
add('    border:1px solid var(--border);\n')
add('    border-radius:18px;\n')
add('    overflow:hidden; touch-action:none; cursor:default;\n')
add('    box-shadow:0 12px 50px rgba(0,0,0,.45);\n')
add('}\n')
add('.board-canvas{ display:block; width:100%; height:100%; }\n')
add('.wb-text-editor{\n')
add('    position:absolute; display:none; z-index:5;\n')
add('    padding:8px; background:transparent;\n')
add('    border:1px dashed var(--accent); color:var(--text);\n')
add('    font:14px/1.45 "Segoe UI", sans-serif;\n')
add('    resize:none; outline:none; box-shadow:none;\n')
add('}\n')
add('.canvas-hud{\n')
add('    position:absolute; bottom:10px; right:14px; pointer-events:none;\n')
add('    font-size:11px; color:var(--muted);\n')
add('    background:rgba(11,13,18,.7);\n')
add('    padding:4px 10px; border-radius:999px;\n')
add('    border:1px solid var(--border);\n')
add('}\n')
add('.canvas-status{ display:inline-flex; align-items:center; gap:8px; font-size:12px; color:var(--muted); margin-left:8px; }\n')
add('.actions{ display:inline-flex; gap:6px; align-items:center; }\n\n')

# Responsive
add('@media (max-width:820px){\n')
add('    .drw-pane-full.board-app{ grid-template-columns:60px 1fr 60px; gap:8px; padding:8px; }\n')
add('    .tool, .icon-btn{ width:38px; height:38px; font-size:15px; }\n')
add('    .swatch{ width:24px; height:24px; }\n')
add('    .slider--vert{ height:90px; }\n')
add('    .top-bar-title{ display:none; }\n')
add('}\n')
add('@media (max-width:560px){\n')
add('    .drw-pane-full.board-app{ grid-template-columns:54px 1fr 54px; }\n')
add('    .tool, .icon-btn{ width:34px; height:34px; font-size:13px; }\n')
add('    .swatch{ width:22px; height:22px; }\n')
add('    .top-bar .tab{ padding:6px 10px; font-size:12px; }\n')
add('}\n')
add('</style>\n\n')

# ─── Part 4: JS — tab switching + body class sync + active-class bridge ───
add('<script>\n')
add('(function(){\n')
add('  const tabs = document.querySelectorAll(".drw-tab");\n')
add('  const panes = {\n')
add('      generator: document.getElementById("drw-pane-generator"),\n')
add('      whiteboard: document.getElementById("drw-pane-whiteboard")\n')
add('  };\n')
add('  function activate(name){\n')
add('      tabs.forEach(b => b.classList.toggle("tab--active", b.dataset.tab === name));\n')
add('      Object.entries(panes).forEach(([k,p]) => { if(p) p.hidden = (k !== name); });\n')
add('      if (name === "whiteboard"){\n')
add('          document.body.classList.add("board-fullscreen");\n')
add('          if (window.WB) requestAnimationFrame(() => window.WB.resize());\n')
add('      } else {\n')
add('          document.body.classList.remove("board-fullscreen");\n')
add('      }\n')
add('  }\n')
add('  tabs.forEach(b => b.addEventListener("click", () => activate(b.dataset.tab)));\n')
add('  window.addEventListener("beforeunload", () => document.body.classList.remove("board-fullscreen"));\n')
add('  // Bridge: keep .tool--active / .swatch--active in sync with legacy .active class used by whiteboard.js\n')
add('  const sync = () => {\n')
add('      document.querySelectorAll("#wbToolbar .wb-tool").forEach(b => {\n')
add('          b.classList.toggle("tool--active", b.classList.contains("active"));\n')
add('      });\n')
add('      document.querySelectorAll(".wb-color").forEach(b => {\n')
add('          b.classList.toggle("swatch--active", b.classList.contains("active"));\n')
add('      });\n')
add('  };\n')
add('  setTimeout(sync, 60);\n')
add('  document.addEventListener("click", (e) => {\n')
add('      if (e.target.closest && (e.target.closest(".wb-tool") || e.target.closest(".wb-color"))){\n')
add('          setTimeout(sync, 0);\n')
add('      }\n')
add('  });\n')
add('})();\n')
add('</script>\n\n')

add("<script src=\"{{ url_for('static', filename='js/drawing.js') }}?v={{ asset_version }}\"></script>\n")
add("<script src=\"{{ url_for('static', filename='js/whiteboard.js') }}?v={{ asset_version }}\"></script>\n")
add('{% endblock %}\n')

if __name__ == '__main__':
    text = ''.join(CHUNKS)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('Wrote', len(text), 'chars to', OUT)
