#!/usr/bin/env python3
"""Generate about.html for FORMYLA."""
import pathlib

BASE = pathlib.Path(__file__).resolve().parent.parent
out = BASE / "templates" / "about.html"

L = []
a = L.append

a('{% extends "base.html" %}')
a('{% block title %}О проекте FORMYLA{% endblock %}')
a('{% block extra_css %}')
a("<link rel=\"stylesheet\" href=\"{{ url_for('static', filename='css/about.css') }}?v={{ asset_version }}\">")
a('{% endblock %}')
a('{% block content %}')
a('<div class="about-page">')
a('')
a('  <section class="about-hero">')
a('    <h1 class="about-title">FORMYLA</h1>')
a('    <p class="about-subtitle">Единственная в России ИИ-платформа для подготовки к математическим олимпиадам с 7 специализированными агентами</p>')
a('  </section>')
a('')
# Stats
a('  <section class="about-section">')
a('    <div class="stats-grid">')
a('      <div class="stat-card"><div class="stat-num">3500+</div><div class="stat-label">задач в адаптивном тесте</div></div>')
a('      <div class="stat-card"><div class="stat-num">8000+</div><div class="stat-label">олимпиадных задач</div></div>')
a('      <div class="stat-card"><div class="stat-num">7</div><div class="stat-label">ИИ-агентов по темам</div></div>')
a('      <div class="stat-card"><div class="stat-num">5\u201311</div><div class="stat-label">классы</div></div>')
a('    </div>')
a('  </section>')
a('')
# How it works
a('  <section class="about-section">')
a('    <h2>\U0001f3af Как это работает</h2>')
a('    <div class="steps-grid">')
a('      <div class="step-card"><div class="step-number">1</div><h3>Пройди диагностику</h3><p>Адаптивный тест определит твой уровень и слабые темы за 10\u201315 минут.</p></div>')
a('      <div class="step-card"><div class="step-number">2</div><h3>Решай задачи дня</h3><p>Каждый день ты получаешь задачи, подобранные лично под твои пробелы.</p></div>')
a('      <div class="step-card"><div class="step-number">3</div><h3>Готовься с ИИ-тьютором</h3><p>7 агентов по темам разбирают задачи, дают подсказки и объясняют шаг за шагом.</p></div>')
a('      <div class="step-card"><div class="step-number">4</div><h3>Выходи на олимпиады</h3><p>База ВсОШ, Турнира городов, Эйлера \u2014 тренируйся на реальных задачах прошлых лет.</p></div>')
a('    </div>')
a('  </section>')
a('')
# Comparison table
a('  <section class="about-section">')
a('    <h2>\u26a1 Почему FORMYLA \u2014 единственная в своём роде в РФ</h2>')
a('    <div class="comparison-table-wrapper">')
a('      <table class="comparison-table">')
a('        <thead>')
a('          <tr><th>Возможность</th><th class="highlight-col">FORMYLA</th><th>Khanmigo</th><th>Photomath</th><th>Учи.ру</th></tr>')
a('        </thead>')
a('        <tbody>')
a('          <tr><td>Работает в РФ без VPN</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td>частично</td><td class="check">\u2713</td></tr>')
a('          <tr><td>Русский язык</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td>частично</td><td class="check">\u2713</td></tr>')
a('          <tr><td>7 специализированных ИИ-агентов</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td class="cross">\u2717</td><td class="cross">\u2717</td></tr>')
a('          <tr><td>База олимпиад РФ (ВсОШ, ТГ, Эйлер)</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td class="cross">\u2717</td><td>частично</td></tr>')
a('          <tr><td>Адаптивные задачи под слабые темы</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td class="cross">\u2717</td><td>частично</td></tr>')
a('          <tr><td>Радар навыков ученика</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td class="cross">\u2717</td><td class="cross">\u2717</td></tr>')
a('          <tr><td>Родитель видит прогресс ребёнка</td><td class="highlight-col check">\u2713</td><td class="cross">\u2717</td><td class="cross">\u2717</td><td>частично</td></tr>')
a('          <tr><td>Цена в месяц</td><td class="highlight-col"><strong>390 \u20bd</strong></td><td>~400 \u20bd</td><td>~950 \u20bd</td><td>990 \u20bd</td></tr>')
a('        </tbody>')
a('      </table>')
a('    </div>')
a('  </section>')
a('')
# For whom
a('  <section class="about-section">')
a('    <h2>\U0001f468\u200d\U0001f393 Для кого FORMYLA</h2>')
a('    <div class="features-grid">')
a('      <div class="feature-card"><span class="feature-icon">\U0001f4da</span><h3>Ученикам 5\u20137 класса</h3><p>Школьный этап ВсОШ, мат. раскраски, игры, \u00abРыцари и лжецы\u00bb. Развитие логики в формате, который не скучно.</p></div>')
a('      <div class="feature-card"><span class="feature-icon">\U0001f3c6</span><h3>Ученикам 8\u201311 класса</h3><p>Муниципальный, региональный и заключительный этапы. Турнир городов, Эйлер, Сириус. Готовься с ИИ-наставником.</p></div>')
a('      <div class="feature-card"><span class="feature-icon">\U0001f468\u200d\U0001f469\u200d\U0001f466</span><h3>Родителям</h3><p>Добавляйся \u00abв друзья\u00bb к ребёнку: смотри прогресс, слабые темы и серии решённых задач в реальном времени.</p></div>')
a('      <div class="feature-card"><span class="feature-icon">\U0001f469\u200d\U0001f3eb</span><h3>Учителям</h3><p>Готовая база задач с решениями. Используй FORMYLA как кружок подготовки к олимпиадам.</p></div>')
a('    </div>')
a('  </section>')
a('')
# AI Agents
a('  <section class="about-section">')
a('    <h2>\U0001f916 Наши ИИ-агенты</h2>')
a('    <div class="features-grid agents-grid">')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f4d0</span><h3>Алгебра</h3><p>Уравнения, неравенства, выражения.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f4cf</span><h3>Геометрия</h3><p>Планиметрия, углы, площади, фигуры.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f522</span><h3>Теория чисел</h3><p>Делимость, остатки, простые числа.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f3b2</span><h3>Комбинаторика</h3><p>Подсчёт, перебор, логика конструкций.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f680</span><h3>Задачи на движение</h3><p>Встречное движение, догонка, скорость.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f9e9</span><h3>Логика</h3><p>Рыцари и лжецы, раскраски, мат. игры.</p></div>')
a('      <div class="feature-card agent-card"><span class="feature-icon">\U0001f3c5</span><h3>Агент-наставник</h3><p>Советы по стратегии олимпиад, план подготовки, психология экзамена.</p></div>')
a('    </div>')
a('  </section>')
a('')
# Pricing
a('  <section class="about-section">')
a('    <h2>\U0001f48e Тарифы</h2>')
a('    <div class="plans-row">')
a('      <div class="plan-box plan-free">')
a('        <h3>Free</h3>')
a('        <div class="plan-price-tag">0 \u20bd / навсегда</div>')
a('        <ul>')
a('          <li>3 задачи дня</li>')
a('          <li>1 олимпиадный вариант в неделю</li>')
a('          <li>10 сообщений ИИ-тьютору в день</li>')
a('          <li>Базовый Радар навыков</li>')
a('          <li>Сообщество и Telegram-канал</li>')
a('        </ul>')
a('        <a href="/login" class="plan-btn plan-btn-free">Начать бесплатно</a>')
a('      </div>')
a('      <div class="plan-box plan-pro">')
a('        <div class="plan-badge-pro">\u2b50 PRO</div>')
a('        <h3>Pro</h3>')
a('        <div class="plan-price-tag">390 \u20bd / месяц</div>')
a('        <ul>')
a('          <li>Безлимит задач и олимпиад</li>')
a('          <li>Безлимит сообщений ИИ-тьютору</li>')
a('          <li>Все 7 специализированных агентов</li>')
a('          <li>Полный Радар навыков + еженедельный анализ</li>')
a('          <li>Родительский доступ к прогрессу</li>')
a('          <li>Проверка фото решений</li>')
a('          <li>Приоритетная поддержка</li>')
a('        </ul>')
a('        <a href="/subscribe" class="plan-btn plan-btn-pro">Оформить Pro</a>')
a('      </div>')
a('    </div>')
a('    <p class="guarantee">\U0001f6e1\ufe0f <strong>Гарантия возврата</strong> \u2014 Не понравилось в первые 7 дней? Вернём деньги без вопросов.</p>')
a('  </section>')
a('')
# Founder
a('  <section class="about-section founder-section">')
a('    <h2>\U0001f44b История проекта</h2>')
a('    <div class="founder-card">')
a('      <div class="founder-avatar">V</div>')
a('      <div class="founder-text">')
a('        <p><strong>Привет, я Виктор \u2014 основатель FORMYLA</strong></p>')
a('        <p>Мне 14 лет, и я сам готовился к олимпиадам по математике. Мне надоело переключаться между десятком сайтов: где-то задачи, где-то разборы, где-то ИИ, но на английском.</p>')
a('        <p>Я собрал FORMYLA \u2014 место, где всё в одном интерфейсе: адаптивный тест, задачи под слабые темы, разборы от 7 ИИ-агентов и полная база олимпиад РФ. То, что я хотел видеть сам.</p>')
a('      </div>')
a('    </div>')
a('  </section>')
a('')
# FAQ
a('  <section class="about-section">')
a('    <h2>\u2753 Частые вопросы</h2>')
a('    <div class="faq-list">')
faqs = [
    ("Для какого класса подходит FORMYLA?", "Для учеников 5\u201311 классов. Задачи адаптируются под уровень \u2014 от школьного этапа до заключительного."),
    ("Нужен ли VPN?", "Нет. FORMYLA работает в России без VPN, все серверы в РФ."),
    ("Чем FORMYLA отличается от ChatGPT?", "FORMYLA \u2014 это не просто чат. Это 7 специализированных агентов, адаптивный тест, база 8000+ олимпиадных задач и система отслеживания прогресса."),
    ("Можно ли отменить подписку?", "Да, в любой момент из профиля. После отмены доступ сохраняется до конца оплаченного периода."),
    ("Как родители могут следить за прогрессом?", "Добавьте ребёнка \u00abв друзья\u00bb по никнейму \u2014 вы увидите его Радар навыков, серии и результаты тестов."),
    ("Безопасно ли ИИ для ребёнка?", "Да. Наши агенты работают только в контексте математики и не отвечают на посторонние темы."),
    ("Что если ребёнку не подошло?", "Гарантия возврата 7 дней. Напишите нам \u2014 вернём деньги без вопросов."),
    ("Есть ли мобильное приложение?", "Пока нет, но сайт полностью адаптирован под мобильные устройства. Приложение в планах на 2026."),
]
for q, ans in faqs:
    a(f'      <div class="faq-item"><div class="faq-q" onclick="this.parentElement.classList.toggle(\'open\')">{q} <span class="faq-arrow">\u25bc</span></div><div class="faq-a">{ans}</div></div>')
a('    </div>')
a('  </section>')
a('')
# Telegram
a('  <section class="about-section">')
a('    <h2>\U0001f4ec Присоединяйся</h2>')
a('    <p>Подписывайся на наш Telegram-канал \u2014 там задачи дня, разборы олимпиад и анонсы новых фич.</p>')
a('    <a href="https://t.me/FormylaMaths" target="_blank" class="tg-btn">\U0001f4e8 @FormylaMaths</a>')
a('  </section>')
a('')
# Support form
a('  <section class="about-section support-section">')
a('    <h2>\U0001f4ac Связаться с нами</h2>')
a('    <p>Нашли баг? Есть идея? Не получается решить? Напиши нам \u2014 ответим в Telegram-канале или на почту.</p>')
a('    <form id="support-form" class="support-form">')
a('      <div class="form-row">')
a('        <label>Тип обращения</label>')
a('        <select name="category" required>')
a('          <option value="bug">\U0001f41b Баг / ошибка</option>')
a('          <option value="suggestion">\U0001f4a1 Идея / предложение</option>')
a('          <option value="question">\u2753 Вопрос</option>')
a('          <option value="other" selected>\u2709\ufe0f Другое</option>')
a('        </select>')
a('      </div>')
a('      <div class="form-row">')
a('        <label>Email <span class="muted">(необязательно)</span></label>')
a('        <input type="email" name="email" placeholder="чтобы мы могли ответить">')
a('      </div>')
a('      <div class="form-row">')
a('        <label>Сообщение</label>')
a('        <textarea name="message" required minlength="5" maxlength="4000" rows="6" placeholder="Опиши проблему или идею..."></textarea>')
a('        <div class="char-count"><span id="char-current">0</span> / 4000</div>')
a('      </div>')
a('      <button type="submit" class="submit-btn">Отправить</button>')
a('      <div id="support-result" class="form-result"></div>')
a('    </form>')
a('  </section>')
a('')
a('</div>')
a('')
# JS
a('<script>')
a('const form = document.getElementById("support-form");')
a('const ta = form.querySelector(\'textarea[name="message"]\');')
a('const counter = document.getElementById("char-current");')
a('const result = document.getElementById("support-result");')
a('ta.addEventListener("input", () => { counter.textContent = ta.value.length; });')
a('form.addEventListener("submit", async (e) => {')
a('  e.preventDefault();')
a('  result.textContent = "Отправка...";')
a('  result.className = "form-result loading";')
a('  const data = { category: form.category.value, email: form.email.value.trim(), message: ta.value.trim(), page_url: window.location.href };')
a('  try {')
a('    const r = await fetch("/api/support", { method: "POST", headers: {"Content-Type": "application/json"}, credentials: "include", body: JSON.stringify(data) });')
a('    let j; try { j = await r.json(); } catch (_) { j = {}; }')
a('    if (r.ok && j.ok) { result.textContent = "\u2705 Спасибо! Мы получили ваше сообщение."; result.className = "form-result ok"; form.reset(); counter.textContent = "0"; }')
a('    else { result.textContent = "\u274c " + (j.error || "Ошибка отправки"); result.className = "form-result err"; }')
a('  } catch (err) { result.textContent = "\u274c Нет соединения. Попробуйте позже."; result.className = "form-result err"; }')
a('});')
a('</script>')
a('')
a('{% endblock %}')

out.write_text('\n'.join(L), encoding='utf-8')
print(f"Written {len(L)} lines to {out}")
