#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate services/daily_pool/meta_reviewer.py"""
import os, sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = os.path.join(BASE, "services", "daily_pool", "meta_reviewer.py")

B1 = chr(123)
B2 = chr(125)

# Build source using list of lines - no f-strings, no braces in content
L = []
L.append('# -*- coding: utf-8 -*-')
L.append('"""')
L.append('Meta Reviewer service: reviews complete 5-problem variant for coherence.')
L.append('Called ONCE after all 5 problems are generated and individually approved.')
L.append('"""')
L.append('import json')
L.append('import logging')
L.append('')
L.append('from services.openrouter_client import openrouter')
L.append('')
L.append('logger = logging.getLogger(__name__)')
L.append('')
L.append('MODEL = "anthropic/claude-opus-4.1"')
L.append('TEMPERATURE = 0.2')
L.append('MAX_META_RETRIES = 2')
L.append('')
L.append('SYSTEM_MSG = (')
L.append('    ' + repr('Ты — главный редактор олимпиадного сборника. '))
L.append('    ' + repr('Проверь ВАРИАНТ ЦЕЛИКОМ (5 задач) на внутреннюю согласованность.'))
L.append(')')
L.append('')
L.append('')
L.append('def review_variant(problems: list, analysis: dict, variant_date: str) -> dict:')
L.append('    """')
L.append('    Review a complete variant (5 problems) for internal consistency.')
L.append('')
L.append('    Args:')
L.append('        problems: list of 5 dicts with statement, answer, topic, difficulty')
L.append('        analysis: analysis profile dict')
L.append('        variant_date: date string')
L.append('')
L.append('    Returns dict with verdict, checks, issues, reject_positions, suggestions.')
L.append('    """')
L.append('    prompt = _build_prompt(problems, analysis, variant_date)')
L.append('')
L.append('    result = openrouter.chat(')
L.append('        model=MODEL,')
L.append('        messages=[')
L.append('            dict(role="system", content=SYSTEM_MSG),')
L.append('            dict(role="user", content=prompt)')
L.append('        ],')
L.append('        temperature=TEMPERATURE,')
L.append('        max_tokens=2048,')
L.append('    )')
L.append('')
L.append('    content = result["content"]')
L.append('    try:')
L.append('        if "```json" in content:')
L.append('            content = content.split("```json")[1].split("```")[0]')
L.append('        elif "```" in content:')
L.append('            content = content.split("```")[1].split("```")[0]')
L.append('        data = json.loads(content.strip())')
L.append('    except json.JSONDecodeError:')
L.append('        logger.error(f"[MetaReview] JSON parse error: ' + B1 + 'content[:200]' + B2 + '")')
L.append('        raise ValueError("MetaReview returned invalid JSON")')
L.append('')
L.append('    # Ensure all expected keys exist')
L.append('    for key in ["theme_diversity", "difficulty_progression", "style_consistency",')
L.append('               "no_overlaps", "balance_ok"]:')
L.append('        if key not in data:')
L.append('            data[key] = True')
L.append('')
L.append('    data.setdefault("issues", [])')
L.append('    data.setdefault("reject_positions", [])')
L.append('    data.setdefault("suggestions", [])')
L.append('')
L.append('    # Override verdict based on checks')
L.append('    all_ok = all(data.get(k, True) for k in [')
L.append('        "theme_diversity", "difficulty_progression",')
L.append('        "style_consistency", "no_overlaps", "balance_ok"')
L.append('    ])')
L.append('    if all_ok and not data.get("reject_positions"):')
L.append('        data["verdict"] = "approve"')
L.append('    else:')
L.append('        data["verdict"] = "reject"')
L.append('')
L.append('    data["_usage"] = result["usage"]')
L.append('    data["_cost"] = result["cost_usd"]')
L.append('')
L.append("    openrouter.log_cost_to_db('meta_review', MODEL, result['usage'], result['cost_usd'])")
L.append('    logger.info(')
L.append('        f"[MetaReview] verdict=' + B1 + "data['verdict']" + B2 + ' "')
L.append('        f"reject_pos=' + B1 + "data['reject_positions']" + B2 + ' "')
L.append('        f"${' + B1 + "result['cost_usd']:.4f" + B2 + '}"')
L.append('    )')
L.append('    return data')
L.append('')
L.append('')
L.append('def _build_prompt(problems: list, analysis: dict, variant_date: str) -> str:')
L.append('    """Build the meta review prompt with all 5 problems."""')
L.append('    sep = chr(9552) * 51')
L.append('    olympiad = analysis.get("olympiad", "")')
L.append('    grade = analysis.get("grade", "")')
L.append('    round_name = analysis.get("round", "")')
L.append('    style_notes = json.dumps(analysis.get("style_notes", dict()), ensure_ascii=False)')
L.append('    themes_dist = json.dumps(analysis.get("themes_distribution", dict()), ensure_ascii=False)')
L.append('    predicted = analysis.get("predicted_variant", [])')
L.append('    expected_diffs = ", ".join(str(p.get("difficulty", "?")) for p in predicted)')
L.append('')
L.append('    header = (')
L.append('        f"' + chr(1054) + chr(1051) + chr(1048) + chr(1052) + chr(1055) + chr(1048) + chr(1040) + chr(1044) + chr(1040) + ': ' + B1 + 'olympiad' + B2 + ', ' + B1 + 'grade' + B2 + ' ' + chr(1082) + chr(1083) + chr(1072) + chr(1089) + chr(1089) + ', ' + B1 + 'round_name' + B2 + '\\n"')
L.append('        f"' + chr(1044) + chr(1040) + chr(1058) + chr(1040) + ' ' + chr(1042) + chr(1040) + chr(1056) + chr(1048) + chr(1040) + chr(1053) + chr(1058) + chr(1040) + ': ' + B1 + 'variant_date' + B2 + '"')
L.append('    )')
L.append('')
L.append('    problems_text = ""')
L.append('    for i, p in enumerate(problems, 1):')
L.append('        topic = p.get("topic", "?")')
L.append('        diff = p.get("difficulty", "?")')
L.append('        stmt = p.get("statement", "")')
L.append('        ans = p.get("answer", "")')
L.append('        problems_text += (')
L.append('            f"\\n' + chr(1047) + chr(1040) + chr(1044) + chr(1040) + chr(1063) + chr(1040) + ' ' + B1 + 'i' + B2 + ' (' + chr(1090) + chr(1077) + chr(1084) + chr(1072) + ': ' + B1 + 'topic' + B2 + ', ' + chr(1089) + chr(1083) + chr(1086) + chr(1078) + chr(1085) + chr(1086) + chr(1089) + chr(1090) + chr(1100) + ': ' + B1 + 'diff' + B2 + '/10):\\n"')
L.append('            f"' + B1 + 'stmt' + B2 + '\\n"')
L.append('            f"' + chr(1054) + chr(1090) + chr(1074) + chr(1077) + chr(1090) + ': ' + B1 + 'ans' + B2 + '\\n"')
L.append('        )')
L.append('')
L.append('    checks = (')
L.append('        {