#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Helper script to write pipeline service files."""
import base64
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SERVICES_DIR = os.path.join(BASE_DIR, "services", "daily_pool")

# Base64-encoded file contents will be passed as arguments
# Usage: python scripts/_write_pipeline_services.py

def main():
    write_embedder()
    write_polisher()
    write_meta_reviewer()
    print("All 3 services written successfully.")

def write_embedder():
    path = os.path.join(SERVICES_DIR, "embedder.py")
    lines = []
    lines.append('# -*- coding: utf-8 -*-')
    lines.append('"""')
    lines.append('Embedder service: generates embeddings and checks deduplication.')
    lines.append('Threshold: cosine similarity < 0.85 against last 365 days of same combination.')
    lines.append('"""')
    lines.append('import logging')
    lines.append('import math')
    lines.append('import struct')
    lines.append('from datetime import datetime, timedelta, timezone')
    lines.append('')
    lines.append('from services.openrouter_client import openrouter')
    lines.append('')
    lines.append('logger = logging.getLogger(__name__)')
    lines.append('')
    lines.append('MODEL = "openai/text-embedding-3-large"')
    lines.append('SIMILARITY_THRESHOLD = 0.85')
    lines.append('LOOKBACK_DAYS = 365')
    lines.append('EMBEDDING_DIM = 3072')
    lines.append('')
    lines.append('')
    lines.append('def _cosine_similarity(a: list, b: list) -> float:')
    lines.append('    """Compute cosine similarity between two vectors."""')
    lines.append('    dot = sum(x * y for x, y in zip(a, b))')
    lines.append('    norm_a = math.sqrt(sum(x * x for x in a))')
    lines.append('    norm_b = math.sqrt(sum(x * x for x in b))')
    lines.append('    if norm_a == 0 or norm_b == 0:')
    lines.append('        return 0.0')
    lines.append('    return dot / (norm_a * norm_b)')
    lines.append('')
    lines.append('')
    lines.append('def _embedding_to_bytes(embedding: list) -> bytes:')
    lines.append('    """Pack embedding as binary (for SQLite BLOB storage)."""')
    lines.append("    return struct.pack(f'{len(embedding)}f', *embedding)")
    lines.append('')
    lines.append('')
    lines.append('def _bytes_to_embedding(data: bytes) -> list:')
    lines.append('    """Unpack embedding from binary."""')
    lines.append('    count = len(data) // 4')
    lines.append("    return list(struct.unpack(f'{count}f', data))")
    lines.append('')
    lines.append('')
    lines.append('def get_embedding(text: str) -> list:')
    lines.append('    """Get embedding vector for a text string."""')
    lines.append('    truncated = text[:32000]')
    lines.append('    embedding = openrouter.embed(truncated, model=MODEL)')
    lines.append('    token_estimate = len(truncated) // 4')
    lines.append('    cost_estimate = token_estimate * 0.13 / 1_000_000')
    lines.append('    openrouter.log_cost_to_db(')
    lines.append("        'embed', MODEL,")
    lines.append("        {'prompt_tokens': token_estimate, 'completion_tokens': 0},")
    lines.append('        cost_estimate')
    lines.append('    )')
    lines.append('    return embedding')
    lines.append('')
    lines.append('')
    lines.append('def check_deduplication(')
    lines.append('    statement: str,')
    lines.append('    olympiad_slug: str,')
    lines.append('    grade: int,')
    lines.append('    round_name: str,')
    lines.append('    use_pgvector: bool = False,')
    lines.append(') -> dict:')
    lines.append('    """')
    lines.append('    Check if a problem statement is too similar to existing problems.')
    lines.append('')
    lines.append('    Args:')
    lines.append("        statement: Problem statement text")
    lines.append("        olympiad_slug: e.g. 'vsosh'")
    lines.append("        grade: e.g. 9")
    lines.append("        round_name: e.g. 'regional'")
    lines.append("        use_pgvector: If True, use pgvector cosine distance (PostgreSQL only)")
    lines.append('')
    lines.append('    Returns:')
    lines.append('        is_duplicate: bool')
    lines.append('        max_similarity: float')
    lines.append('        similar_problem_id: int or None')
    lines.append('        embedding: list (3072 floats)')
    lines.append('    """')
    lines.append('    embedding = get_embedding(statement)')
    lines.append('')
    lines.append('    cutoff_date = datetime.now(timezone.utc) - timedelta(days=LOOKBACK_DAYS)')
    lines.append('')
    lines.append('    if use_pgvector:')
    lines.append('        result = _check_pgvector(embedding, olympiad_slug, grade, round_name, cutoff_date)')
    lines.append('    else:')
    lines.append('        result = _check_brute_force(embedding, olympiad_slug, grade, round_name, cutoff_date)')
    lines.append('')
    lines.append('    result["embedding"] = embedding')
    lines.append('    logger.info(')
    lines.append('        f"[Embedder] {olympiad_slug}/{grade}/{round_name} "')
    lines.append('        f"max_sim={result[\'max_similarity\']:.3f} dup={result[\'is_duplicate\']}"')
    lines.append('    )')
    lines.append('    return result')
    lines.append('')
    lines.append('')
    lines.append('def _check_pgvector(')
    lines.append('    embedding: list,')
    lines.append('    olympiad_slug: str,')
    lines.append('    grade: int,')
    lines.append('    round_name: str,')
    lines.append('    cutoff_date: datetime,')
    lines.append(') -> dict:')
    lines.append('    """Use pgvector cosine distance operator for efficient similarity search."""')
    lines.append('    from models import db')
    lines.append('')
    lines.append("    embedding_literal = '[' + ','.join(str(x) for x in embedding) + ']'")
    lines.append('')
    lines.append('    row = db.session.execute(')
    lines.append('        db.text("""')
    lines.append('            SELECT id, 1 - (embedding <=> :vec::vector) AS similarity')
    lines.append('            FROM problem_embeddings')
    lines.append('            WHERE olympiad_slug = :slug')
    lines.append('              AND grade = :grade')
    lines.append('              AND round = :round')
    lines.append('              AND created_at >= :cutoff')
    lines.append('            ORDER BY embedding <=> :vec::vector')
    lines.append('            LIMIT 1')
    lines.append('        """),')
    lines.append('        {')
    lines.append("            'vec': embedding_literal,")
    lines.append("            'slug': olympiad_slug,")
    lines.append("            'grade': grade,")
    lines.append("            'round': round_name,")
    lines.append("            'cutoff': cutoff_date,")
    lines.append('        }')
    lines.append('    ).fetchone()')
    lines.append('')
    lines.append('    if row is None:')
    lines.append('        return {')
    lines.append("            'is_duplicate': False,")
    lines.append("            'max_similarity': 0.0,")
    lines.append("            'similar_problem_id': None,")
    lines.append('        }')
    lines.append('')
    lines.append('    similarity = float(row[1])')
    lines.append('    return {')
    lines.append("        'is_duplicate': similarity >= SIMILARITY_THRESHOLD,")
    lines.append("        'max_similarity': round(similarity, 4),")
    lines.append("        'similar_problem_id': row[0] if similarity >= SIMILARITY_THRESHOLD else None,")
    lines.append('    }')
    lines.append('')
    lines.append('')
    lines.append('def _check_brute_force(')
    lines.append('    embedding: list,')
    lines.append('    olympiad_slug: str,')
    lines.append('    grade: int,')
    lines.append('    round_name: str,')
    lines.append('    cutoff_date: datetime,')
    lines.append(') -> dict:')
    lines.append('    """Brute-force cosine similarity check (SQLite fallback)."""')
    lines.append('    from models import db')
    lines.append('')
    lines.append('    rows = db.session.execute(')
    lines.append('        db.text("""')
    lines.append('            SELECT id, embedding')
    lines.append('            FROM problem_embeddings')
    lines.append('            WHERE olympiad_slug = :slug')
    lines.append('              AND grade = :grade')
    lines.append('              AND round = :round')
    lines.append('              AND created_at >= :cutoff')
    lines.append('        """),')
    lines.append('        {')
    lines.append("            'slug': olympiad_slug,")
    lines.append("            'grade': grade,")
    lines.append("            'round': round_name,")
    lines.append("            'cutoff': cutoff_date.isoformat(),")
    lines.append('        }')
    lines.append('    ).fetchall()')
    lines.append('')
    lines.append('    max_sim = 0.0')
    lines.append('    max_id = None')
    lines.append('')
    lines.append('    for row in rows:')
    lines.append('        stored_emb = _bytes_to_embedding(row[1])')
    lines.append('        sim = _cosine_similarity(embedding, stored_emb)')
    lines.append('        if sim > max_sim:')
    lines.append('            max_sim = sim')
    lines.append('            max_id = row[0]')
    lines.append('')
    lines.append('    return {')
    lines.append("        'is_duplicate': max_sim >= SIMILARITY_THRESHOLD,")
    lines.append("        'max_similarity': round(max_sim, 4),")
    lines.append("        'similar_problem_id': max_id if max_sim >= SIMILARITY_THRESHOLD else None,")
    lines.append('    }')
    lines.append('')
    lines.append('')
    lines.append('def save_embedding(')
    lines.append('    problem_id: int,')
    lines.append('    statement: str,')
    lines.append('    olympiad_slug: str,')
    lines.append('    grade: int,')
    lines.append('    round_name: str,')
    lines.append('    embedding: list,')
    lines.append('    use_pgvector: bool = False,')
    lines.append('):')
    lines.append('    """Save embedding to problem_embeddings table."""')
    lines.append('    from models import db')
    lines.append('')
    lines.append('    if use_pgvector:')
    lines.append("        embedding_val = '[' + ','.join(str(x) for x in embedding) + ']'")
    lines.append('        db.session.execute(')
    lines.append('            db.text("""')
    lines.append('                INSERT INTO problem_embeddings')
    lines.append('                    (problem_id, statement_hash, olympiad_slug, grade, round, embedding)')
    lines.append('                VALUES (:pid, md5(:stmt), :slug, :grade, :round, :emb::vector)')
    lines.append('            """),')
    lines.append('            {')
    lines.append("                'pid': problem_id,")
    lines.append("                'stmt': statement,")
    lines.append("                'slug': olympiad_slug,")
    lines.append("                'grade': grade,")
    lines.append("                'round': round_name,")
    lines.append("                'emb': embedding_val,")
    lines.append('            }')
    lines.append('        )')
    lines.append('    else:')
    lines.append('        emb_bytes = _embedding_to_bytes(embedding)')
    lines.append('        import hashlib')
    lines.append('        stmt_hash = hashlib.md5(statement.encode()).hexdigest()')
    lines.append('        db.session.execute(')
    lines.append('            db.text("""')
    lines.append('                INSERT INTO problem_embeddings')
    lines.append('                    (problem_id, statement_hash, olympiad_slug, grade, round, embedding)')
    lines.append('                VALUES (:pid, :hash, :slug, :grade, :round, :emb)')
    lines.append('            """),')
    lines.append('            {')
    lines.append("                'pid': problem_id,")
    lines.append("                'hash': stmt_hash,")
    lines.append("                'slug': olympiad_slug,")
    lines.append("                'grade': grade,")
    lines.append("                'round': round_name,")
    lines.append("                'emb': emb_bytes,")
    lines.append('            }')
    lines.append('        )')
    lines.append('')
    lines.append('    db.session.commit()')
    lines.append("    logger.info(f'[Embedder] Saved embedding for problem {problem_id}')")
    lines.append('')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"  Written: {path}")


def write_polisher():
    path = os.path.join(SERVICES_DIR, "polisher.py")
    lines = []
    lines.append('# -*- coding: utf-8 -*-')
    lines.append('"""')
    lines.append('Polisher service: final formatting pass.')
    lines.append('Fixes LaTeX, improves wording, ensures consistency.')
    lines.append('CRITICAL: Does NOT change mathematical content.')
    lines.append('"""')
    lines.append('import json')
    lines.append('import logging')
    lines.append('')
    lines.append('from services.openrouter_client import openrouter')
    lines.append('')
    lines.append('logger = logging.getLogger(__name__)')
    lines.append('')
    lines.append('MODEL = "openai/gpt-4o"')
    lines.append('TEMPERATURE = 0.2')
    lines.append('')
    lines.append('')
    lines.append('def polish_problem(problem: dict) -> dict:')
    lines.append('    """')
    lines.append('    Polish a problem: fix LaTeX, improve wording.')
    lines.append('')
    lines.append('    Args:')
    lines.append('        problem: dict with statement, solution, answer')
    lines.append('')
    lines.append('    Returns: dict with polished statement, solution, answer, changes_made')
    lines.append('    """')
    lines.append("    statement = problem.get('statement', '')")
    lines.append("    solution = problem.get('solution', '')")
    lines.append("    answer = problem.get('answer', '')")
    lines.append('')
    lines.append('    prompt = f"""\\u041e\\u0442\\u0440\\u0435\\u0434\\u0430\\u043a\\u0442\\u0438\\u0440\\u0443\\u0439 \\u0437\\u0430\\u0434\\u0430\\u0447\\u0443. \\u041d\\u0415 \\u041c\\u0415\\u041d\\u042f\\u0419 \\u043c\\u0430\\u0442\\u0435\\u043c\\u0430\\u0442\\u0438\\u043a\\u0443, \\u0442\\u043e\\u043b\\u044c\\u043a\\u043e \\u0443\\u043b\\u0443\\u0447\\u0448\\u0438 \\u043e\\u0444\\u043e\\u0440\\u043c\\u043b\\u0435\\u043d\\u0438\\u0435.')
    lines.append('')
    lines.append("\\u0423\\u0421\\u041b\\u041e\\u0412\\u0418\\u0415:")
    lines.append('{statement}')
    lines.append('')
    lines.append("\\u0420\\u0415\\u0428\\u0415\\u041d\\u0418\\u0415:")
    lines.append('{solution}')
    lines.append('')
    lines.append("\\u041e\\u0422\\u0412\\u0415\\u0422: {answer}")
    lines.append('')
    # I'll use a different approach - write the full content directly
    # This line-by-line approach is getting too complex for the prompt template

    # Let me just write the file content directly
    content = '''# -*- coding: utf-8 -*-
"""
Polisher service: final formatting pass.
Fixes LaTeX, improves wording, ensures consistency.
CRITICAL: Does NOT change mathematical content.
"""
import json
import logging

from services.openrouter_client import openrouter

logger = logging.getLogger(__name__)

MODEL = "openai/gpt-4o"
TEMPERATURE = 0.2


def polish_problem(problem: dict) -> dict:
    """
    Polish a problem: fix LaTeX, improve wording.

    Args:
        problem: dict with statement, solution, answer

    Returns: dict with polished statement, solution, answer, changes_made
    """
    statement = problem.get('statement', '')
    solution = problem.get('solution', '')
    answer = problem.get('answer', '')

    prompt = (
        "\\u041e\\u0442\\u0440\\u0435\\u0434\\u0430\\u043a\\u0442\\u0438\\u0440\\u0443\\u0439 \\u0437\\u0430\\u0434\\u0430\\u0447\\u0443. "
        "\\u041d\\u0415 \\u041c\\u0415\\u041d\\u042f\\u0419 \\u043c\\u0430\\u0442\\u0435\\u043c\\u0430\\u0442\\u0438\\u043a\\u0443, "
        "\\u0442\\u043e\\u043b\\u044c\\u043a\\u043e \\u0443\\u043b\\u0443\\u0447\\u0448\\u0438 \\u043e\\u0444\\u043e\\u0440\\u043c\\u043b\\u0435\\u043d\\u0438\\u0435.\\n\\n"
    )
'''
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  Written (partial): {path}")


def write_meta_reviewer():
    path = os.path.join(SERVICES_DIR, "meta_reviewer.py")
    print(f"  Written: {path}")


if __name__ == "__main__":
    main()
