#!/usr/bin/env python3
import os
target = os.path.join("scripts", "analyze_latex_issues.py")
with open(target, "w", encoding="utf-8") as f:
    f.write("#!/usr/bin/env python3\n")
    f.write('"""\nAnalyze LaTeX issues in adaptive tasks.\n"""\n')
    f.write("import sqlite3, re, json, os\n")
    f.write("from collections import defaultdict\n")
    f.write("from datetime import datetime\n\n")
    f.write('DB_PATH = os.path.join("instance", "formyla.db")\n')
    f.write('REPORT_DIR = os.path.join("data", "audit")\n')
    f.write('JSON_REPORT = os.path.join(REPORT_DIR, "latex_issues_report.json")\n')
    f.write('MD_REPORT = os.path.join(REPORT_DIR, "latex_issues_report.md")\n')
    f.write("MAX_SAMPLES = 5\n\n")
    f.write("LATEX_N_CMDS = {\n")
    f.write("    'neq','nabla','notin','neg','nu','nleq','ngeq','nmid',\n")
    f.write("    'nsubseteq','nsupseteq','ncong','nsim','nrightarrow',\n")
    f.write("    'nleftarrow','not','newline','newcommand','nolimits',\n")
    f.write("    'nonumber','nparallel'\n")
    f.write("}\n\n\n")
    # check_literal_backslash_n
    f.write("def check_literal_backslash_n(text):\n")
    f.write('    """A) HAS_LITERAL_BACKSLASH_N"""\n')
    f.write("    BS2N = chr(92)*2 + 'n'\n")
    f.write("    if BS2N in text:\n")
    f.write("        return True\n")
    f.write("    for m in re.finditer(chr(92)+chr(92)+'n', text):\n")
    f.write("        pos = m.end()\n")
    f.write("        if m.start() > 0 and text[m.start()-1] == chr(92):\n")
    f.write("            continue\n")
    f.write("        if pos < len(text) and text[pos].isalpha():\n")
    f.write("            rest = text[pos:]\n")
    f.write("            skip = any(rest.startswith(c[1:]) for c in LATEX_N_CMDS)\n")
    f.write("            if skip:\n")
    f.write("                continue\n")
    f.write("            return True\n")
    f.write("        else:\n")
    f.write("            return True\n")
    f.write("    return False\n\n\n")
    # check_hline_outside_env
    f.write("def check_hline_outside_env(text):\n")
    f.write('    """B) HLINE_OUTSIDE_ENV"""\n')
    f.write("    BS = chr(92)\n")
    f.write("    if BS+'hline' not in text:\n")
    f.write("        return False\n")
    f.write("    env_pat = r'" + "\\\\begin\\{(array|matrix|pmatrix|bmatrix|vmatrix|tabular)\\}" + "'\n")
    f.write("    if re.search(env_pat, text):\n")
    f.write("        envs = list(re.finditer(env_pat, text))\n")
    f.write("        end_pat = r'" + "\\\\end\\{(array|matrix|pmatrix|bmatrix|vmatrix|tabular)\\}" + "'\n")
    f.write("        ends = list(re.finditer(end_pat, text))\n")
    f.write("        for hl in re.finditer(r'" + "\\\\hline" + "', text):\n")
    f.write("            inside = False\n")
    f.write("            for es, ee in zip(envs, ends):\n")
    f.write("                if es.start() < hl.start() < ee.end():\n")
    f.write("                    inside = True\n")
    f.write("                    break\n")
    f.write("            if not inside:\n")
    f.write("                return True\n")
    f.write("        return False\n")
    f.write("    else:\n")
    f.write("        return True\n\n\n")
    # build_math_map
    f.write("def build_math_map(text):\n")
    f.write('    """Build boolean map of math mode positions."""\n')
    f.write("    n = len(text)\n")
    f.write("    in_math = [False] * n\n")
    f.write("    i = 0\n")
    f.write("    BS = chr(92)\n")
    f.write("    while i < n:\n")
    f.write("        if i < n-1 and text[i] == BS and text[i+1] == '(':\n")
    f.write("            j = text.find(BS+')', i+2)\n")
    f.write("            if j != -1:\n")
    f.write("                for k in range(i, min(j+2, n)): in_math[k] = True\n")
    f.write("                i = j + 2\n")
    f.write("                continue\n")
    f.write("        if i < n-1 and text[i] == BS and text[i+1] == '[':\n")
    f.write("            j = text.find(BS+']', i+2)\n")
    f.write("            if j != -1:\n")
    f.write("                for k in range(i, min(j+2, n)): in_math[k] = True\n")
    f.write("                i = j + 2\n")
    f.write("                continue\n")
    f.write("        if i < n-1 and text[i] == '$' and text[i+1] == '$':\n")
    f.write("            j = text.find('$$', i+2)\n")
    f.write("            if j != -1:\n")
    f.write("                for k in range(i, min(j+2, n)): in_math[k] = True\n")
    f.write("                i = j + 2\n")
    f.write("                continue\n")
    f.write("            else:\n")
    f.write("                i += 2\n")
    f.write("                continue\n")
    f.write("        if text[i] == '$':\n")
    f.write("            j = text.find('$', i+1)\n")
    f.write("            if j != -1:\n")
    f.write("                for k in range(i, j+1): in_math[k] = True\n")
    f.write("                i = j + 1\n")
    f.write("                continue\n")
    f.write("            else:\n")
    f.write("                i += 1\n")
    f.write("                continue\n")
    f.write("        i += 1\n")
    f.write("    return in_math\n\n\n")
    # check_bare_sqrt_frac
    f.write("def check_bare_sqrt_frac(text):\n")
    f.write('    """C) BARE_SQRT_FRAC"""\n')
    f.write("    latex_cmds = list(re.finditer(r'" + "\\\\(sqrt|frac)\\b" + "', text))\n")
    f.write("    if not latex_cmds:\n")
    f.write("        return False\n")
    f.write("    in_math = build_math_map(text)\n")
    f.write("    for m in latex_cmds:\n")
    f.write("        if not in_math[m.start()]:\n")
    f.write("            return True\n")
    f.write("    return False\n\n\n")
    # check_lsqrtl_pattern
    f.write("def check_lsqrtl_pattern(text):\n")
    f.write('    """D) LSQRTL_PATTERN"""\n')
    f.write("    return bool(re.search(r'l(sqrt|frac|cdot)l', text, re.IGNORECASE))\n\n\n")
    # check_unclosed_dollar
    f.write("def check_unclosed_dollar(text):\n")
    f.write('    """E) UNCLOSED_DOLLAR"""\n')
    f.write("    cleaned = text.replace('$$', '')\n")
    f.write("    return cleaned.count('$') % 2 != 0\n\n\n")
    # check_russian_in_latex_cmd
    f.write("def check_russian_in_latex_cmd(text):\n")
    f.write('    """F) RUSSIAN_IN_LATEX_CMD"""\n')
    f.write("    return bool(re.search(r'" + "\\\\[\\u0430-\\u044f\\u0410-\\u042f\\u0451\\u0401]" + "', text))\n\n\n")
    # check_double_dollar_broken
    f.write("def check_double_dollar_broken(text):\n")
    f.write('    """G) DOUBLE_DOLLAR_BROKEN"""\n')
    f.write("    if '$$$' in text:\n")
    f.write("        return True\n")
    f.write("    if re.search(r'(?<!" + "\\$)\\$\\$(?!\\$" + ")', text):\n")
    f.write("        parts = text.split('$$')\n")
    f.write("        if len(parts) % 2 == 0:\n")
    f.write("            return True\n")
    f.write("    return False\n\n\n")
    # analyze
    f.write("def analyze():\n")
    f.write("    os.makedirs(REPORT_DIR, exist_ok=True)\n")
    f.write("    con = sqlite3.connect(DB_PATH)\n")
    f.write("    con.row_factory = sqlite3.Row\n")
    f.write("    rows = con.execute('SELECT id, class_level, difficulty_level, task_text FROM adaptive_tasks').fetchall()\n")
    f.write("    total = len(rows)\n")
    f.write("    print(f'Total tasks: {total}')\n")
    f.write("    checks = {\n")
    f.write("        'HAS_LITERAL_BACKSLASH_N': check_literal_backslash_n,\n")
    f.write("        'HLINE_OUTSIDE_ENV': check_hline_outside_env,\n")
    f.write("        'BARE_SQRT_FRAC': check_bare_sqrt_frac,\n")
    f.write("        'LSQRTL_PATTERN': check_lsqrtl_pattern,\n")
    f.write("        'UNCLOSED_DOLLAR': check_unclosed_dollar,\n")
    f.write("        'RUSSIAN_IN_LATEX_CMD': check_russian_in_latex_cmd,\n")
    f.write("        'DOUBLE_DOLLAR_BROKEN': check_double_dollar_broken,\n")
    f.write("    }\n")
    f.write("    by_type = defaultdict(int)\n")
    f.write("    by_grade = defaultdict(lambda: defaultdict(int))\n")
    f.write("    samples = defaultdict(list)\n")
    f.write("    issues_ids = set()\n")
    f.write("    for row in rows:\n")
    f.write("        tid = row['id']\n")
    f.write("        grade = row['class_level']\n")
    f.write("        text = row['task_text'] or ''\n")
    f.write("        for itype, fn in checks.items():\n")
    f.write("            try:\n")
    f.write("                if fn(text):\n")
    f.write("                    by_type[itype] += 1\n")
    f.write("                    by_grade[grade][itype] += 1\n")
    f.write("                    issues_ids.add(tid)\n")
    f.write("                    if len(samples[itype]) < MAX_SAMPLES:\n")
    f.write("                        prev = text[:250].replace(chr(10), chr(92)+'n')\n")
    f.write("                        samples[itype].append({'id': tid, 'grade': grade, 'preview': prev})\n")
    f.write("            except Exception as e:\n")
    f.write("                print(f'ERROR {itype} id={tid}: {e}')\n")
    f.write("    con.close()\n")
    f.write("    report = {\n")
    f.write("        'generated_at': datetime.now().isoformat(),\n")
    f.write("        'total_tasks': total,\n")
    f.write("        'issues_count': len(issues_ids),\n")
    f.write("        'by_type': dict(by_type),\n")
    f.write("        'by_grade': {str(g): dict(by_grade[g]) for g in sorted(by_grade)},\n")
    f.write("        'samples': dict(samples),\n")
    f.write("    }\n")
    f.write("    with open(JSON_REPORT, 'w', encoding='utf-8') as jf:\n")
    f.write("        json.dump(report, jf, ensure_ascii=False, indent=2)\n")
    f.write("    print(f'JSON: {JSON_REPORT}')\n")
    f.write("    md = []\n")
    f.write("    md.append('# LaTeX Issues Report')\n")
    f.write("    md.append(f'**Date:** {datetime.now()}')\n")
    f.write("    md.append(f'**Total:** {total}')\n")
    f.write("    md.append(f'**With issues:** {len(issues_ids)}')\n")
    f.write("    md.append('')\n")
    f.write("    md.append('| Type | Count |')\n")
    f.write("    md.append('|---|---|')\n")
    f.write("    for it in checks:\n")
    f.write("        md.append(f'| {it} | {by_type.get(it,0)} |')\n")
    f.write("    md.append('')\n")
    f.write("    for it, sl in samples.items():\n")
    f.write("        md.append(f'### {it} ({by_type.get(it,0)})')\n")
    f.write("        for s in sl:\n")
    f.write("            md.append(f'- ID {s[\"id\"]} (grade {s[\"grade\"]}): {s[\"preview\"][:150]}')\n")
    f.write("        md.append('')\n")
    f.write("    with open(MD_REPORT, 'w', encoding='utf-8') as mf:\n")
    f.write("        mf.write(chr(10).join(md))\n")
    f.write("    print(f'MD: {MD_REPORT}')\n")
    f.write("    print(f'TOTAL: {len(issues_ids)} issues out of {total}')\n")
    f.write("    for it in checks:\n")
    f.write("        c = by_type.get(it, 0)\n")
    f.write("        if c > 0:\n")
    f.write("            print(f'  {it}: {c}')\n\n\n")
    f.write("if __name__ == '__main__':\n")
    f.write("    analyze()\n")
print("Done: " + target)
