#!/usr/bin/env python3
"""Generates scripts/fix_latex_adaptive.py"""
import os

target = os.path.join("scripts", "fix_latex_adaptive.py")
with open(target, "w", encoding="utf-8") as f:
    f.write("#!/usr/bin/env python3\n")
    f.write('"""\n')
    f.write("Fix LaTeX issues in adaptive tasks (FORMYLA).\n")
    f.write("Usage:\n")
    f.write("  python scripts/fix_latex_adaptive.py --dry-run\n")
    f.write("  python scripts/fix_latex_adaptive.py --commit\n")
    f.write('"""\n')
    f.write("import sqlite3, re, json, os, sys, shutil\n")
    f.write("from datetime import datetime\n\n")
    f.write('DB_PATH = os.path.join("instance", "formyla.db")\n')
    f.write('BACKUP_DIR = os.path.join("data", "backups")\n')
    f.write('REPORT_DIR = os.path.join("data", "audit")\n\n')
    # LATEX_N_CMDS
    f.write("LATEX_N_CMDS = {\n")
    f.write("    'neq','nabla','notin','neg','nu','nleq','ngeq','nmid',\n")
    f.write("    'nsubseteq','nsupseteq','ncong','nsim','nrightarrow',\n")
    f.write("    'nleftarrow','not','newline','newcommand','nolimits',\n")
    f.write("    'nonumber','nparallel'\n")
    f.write("}\n\n\n")
    # fix_literal_backslash_n
    f.write("def fix_literal_backslash_n(text):\n")
    f.write('    """Fix literal backslash-n to real newlines."""\n')
    f.write("    BS = chr(92)\n")
    f.write("    # Double-escaped first\n")
    f.write("    text = text.replace(BS*2 + 'n', chr(10))\n")
    f.write("    # Now handle single literal backslash-n\n")
    f.write("    # But protect LaTeX commands like \\neq etc.\n")
    f.write("    result = []\n")
    f.write("    i = 0\n")
    f.write("    while i < len(text):\n")
    f.write("        if text[i] == BS and i+1 < len(text) and text[i+1] == 'n':\n")
    f.write("            # Check if this is a LaTeX command\n")
    f.write("            rest = text[i+2:]\n")
    f.write("            is_cmd = False\n")
    f.write("            if rest and rest[0].isalpha():\n")
    f.write("                for cmd in LATEX_N_CMDS:\n")
    f.write("                    if ('n' + rest).startswith(cmd):\n")
    f.write("                        is_cmd = True\n")
    f.write("                        break\n")
    f.write("            if is_cmd:\n")
    f.write("                result.append(BS)\n")
    f.write("                result.append('n')\n")
    f.write("                i += 2\n")
    f.write("            else:\n")
    f.write("                result.append(chr(10))\n")
    f.write("                i += 2\n")
    f.write("        else:\n")
    f.write("            result.append(text[i])\n")
    f.write("            i += 1\n")
    f.write("    return ''.join(result)\n\n\n")
    # fix_bare_sqrt_frac
    f.write("def fix_bare_sqrt_frac(text):\n")
    f.write('    """Wrap bare \\\\frac{...}{...} and \\\\sqrt{...} in $...$."""\n')
    f.write("    BS = chr(92)\n")
    f.write("    # Fix \\frac{...}{...} outside math mode\n")
    f.write("    # Simple approach: find \\frac or \\sqrt not preceded by $ and wrap\n")
    f.write("    changed = False\n")
    f.write("    # We need to check if each occurrence is inside math mode\n")
    f.write("    # Import build_math_map from analyzer\n")
    f.write("    def build_math_map(t):\n")
    f.write("        n = len(t)\n")
    f.write("        im = [False] * n\n")
    f.write("        ii = 0\n")
    f.write("        while ii < n:\n")
    f.write("            if ii < n-1 and t[ii] == BS and t[ii+1] == '(':\n")
    f.write("                j = t.find(BS+')', ii+2)\n")
    f.write("                if j != -1:\n")
    f.write("                    for k in range(ii, min(j+2, n)): im[k] = True\n")
    f.write("                    ii = j + 2; continue\n")
    f.write("            if ii < n-1 and t[ii] == BS and t[ii+1] == '[':\n")
    f.write("                j = t.find(BS+']', ii+2)\n")
    f.write("                if j != -1:\n")
    f.write("                    for k in range(ii, min(j+2, n)): im[k] = True\n")
    f.write("                    ii = j + 2; continue\n")
    f.write("            if ii < n-1 and t[ii] == '$' and t[ii+1] == '$':\n")
    f.write("                j = t.find('$$', ii+2)\n")
    f.write("                if j != -1:\n")
    f.write("                    for k in range(ii, min(j+2, n)): im[k] = True\n")
    f.write("                    ii = j + 2; continue\n")
    f.write("                else: ii += 2; continue\n")
    f.write("            if t[ii] == '$':\n")
    f.write("                j = t.find('$', ii+1)\n")
    f.write("                if j != -1:\n")
    f.write("                    for k in range(ii, j+1): im[k] = True\n")
    f.write("                    ii = j + 1; continue\n")
    f.write("                else: ii += 1; continue\n")
    f.write("            ii += 1\n")
    f.write("        return im\n\n")
    f.write("    # Find all bare \\frac and \\sqrt, wrap each in $...$\n")
    f.write("    # Process from end to start to preserve positions\n")
    f.write("    pat = re.compile(r'" + "\\\\(sqrt|frac)" + r"')\n")
    f.write("    matches = list(pat.finditer(text))\n")
    f.write("    if not matches:\n")
    f.write("        return text\n")
    f.write("    in_math = build_math_map(text)\n")
    f.write("    bare = [m for m in matches if not in_math[m.start()]]\n")
    f.write("    if not bare:\n")
    f.write("        return text\n\n")
    f.write("    # For each bare match, find the extent of the expression\n")
    f.write("    # and wrap in $...$\n")
    f.write("    for m in reversed(bare):\n")
    f.write("        start = m.start()\n")
    f.write("        # Find end of expression\n")
    f.write("        pos = m.end()\n")
    f.write("        cmd = m.group(1)\n")
    f.write("        # Count braces\n")
    f.write("        groups_needed = 2 if cmd == 'frac' else 1\n")
    f.write("        end = pos\n")
    f.write("        for _ in range(groups_needed):\n")
    f.write("            # Skip whitespace\n")
    f.write("            while end < len(text) and text[end] in ' \\t':\n")
    f.write("                end += 1\n")
    f.write("            if end < len(text) and text[end] == '{':\n")
    f.write("                depth = 1\n")
    f.write("                end += 1\n")
    f.write("                while end < len(text) and depth > 0:\n")
    f.write("                    if text[end] == '{': depth += 1\n")
    f.write("                    elif text[end] == '}': depth -= 1\n")
    f.write("                    end += 1\n")
    f.write("            else:\n")
    f.write("                # No brace - take single char/token\n")
    f.write("                if end < len(text):\n")
    f.write("                    end += 1\n")
    f.write("        # Also grab trailing content that looks like it belongs\n")
    f.write("        # (e.g. exponents, subscripts)\n")
    f.write("        while end < len(text) and text[end] in '^_':\n")
    f.write("            end += 1\n")
    f.write("            if end < len(text) and text[end] == '{':\n")
    f.write("                depth = 1\n")
    f.write("                end += 1\n")
    f.write("                while end < len(text) and depth > 0:\n")
    f.write("                    if text[end] == '{': depth += 1\n")
    f.write("                    elif text[end] == '}': depth -= 1\n")
    f.write("                    end += 1\n")
    f.write("            elif end < len(text):\n")
    f.write("                end += 1\n")
    f.write("        expr = text[start:end]\n")
    f.write("        text = text[:start] + '$' + expr + '$' + text[end:]\n")
    f.write("    return text\n\n\n")
    # apply_fixes
    f.write("def apply_fixes(text):\n")
    f.write('    """Apply all fixes to text. Returns (new_text, list_of_fix_types)."""\n')
    f.write("    fixes = []\n")
    f.write("    original = text\n")
    f.write("    # 1. Fix literal backslash-n\n")
    f.write("    new = fix_literal_backslash_n(text)\n")
    f.write("    if new != text:\n")
    f.write("        fixes.append('HAS_LITERAL_BACKSLASH_N')\n")
    f.write("        text = new\n")
    f.write("    # 2. Fix bare sqrt/frac\n")
    f.write("    new = fix_bare_sqrt_frac(text)\n")
    f.write("    if new != text:\n")
    f.write("        fixes.append('BARE_SQRT_FRAC')\n")
    f.write("        text = new\n")
    f.write("    return text, fixes\n\n\n")
    # main
    f.write("def main():\n")
    f.write("    if len(sys.argv) < 2 or sys.argv[1] not in ('--dry-run', '--commit'):\n")
    f.write("        print('Usage: python fix_latex_adaptive.py --dry-run|--commit')\n")
    f.write("        sys.exit(1)\n")
    f.write("    mode = sys.argv[1]\n")
    f.write("    commit = mode == '--commit'\n\n")
    f.write("    con = sqlite3.connect(DB_PATH)\n")
    f.write("    con.row_factory = sqlite3.Row\n")
    f.write("    rows = con.execute('SELECT id, class_level, task_text FROM adaptive_tasks').fetchall()\n")
    f.write("    print(f'Total tasks: {len(rows)}')\n\n")
    f.write("    # Ensure task_text_archive column exists\n")
    f.write("    cols = [r[1] for r in con.execute('PRAGMA table_info(adaptive_tasks)').fetchall()]\n")
    f.write("    if 'task_text_archive' not in cols:\n")
    f.write("        con.execute('ALTER TABLE adaptive_tasks ADD COLUMN task_text_archive TEXT')\n")
    f.write("        con.commit()\n")
    f.write("        print('Added column task_text_archive')\n\n")
    f.write("    if commit:\n")
    f.write("        os.makedirs(BACKUP_DIR, exist_ok=True)\n")
    f.write("        stamp = datetime.now().strftime('%Y%m%d_%H%M%S')\n")
    f.write("        backup = os.path.join(BACKUP_DIR, f'formyla_db_{stamp}.db')\n")
    f.write("        shutil.copy2(DB_PATH, backup)\n")
    f.write("        print(f'Backup: {backup}')\n\n")
    f.write("    changes = []\n")
    f.write("    by_type = {}\n")
    f.write("    for row in rows:\n")
    f.write("        tid = row['id']\n")
    f.write("        text = row['task_text'] or ''\n")
    f.write("        new_text, fix_types = apply_fixes(text)\n")
    f.write("        if fix_types:\n")
    f.write("            changes.append({'id': tid, 'grade': row['class_level'],\n")
    f.write("                'old': text[:200], 'new': new_text[:200], 'types': fix_types})\n")
    f.write("            for ft in fix_types:\n")
    f.write("                by_type[ft] = by_type.get(ft, 0) + 1\n")
    f.write("            if commit:\n")
    f.write("                con.execute(\n")
    f.write("                    'UPDATE adaptive_tasks SET task_text_archive = task_text '\n")
    f.write("                    'WHERE id = ? AND task_text_archive IS NULL', (tid,))\n")
    f.write("                con.execute(\n")
    f.write("                    'UPDATE adaptive_tasks SET task_text = ? WHERE id = ?',\n")
    f.write("                    (new_text, tid))\n\n")
    f.write("    if commit:\n")
    f.write("        con.commit()\n")
    f.write("    con.close()\n\n")
    f.write("    # Report\n")
    f.write("    print(f'\\nMode: {mode}')\n")
    f.write("    print(f'Tasks to fix: {len(changes)}')\n")
    f.write("    print(f'By type: {by_type}')\n")
    f.write("    print()\n")
    f.write("    # Show samples\n")
    f.write("    shown = {}\n")
    f.write("    for c in changes:\n")
    f.write("        for t in c['types']:\n")
    f.write("            shown.setdefault(t, 0)\n")
    f.write("            if shown[t] < 3:\n")
    f.write("                print(f'--- {t} | ID {c[\"id\"]} (grade {c[\"grade\"]}) ---')\n")
    f.write("                print(f'  OLD: {repr(c[\"old\"])}')\n")
    f.write("                print(f'  NEW: {repr(c[\"new\"])}')\n")
    f.write("                print()\n")
    f.write("                shown[t] += 1\n")
    f.write("    if commit:\n")
    f.write("        print(f'COMMITTED {len(changes)} changes.')\n")
    f.write("    else:\n")
    f.write("        print(f'DRY-RUN complete. Use --commit to apply.')\n\n\n")
    f.write("if __name__ == '__main__':\n")
    f.write("    main()\n")

print("Done: " + target)
